### ISSUE TITLE
TypeError: Cannot read property 'clearImmediate' of undefined

### ISSUE THREAD

**Issue by jdahl-va** [thymikee/jest-preset-angular#103]
Trying to load this up into an existing angular project.  I've followed the instructions according to the readme and [This Blog](https://www.xfive.co/blog/testing-angular-faster-jest/).  Running a simple test such as:
```js
it('should be true', () => {
      expect(true).toBe(true);
});
```

gives me an error:
```
TypeError: Cannot read property 'clearImmediate' of undefined
      
      at new FakeTimers (node_modules/jest-util/build/fake_timers.js:106:29)
      at new JSDOMEnvironment (node_modules/jest-preset-angular/testEnvironment.js:27:23)
```

Digging into this, it looks like this library has an issue around here:
```js
this._timerAPIs = {
      clearImmediate: global.clearImmediate,
      clearInterval: global.clearInterval,
      clearTimeout: global.clearTimeout,
      nextTick: global.process && global.process.nextTick,
      setImmediate: global.setImmediate,
      setInterval: global.setInterval,
      setTimeout: global.setTimeout };
```

I've gone through the setup instructions a few times to make sure I didn't miss anything.  Along with deleting-rebuilding node_modules a few times to make sure all of my old jasmine stuff has been properly purged.

**Comment by thymikee** [comment]
Do you have a repro for this? Which Jest version do you use?

**Comment by jdahl-va** [comment]
My relevant dependencies:
```
"@angular/cli": "^1.6.0",
"@angular/compiler-cli": "^5.1.0",
"@angular/language-service": "^5.1.0",
"@types/jest": "^21.1.8",
"jest": "^22.0.0",
"jest-preset-angular": "^4.0.2",
"jest-zone-patch": "0.0.8",
```

jest config:
```
"jest": {
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts"
  }
```

**Comment by thymikee** [comment]
I haven't tested this preset with Jest 22 yet. Also ts-jest is having some issues with it. Can you try it on Jest 21?

**Comment by jdahl-va** [comment]
That worked!  Thanks for the help
