### ISSUE TITLE
Support Jest 22

### ISSUE THREAD

**Issue by thymikee** [thymikee/jest-preset-angular#104]
I guess we can get rid of custom Test Environment, because Jest is now using new JSDOM.
We'll also need to wait for `ts-jest` to update their coverage-related code (because there was a breaking change in how we pass sourcemaps to transformers).

**Comment by AhnpGit** [comment]
Let's wait until ts-jest update finishes. It will make jest 22 more stable too in the meantime

**Comment by Iorg** [comment]
Hi!,

Ts-jest seems to be [updated](https://github.com/kulshekhar/ts-jest/releases/tag/v22.0.0) to Jest 22.

**Comment by thymikee** [comment]
Released `jest-preset-angular@5.0.0-beta.0`, anybody wants to test it?

**Comment by Iorg** [comment]
I'm going to try now.

**Comment by Iorg** [comment]
Just tested `jest-preset-angular@5.0.0-beta.0` with `jest@22.0.3`. Everything seems fine for me. @thymikee thanks for creating the release :-)

**Comment by thymikee** [comment]
Released stable `5.0.0`. Enjoy!

**Comment by dereklin** [comment]
I am getting this error after the upgrade:

```
Cannot find module 'ts-jest' from 'setupJest.ts'
```

What settings did you guys have to change?
