### ISSUE TITLE
Cannot read property clearImmediate

### ISSUE THREAD

**Issue by artigat1** [thymikee/jest-preset-angular#105]
I'm trying to add Jest to a brand new angular CLI generated app. I've followed all the setup instructions on the page, but just get the following when I try to run:

![image](https://user-images.githubusercontent.com/1673835/34155076-e1db5736-e4af-11e7-9a5b-5a46b36624df.png)

This is my Angular CLI setup

![image](https://user-images.githubusercontent.com/1673835/34155113-f9cfd542-e4af-11e7-8f1e-a0c673c1e69b.png)

Any help would be appreciated...

**Comment by thymikee** [comment]
Use Jest 21, Jest 22 is not yet supported

**Comment by thymikee** [comment]
It's even stated in peer deps!
https://github.com/thymikee/jest-preset-angular/blob/1dac93dd120d6afcf30f8ae8e3f774e3e9174775/package.json#L18-L20
Didn't you get the warning from Yarn or NPM install?

**Comment by artigat1** [comment]
Sorry, I just followed the installation instructions copying `yarn add --dev jest jest-preset-angular @types/jest`. I didn't see anything in the readme about getting a specific version. I will give that a go.

**Comment by thymikee** [comment]
Because it was released yesterday ^^. And I didn't have time to make a new release. There's issue about that however!
