### ISSUE TITLE
[Feature]: Add support for SVG

### ISSUE THREAD

**Issue by Granipouss** [thymikee/jest-preset-angular#1055]
### 🚀 Feature Proposal

Hey people,

Should we add support for SVG template? From my experiments, adding svg next to html in https://github.com/thymikee/jest-preset-angular/blob/main/presets/index.js (stringifyContentPathRegex & transform) should do the trick.

Cheers

### Motivation

SVG files can be used as ANgular templates already https://angular.io/guide/svg-in-templates

**Comment by ahnpnl** [comment]
PR is welcome :)
