### ISSUE TITLE
Support Angular v13

### ISSUE THREAD

**Issue by brandonroberts** [thymikee/jest-preset-angular#1090]
### Version

10.0.1

### Steps to reproduce

1. Clone this repo: github.com:brandonroberts/jest-preset-angular
2. Checkout Angular V13 branch: 

```sh
git checkout angular-v13-rc
```
 
3. Go to the `examples/example-app-v13` directory and install dependencies

```sh
cd examples/example-app-v13
yarn
```

4. Run tests

```sh
npm run test
```

### Expected behavior

Tests run

### Actual behavior

Error is thrown

```
> jest-preset-angular@10.0.1 test /home/robertsbt/projects/jest-preset-angular
> jest

ngcc-jest-processor: running ngcc
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './ngcc/main-ngcc.js' is not defined by "exports" in /home/robertsbt/projects/jest-preset-angular/node_modules/@angular/compiler-cli/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.<anonymous> (/home/robertsbt/projects/jest-preset-angular/build/utils/ngcc-jest-processor.js:22:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

### Additional context

Angular introduced the `exports` property in the `package.json` to be more strict about reaching into internal source code which may have caused this.

### Environment

```shell
System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
```

**Comment by petebacondarwin** [comment]
It appears that Jest plugins can use ESM if you make them async: https://jestjs.io/docs/next/code-transformation#:~:text=Note%20that%20ECMAScript,on%20the%20differences.

**Comment by ahnpnl** [comment]
Hi, yes we need access to that one `constructorParametersDownlevelTransform`. I just made a PR today to change internal codes https://github.com/thymikee/jest-preset-angular/blob/main/src/compiler/ng-jest-compiler.ts#L1 to import directly from `@angular/compiler-cli`. That should work I think?

**Comment by ahnpnl** [comment]
Hi, I setup a branch with a simple test https://github.com/thymikee/jest-preset-angular/runs/4050533619?check_suite_focus=true

I noticed that, you are right that core APIs from `@angular/core` still works with CJS syntax `require('@angular/core')`, but `@angular/core/testing` no longer works. Jest module resolution couldn't find it anymore while Angular 12 still works fine. I'm not sure this is a bug for Angular.

The workaround for Jest module resolving issue is configuring `moduleNameMapper`, but imo this is not too ideal.

**Comment by ahnpnl** [comment]
I managed to make CJS tests passed https://github.com/thymikee/jest-preset-angular/runs/4054772234?check_suite_focus=true . I followed the suggestion from @alan-agius4 but not sure if it can be done better:

- I used `github-files-fetcher` to download files for downlevel transformer via a Node script https://github.com/ahnpnl/jest-preset-angular/blob/angular-v13/scripts/prebuild.js and then bundle it together with this repo codes.
- The most troublesome part is configuring Jest module resolution to understand new Angular package format https://github.com/ahnpnl/jest-preset-angular/blob/angular-v13/e2e/async/jest.config.js#L16 which we don’t have problems with Angular 12

**Comment by alan-agius4** [comment]
@ahnpnl, I was going to look into this on Monday. 

I suspect that to get ride of the module mapper workaround you might need to enable Jests’ `module` which would Instruct it to take the module property in the package.json of secondary entrypoints into consideration.

**Comment by alan-agius4** [comment]
@ahnpnl, I did a take a look at the CJS tests and it appears that the reason why you need the `moduleNameMapper` is because Jests' default resolver doesn't take into consideration the `module` field. 
https://github.com/facebook/jest/blob/97e1eac39d4506e6a7a86898a083e73c5bdad37e/packages/jest-resolve/src/defaultResolver.ts#L102-L124

From the docs, it appears that one needs a custom resolve for this:
https://jestjs.io/docs/configuration#resolver-string

I did monkey patch the resolver instead of implementing my own and it I was able to get rid of the module mappers

**https://github.com/facebook/jest/blob/97e1eac39d4506e6a7a86898a083e73c5bdad37e/packages/jest-resolve/src/defaultResolver.ts#L102-L124**

```diff
     if (filteredPkg.main != null) {      
       return filteredPkg;
     }

+    if (filteredPkg.module != null) {
+      filteredPkg.main = filteredPkg.module;
+    }
```


For Jest, it is also important to use `FESM2015` and not `FESM2020`, for 2 main reasons.
- Unlike browsers, FESM2020 contains syntax which is not yet supported by all Node.JS versions such as optional chaining.
- Zone.JS cannot intercept native `async`/`await` which are present in ES2017+. For users wishing to use ES2017+, they will need to downlevel these using `@babel/plugin-transform-async-to-generator`.

Maybe we can include the resolver as part of this preset?

**Comment by ahnpnl** [comment]
Thanks a lot @alan-agius4 !! I was suspecting that a custom resolver seems to be the only way to solve `moduleNameMapper` config in a better way. I think yes it makes sense to include a custom resolver in this repository.

Indeed I was confused between `FESM2015` vs `FESM2020` and I was thinking `FESM2015` seems to be a better fit, which is related to #1058 which was explained by your team as well. Thanks for clarifying this! 

Does internal Angular CLI use any custom resolvers for webpack to deal with `module` field? If yes, it would be nice if you can reference me there so I can implement a similar resolver for Jest.

**Comment by alan-agius4** [comment]
> Does internal Angular CLI use any custom resolvers for webpack to deal with module field? If yes, it would be nice if you can reference me there so I can implement a similar resolver for Jest.

No we don't have any custom resolver The tools used by the Angular CLI, Webpack, Node.js and Rollup (Which are used in different pipeline and phases) all support `package exports` and the `module` field. 

For Webpack we only provide the fields and the order that the resolver should consider.

https://github.com/angular/angular-cli/blob/ebccb5de4a455af813c5e82483db6af20666bdbd/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L302-L305

In think in your case, the resolver should look like the below

```js
module.exports = (request, options) =>
  options.defaultResolver(request, {
    ...options,
    packageFilter: (pkg) => ({
      ...pkg,
      main: pkg.main || pkg.es2015 || pkg.module,
    }),
  });
```

**Comment by ahnpnl** [comment]
that's simpler than I expected. Thanks again. I will test out this resolver. A quick test I could see that e2e test passed 👍

**Comment by alan-agius4** [comment]
Feel free to ping me if you need any help or have any question. You can also reach on out [Twitter](https://twitter.com/alanagius4)

**Comment by tja4472** [comment]
Firebase recommended this resolver.

Upgrade to 9.2.0 gives error in jest unit tests: 
https://github.com/firebase/firebase-js-sdk/issues/5687

```js
// my-module-resolve.js
module.exports = (request, options) => {
  // Call the defaultResolver, so we leverage its cache, error handling, etc.
  return options.defaultResolver(request, {
    ...options,
    // Use packageFilter to process parsed `package.json` before the resolution (see https://www.npmjs.com/package/resolve#resolveid-opts-cb)
    packageFilter: pkg => {
      if(pkg.name.startsWith('@firebase')) {
        return {
          ...pkg,
          // Alter the value of `main` before resolving the package
          main: pkg.esm5 || pkg.module,
        };
      }

      return pkg;
    },
  });
};
```
```js
module.exports = {
  ....
  // set the value to the custom resolver created in step 1
  resolver: '<rootDir>/my-module-resolve.js',
  // browser bundles in firebase are ESM, transform them to CJS to work in Jest
  transformIgnorePatterns: [
    "<rootDir>/node_modules/(?!(@firebase.*)/)"
  ]
};
```

**Comment by ahnpnl** [comment]
Thanks for your input @tja4472, but here we are making a generic resolver for Angular 13, not specific to `@firebase` case. Of course end users feel free to copy the generic resolver of this preset and extend on their own to fit with their usage.

**Comment by michaelfaith** [comment]
@ahnpnl I'm not sure if this is an issue with the configuration, or with the Angular Material library, but we're seeing failures to import on a few of their components (but oddly not all).

```
Test suite failed to run

    ReferenceError: Cannot access 'MatButtonToggle' before initialization

       6 |
       7 | import { ComponentFixture, TestBed } from '@angular/core/testing';
    >  8 | import { MatButtonToggleModule } from '@angular/material/button-toggle';
         | ^
       9 | import { MatIconModule } from '@angular/material/icon';
      10 |
      11 | import { ButtonToggleDemoComponent } from './button-toggle-demo.component';

      at Object.<anonymous> (../../node_modules/@angular/node_modules/@angular/material/fesm2015/button-toggle.mjs:254:63)
      at Object.<anonymous> (src/app/component-demos/button-toggle-demo/button-toggle-demo.component.spec.ts:8:1)
```

Does this look like something that would be a configuration issue (this project), or something more on their side?

**Comment by JoostK** [comment]
@michaelfaith That's a bug in Angular's partial compilation output. @petebacondarwin is working on a fix in the Angular compiler.

**Comment by michaelfaith** [comment]
@joostk Excellent!  Thank you for the heads up

**Comment by michaelfaith** [comment]
@ahnpnl I'm seeing a slightly different issue with testing of a library build with Angular 13.  Similar to Material, these errors are popping up in Jest unit tests that involve components from the library, but it runs fine with `ng serve` (aot).  According to https://github.com/angular/angular/pull/44113#issuecomment-964199439 this doesn't appear to be related to the compiler issue currently being worked on affecting Angular Material.  Are there additional config changes needed in order to test Angular 13 compiled libraries?

```
Details:

    C:\Users\<user>\src\fabric-starter\node_modules\@fabric\components\fesm2015\fabric-components-breadcrumbs.mjs:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as i4 from '@angular/common';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      10 | import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
      11 | import { RouterTestingModule } from '@angular/router/testing';
    > 12 | import { FabBreadcrumbsModule } from '@fabric/components/breadcrumbs';
         | ^
      13 | import { FabHeaderModule } from '@fabric/components/header';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/app/app.component.spec.ts:12:1)

```

and 

```
 Details:

    C:\Users\<user>\src\fabric-starter\node_modules\@fabric\components\fesm2015\fabric-components-utilities.mjs:196
    export { compareById, convertDateTimeToTimestamp, doesContainOnlyStrings, findObjWithKey, getCoreRoute, isNotNull, isNotNullOrUndefined, isNull, isNullOrUndefined, isObject, isUndefined, removeIntersection, removeItemFromArray,
removeLeadingSlash, removeQueryParams, replaceAll };
    ^^^^^^

    SyntaxError: Unexpected token 'export'

       7 | import { Injectable } from '@angular/core';
    >  8 | import { isNotNull } from '@fabric/components/utilities';
         | ^
        9 | import { AuthenticationService } from '../authentication/authentication.service';
      10 |
      11 | /**

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/app/core/user/user.service.ts:9:1)

```

Comment from @JoostK:
> @michaelfaith that does not look related to what is being fixed here, it seems. I believe that Jest creates a CommonJS wrapper for any module it loads, in order to sandbox things like `require` and `module` and the like. That does require however that CommonJS code is used, whereas it appears that in your case the ESM ends up within the CommonJS wrapper. That is invalid, as ESM must be top-level.

**Comment by ahnpnl** [comment]
You can check this https://github.com/thymikee/jest-preset-angular/issues/1149#issuecomment-963506942

**Comment by michaelfaith** [comment]
@ahnpnl perfect!  That did the trick. I knew you'd have the solution.  Thanks a ton.  And for working through this upgrade with us all.  Really appreciate it.  You as well @JoostK.  You guys rock.

**Comment by pinich** [comment]
You closed this issue but the problem remains,
I'm facing the following error and I can't find any workaround for it.
```
  ● Test suite failed to run

    Error [ERR_REQUIRE_ESM]: require() of ES Module C:\...\node_modules\@angular\compiler-cli\bundles\index.js from C:\...\node_modules\jest-preset-angular\build\compiler\ng-jest-compiler.js not supported.
    Instead change the require of index.js in C:\...\node_modules\jest-preset-angular\build\compiler\ng-jest-compiler.js to a dynamic import() which is available in all CommonJS modules.

      at Object.<anonymous> (node_modules/jest-preset-angular/build/compiler/ng-jest-compiler.js:4:24)
      at ScriptTransformer._getTransformer (node_modules/@jest/transform/build/ScriptTransformer.js:347:21)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:427:28)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:569:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:607:25)
```

**Comment by ahnpnl** [comment]
@pinich please use `next` tag, we haven’t published official release yet.

**Comment by KonkypenT** [comment]
I am still unable to run tests on angular 13.
I am using the latest version of the library, as written in this thread.
Please tell me if this is a configuration or angular issue?

![image](https://user-images.githubusercontent.com/44831445/146874511-f4ce72fb-e290-4fad-816e-2addd4d667f6.png)

**Comment by ahnpnl** [comment]
I think you missed some configuration. You can take a look at our example app https://github.com/thymikee/jest-preset-angular/tree/main/examples/example-app-v13

**Comment by KonkypenT** [comment]
> I think you missed some configuration. You can take a look at our example app https://github.com/thymikee/jest-preset-angular/tree/main/examples/example-app-v13

Great! Thanks a lot! The problem was in the configuration

**Comment by JaapBarnhoorn** [comment]
How did you fix it @KonkypenT?

**Comment by KonkypenT** [comment]
@JaapBarnhoorn , I changed the library config, copied from the example that reset @ahnpnl.

![image](https://user-images.githubusercontent.com/44831445/147091360-c8ce5b93-dbc0-4bd5-8fec-48b883f25adb.png)
![image](https://user-images.githubusercontent.com/44831445/147091375-39aa06dd-ad8c-4881-8c56-00e569342284.png)
![image](https://user-images.githubusercontent.com/44831445/147091384-059d8aef-b31f-4c74-a10f-855359c0eaa0.png)

**Comment by JaapBarnhoorn** [comment]
Thank you @KonkypenT! 👍
