### ISSUE TITLE
Add more tests to example app

### ISSUE THREAD

**Issue by thymikee** [thymikee/jest-preset-angular#110]
In the `example` dir of this repository we have couple of tests to check if we didn't break some common testing cases. It is a very simple app and I treat it as sanity check before releasing. Also, a good reference for anybody wanting to see how to write specific tests. It would be nice to extend this test suite, to cover more cases, so we have more confidence in further releases. 

Since I'm not actively involved in any Angular project for quite some time and I still want this project to be alive, I reach out to you as a community to help with this task. I'm sure we can make this project more stable with every release.

If anyone is interested in contributing tests, please let me know by either commenting in this thread or sending a PR 🙂

**Comment by ahmedifhaam** [comment]
I need some help I am currently using JEST to test an angular 9 app, There i want to mock service classes which are dependencies for my component. I want my tests to take a default mock from __mocks__ folder and if i need i will override  with mockImplementaion(). currently its working if i import the mock file but i think the  way jest documentation says it should pick the mock when i call jest.mock('filepath'). In my case its not working

**Comment by wtho** [comment]
@ahmedifhaam best would be you either create a PR with the test case not working in example app, or you create another new issue with your specific request and provide a minimal reproduction in form of an own, linked repository, that will enable us to help you quickly.

**Comment by rfprod** [comment]
- https://github.com/thymikee/jest-preset-angular/pull/1182
- https://github.com/thymikee/jest-preset-angular/pull/1183
- https://github.com/thymikee/jest-preset-angular/pull/1181
- https://github.com/thymikee/jest-preset-angular/pull/1185
- https://github.com/thymikee/jest-preset-angular/pull/1184

**Comment by ahnpnl** [comment]
Closes via all mentioned MRs above.

**Comment by wtho** [comment]
Just wondering - does the V10 example app also get the tour of heroes tests?
Totally ok for me if not, but just wanted to make sure this was not just left out my mistake, but on purpose.

**Comment by ahnpnl** [comment]
Angular 10 support will be dropped on 24th this month so we don’t need to add tests to example app Angular 10 :)
