### ISSUE TITLE
[Bug]: Decorators fail in library specs with nested package.json files 

### ISSUE THREAD

**Issue by abierbaum** [thymikee/jest-preset-angular#1106]
### Version

10.0.1

### Steps to reproduce

1. Clone repository from: https://github.com/abierbaum/jest-preset-angular/
2. git checkout dev/package_problems
3. cd examples/example-app-v12
4. yarn install
5. yarn test --updateSnapshot

Note: you can see the code directly here: https://github.com/abierbaum/jest-preset-angular/tree/dev/package_problems/examples/example-app-v12

It extends the base sample with:
   * A `libs` subdirectory with 2 local libraries
   * Adds a pacakge.json file in `libs/lib1/src` directory
 

### Expected behavior

I would expect the specs to run correctly to completion.  For example the spec in lib2 does run to completion.  But in lib1 where there is an angular  library package.json file, it fails to run.

### Actual behavior

```
$ yarn test
yarn run v1.22.5
$ jest
ngcc-jest-processor: running ngcc
 FAIL  libs/lib1/src/simple.spec.ts
  ● Test suite failed to run

    SyntaxError: /.../jest-preset-angular/examples/example-app-v12/libs/lib1/src/simple.spec.ts: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (9:4):

       7 | /** blah */
       8 | export class JestInlineSnapBugComponent {
    >  9 |    @decTest('blah') val3: string = 'val3';
         |    ^
      10 | }
      11 | export const B = new JestInlineSnapBugComponent();
      12 |

      at Object._raise (node_modules/@babel/parser/src/parser/error.js:134:45)

```

### Additional context

I ran into this when bringing the workaround from https://github.com/thymikee/jest-preset-angular/issues/1084 back into my main production codebase.  I don't think it is related, but it could be.

### Environment

```shell
System:
    OS: Linux 5.8 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 12.22.5 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.14 - /usr/bin/npm
  npmPackages:
    jest: ^27.2.4 => 27.2.4
```

**Comment by ahnpnl** [comment]
It is the same issue with #1084 which should be reported to Jest instead. The API `toMatchInlineSnapshot` has changed in v27 comparing to v26 which `jest-preset-angular` cannot do anything about it.
