### ISSUE TITLE
TypeError: Cannot read property prototype/document of undefined - d3.js related

### ISSUE THREAD

**Issue by tkstang** [thymikee/jest-preset-angular#113]
Hello and thanks for all your great work on this project!  In attempting to get things set up to use jest in my project the tests I am actually running work fine (aside from a fakeAsync issue that I have been unable to resolve updating etc. as listed in that closed issue).  My main issue I'm having seems to be related to c3 and d3.  Components that import an rely on c3 and d3 are failing to run.  Note these are tests where I have "xdescribe'd" the suite.  I have both c3 and d3 in my transformIgnorePatterns. 

For the two c3 dependent components I get TypeError: Cannot read property 'prototype' if undefined'.
For the d3 dependent component I get TypeError: Cannot read property 'document' of undefined.

I'm currently using:

angular/cli: 1.3.0
jest: ^22.0.6
jest-preset-angular: ^5.0
babel-preset-env: ^1.6.1

My transformIgnorePatterns looks as such:

        "transformIgnorePatterns": [
            "node_modules/(?!c3|angular2-json2csv|d3|promise-script-loader)"
        ]

**Comment by thymikee** [comment]
It's possible that you need to pass them through babel first, see: https://github.com/thymikee/jest-preset-angular#transpile-js-files-through-babel-jest

**Comment by tkstang** [comment]
So I do currently currently already have babel-preset-env installed.  I have within my package.json in the jest configuration

`
        "transform": {
            "^.+\\.(ts|html)$": "<rootDir>/node_modules/jest-preset-angular/preprocessor.js",
            "^.+\\.js$": "babel-jest"
        },
`

and a .babelrc file at the root of that project with 

`
{
  "presets": ["env"]
}
`

It was my understanding that this would pass any js files to babel-jest to transpile.  Am I missing something with the configuration?

**Comment by thymikee** [comment]
And that doesn't work? Do you have a small repro you can share?

**Comment by tkstang** [comment]
No, it did fix some other issues for me but I'm still getting the errors from my c3chart and d3chart component files.  What seems more odd to me is I'm getting an error from another component that does not use c3 or d3 at all.  I will attach a screen of the failures in case that is helpful at all.  It will probably be a couple of days before I have an opportunity to put together a repro to share. 

![screen shot 2018-01-16 at 1 54 33 pm](https://user-images.githubusercontent.com/23129892/35014297-eb7bfdce-fac4-11e7-84d4-7fcd9daad95f.png)

**Comment by thymikee** [comment]
You need to include class properties transform: https://babeljs.io/docs/plugins/transform-class-properties/

**Comment by thymikee** [comment]
But hm, these are TS files, so discard my previous comment. You'll need to see what's inside `d3/d3.js:8:26` and alike to get the idea which objects are getting undefined. 
On the other hand, I'm pretty sure d3 should transform their sources to ES5, so that's weird. Maybe you call some untranspiled endpoint?

**Comment by tkstang** [comment]
c3.js:2720
`
window.SVGPathElement.prototype.createSVGPathSegClosePath = function () {
  return new window.SVGPathSegClosePath(undefined);
};
`

d3.js:8
var d3_document = this.document;
d3.js:9554 - just the very end of the file
}();

Interestingly I have a force directed graph component that relies on d3v4 which is imported as an asset (just the minified js file) since we can't use two versions of d3 in parallel and I don't seem to have any problems from the components using that version.  We've been waiting for c3 to update to use d3v4 but the progress has been moving at a glacial pace so I recently found billboard.js which the maintainers forked c3 and made the necessary changes to work with d3v4, I'm planning on migrating to that from c3 sometime within the next month.  Perhaps its the older version of d3 though.  Either way it would be nice to get this sorted.

**Comment by nickforddesign** [comment]
The problem is almost definitely that when you run your tests, you don't have a real browser environment, but rather a mocked environment via `jsdom`. I'm fairly certain they just haven't implemented all of these SVG prototype methods.

**Comment by rfprod** [comment]
As far as I know it's a good practice to mock such libraries on the unit test level. Nothing should be actually rendered. It should be tested that the respective library methods are called only. And this can be achieved by properly mocking a library.

**Comment by ahnpnl** [comment]
Close as this was reported with angularjs

**Comment by ASA018** [comment]
Hi,

Thanks in advance!

I did an Angular upgrade from 12.2.17 to 13.3.8 and when launching my application i got this error:
**Uncaught TypeError: Cannot read properties of undefined (reading 'document')
    at d3.js:8:26
    at 83064 (d3.js:1:2)
    at __webpack_require__ (bootstrap:19:1)
    at 46491 (index.js:11:10)
    at __webpack_require__ (bootstrap:19:1)
    at 3372 (plotcss.js:3:11)
    at __webpack_require__ (bootstrap:19:1)
    at 48553 (core.js:17:1)
    at __webpack_require__ (bootstrap:19:1)
    at 25724 (core.js:11:1)**

Thanks for your help,
Regards,
Amal,

**Comment by ahnpnl** [comment]
This is because Jest deps are not in v28. You need to ensure all Jest packages are in v28

**Comment by ASA018** [comment]
Hi @ahnpnl,
Thanks for your reply.
I changed the types/jest to 28.1.0 on package.json but still not working.

Regards,
Amal,

**Comment by ahnpnl** [comment]
the `document` error is caused by one of the Jest packages. You might need to reinstall deps or regenerate lock file or just run
```
yarn remove jest jest-preset-angular && yarn add -D jest jest-preset-angular
```

If you are using `jest-builder`, you would need to contact that repo.

**Comment by rfprod** [comment]
> Hi @ahnpnl, Thanks for your reply. I changed the types/jest to 28.1.0 on package.json but still not working.
> 
> Regards, Amal,

@ASA018  Do you have `"jest-environment-jsdom": "28.1.1"` in your devDependencies along with `"jest-preset-angular": "12.x.x"`?

**Comment by ASA018** [comment]
Hi @ahnpnl,

Thanks for your replay!

Yes i have "jest-environment-jsdom" in **package-lock.json** below the values:
    "node_modules/jest-environment-jsdom": {
      "version": "28.1.1",
      "resolved": "https://registry.npmjs.org/jest-environment-jsdom/-/jest-environment-jsdom-28.1.1.tgz",
      "integrity": "sha512-41ZvgSoPNcKG5q3LuuOcAczdBxRq9DbZkPe24okN6ZCmiZdAfFtPg3z+lOtsT1fM6OAERApKT+3m0MRDQH2zIA==",
      "dev": true,
      "dependencies": {
        "@jest/environment": "^28.1.1",
        "@jest/fake-timers": "^28.1.1",
        "@jest/types": "^28.1.1",
        "@types/jsdom": "^16.2.4",
        "@types/node": "*",
        "jest-mock": "^28.1.1",
        "jest-util": "^28.1.1",
        "jsdom": "^19.0.0"
      },
      "engines": {
        "node": "^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0"
      }
    },

And "jest-preset-angular" too in **package.json** below the value:
"jest-preset-angular": "^12.1.0",

Regards,
Amal,

**Comment by ahnpnl** [comment]
Probably clear Jest cache should help.

**Comment by ASA018** [comment]
Hi @ahnpnl ,

Thank you for your replay.

I checked the config by comparing your example with mine i think that in my case the problem is related to "plotly.js"

![image](https://user-images.githubusercontent.com/107614994/174765221-6efba5da-0645-4455-a434-ab920065332d.png)

FYI: I migrated my app from angular 12.2.17 to 13.3.8 and before the migration the jest was not exist.

Even if i changed the plotly version to "plotly.js": "^1.58.5",  but still getting the same error.

Regards,
Amal,

**Comment by ahnpnl** [comment]
in the stacktrace, I see something related to `webpack`. Jest doesn't use `webpack` so I think your problem is something else, related to your Angular application rather than Jest itself.

**Comment by rfprod** [comment]
> I checked the config by comparing your example with mine i think that in my case the problem is related to "plotly.js"
> 
> ![image](https://user-images.githubusercontent.com/107614994/174765221-6efba5da-0645-4455-a434-ab920065332d.png)
> 
> FYI: I migrated my app from angular 12.2.17 to 13.3.8 and before the migration the jest was not exist.
> 
> Even if i changed the plotly version to "plotly.js": "^1.58.5", but still getting the same error.
> 
> Regards, Amal,

@ASA018 You show a browser console in the screenshot, but Jest uses jsdom instead of a browser...

I suppose your app does not work as expected, does it? If so, it seems like the issue has nothing to do with Jest or jest-preset-angular.

Have you tried using the latest version https://github.com/plotly/plotly.js/releases/tag/v2.12.1?
```json
...
  "plotly.js": "2.12.1"
...
```

Have you tried the following?
- https://github.com/plotly/plotly.js/issues/5714

**Comment by erperejildo** [comment]
> I am using nvd3 charts(nvd3-1.8.5, d3-3.5.17), facing the below issue after Upgrading from angular 12 to angular 14. When it was in angular 12 I didn't face any issues.
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading 'document')
>     at d3.js:8:26
>     at 83064 (d3.js:1:2)
>     at __webpack_require__ (bootstrap:19:1)
>     at 54058 (index.ts:8:44)
>     at __webpack_require__ (bootstrap:19:1)
>     at 84096 (settings.saveview.html:41:141)
>     at __webpack_require__ (bootstrap:19:1)
>     at 70299 (UserServiceResolver.ts:18:33)
>     at __webpack_require__ (bootstrap:19:1)
>     at 64349 (viewlogmessage.html:65:57)
> ```
> 
> Even I tried with nvd3 1.8.5 with d3 V4(With Angular 14) getting the below issue.
> 
> ```
> core.mjs:6397 ERROR TypeError: nv.dispatch.render_start is not a function
>     at Object.render (nv.d3.js:93:17)
>     at nv.addGraph (nv.d3.js:145:12)
>     at ViewActionsComponent.ts:169:17
>     at Array.forEach (<anonymous>)
>     at ViewActionsComponent.onGetMessageSuccessCallback (ViewActionsComponent.ts:140:11)
>     at SafeSubscriber._next (ViewActionsComponent.ts:83:36)
>     at SafeSubscriber.__tryOrUnsub (Subscriber.js:183:16)
>     at SafeSubscriber.next (Subscriber.js:122:22)
>     at Subscriber._next (Subscriber.js:72:26)
>     at Subscriber.next (Subscriber.js:49:18)
> ```
> 
> I tried adding "plotly.js": "2.12.1" in package.json but it didn't work.
> 
> Any idea how to fix this error?
> 
> Thanks in advance

how did you fix this? I'm facing the same after moving from Angular 14 to 15
