### ISSUE TITLE
[Bug]: super() throw error with coverage enabled

### ISSUE THREAD

**Issue by matheo** [thymikee/jest-preset-angular#1152]
### Version

9.0.7

### Steps to reproduce

We have a private repo with `@angular@12.2.13`, `@angular-builders/jest@12.1.2`, `jest@27.3.1`, `jest-preset-angular@9.0.7` and we're having issues with one test on a component extending another one (only the parent has constructor).

We've found that `jest --coverage` fails but `jest` alone passes,
so digging into that I've found this issue: https://github.com/facebook/jest/issues/11706
which is linked to this PR: https://github.com/auth0/nextjs-auth0/pull/513/files#r724342423

It seems that `istanbul` has something to do with the error
but targetting `ts-jest` to `es6` nor enabling `sourceMap` did the trick :( 

### Expected behavior

Have the test passing just like we had on `jest@26`

### Actual behavior

The child component is having an issue to get the `NgControl` via DI
and the component is throwing an error in the test:
```
No value accessor for form control with name: 'assignedBoUser'
```
for this `pug` template:
```pug
form([formGroup]="form")
  autocomplete-bo-user(
      formControlName="assignedBoUser",
      [mapWith]="mapWith",
  )
```

### Additional context

The child component `autocomplete-bo-user` extends from `autocomplete` without defining a constructor.

The parent component (`autocomplete`) uses a workaround to define the `ValueAccesor` which is not working because the injected `NgControl` is `undefined`:
```typescript
  constructor(
    public elementRef: ElementRef,
    protected injector: Injector,
    protected cdr: ChangeDetectorRef,
    protected getObjectValue: MyndGetObjectValuePipe,
    @Self() @Optional() public ngControl: NgControl,
    @Optional() @Inject(MyndFormFieldComponent) protected parentFormField: MyndFormFieldComponent,
  ) {
    super();

    if (this.ngControl) {
      this.ngControl.valueAccessor = this;
    }
  }
```

as said, the `--coverage` flag for `jest` is the one not working properly
any hint to solve this situation please? :pray: 

### Environment

```shell
System:
  OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Binaries:
  Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
  Yarn: 1.22.15 - /usr/bin/yarn
  npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
```

**Comment by matheo** [comment]
The test passes with `coverageProvider: 'v8'` 
any idea why? or what can we set for `babel` to pass it? :thinking:

**Comment by ahnpnl** [comment]
You can try **10.1.0** whereas we set `target` for compilation to `ES2015` (ES6) or `ES2016` :)

**Comment by ahnpnl** [comment]
Would you pls create a reproduction? You can use https://github.com/thymikee/jest-preset-angular/tree/main/examples/example-app-v12

**Comment by wSedlacek** [comment]
I am running into a similar error when using [@ngneat/spectator](https://github.com/ngneat/spectator).

### Steps to reproduce:
1. Install example-app-v13
2. Install `@ngneat/spectator`
3. Configure `app.component.spec.ts` like so
```ts
import { Spectator, createRoutingFactory } from '@ngneat/spectator/jest';

import { AppComponent } from './app.component';

describe('AppComponent', () => {
  let spectator: Spectator<AppComponent>;
  const createComponent = createRoutingFactory({
    component: AppComponent,
    stubsEnabled: false,
    routes: [],
  });

  beforeEach(() => (spectator = createComponent()));

  it('should create the app', () => {
    const app = spectator.fixture.componentInstance;

    expect(app).toBeInstanceOf(AppComponent);
  });
});
```
4. Run test

### Expected results
Test to pass

### Actual results
Test fail with the following error
```
$ jest --no-cache
ngcc-jest-processor: running ngcc
 FAIL  src/app/app.component.spec.ts
  AppComponent
    ✕ should create the app (6 ms)

  ● AppComponent › should create the app

    TypeError: Class constructor ActivatedRoute cannot be invoked without 'new'

      11 |   });
      12 |
    > 13 |   beforeEach(() => (spectator = createComponent()));
         |                                 ^
      14 |
      15 |   it('should create the app', () => {
      16 |     const app = spectator.fixture.componentInstance;

      at new ActivatedRouteStub (node_modules/projects/spectator/src/lib/spectator-routing/activated-route-stub.ts:30:5)
      at src/app/app.component.spec.ts:13:33

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.842 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I traced this back and it's actually trying to run the `examples/example-app-v13/node_modules/@ngneat/spectator/bundles/ngneat-spectator.umd.js` file which errors on this line
```js
  var ActivatedRouteStub = /** @class */ (function (_super) {
        __extends(ActivatedRouteStub, _super);
        function ActivatedRouteStub(options) {
            var _this = _super.call(this) || this;
            ...
```

Running the same test with the `example-app-v12` does not produce such an error.
The same `ngneat-spectator.umd.js` file is run, it just runs without errors on v12 for some reason.

**Comment by rfprod** [comment]
I would like to chime in.
I am maintaining a relatively advanced template monorepo (nx + angular + nestjs) which uses the `jest-preset-angular` plugin.
The repo is regularly updated and uses the latest dependencies.
There are no issues with collecting code coverage.
The repo - https://github.com/rfprod/nx-ng-starter
There are several pipelines in the repo. The [trunk-on-push](https://github.com/rfprod/nx-ng-starter/actions/workflows/trunk-on-push.yml) pipeline executes all unit tests with code coverage on.
For instance, this test run https://github.com/rfprod/nx-ng-starter/runs/4408697072?check_suite_focus=true. Find the `Unit test all (with code coverage)` step.
Hope it helps somehow.

**Comment by ahnpnl** [comment]
I can no longer reproduce this bug with the reproduce example above with Jest 28. If you guys still encounter it, feel free to put a reproduce scenario which I can use to check.
