### ISSUE TITLE
[Bug]: Slow startup on larger projects

### ISSUE THREAD

**Issue by callumelgrant** [thymikee/jest-preset-angular#1168]
### Version

11.0.0-rc.3

### Steps to reproduce

1. Clone https://github.com/callumelgrant/jest-preset-angular
2. Run yarn test in the Angular 13 example.

### Expected behavior

It would be nice to see a test run time more similar to the earlier versions of jest-preset-angular. 

### Actual behavior

Running yarn test takes ~65 seconds from a cold cache after adding lodash-es. Is there any way to reduce this?

### Additional context

After adding more packages to the solution the transformation time seems to increase considerably - in our yarn workspace running yarn test on a cold cache takes 20 minutes before starting to run tests.

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^27.3.1 => 27.3.1
```

**Comment by ahnpnl** [comment]
Currently workaround is:
- Switch to `isolatedModules: true` which will disable type checking.
- Add `moduleNameMapper` for `lodash-es`, see https://github.com/nrwl/nx/issues/812#issuecomment-787141835

**Comment by ahnpnl** [comment]
The provided solution will solve partially the problem only as we rely on `ts-jest` about performance with type checking.
