### ISSUE TITLE
[Bug]: Error when executing test with jest and jest-circus as testRunner

### ISSUE THREAD

**Issue by cedricduffournet** [thymikee/jest-preset-angular#1187]
### Version

 11.0.0-rc.4

### Steps to reproduce

1. Clone this repo: github.com:cedricduffournet/test-ngrx-error.git
2. Install dependencies
```
yarn install
```
3. yarn jest
```
yarn test
```

### Expected behavior

Test should run without errors

### Actual behavior

The following error occur in all tests with `provideMockStore` added to `providers` in `configureTestingModule`
```
 Cannot configure the test module when the test module has already been instantiated. Make sure you are not using `inject` before `R3TestBed.configureTestingModule`.
 beforeEach(() => {  
  TestBed.configureTestingModule({
                ^
```

### Additional context

I initially thought the issue came from NgRx package (see https://github.com/ngrx/platform/issues/3243). But its seems that this is more of jest-preset-angular issue. I double check my config and didn't find anything wrong

If i set `jest-jasmine2` as `testRunner` in jest config, I don't have any error.
I did not have this issue in  version 12 of angular ngrx, jest-preset-angular 10

### Environment

```shell
npx : 1 installé(s) en 2.093s

  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  npmPackages:
    jest: ^27.3.1 => 27.3.1
```

**Comment by ahnpnl** [comment]
I believe the error comes from the implementation of `provideMockStore` itself. That is outside of the scope of `jest-preset-angular`. Regarding to jest-runner `jest-circus`, that is also outside of the scope of `jest-preset-angular` too.

**Comment by cedricduffournet** [comment]
Ok, thanks the quick answer, I'm going to check again with NgRx team

**Comment by ahnpnl** [comment]
Another hint is, with `jest-circus`, this test https://github.com/cedricduffournet/test-ngrx-error/blob/master/src/app/books/containers/collection-page.component.spec.ts#L55 if you comment out, the test runs successfully.

**Comment by cedricduffournet** [comment]
Yes, actually there is an error after the first executed test, the 1er test always pass successfully

**Comment by cedricduffournet** [comment]
as well, if I disable `destroyAfterEach` in `configureTestingModule` all test pass https://github.com/cedricduffournet/test-ngrx-error/blob/master/src/app/books/containers/collection-page.component.spec.ts#L40 successfully

**Comment by cedricduffournet** [comment]
Yes, I think the issue is related to `destroyAfterEach` activated by default.

I checked on NgRx repo and this line seems to be the problem : https://github.com/ngrx/platform/blob/master/modules/store/testing/src/mock_store.ts#L21 
Because `TestBed` is already clean up, injecting `MockStore` in `afterEach` test generate an error

Thanks for you help, I'll report this to NgRx team

**Comment by ahnpnl** [comment]
Thanks I will close this issue then:)
