### ISSUE TITLE
jest not working with a minimal angular-cli 1.0 project

### ISSUE THREAD

**Issue by vecernik** [thymikee/jest-preset-angular#12]
On osx sierra, node 7.8, yarn 0.22, jest doesn't do anything when added to the project. Steps to reproduce:
1. create new project
$ ng new --skip-commit  --skip-git --skip-install for-jest-preset-angular 

2. in new folder:
$ yarn add --dev jest jest-preset-angular @types/jest
$ yarn remove @types/jasmine

3. created file src/setupJest.ts witch :
import 'jest-preset-angular';

4. added to package.json : 
"jest": {
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts"
  }
and 
scripts: {
"test": "jest",
"test:watch": "jest --watch",
"karma": "ng test"
}

5. run test:
$ yarn run test
yarn run v0.22.0
$ jest 

and nothing happens.
$ yarn run karma
executes 3 tests in Chrome browser properly.

Can that be a macosx specific issue?

**Comment by vecernik** [comment]
I also tried out https://github.com/beeman/angular-cli-jest with the same (no) result.

**Comment by thymikee** [comment]
Can you publish this to github so I could check out?

**Comment by vecernik** [comment]
https://github.com/vecernik/angular-cli-100-jest 
Running on node 7.9 didn't help, npm run test doesn't work either.

**Comment by thymikee** [comment]
Just ran on 7.7.4 and it works normally

**Comment by thymikee** [comment]
<img width="338" alt="screen shot 2017-04-12 at 15 52 20" src="https://cloud.githubusercontent.com/assets/5106466/24961104/12d88ff8-1f98-11e7-94ab-d1f86fe89f37.png">

Maybe you can try install/reinstall watchman? (`brew install watchman`)

**Comment by intellix** [comment]
@vecernik this works for me: https://github.com/intellix/angular-cli-jest/commit/07829f51502070a47a1a10c7bfa58a534c33baa1

**Comment by vecernik** [comment]
on macos/sierra finally brew uninstall watchman did the trick. Thank you.
