### ISSUE TITLE
How to get coverage?

### ISSUE THREAD

**Issue by shanehsu** [thymikee/jest-preset-angular#120]
After importing this package as preset, I am able to test Angular. 

I did find that I have to add the ts-jest transform myself. However, this didn’t give me the coverage report I wanted so badly. :)

I did not have a separate tsconfig.json, but my main one does have source map. 

Is there anything I’m missing?

**Comment by thymikee** [comment]
run jest with `--coverage` flag

**Comment by shanehsu** [comment]
@thymikee Thanks for the swift reply.

I'm taking a closer look in my config file and the example project, but any pointers would be much appreciated!

 I did so, but it shows something like this,

```
$ tsc jest.config.ts && jest --no-cache --coverage
 PASS  src/app/first.spec.ts
  testing-jest
    ✓ testOne (78ms)
    ✓ testTwo (1ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        2.378s
Ran all test suites.
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
✨  Done in 6.72s.
```

**Comment by AhnpGit** [comment]
@shanehsu actually you don't need to declare ts-jest to transform anymore because inside the package it already used ts-jest to transform .ts file. You can declare in your package.json like this
`"jest": {
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/setup-jest.ts",
    "globals": {
      "ts-jest": {
        "tsConfigFile": "src/tsconfig.spec.json"
      },
      "__TRANSFORM_HTML__": true
    },
    "transform": {
      "^.+\\.(ts|js|html)$": "<rootDir>/node_modules/jest-preset-angular/preprocessor.js"
    },
    "mapCoverage": true,
    "coverageReporters": [
      "json",
      "html",
      "text"
    ],
    "collectCoverageFrom": [
      "src/app/**/*.actions.ts",
      "src/app/**/*.component.ts",
      "src/app/**/*.effects.ts",
      "src/app/**/*.helper.ts",
      "src/app/**/*.pipe.ts",
      "src/app/**/*.reducer.ts",
      "src/app/**/*.service.ts"
    ],
  }`

**Comment by shanehsu** [comment]
@AhnpGit I can't use a `setup-jest.ts` file or `.spec.ts` file this way.

It will output the error: `SyntaxError: Unexpected token import`

**Comment by thymikee** [comment]
Can you share your config or the repo?

**Comment by shanehsu** [comment]
@thymikee Turns out I'm not able to reproduce it with a minimum reproducible example. Should've done this before bothering you guys. I'll take a look at what's different between my dumbed-down version.

**Comment by thymikee** [comment]
No worries, good luck! I'll close it for now, but feel free to report back what was the issue :)

**Comment by shanehsu** [comment]
@thymikee Thanks :) I worked my way back from the good MRE, and got it working. Thanks!
I think one of the configuration I set before is interfering with the preset :)
