### ISSUE TITLE
[Bug]: getTestBed is not a function - JPAv11 with custom jest config

### ISSUE THREAD

**Issue by dharms40au** [thymikee/jest-preset-angular#1217]
### Version

11.0.1

### Steps to reproduce

update jest-preset-angular from 10 to 11.
run test suite `yarn run ng test ui --watch`

### Expected behavior

tests that were passing before pass again.

### Actual behavior

 FAIL   ui  libs/ui/src/lib/lesson-landing-page/lesson-landing-page.component.spec.ts
  ● Test suite failed to run

    TypeError: getTestBed is not a function

    > 1 | import 'jest-preset-angular/setup-jest';
        | ^
      2 |

      at Object.<anonymous> (../../node_modules/jest-preset-angular/build/config/setup-jest.js:20:1)
      at Object.<anonymous> (../../node_modules/jest-preset-angular/setup-jest.js:1:100)
      at Object.<anonymous> (src/test-setup.ts:1:1)

### Additional context

test-setup.ts

```
import 'jest-preset-angular/setup-jest';
```

jest.config.js

```
module.exports = {
  displayName: 'ui',
  preset: '../../jest.preset.js',
  setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.spec.json',
      stringifyContentPathRegex: '\\.(html|svg)$',
    },
  },
  coverageDirectory: '../../coverage/libs/ui',
  transform: {
    '^.+\\.(ts|js|mjs|html|svg)$': 'jest-preset-angular',
  },
  snapshotSerializers: [
    'jest-preset-angular/build/serializers/no-ng-attributes',
    'jest-preset-angular/build/serializers/ng-snapshot',
    'jest-preset-angular/build/serializers/html-comment',
  ],
  transformIgnorePatterns: ['node_modules/(?!.*.(mjs|ts)$)']
};
```

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  npmPackages:
    jest: 27.2.3 => 27.2.3
```

**Comment by wtho** [comment]
@dharms40au Which version of Angular are you using?

First of all, you are missing the resolver. See the [default preset](https://github.com/thymikee/jest-preset-angular/blob/9739b7f384b912d190034dac547bd30527e8903c/presets/index.js#L17-L23), and the values it takes from the `basePreset` to fix your configuration (or `defaultsESM` if you use ESM).

Cheers and happy coding~

**Comment by dharms40au** [comment]
please close this. so sorry to waste your time. I did an nx migrate latest and fixed this issue.
