### ISSUE TITLE
[Bug]: Errors running v13 example with ESM

### ISSUE THREAD

**Issue by johncrim** [thymikee/jest-preset-angular#1222]
### Version

main (v11.0.1)

### Steps to reproduce

1. git clone git@github.com:thymikee/jest-preset-angular.git
2. cd examples\example-app-v13
3. yarn
4. yarn test-esm

### Expected behavior

Example tests run without error.

### Actual behavior

All tests fail. Most tests fail with this error:

```
 FAIL  src/app/demo/async-helper.spec.ts
  ● Test suite failed to run

    Must use import to load ES Module: C:\src\github\angular\jest-preset-angular\examples\example-app-v13\node_modules\@angular\core\fesm2015\testing.mjs

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:972:21)
```

A few tests also have the error: `ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.`

```
 FAIL  src/app/demo/demo.testbed.spec.ts
  ● Test suite failed to run

    Must use import to load ES Module: C:\src\github\angular\jest-preset-angular\examples\example-app-v13\node_modules\@angular\core\fesm2015\testing.mjs

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:972:21)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From src/app/demo/async-helper.spec.ts.

          at async Promise.all (index 1)
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^27.4.4 => 27.4.4
```

**Comment by johncrim** [comment]
If I change the setup-jest.ts file to use ESM imports (and skip using `jest-preset-angular/setup-jest`), most of the tests pass:

```ts
// examples/example-app-v13/setup-jest.ts

// Removed:
// import 'jest-preset-angular/setup-jest';

import 'zone.js/fesm2015/zone-testing-bundle.min.js';
import './jest-global-mocks';

import { getTestBed } from '@angular/core/testing';
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';

getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());
```

**Comment by johncrim** [comment]
@ahnpnl : Is this a known issue for jest-preset-angular (are we waiting on an external dependency for ng13 + ESM to work)?

I'm just wondering if there's anything to do to address this, or if I'd be wasting my time.

**Comment by ahnpnl** [comment]
This is a known issue and ESM mode isn't worked on for Angular 13 yet. 

> If I change the setup-jest.ts file to use ESM imports (and skip using `jest-preset-angular/setup-jest`), most of the tests pass:
> 
> ```ts
> // examples/example-app-v13/setup-jest.ts
> 
> // Removed:
> // import 'jest-preset-angular/setup-jest';
> 
> import 'zone.js/fesm2015/zone-testing-bundle.min.js';
> import './jest-global-mocks';
> 
> import { getTestBed } from '@angular/core/testing';
> import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';
> 
> getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());
> ```
> 

This workaround is valid. I tried to create a file in the preset to allow to import like `import 'jest-preset-angular/setup-jest.mjs` but this doesn't work with monorepo and yarn workspace. 

The error about 
```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From src/app/app.component.spec.ts.

          at async Promise.all (index 3)
```
is caused by the dependency https://github.com/thymikee/jest-preset-angular/blob/main/examples/example-app-v13/package.json#L23 wasn't updated to be compatible with Angular 13. Internally, that dependency used syntax `require` to use Angular APIs but that won't work with Angular 13. Update to the latest version of this dependency would solve that error.

**Comment by johncrim** [comment]
Thank you very much @ahnpnl . Updating the `angular-in-memory-web-api` dependency does indeed fix the `You are trying to `import` a file after the Jest environment has been torn down.` errors, and updating the ng dependencies fixes this error:

```
    Must use import to load ES Module: C:\src\github\angular\jest-preset-angular\examples\example-app-v13\node_modules\@angular\core\fesm2015\core.mjs
      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:972:21)
```

I've [published a branch here with a few changes](https://github.com/johncrim/jest-preset-angular/tree/bug/ng13-esm-example), which together are enough for the example tests to all pass. Lmk if you'd like a PR for these changes.

**Comment by ahnpnl** [comment]
PR is welcome :)
