### ISSUE TITLE
Host bindings in the snapshot

### ISSUE THREAD

**Issue by yurii-sorokin** [thymikee/jest-preset-angular#125]
Hi. Is there any plan to add attributes (classes, styles) added by `@HostBinding` to the snapshot?

**Comment by thymikee** [comment]
No plans, but feel free to take a stab on it :)

**Comment by yurii-sorokin** [comment]
Ok. I decided to create serializer as a separate package. It slightly different from serializer in this repo. It relies on debugNodes + existing react serializer. It's not stress tested yet, but you could take a look.

**Comment by thymikee** [comment]
Share it :)

**Comment by yurii-sorokin** [comment]
Oops, 🤦‍♂️.  The package on [github](https://github.com/yurii-sorokin/ngx-jest-snapshot-serializer) or on [npm](https://www.npmjs.com/package/ngx-jest-snapshot-serializer).

**Comment by AhnpGit** [comment]
I like that you use serialize which is available since jest 21 👍

**Comment by yurii-sorokin** [comment]
Also, as my serializer will break all existing tests (till the snapshot update of course), I have moved setup of serializers to jest config (PR #126). Now it would be possible to play with my serializer with this preset untouched.

**Comment by yurii-sorokin** [comment]
I guess the issue could be closed.
