### ISSUE TITLE
[Feature]: 'ng add' schematic support

### ISSUE THREAD

**Issue by grant-wilson** [thymikee/jest-preset-angular#1299]
### 🚀 Feature Proposal

Some manual setup is required to add jest and jest-preset-angular to an angular project.
This includes installing dependencies and creating files.
Angular schematics provides an opportunity to automate this manual setup.
By supporting the `ng-add` schematic, jest-preset-angular can become easier to use in a new project.

### Motivation

Setting up jest with an angular project should be as easy as possible. Today this requires manual setup of installing dependencies, creating new files, updating existing files. All of this could be automated using Angular schematics to streamline the process and reduce potential user errors of doing this by hand.

### Example

When setting up an angular project to use jest and jest-preset-angular, the developer can simply run `ng add jest-preset-angular`. This will run the `ng-add` schematic implemented in jest-preset-angular making the necessary changes to the project to switch from karma to jest.

**Comment by ahnpnl** [comment]
Hi, this has been discussed in the past and we decided that this is out of the scope for this repo. You can request it at https://github.com/just-jeb/angular-builders which takes care of integrating with Angular CLI. Thank you for understanding.
