### ISSUE TITLE
Possible deduplication of dependencies.

### ISSUE THREAD

**Issue by vangorra** [thymikee/jest-preset-angular#13]
I see this project depends on jest-zone-patch which does a good job of patching jasmine to run functions within a zone.js context.

In digging through node_modules, I noticed zone.js/dist/jasmine-patch.js pretty much does the same thing. It may be advisable to set a peer dependency on zone.js via `require('zone.js/dist/jasmine-patch');`. I haven't tested the implementation but it provides the possibility of removing dependencies you have to maintain.

**Comment by thymikee** [comment]
The reason I've written `jest-zone-patch` was because I couldn't get it to work with Jest. Also, Jest slightly differs in API from Jasmine, so I'd like to have my own patch with my custom code and without QueueRunner hack. 
I'm happy to donate it to Zone.js some time later when it becomes stable.

**Comment by thymikee** [comment]
It's a good idea to add `zone.js` as a peerDep though.

**Comment by vangorra** [comment]
Good point. Jest is documented as a fork of Jasmine and is expected to continue to diverge as time goes by.
