### ISSUE TITLE
[bug] TypeScript type errors are not reported during tests

### ISSUE THREAD

**Issue by benjamincharity** [thymikee/jest-preset-angular#133]
I'm not sure exactly where this lies, but it seems like `ts-jest` added support for this a bit ago, but I'm not seeing any TS errors reported after adding the flag: https://github.com/kulshekhar/ts-jest#ts-compiler--error-reporting

```
{
  "jest": {
    "globals": {
      "ts-jest": {
        "enableTsDiagnostics": true
      }
    }
  }
}
```

Since `ts-jest` users report that feature working, I'm thinking it's possibly related to this repo.

#### Reproduction

```typescript
// One TS issue here: The return type should be `string|{[key: string]: string}`
public getValueKey(item: {[key: string]: string}, valueKey?: string): string {
  return valueKey ? item[valueKey] : item;
}

// Test:

// One TS issue here: Passing in an array rather than an object
test.only(`should return the item if no valueKey was passed in`, () => {
  const items: string[] = ['a', 'b'];
  expect(this.component.getValueKey(items)).toEqual(items);
});
```

But in the above case the test passes with no errors/warnings.

When consuming this code in an Angular CLI app, the TypeScript compiler _does_ correctly throw errors for the above. Any ideas here?

**Comment by AhnpGit** [comment]
@thymikee I talked to you about this one a few days ago I think

**Comment by AhnpGit** [comment]
Hi @benjamincharity, we did update dependencies ts-jest for this package but it is not released yet.
cc @thymikee

**Comment by benjamincharity** [comment]
Ahh didn't event check the version in `package.json`! Thanks for the quick response!

**Comment by thymikee** [comment]
FYI v5.2.1 released

**Comment by thymikee** [comment]
Please close the issue if it's resolved :)
