### ISSUE TITLE
Snapshots of components with ngFor directives using trackBy functions differ when using the --coverage flag

### ISSUE THREAD

**Issue by asgallant** [thymikee/jest-preset-angular#134]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

Jest snapshot test produces different results for Angular component with an `ngFor` directive using a `trackBy` function, when run with and without the `--coverage` flag.

**If the current behavior is a bug, please provide the steps to reproduce and
either a repl.it demo through https://repl.it/languages/jest or a minimal
repository on GitHub that we can `yarn install` and `yarn test`.**

1. Create a new Angular-CLI app
2. Add jest and [jest-preset-angular](https://github.com/thymikee/jest-preset-angular) as dependencies
3. Configure Jest to use jest-preset-angular
4. Create a new component `TestComponent`:
    ```
    // test.component.ts
    import { Component, TrackByFunction } from '@angular/core';

    class Item {
      id: number;
      name: string;
    }

    @Component({
      selector: 'app-test',
      template: '<div *ngFor="let item of items; trackBy: trackById">{{item.name}}</div>'
    })
    export class TestComponent {
      items: Item[] = [
        {
          id: 1,
          name: 'foo',
        },
        {
          id: 2,
          name: 'bar',
        },
        {
          id: 3,
          name: 'baz',
        }
      ];
      trackById: TrackByFunction<Item> = (index: number, item: Item) => item.id;
    }
    ```
5. Write a snapshot test against the component
    ```
    // test.component.spec.ts
    import { async, ComponentFixture, TestBed } from '@angular/core/testing';
    import { TestComponent } from './test.component';

    describe('TestComponent', () => {
      let component: TestComponent;
      let el: HTMLElement;
      let fixture: ComponentFixture<TestComponent>;

      beforeEach(async(() => {
        TestBed.configureTestingModule({
          declarations: [ TestComponent ]
        })
        .compileComponents();
      }));

      beforeEach(() => {
        fixture = TestBed.createComponent(TestComponent);
        component = fixture.componentInstance;
        fixture.detectChanges();
        el = fixture.debugElement.nativeElement;
      });

      it('should match snapshot', () => {
        expect(el.outerHTML).toMatchSnapshot();
      });
    });
    ```
6. Run test with `--coverage` flag
    ```
    <div id=\\"root0\\" ng-version=\\"5.2.7\\"><!--bindings={
      \\"ng-reflect-ng-for-of\\": \\"[object Object],[object Object\\",
      \\"ng-reflect-ng-for-track-by\\": \\"function (index, item) {/* ist\\"
    }--><div>foo</div><div>bar</div><div>baz</div>
    </div>
    ```
7. Run test without `--coverage` flag
    ```
    <div id=\\"root0\\" ng-version=\\"5.2.7\\"><!--bindings={
      \\"ng-reflect-ng-for-of\\": \\"[object Object],[object Object\\",
      \\"ng-reflect-ng-for-track-by\\": \\"function (item) {\\n        retu\\"
    }--><div>foo</div><div>bar</div><div>baz</div>
    </div>
    ```

**What is the expected behavior?**
The `--coverage` flag should not change the snapshots.

Angular injects comments like `/* istanbul ignore <something> */` in a lot of places. If you shorten the function signature of the `trackById` method (`trackById = () =>{}`), you get more text in the bindings output that shows this is what is being added when running the tests with the `--coverage` flag.

**Comment by yurii-sorokin** [comment]
You can give a try (my) alternate serializer for this preset [yurii-sorokin/ngx-jest-snapshot-serializer](https://github.com/yurii-sorokin/ngx-jest-snapshot-serializer). It produces a little bit different output and requires auto-update for all snapshot files when migrating. And it does not have such issue.

But of course, the PR with a fix would be much more appreciated.

**Comment by asgallant** [comment]
@yurii-sorokin I followed the instructions on your Github page, but Jest doesn't seem to be using the `ngx-jest-snapshot-serializer` - all of the snapshot tests are still run with the `AngularSnapshotSerializer` from `jest-preset-angular`. Is there a secret to overriding the serializer specified by `jest-preset-angular`?

**Comment by yurii-sorokin** [comment]
@asgallant, are you using the latest version of `jest-preset-angular`? The possibility to override serialized was added in  v5.1.0 (#126).

**Comment by asgallant** [comment]
I am using jest-preset-angular@5.2.1.

**Comment by asgallant** [comment]
Hmmmmm...I think I might just be completely off base here. I did some further digging, and it looks like neither one is processing the snapshots. I'm leaning towards this being an ID10T error.

**Comment by asgallant** [comment]
*facepalm*

Forget this whole issue. The root of the problem is that my tests are testing the wrong objects:

```
expect(fixture.debugElement.nativeElement.outerHTML).toMatchSnapshot();
```

should have just been:

```
expect(fixture).toMatchSnapshot();
```

Nevermind...nothing to see here...move along folks.
