### ISSUE TITLE
Multi-lined `styleUrls` seems to break tests.

### ISSUE THREAD

**Issue by phenomnomnominal** [thymikee/jest-preset-angular#136]
Components that are declared like this:

```
@Component({
    selector: 'whatever',
    styleUrls: [
        '../some-styles.scss',
        '../some-more-styles.scss',
        '../even-more-styles.scss',
    ]
```

break the regex of the preprocessor, resulting in:

```
SyntaxError: The string did not match the expected pattern.
      
      at XMLHttpRequest.open [as __zone_symbol__open] (../../node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:470:15)
```

Putting the `styleUrls` all on one line fixes this issue.

Seems to me that the regex could just be `styleUrls:\s*\[[^\]]*\]`? Unless I'm really missing something. Let me know and I will make a PR.

**Comment by thymikee** [comment]
That's a regex issue. Would you mind sending a PR with this fix an test case? :)

**Comment by Naooki** [comment]
Getting the same error on templateUrl.

**Comment by thymikee** [comment]
@Naooki can you create an issue with the reproducible example?

**Comment by Naooki** [comment]
@thymikee Sorry, my problem was that I've forgotten to change preprocessor in the transform section of jest config. It was ts-jest, instead of jest-preset-angular preprocessor. Interesting though that I've got the same error mentioned here.
But now everything is fine, thanks for a great work)

**Comment by jeremyfry** [comment]
@thymikee Thanks! I'll try to put in a new pr this week as well. I'm cleaning up a codebase that's a bit of a mess and it looks like this regex fails on some of the messier formats for some reason. I just forced some formatting for now, but I'll try to make it more robust.

**Comment by thymikee** [comment]
Awesome!
