### ISSUE TITLE
[Feature]: support jest.config.mjs

### ISSUE THREAD

**Issue by emzet** [thymikee/jest-preset-angular#1370]
### 🚀 Feature Proposal

Add support of jest.config.mjs as here https://github.com/facebook/jest/issues/9225

### Motivation

More compatible with Jest

**Comment by ahnpnl** [comment]
Can you be more specific about what to do for this preset? And what kind of issues are you running into with `jest.config.mjs`?

**Comment by emzet** [comment]
When I try to use `jest.config.mjs` I got this warning, so I assume that `.mjs` files are not supported currently by `jest-preset-angular` either I not found any info in documentation regarding usage of `jest.config.mjs` within this preset

```
warning: unable to locate custom jest configuration file at path "{stripped_path}\jest.config.js"
```

**Comment by ahnpnl** [comment]
We don’t take care of how Jest config is loaded. We only provide the necessary configuration to work with Jest, which is independent from Jest core. Loading Jest config is Jest core itself. 

If you are running Jest under node ESM mode and you get this issue, it’s most likely Jest issue itself. 

Besides, I see you are using Jest builder, which might cause issue too. 

This is out of scope for this preset :)
