### ISSUE TITLE
[Feature]: allow skipping ngcc-jest-processor 

### ISSUE THREAD

**Issue by Lonli-Lokli** [thymikee/jest-preset-angular#1396]
### 🚀 Feature Proposal

allow skipping ngcc-jest-processor (Related to https://github.com/thymikee/jest-preset-angular/pull/1013)

### Motivation

We have setup withing CI with several steps, first steps installs all dependencies with ngcc, others just using cached node_modules.

Right now ngcc-jest-processor do not allow skipping with some external args, only hardcoded. So with our setup with this command there is no way to skip running useless ngcc-jest

`jest --coverage --coverageDirectory=coverage/jest --reporters=default --reporters=jest-junit`

**Comment by ahnpnl** [comment]
This feature can only be used with Jest 28 because Jest 28 exposes `ProjectConfig` in `globalSetup`
