### ISSUE TITLE
Is coverage reliable?

### ISSUE THREAD

**Issue by nicolaspanel** [thymikee/jest-preset-angular#14]
hi @thymikee,

Running `jest --coverage` from a fresh angular-cli@1.0.0 project give me following outputs:
 - console:  
  ![2017-04-12 20-26-46](https://cloud.githubusercontent.com/assets/2500584/24973356/b87f2586-1fbe-11e7-8b49-e62e388bc00c.png)
 - browser:
  ![2017-04-12 20-28-00](https://cloud.githubusercontent.com/assets/2500584/24973360/bb4f1a32-1fbe-11e7-92d8-2f8d76279a24.png)

Branch coverage should be 100% on `app.component.ts`, right?

PS: thank you for this, amazing!

**Comment by thymikee** [comment]
Hi @nicolaspanel! 
Coverage is done by [istanbul](https://github.com/istanbuljs/istanbuljs) project and Jest presents the report, so maybe would be appropriate to ask there? 

Thanks for using it! :)

**Comment by dominique-mueller** [comment]
Hey @nicolaspanel, after reading @thymikee's article I just tried out this preset, and while it works like a charm I've experienced the same issue as you. The code coverage seemed a bit off.

Took me some research, but I think I finally found a solution; the following needs to be added to the *jest* configuration, e.g. the one in the `package.json` file:

``` json
"testResultsProcessor": "<rootDir>/node_modules/ts-jest/coverageprocessor.js"
```

This seems to actually trigger the Istanbul Coverage Remap process. @thymikee, is that something to be put in the `jest-preset.json` file of this package? I'm not sure, would that solve the issue for everyone?

**Comment by thymikee** [comment]
Definitely!

**Comment by thymikee** [comment]
Just published v0.1.0 with the fix 🙂

**Comment by nicolaspanel** [comment]
Thank you guys.

I updated jest-preset-angular to 0.1.0 but the coverage output is still the same.

Same result with jest `--no-cache` option as described [here](https://www.npmjs.com/package/ts-jest). 

Same result with following config:
```json
  ...
  "jest": {
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts",
    "testResultsProcessor": "<rootDir>/node_modules/ts-jest/coverageprocessor.js"
  }
```

Did it work for you ?
Best regards

**Comment by nicolaspanel** [comment]
After some digging, it seems to be related to `ts-jest` and `jest` (no workaround now, see https://github.com/kulshekhar/ts-jest/issues/42#issuecomment-256792842 for more info).

NB: correct coverage infos are located in `./coverage/remapped/...`

**Comment by dominique-mueller** [comment]
@nicolaspanel  Did you check the `remapped` folder within the `coverage` folder? That's where the remapped coverage gets placed in ...
