### ISSUE TITLE
[Bug]: wrong deprecation message

### ISSUE THREAD

**Issue by eng-dibo** [thymikee/jest-preset-angular#1411]
### Version

11

### Steps to reproduce

--

### Expected behavior

see the next section

### Actual behavior

we got the deprecation warning
```
ng-jest-processor is deprecated and will be removed in the next major version v12. Please use jest-preset-angular/global-setup in Jest config instead, e.g. 

    module.exports = {
       globalSetup: 'jest-preset-angular/global-setup',
    };
```

but the actual deprecated package is `ngcc-jest-processor`, not `ng-jest-processor`
https://github.com/thymikee/jest-preset-angular/pull/1275

### Environment

```shell
--
```

**Comment by ahnpnl** [comment]
fixed in **11.1.2**
