### ISSUE TITLE
adding all angular.io tests cases

### ISSUE THREAD

**Issue by Hotell** [thymikee/jest-preset-angular#142]
I've successfully migrated whole angular.io test suite to jest https://stackblitz.com/angular/ebxxmrjmbjp. It took me some time 🤯 💃 but in the end It's done. 

Opening this issue just to ask if you'll be ok if I add all those test to this repo for great coverage that everything works as it should be.

## Jest

![image](https://user-images.githubusercontent.com/1223799/38768159-7c0f45e8-3fef-11e8-8888-05fcad80bc9f.png)

## Karma/Jasmine

![image](https://user-images.githubusercontent.com/1223799/38768162-8af52140-3fef-11e8-8d1f-b8f86de10e7f.png)

cheers

**Comment by AhnpGit** [comment]
That would be nice 👍. @thymikee does leave an open issue at #110 to add more examples to the example app

**Comment by thymikee** [comment]
You're more than welcome to do so!

**Comment by ahnpnl** [comment]
Closes as duplicate with #110
