### ISSUE TITLE
Angular CLI environment setup

### ISSUE THREAD

**Issue by blackholegalaxy** [thymikee/jest-preset-angular#143]
### Example of environment use with Angular CLI and Karma

Using angular CLI native test setup with karma, we get an option in karma.conf.js to defined under which environment we want to execute the test suite. 

```
angularCli: {
      environment: 'test',
},
```

it can be useful to define specific test configuration values.

For example, we use `environment` configuration to execute some specific code depending on environment.

```
import { environment } from 'src/environments';

if (environment.production || environment.test) {
     this.service.doSomething();
    }
```

Testing these parts of code require us to be able to switch to `test` environment which will use `environment.tesst.ts` file.

### With Jest

I know jest doesn't actually compile the code using Angular CLI so I struggle to find a way to reproduce the environment thing with Jest. Basically, when setting the environment `--test` flag for example, Angular CLI  replaces `environment.ts` values with `environment.test.ts` ones.

So running tests with Jest basically always uses `environment.ts`

Is there any way we can ask jest to make that replacement and use of correct environment file during the tests? 

If it's impossible, how to mock this static file and replace values as needed within the spec file itself?

**Comment by thymikee** [comment]
I don't quite understand this. Jest _does_ compile your code and _doesn't_ have anything related to karma - you should delete it form the project.
Jest will also run your tests with `NODE_ENV=test`, unless you tell it otherwise.
If you want to use some kind of global setup for every test, use `setupFiles` for that

**Comment by blackholegalaxy** [comment]
You didn't understand my point. I was just making a comparison with karma conf. But i'm not using it.

And for the environment I talk about, it's an Angular CLI thing. So nothing in common with NODE_ENV. It's just a flag you set when running `ng` commands. Since jest doesn't seems to run angular CLI commands, we loose the hability to use this `ng` flag.

https://github.com/angular/angular-cli/wiki/stories-application-environments

**Comment by thymikee** [comment]
cc @Hotell @AhnpGit who are actually using Angular in their projects and can have better insights on the topic :)

**Comment by AhnpGit** [comment]
I encountered this issue since the 1st day I applied jest to my project. Until now I haven't found a way to have the same behavior like angular-cli. From what I understand angular-cli has some logics to get that environment option and pass it to karma. It is similar to create-react-app has a way to do similar thing inside test.js script if you eject the project.

I think to be able to do similar thing with karma for jest, we need to understand behind the scene what cli does then we can apply same thing for jest.

**Comment by blackholegalaxy** [comment]
For the `environment` file part at least. I think the CLI, when passed `--env=xyz` just takes all attributes in `environment.XXX.ts` and replace it in `environment.ts` in compiled code. 

Basically (of course not valid code):

`environment = {...environment, ...environmentXYZ}`

**Comment by AhnpGit** [comment]
perhaps you can try to combine with webpack `DefinePlugin` like this: https://codereviewvideos.com/course/react-redux-and-redux-saga-with-symfony-3/video/using-webpack-environment-variables-in-jest-tests . In the end those files `environment.prd.ts` or `environment.ts` to define global variables. I think if you can define via webpack `DefinePlugin`, you can have similar thing like angular-cli

**Comment by Hotell** [comment]
Hmm, to be completely honest, I really dislike proprietary things like CLI is doing with environments. I prefer to use `dotenv` like create-react-app with small custom script to make it work, then I have my `environment.ts` which just exports env variables

```ts
export const IS_DEV = process.env.NODE_ENV === 'development'
export const IS_PROD = process.env.NODE_ENV === 'production'
export const IS_TEST = process.env.NODE_ENV === 'test'

export const ENDPOINT = process.env.APP_ENDPOINT
export const API_VERSION = process.env.APP_API_VERSION
```

check https://medium.com/@natchiketa/angular-cli-and-os-environment-variables-4cfa3b849659

> perhaps you can try to combine with webpack DefinePlugin like this

ejecting is a no go for anyone  👀

> For the environment file part at least. I think the CLI, when passed --env=xyz just takes all attributes in environment.XXX.ts and replace it in environment.ts in compiled code

that `--env=xyz` is again a webpack proprietary stuff --> `module.exports = (env, argv) => {}` https://webpack.js.org/configuration/configuration-types/

> In a given test suite file, I managed to mock is using something like...

or you can create explicitly `__mock__` directory within your `environments` folder so you don't have to invoke `jest.mock('../environment/environment')` manually everytime

```
environment/
  |-__mocks__/
  |-- |- environment.ts
  |-environment.ts
  |-environment.test.ts
  |-environment.prod.ts
```

and `environment/__mocks__/environment.ts` just `export * from '../environment.ts'`

**OR**

 you can import `environment/environment` via path aliasing ( absolute path import ) and setup jest `moduleMapper` o point to your particular environment file

https://facebook.github.io/jest/docs/en/configuration.html#modulenamemapper-object-string-string

**Comment by blackholegalaxy** [comment]
Wow plenty of stuff. Will dig into it for a solution :) thanks for your help on that :)

**Comment by ddehghan** [comment]
For anyone else that got here:

you can use module mapper to load different environments in your tests. 

> mycode.ts
> import {environment} from '../../../../environments/environment';
> 

In jest config:

>  moduleNameMapper: {
>         '^(.*)environments(.*)$': '<rootDir>/src/environments/environment.devserver.ts',
> }

**Comment by oveits** [comment]
@ddehghan : your comment helped me a lot. I had to replace (.) by (.*), though:

    mycode.ts
    import {environment} from '../../../../environments/environment';

In jest config:

    moduleNameMapper: {
    '^(.*)/environments/(.*)$': '/src/environments/environment.jest.ts',
    }

**Comment by AnderssonPeter** [comment]
To allow relative imports I changed the regex to the following `'^(.*/)?environments/(.*)$'`.

I had a file in the `src` directory that imported the environment and that gave the following line `import { environment } from 'environments/environment';` and the regex from the comment above didn't work there.
