### ISSUE TITLE
[Feature]: Add option to transform esm's `import` into cjs `require`

### ISSUE THREAD

**Issue by maxkoretskyi** [thymikee/jest-preset-angular#1437]
### 🚀 Feature Proposal

Add option to transform esm's `import` into cjs `require`, so that code like this:

```
var defaultEditorExtensions = [
    import('@tiptap/starter-kit').then(defaultExtractor).then(starterKitConfigurator),
    ...
]
```

can be transformed to this:

```
var defaultEditorExtensions = [
    require('@tiptap/starter-kit').then(defaultExtractor).then(starterKitConfigurator),
    ...
]
```

### Motivation

In my Angular project I use `taiga-ui-addon-editor-extensions` library that ships `umd` bundles with ESM like this:

```
var defaultEditorExtensions = [
    import('@tiptap/starter-kit').then(defaultExtractor).then(starterKitConfigurator),
    ...
]
```

To be able to run Jest, they need to be transformed into CommonJS `require`. It seems like `NgJestTransformer` can't do that. 

I put a `debugger` [where the transformation happens](https://github.com/thymikee/jest-preset-angular/blob/1f0a00917ebed61873b8f32c22fbe0d442d3b576/src/ng-jest-transformer.ts#L76-L76) and although `use ESM` is `false`

![image](https://user-images.githubusercontent.com/6124091/166094744-d93bab29-7bc7-4bbd-b545-6cb87d288103.png)

the output still contains `import` statements.

Currently I'm solving it by simply removing the library from regex that 'jest-preset-angular' is using, and this makes default `babel-jest` transformer to do that job:

```
transform: {
  '^(?!.*(taiga-ui-addon-editor-extensions)).*(ts|mjs|js|html)$': 'jest-preset-angular',
},
transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$|@taiga-ui.*\\.js$)'],
```

but it would be great if I could do it with `jest-preset-angular`.

**Comment by ahnpnl** [comment]
Hi, what you do is the correct way. We are transforming codes based on what Jest tells us. A Jest transformer can’t decide on its own. Unfortunately your request can’t be done with Jest architecture.

**Comment by maxkoretskyi** [comment]
@ahnpnl thanks, could you please elaborate more on this? I'm trying to understand

> We are transforming codes based on what Jest tells us. A Jest transformer can’t decide on its own. 

I see in the debugger that the original code is processed with `NgJestTransformer` and is fed into `esbuild`

> I also tried putting a simple thing like const foo = import('@angular/core'); which is transformed correctly to var import_core = require("@angular/core"); by esbuild.

I should've mentioned that the library I'm using is JavaScript file, not TypeScript.

**Comment by ahnpnl** [comment]
Yes I tested by manually modifying a `js` file in `node_modules` and let `esbuild` process it, which gives the correct output. 

I think for your case, it's either `esbuild` issue or your file isn't processed by `NgJestTransformer` which makes the `import` syntax not transformed. 

Would you please try to put your problem into https://github.com/thymikee/jest-preset-angular/tree/main/examples/example-app-v13 ?

**Comment by maxkoretskyi** [comment]
@ahnpnl , sure, [there you go](https://github.com/maxkoretskyi/jest-preset-angular/commit/74ae21916c34759100186b400114dee38a03928d). Thanks!

**Comment by ahnpnl** [comment]
The problem is because of `esbuild`. Now we introduce a new config option which allows to configure which files to be processed by `esbuild`

**Comment by ahnpnl** [comment]
Yes exactly. When I debugged and I could see that `esbuild` transform result is different from TypeScript API.

**Comment by maxkoretskyi** [comment]
@ahnpnl cool, thanks! so I'll wait for the upcoming release, give it a try and let you know how it goes

**Comment by ahnpnl** [comment]
You can try now with `next` tag. However, the fix only guarantees that TypeScript API was used but won’t guarantee if the tests will work. Of course you can add console log in transformer codes and see the output

**Comment by maxkoretskyi** [comment]
@ahnpnl just tried it on `@12.0.1`, all good, thanks!
