### ISSUE TITLE
[Bug]: Missing jest and typescript as peerDependencies

### ISSUE THREAD

**Issue by bulldog98** [thymikee/jest-preset-angular#1441]
### Version

11.1.1, 11.1.2

### Steps to reproduce

1. Clone my repo at https://github.com/bulldog98/jest-preset-angular-missing-peerdeps-reproduction
2. yarn install
3. Observe the warning of yarn about

### Expected behavior

I expected to see no warning about missing typescript and jest

### Actual behavior

➤ YN0000: ┌ Resolution step
➤ YN0002: │ jest-preset-angular@npm:11.1.2 [a1418] doesn't provide jest (p6947d), requested by ts-jest
➤ YN0002: │ jest-preset-angular@npm:11.1.2 [a1418] doesn't provide typescript (pb8907), requested by ts-jest
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 215ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 354ms
➤ YN0000: Done with warnings in 0s 929ms

### Environment

```shell
yarn 3.2.0
```

**Comment by bulldog98** [comment]
I'd be willing to provide a PR to fix this issue

**Comment by ahnpnl** [comment]
Thanks!
