### ISSUE TITLE
[Question]: yarn workspace configuration

### ISSUE THREAD

**Issue by paulsouche** [thymikee/jest-preset-angular#145]
Hi,

This is not really an issue but I'm pretty new to jest and I wanted to know if my yarn workspace integration could be better.

Here is my jest config

```json
  "jest": {
    "globals": {
      "ts-jest": {
        "tsConfigFile": "src/tsconfig.json"
      }
    },
    "transform": {
      "^.+\\.(ts|js|html)$": "<rootDir>../../node_modules/jest-preset-angular/preprocessor.js"
    },
    "preset": "jest-preset-angular",
    "roots": [
      "<rootDir>/src/"
    ],
    "setupFiles": [
      "whatwg-fetch",
      "jest-localstorage-mock"
    ],
    "setupTestFrameworkScriptFile": "<rootDir>/setup-jest.ts",
    "snapshotSerializers": [
      "<rootDir>../../node_modules/jest-preset-angular/AngularSnapshotSerializer.js",
      "<rootDir>../../node_modules/jest-preset-angular/HTMLCommentSerializer.js"
    ]
  }
```

You can see as node_modules are not in cwd, I have to override `transform` && `snapshotSerializers`. This work as is but I wonder if there is a better way to achieve this ?

I hope others can find it usefull.

Thanks anyway for the great job ! I definitely buried karma because of you and, for that, I owe you one.

**Comment by thymikee** [comment]
Hey @paulsouche, I'm afraid there's nothing more I can do to make it easier. Preset is just a preset. 

FWIW you can move snapshot serializers to your `setup-jest.ts` file using `expect.addSnapshotSerializer()` API: https://facebook.github.io/jest/docs/en/expect.html#expectaddsnapshotserializerserializer

**Comment by paulsouche** [comment]
Thanks for your quick answer ! I will have a look at this ASAP.

What about a README PR for this case (and maybe for snapshots solution). I found lot of solutions in it and I think it's a perfect place.

Let me know about this.

**Comment by thymikee** [comment]
Sure, I'm always happy to accept such PRs :)

**Comment by tsvayer** [comment]
Hi @paulsouche @thymikee 
It can be specified as `jest-preset-angular/preprocessor.js` instead of `<rootDir>/node_modules/jest-preset-angular/preprocessor.js` and then it will be resolved using usual module resolution strategy. The same for `AngularSnapshotSerializer.js` and `HTMLCommentSerializer.js`.
It seems to work ok in normal npm based project and in yarn workspaces environment as well.
What do you think?

**Comment by ahnpnl** [comment]
You can use Jest `projects` to achieve this.  We have an example here https://github.com/thymikee/jest-preset-angular/blob/master/examples/example-app-v12-monorepo/jest.config.js
