### ISSUE TITLE
Support jest@28

### ISSUE THREAD

**Issue by kirillgroshkov** [thymikee/jest-preset-angular#1454]
### 🚀 Feature Proposal

Would be nice to support jest@28

### Motivation

&nbsp;

**Comment by ghiscoding** [comment]
that is what the `next` is for, it works nicely on my side with the following
```json

**Comment by wtho** [comment]
@kirillgroshkov feel free to test out your project with the `-next` version, feedback is highly appreciated.

**Comment by ahnpnl** [comment]
Please try out `next-2` as it's close to stability state for final release.
