### ISSUE TITLE
[Bug]: Coverage fails when extending a class from another library, but test passes

### ISSUE THREAD

**Issue by boyanio** [thymikee/jest-preset-angular#1472]
### Version

11.1.2

### Steps to reproduce

1. Clone https://github.com/boyanio/jest-angular-issue-coverage
2. `npm i`
3. `npx ng test --coverage` fails, but `npx ng test` works

### Expected behavior

I expect the coverage to pass

### Actual behavior

It fails

### Additional context

Similar to https://github.com/thymikee/jest-preset-angular/issues/1152 I have encountered that `--coverage` fails when you extend a class from another external library and add a property with a default value to this class (see `toggle.component.ts` in my repo).

### Environment

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) x64 Apple M1 Pro
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    npm: 6.14.16 - /usr/local/bin/npm
  npmPackages:
    jest: ^27.4.7 => 27.5.1
```

**Comment by ahnpnl** [comment]
I'm not sure what can be the reason. Your problem doesn't popup in our example app https://github.com/thymikee/jest-preset-angular/tree/main/examples/example-app-v13 Would you pls try to reproduce there? 

I noticed that your repo is using ng-jest/builder so I would recommend you to try to reproduce in our example apps.

**Comment by ahnpnl** [comment]
I know one thing that coverage report is done byJest via instanbul plugin Babel, which we are not in control. Probably configuring something for Babel would solve the issue.

**Comment by ahnpnl** [comment]
OK i found the fix for your case. You will need to do these followings:
- In `jest.config.js`, declare Babel usage
```
globals: {
    'ts-jest': {
      babelConfig: true,
    }
  },
```
- Add `.babelrc` to root of your repo with the following content
```
{
  "plugins": ["@babel/plugin-transform-classes"]
}
```

The problem is that, Jest coverage uses Babel behind the scene which `jest-preset-angular` doesn't control that.

I will update documentation about this.

**Comment by boyanio** [comment]
@ahnpnl thank you for the quick response and the provided explanation - it does indeed solve the issue!
