### ISSUE TITLE
Overriding getTestBed initTestEnvironment

### ISSUE THREAD

**Issue by villelahdenvuo** [thymikee/jest-preset-angular#148]
It seems like the preset calls the initTestEnvironment automatically, if I would like to register a global module for all tests Angular will complain that it has already been called.

Is there any way to tell the preset not to call it for me? My use case is to import NoopAnimationsModule globally to avoid adding it to a million test files.

**Comment by thymikee** [comment]
This is just a preset. You can provide your own `setupJest` file without calling `initTestEnvironment`.

**Comment by villelahdenvuo** [comment]
@thymikee You're completely correct, I was under the impression that the module did something more in the background, but I can just copy the preset and modify it for my needs. Sorry for the inconvenience!

**Comment by thymikee** [comment]
no worries! :)
