### ISSUE TITLE
angular 6 

### ISSUE THREAD

**Issue by PsychicCat** [thymikee/jest-preset-angular#149]
I get a lot of tests failing after upgrading to Angular 6. Anyone else? The error message is not very informative, I will have some more time to drill down into the problem this weekend.

```
  ● Test suite failed to run

    TypeError: Converting circular structure to JSON
        at JSON.stringify (<anonymous>)

      at readCompilerOptions (node_modules/ts-jest/dist/utils.js:41:26)
      at Object.getTSConfig (node_modules/ts-jest/dist/utils.js:101:16)
      at process (node_modules/ts-jest/dist/preprocessor.js:10:35)
      at Object.module.exports.process (node_modules/jest-preset-angular/preprocessor.js:13:10)
```

**Comment by AhnpGit** [comment]
I haven't tried with Angular 6 yet. But the first line of the error log shows something related to ts-jest. Perhaps you can check in their repo first ?

**Comment by PsychicCat** [comment]
@AhnpGit will do, thanks.

**Comment by AhnpGit** [comment]
@PsychicCat I just submitted a PR to upgrade example app of this repository to Angular 6. So far I haven't encountered any issues like you described. Perhaps you can take a look at the example app in my PR.
I also generated a completely new Angular 6 project with CLI v6 and put a base setup with Jest, nothing is broken. 

Can you please provide a sample project that you encountered the error ?

**Comment by matthiaskern** [comment]
@PsychicCat 
Check your `src/tsconfig.spec.json`.
`ng update` messed up my configuration which resulted in the same error.

**Comment by PsychicCat** [comment]
@matthiaskern thanks! 

Indeed, the schematics must have something wrong as example shown below. all tests green now 👍 

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "baseUrl": "./",
    "module": "commonjs",
    "types": ["jest", "node"],
    "allowJs": true
  },
  "files": ["test.ts"  "polyfills.ts"
  ,],
  "include": ["**/*.spec.ts", "**/*.d.ts"]
}
```
