### ISSUE TITLE
Help with configuring Jest on a nx workspace

### ISSUE THREAD

**Issue by joelmuskwe** [thymikee/jest-preset-angular#152]
Do you know how i can configure jest on a nx workspace with multiple libs and apps?

i followed instructions and i discovered that major challenge is specifying location of tsconfig.spec.json

and i had to change the jest-preset.json in the jest-preset-angular from
   `"ts-jest": {
      "tsConfigFile": "src/tsconfig.spec.json"
    },`
to
`"ts-jest": {
      "tsConfigFile": "tsconfig.spec.json"
    },`

is there a way i can overide the location say in the package.json

**Comment by thymikee** [comment]
You can override anything in the preset, it's just a base for your configuration.

**Comment by joelmuskwe** [comment]
do you have example of an override sorry for the trouble

**Comment by thymikee** [comment]
https://github.com/thymikee/jest-preset-angular/blob/master/README.md#usage

We define a preset and next we can override anything, like setupTestFrameworkScriptFile if it was defined by a preset.
