### ISSUE TITLE
Angular 6 template doesn't seem recompiled on forms

### ISSUE THREAD

**Issue by blackholegalaxy** [thymikee/jest-preset-angular#157]
I have a basic form with error:

```
<input type="email" class="login-input" formControlName="login" autocomplete="off">
<div *ngIf="login.invalid && login.touched" class="login-error">
  <p class="login-error__required" 
    *ngIf="login.hasError('required')">Required</p>
  <p class="login-error__invalid-email" 
    *ngIf="!login.hasError('required') && login.hasError('email')">Invalid email</p>
</div>
```

Here is the `login` getter:

```
get login(): AbstractControl {
    return this.loginForm.get('login');
  }
```

Here is my test:

```
describe('when login is invalid', () => {
        describe('due to empty value', () => {
          beforeEach(() => {
            component.login.setValue('');
            component.login.markAsTouched();
            fixture.detectChanges();
          });

          it('should display required error message', () => {
            expect(component.login.touched).toBe(true);
            expect(component.login.invalid).toBe(true);
            expect(fixture.loginError).toBeTruthy();
            expect(fixture.loginErrorRequired).toBeTruthy();
          });
        });
});
```

The tests fails at ` expect(fixture.loginError).toBeTruthy();`. The values of touched and invalid are correctly set to true in the reactive form. But the template ngIf is not "updated".

This test used to pass in Angular 5 and doesn't anymore in Angular 6. Please note that when running the app, the form behaves as expected.

If I remove `login.touched` condition in the `*ngIf` condition, then the test passes, but the behavior is incorrect for our use case.

A console log in the test of `login.touched` and `login.invalid` both return true.

I don't really get why, but the template is not properly refreshed.

Also please note: 

If I trigger a blur event, the tests passes

```
beforeEach(() => {
            component.login.setValue('');
            fixture.debugElement.query(By.css('.login-input')).triggerEventHandler('blur', null);
            fixture.detectChanges();
          });
```

**Comment by blackholegalaxy** [comment]
Closed. Not a jest nor preset problem.

**Comment by Darkein** [comment]
I have the same problem with a new app generated with angular-cli, with the appComponent :
```
    Expected string:
      " Welcome to ! "
    To contain value:
      "Welcome to app!"
```

it seems that `fixture.detectChanges();` is not taken into account when it's not in `beforeEach()`, even with  `default` changeDetection.

the test is the following:
```
  it('should render title in a h1 tag', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('h1').textContent).toContain('Welcome to app!');
  }));
```
