### ISSUE TITLE
[Feature]: Add support for `ng add` schematic for initial setup

### ISSUE THREAD

**Issue by brandonroberts** [thymikee/jest-preset-angular#158]
Makes it a little easier for those using the `Angular CLI` to install the package and handle the initial setup. I can work a PR for this if needed.

**Comment by davinkevin** [comment]
I've done this recently 😎
> https://github.com/davinkevin/jest

It's a really basic setup

**Comment by ahnpnl** [comment]
Close as not in preset scope. This can be done by extending angular CLI schematics.
