### ISSUE TITLE
Issues with NX Workspace on the tsConfigFile configuration

### ISSUE THREAD

**Issue by joelmuskwe** [thymikee/jest-preset-angular#159]
Is it possible to use a regex expression for the tsConfigFile below:
`"ts-jest": {
      "tsConfigFile": "src/tsconfig.spec.json"
    },`
to
`"ts-jest": {
        "tsConfigFile": "<rootDir>/apps/**/tsconfig.spec.json"
      },`

my issue is with nx workspaces i can create multiple apps that have their own tscongig.spec.json hence it is failing to locate them

**Comment by AhnpGit** [comment]
Yes you can overwrite the settings

**Comment by thymikee** [comment]
You're using glob, not regex. Using regex will probably fix the issue. If not, feel free to reach out to the `ts-jest` maintainers :)

**Comment by Nxt3** [comment]
@joelmuskwe Have you figured out how to setup Jest with Nrwl 6?

**Comment by lonix1** [comment]
@joelmuskwe @Nxt3 Did you figure it out or have a config snippet to share? The new version of nx doesn't work with this anymore.

**Comment by ahnpnl** [comment]
cc @FrozenPandaz
