### ISSUE TITLE
Importing undefined which does not have a ɵmod property at node_modules/@angular/core/fesm2015/core.mjs:24155:19 [ProxyZone] at Array.forEach

### ISSUE THREAD

**Issue by Avinash4243** [thymikee/jest-preset-angular#1605]
![image](https://user-images.githubusercontent.com/22216832/171601257-c4a79056-7d84-491d-aaaa-85d2aaa3a1f4.png)
![image](https://user-images.githubusercontent.com/22216832/171601312-8727ca03-feb6-4631-8703-249d50d2b39e.png)

**Comment by ahnpnl** [comment]
Would you please provide information following the GitHub template like how to reproduce it, a reproduce repo, your environment, version of jest etc…

Without those information, it is not possible to debug what you are showing in the screenshot.
