### ISSUE TITLE
Snapshot with outerHTML of fixture.

### ISSUE THREAD

**Issue by etavener** [thymikee/jest-preset-angular#161]
In the past i had:

`expect(fixture).toMatchSnapshot();`

However, I've had memory issues with Angular 5 and I've been advised to use this instead:

`expect(fixture.debugElement.nativeElement.outerHTML).toMatchSnapshot();`

The problem is that the whitespace / formatting with my snapshots has all changed and misaligned.

I already use the `.configureCompiler({ preserveWhitespaces: false } as any )` in my tests and removing this doesn't help.

Does anyone have a solution or experienced similar? Ideally i don't want to change the snapshots just for bad formatting.

**Comment by ahnpnl** [comment]
Hi,

Unfortunately as far as I know, there is no workaround for this issue. preserveWhitespaces option only works on fixture but it doesn't work with nativeElement.outerHTML. I don't know why it is like that but you can try to put the question related to that to the Angular team.

**Comment by etavener** [comment]
Hi,

I've done a bit more digging.

I've just seen this issue, https://github.com/thymikee/jest-preset-angular/issues/134

If i use `fixture.debugElement.nativeElement.outerHTML` instead of `fixture` it seems like the jest-preset-angular serialiser is not used. This is why the formatting of my snapshots is bad.

Any idea why this is? I don't know enough about how the snapshots or serializers work to understand this.

**Comment by ahnpnl** [comment]
Hi @etavener,

Regarding to the memory issue, it might be related to [this](https://github.com/angular/angular/issues/24048). From my point of view, the tests also need to be written in a performant way as well, that would help a bit. For now I think we have to wait for the Angular team to solve the issue with TestBed. 

I haven't tried to debug further yet into how snapshot serializer is used with fixture but not with nativeElement so I don't really know about that one.

**Comment by ahnpnl** [comment]
Close as inactivity
