### ISSUE TITLE
[Bug]: Cannot use import statement outside a module for some esm.js dependencies

### ISSUE THREAD

**Issue by blackholegalaxy** [thymikee/jest-preset-angular#1625]
### Version

12.1.0 

Please note this didn't occured in previous versions of preset / jest 27 but we had to update to keep up with angular 14. Keeping old versions along with angular 14 doesn't work.

### Steps to reproduce

On a repository using `firebase` dependencies, we cannot run tests anymore since update to latest jest-angular-preset and jest 28. At first we didn't have much configuration

### Initial configuration

**jest.config.js**

```
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/src/setupJest.ts'],
  globalSetup: 'jest-preset-angular/global-setup',
```

### Error

```
/Users/X/dev/ourApp/node_modules/firebase/compat/auth/dist/index.esm.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import '@firebase/auth-compat';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1773:14)
      at node_modules/@angular/fire/bundles/angular-fire-compat-auth.umd.js:2:85
      at Object.<anonymous> (node_modules/@angular/fire/bundles/angular-fire-compat-auth.umd.js:5:2)
```

### fix attempt using babel

**jest.config.js**

```
preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/src/setupJest.ts'],
  globalSetup: 'jest-preset-angular/global-setup',
  transform: {
    '^.+\\.(ts|html)$': 'jest-preset-angular',
    '^.+\\.js$': 'babel-jest',
  },
```

**babel.config.js**
```
module.exports = {
  presets: ['@babel/preset-env'],
  env: {
    test: {
      plugins: ["@babel/plugin-transform-runtime"]
    }
  }
};
```

### Error is the same

```
/Users/X/dev/ourApp/node_modules/firebase/compat/auth/dist/index.esm.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import '@firebase/auth-compat';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1773:14)
      at node_modules/@angular/fire/bundles/angular-fire-compat-auth.umd.js:2:85
      at Object.<anonymous> (node_modules/@angular/fire/bundles/angular-fire-compat-auth.umd.js:5:2)
```

### Expected behavior

We expect preset to manage transforms for all required files and avoid `SyntaxError: Cannot use import statement outside a module` error on some js files in `node_modules`.

### Actual behavior

`SyntaxError: Cannot use import statement outside a module` error on some js files in `node_modules`.

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  npmPackages:
    jest: 28.1.0 => 28.1.0
```

**Comment by ahnpnl** [comment]
The preset can't transform everything by default. The preset has a Jest transformer, which receives files to transform from Jest module resolution. 

For your case, you need to adjust `transformIgnorePatterns` to process the files from `'@firebase/auth-compat'` since Jest detects that the module is not CJS. 

You can also run test in ESM mode if you wish. Please check our documentation for it https://thymikee.github.io/jest-preset-angular/docs/

**Comment by blackholegalaxy** [comment]
We tried to add to transformIgnorePatterns the files, but with both configuration, error still occurs.

**Comment by ahnpnl** [comment]
@blackholegalaxy i can help to fix the transformIgnorePattern thing, but I need reproduce scenario. You can use the example app in `examples` folder to do it. That would be helpful

**Comment by blackholegalaxy** [comment]
I will provide this later this week as I am sure others will fall into same problems

**Comment by blackholegalaxy** [comment]
@ahnpnl  here is the repro. https://github.com/blackholegalaxy/repro-bug-jest

I cleared most of our project files but i left one test with the mentionned problem: window-ref service. I will be sufficient to trigger the error.

Don't try running the app it will for sure crash :)

**Comment by ahnpnl** [comment]
strangely with your repo, I did
```
transformIgnorePatterns: [
    "node_modules/(?!@angular|@firebase|firebase|@ngrx)",
    // 'node_modules/(?!.*\\.mjs$)'
  ],
```
and the tests passed (with clear cache)

**Comment by blackholegalaxy** [comment]
I tried on our full repo, deleting mjs entry in transformIgnorePatterns doesn't work as it did for you it seems. The error is exactly the same.

Also, any idea on why we cannot add mjs ignore entry along with others? It may be required in some projects.

**Comment by ahnpnl** [comment]
I just managed to find back the thread https://github.com/facebook/jest/issues/12584#issuecomment-1094034513

**Comment by blackholegalaxy** [comment]
I had a look at that post in my search for answers. I tried to change on our project to:

```
const esModules = ['@angular', '@firebase', 'firebase', '@ngrx'].join('|');

transformIgnorePatterns: [
    `/node_modules/(?!(${esModules}|.*.mjs$))`,
  ],
```

It leaded to:
```
node_modules\@angular\fire\node_modules\@firebase\firestore\dist\index.esm2017.js:12705
                    function (t, e) {
                    ^^^^^^^^

    SyntaxError: Function statements require a function name

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1773:14)
      at Object.<anonymous> (node_modules/@angular/fire/node_modules/@firebase/firestore-compat/dist/index.esm2017.js:2:1)
```

**Comment by ahnpnl** [comment]
It seems like the `index.esm2017.js` is funny somehow. Probably you need to `moduleNameMapper` to tell Jest to map to `umd` or `cjs` file instead

**Comment by ahnpnl** [comment]
> It seems it's because it's a sub node_modules folder. I am not sure to understand what you are suggesting. Do you have any example?

I don't see this in your reproduce repo :o


> I had a look at that post in my search for answers. I tried to change on our project to:
> 
> ```
> const esModules = ['@angular', '@firebase', 'firebase', '@ngrx'].join('|');
> 
> transformIgnorePatterns: [
>     `/node_modules/(?!(${esModules}|.*.mjs$))`,
>   ],
> ```
> 
> It leaded to (it seems it's because it's a sub node_modules folder)
> 
> ```
> node_modules\@angular\fire\node_modules\@firebase\firestore\dist\index.esm2017.js:12705
>                     function (t, e) {
>                     ^^^^^^^^
> 
>     SyntaxError: Function statements require a function name
> 
>       at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1773:14)
>       at Object.<anonymous> (node_modules/@angular/fire/node_modules/@firebase/firestore-compat/dist/index.esm2017.js:2:1)
> ```

Did you also run with `--no-cache` flag?

**Comment by blackholegalaxy** [comment]
I pushed a new commit on my repo to reproduce this. Yes ran with no cache every time to ensure proper isolation :)

**Comment by ahnpnl** [comment]
Ok so I managed to find the repeated pattern which you can try to fix. Here is the on-going Jest config which I tried out
```
module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/src/setupJest.ts'],
  globalSetup: 'jest-preset-angular/global-setup',
  moduleNameMapper: {
    'assets/(.*)': '<rootDir>/src/assets/$1',
    '@core/(.*)': '<rootDir>/src/app/core/$1',
    '@env': '<rootDir>/src/environments/environment',
    'environments/(.*)': '<rootDir>/src/environments/$1',
    'firebase/compat': '<rootDir>/node_modules/firebase/compat/dist/index.node.cjs',
    '@firebase/util': '<rootDir>/node_modules/@firebase/util/dist/index.node.cjs.js'
  },
  coverageReporters: ['html', 'text-summary', 'text'],
  collectCoverageFrom: [
    'src/app/core/**/*.ts',

    // Exclusions
    '!src/app/*.ts',
    '!src/app/core/store/utils/*.ts',
    '!src/tests/**/*.ts',
    '!src/environments/*.ts',
    '!src/*.ts',
    '!src/app/**/*.module.ts',
    '!src/app/**/*.routes.ts',
    '!src/app/**/*.model.ts',
    '!src/app/**/models/*.ts',
    '!src/app/**/models/**/*.ts',
    '!src/app/**/model/*.ts',
    '!src/app/**/model/**/*.ts',
    '!src/app/**/animations/*.ts',
    '!src/app/**/*.animation.ts',
    '!src/app/**/vendors.ts',
    '!src/app/**/index.ts',
  ],
  modulePathIgnorePatterns: [
    '<rootDir>/coverage/',
  ],
  cacheDirectory: './jest-cache'
};
```

# How to proceed further

There are 2 repeated patterns here:

- `'firebase/compat': '<rootDir>/node_modules/firebase/compat/dist/index.node.cjs',` 
This pattern applies to all packages under `firebase`. You need to configure the regex in such a way that it would look like
```
'firebase/<package_name>': '<rootDir>/node_modules/firebase/<package_name>/dist/index.node.cjs',
```

- `'@firebase/util': '<rootDir>/node_modules/@firebase/util/dist/index.node.cjs.js'`
This pattern applies to all packages under `@firebase`. You need to configure the regex in such a way that it would look like
```
'@firebase/<package_name>': '<rootDir>/node_modules/@firebase/<package_name>/dist/index.node.cjs.js'
```

I hope this can guide you to go further.

**Comment by blackholegalaxy** [comment]
I used your guidelines to add proper packages individually.

```
'firebase/compat/auth': '<rootDir>/node_modules/firebase/auth/dist/index.cjs.js',
    '@firebase/auth': '<rootDir>/node_modules/@firebase/auth/dist/node/index.js',
    '@firebase/util': '<rootDir>/node_modules/@firebase/util/dist/index.node.cjs.js',
    'firebase/app': '<rootDir>/node_modules/firebase/app/dist/index.cjs.js'
```

Then I land in a different issue. We can see that in the repro I gave earlier. That's REALLY weird haha.

```
TypeError: app.registerVersion is not a function

      1 | import { Injectable } from '@angular/core';
      2 | import { Router } from '@angular/router';
    > 3 | import { AngularFireAuth } from '@angular/fire/compat/auth';
        | ^
      4 | import { AngularFirestore } from '@angular/fire/compat/firestore';
      5 |
      6 | import { of, combineLatest } from 'rxjs';

      at Object.registerVersion (node_modules/firebase/app/index.ts:20:1)
      at Object.<anonymous> (node_modules/@firebase/auth/dist/node/index-cc504aa1.js:5:11)
      at Object.<anonymous> (node_modules/@firebase/auth/dist/node/index.js:5:13)
      at Object.<anonymous> (node_modules/firebase/auth/dist/index.cjs.js:5:12)
      at node_modules/@angular/fire/bundles/angular-fire-compat-auth.umd.js:2:85
      at Object.<anonymous> (node_modules/@angular/fire/bundles/angular-fire-compat-auth.umd.js:5:2)
```

**Comment by ahnpnl** [comment]
I updated a bit 
```
'firebase/compat': '<rootDir>/node_modules/firebase/firebase-compat.js',
'firebase/app': '<rootDir>/node_modules/firebase/firebase-app.js',
'firebase/remote-config': '<rootDir>/node_modules/firebase/firebase-remote-config.js',
'@firebase/auth': '<rootDir>/node_modules/@firebase/auth/dist/node/index.js',
'@firebase/util': '<rootDir>/node_modules/@firebase/util/dist/index.node.cjs.js',
```

with 
```
const esModules = ['firebase', '@firebase'].join('|');

transformIgnorePatterns: [
    `/node_modules/(?!(${esModules}|.*.mjs$))`,
  ],
```

However, now the error is something else 
```
 FAIL  src/app/core/services/window-ref/window-ref.service.spec.ts
  ● Test suite failed to run

    Cannot find module 'https://www.gstatic.com/firebasejs/9.8.2/firebase-app.js' from 'node_modules/firebase/firebase-remote-config.js'
```

Not sure how to fix this one, but I think this is as far as I can help with and it's not in the scope of this preset can handle.

**Comment by ahnpnl** [comment]
Another config which results into the same error is
```
'firebase/app': '<rootDir>/node_modules/firebase/firebase-app.js',
    'firebase/remote-config': '<rootDir>/node_modules/firebase/firebase-remote-config.js',
    '@angular/fire': '<rootDir>/node_modules/@angular/fire/bundles/angular-fire.umd.js',
    '@angular/fire/compat': '<rootDir>/node_modules/@angular/fire/bundles/angular-fire-compat.umd.js',
    '@angular/fire/compat/auth': '<rootDir>/node_modules/@angular/fire/bundles/angular-fire-compat-auth.umd.js',

transformIgnorePatterns: [
    `node_modules/(?!.*\\.mjs|firebase)`,
  ],
```

I think you do need to mock something for your test to let it not doing too deep import

**Comment by tja4472** [comment]
Using a resolver seems to work:crossed_fingers:
see:

https://github.com/tja4472/ng-angularfire-testbed-single-app/blob/cypress-10/jest-resolver.js

https://github.com/tja4472/ng-angularfire-testbed-single-app/blob/cypress-10/jest.config.js#:~:text=resolver%3A%20%27%3CrootDir%3E/jest%2Dresolver.js%27%2C

**Comment by dereekb** [comment]
The resolver ultimately cleared up the import issues in my project. Was fighting my configurations and caching for a while but figured it out. Despite using @angular/fire I didn't have to add anything related to that, but I did have to [add almost every single @firebase package](https://github.com/dereekb/dbx-components/pull/12/files#diff-af33cb687b3bdd547590c1e24531fd6e3d41d4d6cbe4755a7053611dc1e1766e) to get handled properly.

**Comment by blackholegalaxy** [comment]
@dereekb I can confirm using a resolver worked except for one single test relying on `firebase.auth`. Since the resolver delete some parts, it may cause this I guess.

```
TypeError: Cannot read properties of undefined (reading 'FacebookAuthProvider')

import firebase from 'firebase/compat/app';
import '@firebase/auth';

      19 | import { WindowRefService } from '../window-ref/window-ref.service';
      20 |
    > 21 | export const facebookAuthProvider = new firebase.auth.FacebookAuthProvider();
         |                                                       ^
      22 | export const googleAuthProvider = new firebase.auth.GoogleAuthProvider();
      23 | export const appleAuthProvider = new firebase.auth.OAuthProvider('apple.com');
      24 | export const twitterAuthProvider = new firebase.auth.TwitterAuthProvider();
```

**Comment by dereekb** [comment]
What version of firebase are you using? You might want to try adding more of those compats to the resolver ignore/fix list. The errors were fairly helpful in figuring out what needed to be ignored in my case. [From this one](https://app.circleci.com/pipelines/github/dereekb/dbx-components/841/workflows/ff8f478d-8f42-473c-a8ca-824edcf0dfbf/jobs/2051/parallel-runs/0/steps/0-105):

```
  Details:

    /home/circleci/code/node_modules/@firebase/firestore/dist/index.esm2017.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { _registerComponent, registerVersion, _getProvider, getApp, _removeServiceInstance, SDK_VERSION } from '@firebase/app';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { CollectionReference, doc, getDoc, setDoc } from '@firebase/firestore';
        | ^
      2 | import { MockItemCollectionFixture, testWithMockItemFixture } from '../common/firestore.mock.item.fixture';
      3 | import { authorizedFirestoreFactory } from './firestore.authorized';
      4 |

      at Runtime.createScriptFromCode (../../../node_modules/@jest/core/node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (src/lib/client/firestore.mock.item.spec.ts:1:1)
```

I added both @firebase/firestore and @firebase/app. It is mostly an obnoxious game of guess and check though. I tried ignoring all "@firebase/" prefixed packages (pkg.name.startsWith('@firebase/') and that seemed to break the resolver.

**Comment by blackholegalaxy** [comment]
Firebase is at latest version I think. In the repro you'll see the issue has two possible outcomes.

Removing transformIgnorePattern but keeping resolver produces:
```
node_modules\@angular\fire\node_modules\firebase\compat\auth\dist\index.esm.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import '@firebase/auth-compat';
```

Please note the firebase/compat which causes the issue is within the node_modules inside @angular/fire dep.

If I keep both (current state in repro repo), i obtain the issue mentionned earlier:

```
TypeError: Cannot read properties of undefined (reading 'FacebookAuthProvider')

      10 | import UserCredential = firebase.auth.UserCredential;
      11 |
    > 12 | export const facebookAuthProvider = new firebase.auth.FacebookAuthProvider();
         |                                                       ^
      13 | export const googleAuthProvider = new firebase.auth.GoogleAuthProvider();
      14 | export const appleAuthProvider = new firebase.auth.OAuthProvider('apple.com');
      15 | export const twitterAuthProvider = new firebase.auth.TwitterAuthProvider();

      at Object.<anonymous> (src/app/core/services/auth/auth.service.ts:12:55)
      at Object.<anonymous> (src/app/core/services/index.ts:1:1)
      at Object.<anonymous> (src/app/core/services/window-ref/window-ref.service.spec.ts:3:1)
```

**Comment by nhhockeyplayer** [comment]
this is so disruptive... so much time spent in build and never anytime for pure business logic
praying for change

**Comment by henryruhs** [comment]
By accident I found a hack to let `ngcc-jest-processor:` process the whole `node_modules` what is usually forbidden:

> By default "node_modules" folder is ignored by transformers.

```
	transformIgnorePatterns:
	[
		'node_modules'
	]
```

Using this pattern seems to bypass the Jest internal check.

```
module.exports =
{
	preset: 'jest-preset-angular',
	globalSetup: 'jest-preset-angular/global-setup',
	transformIgnorePatterns:
	[
		'//node_modules'
	]
};
```

It this a hack? Yes! Is this slow? Yes! But properly it can help someone who needs a quick fix.

**Comment by ahnpnl** [comment]
It is the proper way to configure Jest, see troubleshooting guide https://thymikee.github.io/jest-preset-angular/docs/guides/troubleshooting

To improve speed, you can use this https://thymikee.github.io/jest-preset-angular/docs/getting-started/options#processing-with-esbuild

**Comment by walter-odoo-11** [comment]
@dereekb https://angulars.space/questions/how-to-include-a-javascript-file-from-the-nodemodules-folder-in-an-angular-project
