### ISSUE TITLE
[Question] How to use Puppeteer with this?

### ISSUE THREAD

**Issue by HamedFathi** [thymikee/jest-preset-angular#163]
Can you help me how to use your preset with Puppeteer?
I want to use Jest and Puppeteer together in Angular projects Is it possible?

A project exists for this purpose as [Jest Puppeteer](https://github.com/smooth-code/jest-puppeteer) but I am not sure to work with yours.

Can anyone guide me?

**Comment by thymikee** [comment]
As of now you cannot mix presets. Feel free to recreate the setting used by jest-puppeteer and use it with this preset, it should work. I won't have time to guide you through it unfortunately though.

**Comment by hadanin** [comment]
Same here. Did you @HamedFathi find any solution to that?
