### ISSUE TITLE
[Bug]: v14 example does not seem to work 

### ISSUE THREAD

**Issue by kemsky** [thymikee/jest-preset-angular#1636]
### Version

^12.1.0

### Steps to reproduce

I'm on windows 11 and both `yarn test` and `yarn test-isolated` consume 100% CPU 100% memory (then 80% SSD) and hang. `yarn test-esm`  consumes 100% CPU 100% memory but eventually completes. 

### Expected behavior

Working example for `yarn test`, `yarn test-isolated`  `yarn test-esm` 

### Actual behavior

Two options out of three do not work, the third one has bad performance.

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^28.1.1 => 28.1.1
```

**Comment by ahnpnl** [comment]
Does the issue occur to other example apps like v13, v12?

**Comment by kemsky** [comment]
@ahnpnl, v13 consumes 100% CPU but works, the same for v12 except some tests fail.

**Comment by ahnpnl** [comment]
Not sure what happened to your computer because we don’t change anything related to that.
