### ISSUE TITLE
[Bug]: Jest 28 + Jest-preset-angular + angular 14 + firebase fails to work

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [thymikee/jest-preset-angular#1648]
### Version

12.1.0

### Steps to reproduce

We're trying to upgrade from angular 13 and jest 27 to angular 14 and jest 28
this necessitates also the upgrade to jest-preset-angular 12
With all the latest upgrades in place, I bump consistently into the same error, even after trying quite a few different solutions:

C:\lander\devprojects\acro-companion\node_modules\firebase\compat\app\dist\index.esm.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import firebase from '@firebase/app-compat';       
                                                                                  ^^^^^^

SyntaxError: Cannot use import statement outside a module

I've recreated a minimal setup from our application, and yes, just one very small test gives the same issue.
The repro is here:
https://github.com/LanderBeeuwsaert/clean-ng-project

I also used the example application of jest-preset-angular as a base, and just added firebase to package.json and to a test. Which made jest fail as well:
https://github.com/LanderBeeuwsaert/jest-preset-angular-firebase-fail

Any ideas?

### Expected behavior

well yeah, that it doesn't give the error :)

### Actual behavior

C:\lander\devprojects\acro-companion\node_modules\firebase\compat\app\dist\index.esm.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import firebase from '@firebase/app-compat';       
                                                                                  ^^^^^^

SyntaxError: Cannot use import statement outside a module

### Environment

```shell
Windows 10
8 cores
Node.js v16.14.2
angular cli 14.0.2
package versions: see repros (it all the latest versions)
```

**Comment by ahnpnl** [comment]
Please check our troubleshooting doc https://thymikee.github.io/jest-preset-angular/docs/guides/troubleshooting#resolver-needed-for-some-javascript-library-or-nested-dependencies as well as checking this duplicate issue https://github.com/thymikee/jest-preset-angular/issues/1625 Thanks

**Comment by LanderBeeuwsaert** [comment]
@ahnpnl that did the trick, thanks!

**Comment by mmalomo** [comment]
> Please check our troubleshooting doc https://thymikee.github.io/jest-preset-angular/docs/guides/troubleshooting#resolver-needed-for-some-javascript-library-or-nested-dependencies as well as checking this duplicate issue #1625 Thanks

You saved my day. Thanks!
