### ISSUE TITLE
[Feature]: Allow configuring `errorOnUnknownElements` and `errorOnUnknownProperties` for setup test env

### ISSUE THREAD

**Issue by cedricduffournet** [thymikee/jest-preset-angular#1656]
### 🚀 Feature Proposal

Allow configuring `errorOnUnknownElements` and `errorOnUnknownProperties` is test environment option

see: https://angular.io/api/core/testing/TestEnvironmentOptions

### Motivation

This new properties has been introduce in angular V14. This is usefull  to throw errors on unknown elements or properties found in a template

### Example

like destroyAfterEach option, we could add `errorOnUnknownElements` and `errorOnUnknownProperties`

```
globalThis.ngJest = {
  errorOnUnknownElements: true,
  errorOnUnknownProperties: true,
};
```

As `TestEnvironmentOptions` may introduce more properties in the future, we could add `testEnvironmentOptions` property in config:

```
globalThis.ngJest = {
  testEnvironmentOptions: {
    errorOnUnknownElements: true,
    errorOnUnknownProperties: true,
    teardown: { destroyAfterEach: false },
  },
```

**Comment by ahnpnl** [comment]
PR is welcome, should be similar to #1475

I like this option

> As `TestEnvironmentOptions` may introduce more properties in the future, we could add `testEnvironmentOptions` property in config:
> 
> ```
> globalThis.ngJest = {
>   testEnvironmentOptions: {
>     errorOnUnknownElements: true,
>     errorOnUnknownProperties: true,
>     teardown: { destroyAfterEach: false },
>   },
> ```

**Comment by cedricduffournet** [comment]
Yes, I'll do the PR

**Comment by Yohandah** [comment]
@cedricduffournet Can you guide me on how to use this ?
I've added the following in my setup-jest.js

**setup-jest.js**
```
globalThis.ngJest = {
  testEnvironmentOptions: {
    errorOnUnknownElements: true,
    errorOnUnknownProperties: true,
    teardown: { destroyAfterEach: false },
  }
}
```
and in **jest.config.js**

```
module.exports = {
  ...
  setupFilesAfterEnv: ['<rootDir>/setup.js'],
  ...
```

But it doesn't work when I execute `ng test`

**Comment by cedricduffournet** [comment]
@Yohandah this should work.
Could you please provide a reproduce scenario with https://github.com/thymikee/jest-preset-angular/tree/main/examples

**Comment by Yohandah** [comment]
@cedricduffournet I have a reproduction here : but using @angular-builders/jest ... https://github.com/Yohandah/angular-builder-jest-errorOnUnknownElementsr

It could come from this package then ...

**Comment by cedricduffournet** [comment]
I don't know about `@angular-builders/jest`, but I can't see any reference to `setupFilesAfterEnv` in your example, neither the`setup-jest.js` file where you should add `testEnvironmentOptions`

**Comment by Yohandah** [comment]
@cedricduffournet yeah that's because I've added it directly inside `jest.config.js`, I pushed the change. I will try to see with `@angular-builders/jest` maintainer.

**Comment by Yohandah** [comment]
@cedricduffournet I tried to enable these options using `jest-preset-angular` only but it's not working :/ I can't find docs on how to use these.

checkout the repo (jest-preset-angular-only branch): https://github.com/Yohandah/angular-builder-jest-errorOnUnknownElementsr/tree/jest-preset-angular-only

**Comment by ahnpnl** [comment]
Doc is here https://thymikee.github.io/jest-preset-angular/docs/getting-started/test-environment

**Comment by Yohandah** [comment]
ohhh I had to import AFTER declaring .ngJest OK !! nice thank you

**left: wrong -- right: right**
![image](https://user-images.githubusercontent.com/15921402/196467113-640b1664-370f-4856-b370-cc5b9d8bcb4d.png)
