### ISSUE TITLE
Haste module map error with @angular/cli libraries

### ISSUE THREAD

**Issue by Itrulia** [thymikee/jest-preset-angular#167]
The library is generated by `ng g library @itrulia/dates`

```
    The name `@itrulia/dates` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or blacklist files until there remains only one of these:

      * `/home/talleane/Documents/@itrulia/dates/dist/itrulia/dates/package.json` (package)
      * `/home/talleane/Documents/@itrulia/dates/projects/itrulia/dates/package.json` (package)
```

dist is the generated output by `ng build @itrulia/dates`.

spec looks like this:

```
import {ReactiveFormsModule} from "@angular/forms";
import {async, ComponentFixture, TestBed} from "@angular/core/testing";
import {AppComponent} from "./app.component";
import {DatesModule} from "@itrulia/dates";

describe("AppComponent", () => {
    let component: AppComponent;
    let fixture: ComponentFixture<AppComponent>;

    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [
                AppComponent
            ],
            imports: [
                DatesModule,
                ReactiveFormsModule
            ]
        })
        .compileComponents();
    }));

    beforeEach(() => {
        fixture = TestBed.createComponent(AppComponent);
        component = fixture.componentInstance;
        fixture.detectChanges();
    });

    it("should create", () => {
        expect(component).toBeTruthy();
    });
});
```

I have tried adding

```
modulePathIgnorePatterns: [
    "<rootDir>/projects"
  ],
```

This resulted in to Jest not being able to find @itrulia/dates.

**Comment by Itrulia** [comment]
Created that issue here because I thought that the preset should handle this, I am currently testing stuff for my schematics :)

**Comment by Itrulia** [comment]
So the plan is to not support the Angular CLI?

**Comment by ahnpnl** [comment]
Without specifying `moduleNameMapper`, by default Jest won't understand the import path like that I think. Because Angular CLI has embedded `karma` + `jasmine` therefore by default therefore they have to make it work. When you configure external things like `jest`, by default you won't get the same support as the Angular CLI does for `karma` + `jasmine`.

**Comment by Itrulia** [comment]
Thats why I asked if this library will not support the Angular CLI.

**Comment by acailly** [comment]
I fixed this issue by excluding `dist` dir in `modulePathIgnorePatterns` and mapping packages from `@myscope` to `dist` folder:

```javascript
module.exports = {
  ... ,
  modulePathIgnorePatterns: [... , "<rootDir>/dist/"],
  ... ,
  moduleNameMapper: {
    "^@myscope/(.*)$": "<rootDir>/dist/myscope/$1"
  }
};
```

**Comment by Itrulia** [comment]
See the comment above: https://github.com/thymikee/jest-preset-angular/issues/167#issuecomment-402055416

👍 thanks for sharing tho

**Comment by tiagowanke** [comment]
> I fixed this issue by excluding `dist` dir in `modulePathIgnorePatterns` and mapping packages from `@myscope` to `dist` folder:
> 
> ```js
> module.exports = {
>   ... ,
>   modulePathIgnorePatterns: [... , "<rootDir>/dist/"],
>   ... ,
>   moduleNameMapper: {
>     "^@myscope/(.*)$": "<rootDir>/dist/myscope/$1"
>   }
> };
> ```

Thanks

**Comment by hard-rox** [comment]
> I fixed this issue by excluding `dist` dir in `modulePathIgnorePatterns` and mapping packages from `@myscope` to `dist` folder:
> 
> ```js
> module.exports = {
>   ... ,
>   modulePathIgnorePatterns: [... , "<rootDir>/dist/"],
>   ... ,
>   moduleNameMapper: {
>     "^@myscope/(.*)$": "<rootDir>/dist/myscope/$1"
>   }
> };
> ```

This resolved the issue even in 2024. Thumbs up, man. 👍
