### ISSUE TITLE
Can this be used with a jest.config.js file?

### ISSUE THREAD

**Issue by Nxt3** [thymikee/jest-preset-angular#168]
All of the documentation for `jest-preset-angular` doesn't say anything about support for using the `jest.config` as a Javascript file. Is that still possible?

```
const { defaults } = require('jest-config');

module.exports = {
  globals: {
    'ts-jest': {
      tsConfigFile: 'tsconfig.spec.json'
    },
    __TRANSFORM_HTML__: true
  },
  preset: 'jest-preset-angular',
  roots: ['<rootDir>/apps/', '<rootDir>/libs/'],
  transform: {
    '^.+\\.(j|t)sx?$': '<rootDir>/node_modules/ts-jest/preprocessor.js'
  },
  transformIgnorePatterns: ['<rootDir>/node_modules/(?!lodash-es/.*)'],
  collectCoverage: true,
  collectCoverageFrom: [
    '**/*.{ts}',
    '!**/node_modules/**',
    '!**/vendor/**',
    '!scripts/**',
    '!**/test.ts',
    '!**/index.ts'
  ],
  setupFiles: [],
  setupTestFrameworkScriptFile: './scripts/setup-jest.ts'
};
```

Is that correct?

**Comment by ahnpnl** [comment]
Hi,

The preset doesn't do anything regarding to `jest.config.js`. It only provides a base setup to run `jest` with an Angular project (all the configurations mapping back to `package.json`). Your question is about `jest` configuration and of course it is possible to run `jest` with this preset via a `jest.config.js`

**Comment by Nxt3** [comment]
But the preset will work if I use `jest.config.js` as opposed to `jest.config.json`? Just making sure so I can avoid unnecessary headaches.

**Comment by ahnpnl** [comment]
it should work the same regardless `json` or `js` file as your configuration file

**Comment by Nxt3** [comment]
Great, thanks!
