### ISSUE TITLE
[Feature]: Angular Library/Showcase Example

### ISSUE THREAD

**Issue by Giocapetini** [thymikee/jest-preset-angular#1681]
### 🚀 Feature Proposal

I see the examples are all angular apps, and i'm having trouble finding the ideal config for a lib/showcase setup angular-cli style.
Although i've seen some blog, threads and posts about how to setup it up like so, there's no solid example, all say the config need something especific making it harder to config.

Can a example of a framework/library for angular be made  please ? Something that would solidify as THE way to config angular libs with jest.

A Project structure would look like as follows

projects/myLib1
projects/myLib2
projects/myShowCaseApp1
jest.config.js
jest-global-mocks.ts
setup-jest.ts
package.json
etc...

### Motivation

as of now there's no lib example only app, and when you create a new empty app in angular and generate libs and apps, the configuration gets troublesome.

### Example

it would be used to exemplify, and solidify a standard practice for angular lib jest implementation.

**Comment by ahnpnl** [comment]
Would you please check if this https://github.com/thymikee/jest-preset-angular/tree/main/examples/example-app-monorepo suits your need. Even though the name sounds not really related but in the end when a project includes app and libs, it is more likely a monorepo structure.
