### ISSUE TITLE
[Feature]: optional styles testing

### ISSUE THREAD

**Issue by dzonatan** [thymikee/jest-preset-angular#1712]
### 🚀 Feature Proposal

I see there was once [a partial support for this](https://github.com/thymikee/jest-preset-angular/pull/900) which was later [removed](https://github.com/thymikee/jest-preset-angular/pull/930).
It would be nice to bring this support back together with `styleUrls` resolver, at least as an option.

### Motivation

- to have a better support for custom jest matchers like [`toBeVisible`](https://github.com/testing-library/jest-dom#tobevisible) from the testing-library as they heavily rely on css rules;
- better integration with [jest-preview](https://www.jest-preview.com/docs/getting-started/intro).

**Comment by dzonatan** [comment]
After fiddling around I found that [it had a full support including `styleUrls`](https://github.com/thymikee/jest-preset-angular/pull/903) at some point but was [reverted](https://github.com/thymikee/jest-preset-angular/pull/909) due to <...>some syntaxes are not processed by Jest.<...>. What are those syntaxes, could you elaborate @ahnpnl? I'm willing to spend some time on this.

**Comment by ahnpnl** [comment]
IIRC the problem was processing different style extension files `.sass`, `.css`, `.scss` with importing other style files and Jest cannot process them. For example
```
@use 'foo';

@include foo.bar();
```

The `@use 'foo';` causes the problem. Maybe using `esbuild` to process style files can make Jest happy, not so sure.

**Comment by nvh95** [comment]
Thank you @dzonatan for opening this and @ahnpnl for your context. I am the author of [jest-preview](https://github.com/nvh95/jest-preview) and I am about to open a similar issue to request this feature. I also open an issue in my repo to track this [Support styleUrls and styles for Angular](https://github.com/nvh95/jest-preview/issues/237). If possible, I invite you guys (maintainers of `jest-preview-angular`) to take a look at that issue.

Briefly, `jest-preview` is a new library that gives users a visual debugging experience when writing tests in Jest. It previews the UI of a Jest test to a browser like Chrome. By doing that, it increases the productivity of frontend engineers when they debug a failed test or write a new test. It was initially designed to work well with react, but it's a framework-agnostic and we are working to support more frameworks (e.g: Angular). You can see a working example of jest-preview + Angular [here](https://www.jest-preview.com/docs/examples/angular).

<img align="center" src="https://user-images.githubusercontent.com/8603085/162563155-7e18c9ef-4fe3-45f2-9065-7fcea8ddb18e.gif" alt="Jest Preview Demo" />

`jest-preview` depends heavily on [Jest Code Transformation](https://jestjs.io/docs/next/code-transformation). In this case, `jest-preset-angular` for Angular apps. So it will be super nice if `jest-preset-angular` supports processing styles via `styleUrls` and `styles` out of the box (a flag to opt-in is a decent solution).

What do you think of supporting this? I absolutely can help with this feature with some support from you guys.

Thank you very much. Also, thank you for creating and maintaining a wonderful library.

cc: @thymikee

**Comment by ahnpnl** [comment]
Currently, this is not possible because the code transformation here is doing file per file and each Jest worker doesn't know anything about the other workers which make it not possible to retrieve full information of other CSS files.
