### ISSUE TITLE
[Bug]: full lodash-es import results into slow startup

### ISSUE THREAD

**Issue by CSchulz** [thymikee/jest-preset-angular#1713]
### Version

12.2.0

### Steps to reproduce

1. Clone https://github.com/CSchulz/jest-preset-angular-lodash-bug
2. Run yarn test in the Angular 12 example.

### Expected behavior

Fast startup because it is a very small project.

If you change one line in the app.component.ts the startup is fast again.

```
- import { deburr } from 'lodash-es';
+ import deburr from 'lodash-es/deburr';
```

```
yarn run v1.22.19
$ jest --no-cache
ngcc-jest-processor: running ngcc
 PASS  src/app/app.component.spec.ts
  AppComponent
    √ should create the app (137 ms)
    √ should have as title 'example-app-v13' (36 ms)
    √ should render title (35 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        5.517 s
Ran all test suites.
Done in 7.53s.
```

### Actual behavior

```
$ jest --no-cache
ngcc-jest-processor: running ngcc
 PASS  src/app/app.component.spec.ts (66.717 s)
  AppComponent
    √ should create the app (144 ms)
    √ should have as title 'example-app-v13' (37 ms)
    √ should render title (35 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        71.856 s
Ran all test suites.
Done in 82.32s.
```

### Additional context

Followup of #1168

The suggested workaround does not work any longer.

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.14.2 - C:\nodejs\node.EXE
    Yarn: 3.2.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.0 - C:\nodejs\npm.CMD
  npmPackages:
    jest: ^28.1.3 => 28.1.3
```

**Comment by ahnpnl** [comment]
This is because by default, `lodash` is not processed by `esbuild`. If you want to do that, you need to use option https://thymikee.github.io/jest-preset-angular/docs/getting-started/options#processing-with-esbuild

**Comment by ahnpnl** [comment]
Besides, the way how `lodash` file is resolved depending on Jest, which is related to `jest-resolve` and `moduleNameMapper`. That is out of scope for this preset.

**Comment by CSchulz** [comment]
Just to be sure I got you, esbuild is required to transform the es modules of lodash-es to commonjs?
Why should I use esbuild additionally if the "other" import will fix my issue?

Perhaps you can add some more information to the "processing with esbuild" chapter for understanding when you have to use this.

**Comment by ahnpnl** [comment]
Using `esbuild` to transform `lodash-es` would be faster than using TypeScript compiler to API and yes to transform `lodash-es` to commonjs.

Feel free to submit a PR to adjust the documentation if you think it's not clear.

**Comment by CSchulz** [comment]
esbuild will be called before ts-jest take place, right?
Is there any reason why esbuild isn't used all the time?
In the test repo I couldn't notice any performance gain with esbuild. Is there a good way to get some debug output?

**Comment by ahnpnl** [comment]
- When you define explicitly which path to be processed by `esbuild`, `ts-jest` won't do anything with it. The result of transforming by `esbuild` is given directly to Jest.
- We can't use `esbuild` for Angular codes because Angular is tight to TypeScript compiler API which they rely on TypeScript program to do some magic.
- Some distributed npm packages after transforming with `esbuild` aren't accepted by Jest.
- I usually use IDE and put debug point in `node_modules/jest-preset-angular/build/ng-jest-transformer.js` which is compiled from https://github.com/thymikee/jest-preset-angular/blob/main/src/ng-jest-transformer.ts#L54
+ or you can also put `console.log` there to output what you need.

**Comment by CSchulz** [comment]
I am trying to debug the transformations but it seems that not all files are handled by the preset. I have enabled the debug log and it doesn't show me for example the uuid files.

I have adjusted the transformIgnorePattern to include lodash-es and uuid and also adjusted processWithEsbuild, but the files of uuid (node_modules/uuid) are never passed into it.

It still fails with trying to load esm files:

    C:\Users\Ich\Daten\huk\web-app-tr\node_modules\uuid\dist\esm-browser\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { default as v1 } from './v1.js';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

**Comment by ahnpnl** [comment]
If the files don't land on the `ng-jest-transformer`, it means that Jest runtime doesn't pass those files to the `ng-jest-transformer`, perhaps the `transformIgnorePattern` don't contain the correct values. This is Jest config issue.

Another thing you can try is use `moduleNameMapper` to map things to the place they suppose to be.

**Comment by CSchulz** [comment]
To be honest I have set the transformIgnorePattern correctly otherwise the tests wouldn't run, but it doesn't get into the ng-jest-transformer. 
Here is my pattern:

    transformIgnorePatterns: [
      '/node_modules/(?!(uuid|lodash-es|@angular|friendly-challenge)/)',
      '/dist/',
    ],

Can I do anything else to find out what is going on?

```
● Test suite failed to run
  Jest encountered an unexpected token
  Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
  Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
  By default "node_modules" folder is ignored by transformers.
  Here's what you can do:
   • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
   • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
   • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
   • If you need a custom transformation specify a "transform" option in your config.
   • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
  You'll find more details and examples of these config options in the docs:
  https://jestjs.io/docs/configuration
  For information about custom transformations, see:
  https://jestjs.io/docs/code-transformation
  Details:
  node_modules\uuid\dist\esm-browser\index.js:1
  ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { default as v1 } from './v1.js';
```

**Comment by ahnpnl** [comment]
You can check this e2e test https://github.com/thymikee/jest-preset-angular/tree/main/e2e/process-js-packages to see the config

**Comment by CSchulz** [comment]
I have no clue why it is working now. I thought I have already done it like that.

But I have encountered the next issue with ESM imports in ESM modules. I have also looked at the esbuild repo and tried a newer esbuild version without any luck. I am not sure if it is similar to this issue https://github.com/evanw/esbuild/issues/2384

```
TypeError: (0 , import_isPlainObject.default) is not a function
    at isPlainObject (commons-testing\fesm2015\commons-testing.mjs:185:10)
```

Here are the specific file parts:

```
  var import_isPlainObject = __toESM(require("lodash-es/isPlainObject"), 1);

  if (!(0, import_isPlainObject.default)(methods)) {
    return typedJestCreateSpyObj(objType, methods);
  }
```

**Comment by ahnpnl** [comment]
That is a separate issue which is `esbuild` specific.

**Comment by CSchulz** [comment]
Should I open here another issue for it?
I think https://thymikee.github.io/jest-preset-angular/docs/guides/troubleshooting#resolver-needed-for-some-javascript-library-or-nested-dependencies could help to fix that issue, couldn't it?

**Comment by ahnpnl** [comment]
> Should I open here another issue for it? I think https://thymikee.github.io/jest-preset-angular/docs/guides/troubleshooting#resolver-needed-for-some-javascript-library-or-nested-dependencies could help to fix that issue, couldn't it?

It is not `jest-preset-angular` issue because it's for `esbuild`. 

About the troubleshooting guide, I suggest you try out that one. If it misses something, feel free to update the doc. In general, the issue you are opening here is about configuration, not about internal codes of `jest-preset-angular`.
