### ISSUE TITLE
[Bug]: Could not locate module for Angular module after migration to Angular 14 + Jest 28

### ISSUE THREAD

**Issue by NLueg** [thymikee/jest-preset-angular#1759]
### Version

12.2.2

### Steps to reproduce

1. Clone my repo https://github.com/NLueg/jest-preset-angular-issue
2. npm i
3. ng build @test/mylib
4. jest --testNamePattern=AppComponent

### Expected behavior

The loading of Angular libraries still should be possible.

### Actual behavior

In our project, we migrated to Angular 14 and moved to Jest 28. We don't changed anything in our configs as no breaking changes were noted here.
You can see the same behavior we have in our project in the minimal example I provided.

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.24.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^28.1.3 => 28.1.3
```

**Comment by ahnpnl** [comment]
- From which version of Angular did you migrate?
- You can also take a look at https://github.com/thymikee/jest-preset-angular/tree/main/examples/example-app-v14 to compare the config.
- Did you check our CHANGELOG?
- Did you read our migration guide on documentation site?

**Comment by NLueg** [comment]
Wow, thanks for the fast response!

1. We migrated from `13.3.4` to `14.2.0`
2. I also checked the examples without success
3. Yes, the breaking changes don't affect us
4. Yes, but there were nothing to do as we always were on Angular 13.

I struggle with this for several hours (if not already days) and tried many things without success. That's why I created a repo where I basically just created a new Angular application + library. After migration to Jest I have the same issue as we have in our product.

**Comment by ahnpnl** [comment]
I checked your repo, the problem is not because of `jest-preset-angular`. Your `tsconfig.json` contains the incorrect mapping for `@test/my-lib`. If you change the `paths` in `tsconfig.json` to be
```
"paths":{
      "@test/my-lib":[
        "projects/test/my-lib/src/public-api.ts"
      ]
},
```

When I open `app.component.ts`, my WebStorm also informs me that the path. 

If you wish to keep the same `paths`, you would need to build your lib first before running tests.

**Comment by NLueg** [comment]
Oh wow, you're totally right. Then it just was coincidence that it worked before.
Thank you so much for looking into the problem and helping me out although it has nothing to do with this plugin!
