### ISSUE TITLE
Wrong dependencies when installing

### ISSUE THREAD

**Issue by hankolsen** [thymikee/jest-preset-angular#176]
Hi!
Now, I'm not sure if this is an issue with jest-preset-angular or npm or if I'm doing something wrong.

When I try to install jest-preset-angular with yarn or npm, the package.json shows "jest": "^22.4.0" as a dependency. But when I look at the code here on GitHub it says "jest": "^23.2.0". 

I have tried to clean my yarn cache, but it doesn't install the version with the updated dependency.

I'm I doing something wrong on my end...?

**Comment by thymikee** [comment]
We've not yet published version with Jest 23. You can install latest pre-release marked as `6.0.0-rc.0`

**Comment by thymikee** [comment]
@ahnpnl do you think we can release stable now?

**Comment by ahnpnl** [comment]
I haven't seen any issues so far. However, there is a big PR on [`ts-jest`](https://github.com/kulshekhar/ts-jest/pull/626) almost gets merge and release. Do you want to wait for that big PR because it solves quite a lot issues right now.

**Comment by thymikee** [comment]
Yep, gonna wait. Thanks!
