### ISSUE TITLE
[Bug]: jest-preset-angular depends on phantom dependency jest-util

### ISSUE THREAD

**Issue by troywweber7** [thymikee/jest-preset-angular#1773]
### Version

12.2.2

### Steps to reproduce

1. reproduction steps for how I stumbled upon this phantom dependency can be found at [original issue](https://github.com/nxext/nx-extensions/issues/808)
2. simpler reproductions steps are to look at `jest-preset-angular/build/config/ng-jest-config.js` and confirm that `jest-util` is a directly required dependency, and should thus be included in the `dependencies` or `peerDependencies` of this package's `package.json`

### Expected behavior

When installing `jest-preset-angular`, any packages which are directly depended on by javascript files published by `jest-preset-angular` should be listed in either the `dependencies` or `peerDependencies`.

### Actual behavior

When installing `jest-preset-angular` and inspecting it's `package.json`, it currently does not list `jest-util` under it's dependencies. It is probably publicly hoisted by some other package that `jest-preset-angular` depends on, but when using pnpm which does not publicly hoist dependencies, it fails.

### Additional context

I'm using pnpm which by default, and with good reason, does not publicly hoist dependencies.

### Environment

```shell
System:
- `uname -a` return `Linux tww-hp-ubuntu 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
Binaries:
- `node -v` returns `v16.16.0`
- `pnpm -v` returns `7.11.0`
```

**Comment by ahnpnl** [comment]
PR is welcome, we should put it as direct dep.
