### ISSUE TITLE
[Bug]: npm install fails with latest jest 29.0.3

### ISSUE THREAD

**Issue by qwertyuiopzxcvbnmlkjhgfdsa1** [thymikee/jest-preset-angular#1774]
### Version

2.2.2

### Steps to reproduce

1,Use jest 29.0.3 as dependency with latest jest-preset-angular 2.2.2
2, npm install fails ERESOLVE unable to resolve dependency tree

### Expected behavior

npm install works

### Actual behavior

 npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xxx@3.0.1
npm ERR! Found: jest@29.0.3
npm ERR! node_modules/jest
npm ERR!   dev jest@"29.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jest@"^28.0.0" from jest-preset-angular@12.2.2
npm ERR! node_modules/jest-preset-angular
npm ERR!   dev jest-preset-angular@"12.2.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Additional context

Would you release jest-angular-preset with jest 29 supported?

### Environment

```shell
System:
    OS: Linux 5.18 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    npm: 8.15.0 - /usr/bin/npm
```

**Comment by ahnpnl** [comment]
We haven’t finished supporting Jest 29 yet so ye this will have to wait for a major release.

**Comment by bendehghan** [comment]
Any updates/guesses on when 29 will be supported?

**Comment by bendehghan** [comment]
Anything yet? It's been 2 weeks. Can you give an estimate please? At least we can plan things better on our end. Thanks

**Comment by qwertyuiopzxcvbnmlkjhgfdsa1** [comment]
We downgraded Jest to version 28 and managed to get project working.

**Comment by bendehghan** [comment]
Well, yeah, my project already works fine with Jest 28. We just wanted to keep up with Jest as it moves forward. I guess we'll wait until this is issue resolved and 29 is supported.

**Comment by minijus** [comment]
Are there any plans to cut new release any time soon? It seems new version of Jest was merged to main branch and it passed CI just fine: https://github.com/thymikee/jest-preset-angular/pull/1804 

There is a chain of changes that increases the importance of having `jest-preset-angular` with Jest 29 support:
1. There is outstanding Jest and Node.js 16.10+ issue with memory consumption: https://github.com/facebook/jest/issues/11956 
2. Jest 29 added a workaround with new option `workerIdleMemoryLimit`
3. Angular 15 drops support for Node.js 16.10 https://github.com/angular/angular-cli/pull/24026 putting Jest users in a limbo state.
4. Nrwl seems to wait for `jest-preset-angular` release to add official support for Jest 29 to nx: https://github.com/nrwl/nx/issues/11892

**Comment by bendehghan** [comment]
Hey guys,
how are we looking on this?? Can we expect this before Angular 15 gets out?

**Comment by ahnpnl** [comment]
It will be together with angular 15 support in a major version:)

**Comment by kubabuda** [comment]
- Do you have release date planned?
- How can one help with that?

**Comment by bendehghan** [comment]
> 

Do you have a working branch we can test with current RC version of Angular 15?

**Comment by ahnpnl** [comment]
You can test against `main`. 

The leftover work now includes:
- Adopt changes from `ts-jest` 29
- Migrate any config under `globals` to be transformer config, just like `ts-jest`
- Test with angular 15

**Comment by christrude** [comment]
Whats interesting about this error: `npm ERR! peer jest@"^28.0.0" from jest-preset-angular@12.2.2` is that in 12.2.2 the package.json file already points to "jest": "^29.1.2", and "ts-jest": "^29.0.0". 28 isn't stated anywhere, and my corollary upgrades are being held back by this.  I consider this a bug with 12.2.2. https://github.com/thymikee/jest-preset-angular/blob/main/package.json Agree/disagree?

**Comment by michaelfaith** [comment]
@christrude you're not looking at the state of the file when the `12.2.2` tag was applied (i.e. when the release was made).  https://github.com/thymikee/jest-preset-angular/blob/v12.2.2/package.json  It's only on jest 28

**Comment by christrude** [comment]
> @christrude you're not looking at the state of the file when the `12.2.2` tag was applied (i.e. when the release was made). https://github.com/thymikee/jest-preset-angular/blob/v12.2.2/package.json It's only on jest 28

you are right, i am a dumb dumb.

**Comment by joshwiens** [comment]
> You can test against `main`.
> 
> The leftover work now includes:
> 
> * Adopt changes from `ts-jest` 29
> * Migrate any config under `globals` to be transformer config, just like `ts-jest`
> * Test with angular 15

I'd like to pose a question. Would it not make more sense to push a tag that supports Angular 15 and then deal with all of the breaking updates for Jest v29.

At the moment anyone that updates via Nx to migrate to Angular 15 ( or without ) is getting blocked by what is effectively a single line package.json change related to peer dependencies.

**Comment by ahnpnl** [comment]
12.2.3 supports Angular 15:)

**Comment by joshwiens** [comment]
Releasing on a holiday like a complete boss :)

**Comment by wmarques** [comment]
Any help needed on this ? :) Never contributed to this project but I'm willing to help if necessary, but I dont find what's left to do, sorry ! 😄

**Comment by DerHerrGammler** [comment]
Any updates on this?

**Comment by bendehghan** [comment]
Happy new year! Hope we can get back to solving this issue. It's holding up any real angular 15 release on our side.

**Comment by bendehghan** [comment]
@ahnpnl, @thymikee, Can you please update us on what is remaining here and what help you need? Is there a dependency issue on other packages or is the work only in this package? We can try to help. But how and on what??
Thanks, Ben

**Comment by michaelfaith** [comment]
> It's holding up any real angular 15 release on our side.

Why, if 12.2.3 supports Angular 15?

**Comment by bendehghan** [comment]
Yes, sorry, I mean angular with Jest 29. Jest 28 + angular 15 is working.

**Comment by ahnpnl** [comment]
> You can test against `main`.
> 
> The leftover work now includes:
> 
> * Adopt changes from `ts-jest` 29
> * Migrate any config under `globals` to be transformer config, just like `ts-jest`

@bendehghan

**Comment by bendehghan** [comment]
Are these things the community can help with? Is it a block like there is no solution you can see or that there isn't time to make the changes? It's been taking a long time so I wanted to see what we can help with.

**Comment by ahnpnl** [comment]
Yes feel free to tackle these.

**Comment by michaelfaith** [comment]
You could always pitch in and help out... Complaining like that, just to complain, isn't helpful.  ahnpnl's done an amazing job maintaining this project.  They're very responsive and jumps on stuff quickly, when needed.  We're just on the other side of a long holiday;  why not give them the space to make the change, or pitch in and help out yourself.  This is open source after all.

**Comment by beeman** [comment]
> You could always pitch in and help out... Complaining like that, just to complain, isn't helpful. 

People offered to help for months with no result. I'm trying to come up with a real solution instead of your utopian scenario.

Already talking to Nrwl as we speak.

**Comment by Tommy228** [comment]
What changes from `ts-jest` 29 need to be adopted? I don't see anything from the [changelog](https://github.com/thymikee/jest-preset-angular/blob/main/CHANGELOG.md), except the migration from a global config to a transformer config.

**Comment by ahnpnl** [comment]
That’s the only change which produces warning logs when running tests in `main`. Internally we patch `globals` object to pass to `ts-jest`

**Comment by ahnpnl** [comment]
closes via #1901

**Comment by ahnpnl** [comment]
Hi, I’m glad to hear that. I will arrange asap.

**Comment by ghiscoding** [comment]
> You can test against `main`.
> 
> The leftover work now includes:
> 
> * Adopt changes from `ts-jest` 29
> * Migrate any config under `globals` to be transformer config, just like `ts-jest`
> * Test with angular 15

Note that the documentation to migrate `ts-jest` config from `globals` to `transform` is not reflected in the Documentation and it took me a few trials and errors to get it working. It might be a good idea to reflect the changes in the docs. Thanks for the lib :)
