### ISSUE TITLE
New version release?

### ISSUE THREAD

**Issue by slawiko** [thymikee/jest-preset-angular#178]
It is not an issue, it's a question: when are you planning to release version with Jest v23?

**Comment by thymikee** [comment]
We wanted to wait for this release: https://github.com/thymikee/jest-preset-angular/pull/173
Until that, feel free to use `next` tag on npm

**Comment by thymikee** [comment]
Just released v6.0.0 enjoy :)

**Comment by slawiko** [comment]
@thymikee realtime :) thank you!

**Comment by ahnpnl** [comment]
tested with CI of company's projects. Everything looks good.
