### ISSUE TITLE
Tests won't run with angular/cli@6.1.2

### ISSUE THREAD

**Issue by comatose-turtle** [thymikee/jest-preset-angular#181]
Hello,

When creating a new app via angular cli, and then following the instructions on adding jest-preset-angular, the tests will not run.
My pair and I have been trying to figure out what the problem is for about a week, but we have had no luck other than reverting the version of angular cli.

To reproduce: 
1. `npm install -g @angular/cli` (get the latest)
1. `ng new my-app && cd my-app`
1. `npm install --save-dev jest jest-preset-angular`
1. Create the `setupJest.ts` and `jestGlobalMocks.ts` files, provided by `jest-preset-angular`
1. Add jest configurations for `preset`, `setupTestFrameworkFile` and `testURL` to `package.json`
1. `npx jest`
1.  Test fail :(
```
Test suite failed to run

    /Users/pivotal/workspace/last-hope/src/setupJest.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import 'jest-preset-angular';
                                                                                                    ^^^^^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected string

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
```

This appears to be complaining about having been translated to the wrong ECMAScript version (i.e., es2015 vs. commonjs).  Here is the generated `tsconfig.json`:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

We think the issue is that jest cannot handle the es2015, but the problem still exists if we change `module` to `commonjs`.

If we rollback the version of angular cli to 6.0.8, we get no issues.
No one else seems to have encountered this, but we can reproduce it reliably.

**Comment by ahnpnl** [comment]
Close via #183

**Comment by vanpeta** [comment]
This issue persist using Angular CLI 6.2. The provided fix, adding
`"moduleNameMapper": {"@lib/(.*)": "<rootDir>/src/lib/$1"}`
to jest configuration on package.json doesn't solve it.

**Comment by ahnpnl** [comment]
After adding moduleNameMapper to jest config, you need to clear jest cache. The same this discussion in #185
