### ISSUE TITLE
[Bug]: Getting ReferenceError when using decorators

### ISSUE THREAD

**Issue by philippesc** [thymikee/jest-preset-angular#1810]
### Version

12.2.2

### Steps to reproduce

1. Clone my repo at [https://github.com/philippesc/ng-jest-issue](https://github.com/philippesc/ng-jest-issue)
2. yarn install
3. yarn test
4. You should see the error come up

### Expected behavior

I expect that no error comes up as the test should work properly.

### Actual behavior

This is what comes up:

    ReferenceError: app_state_model_1 is not defined

       5 | export class AppSelectors {
       6 |   @Selector([AppState])
    >  7 |   static appName(state: AppStateModel): string {
         |                         ^
       8 |     return state.name;
       9 |   }
      10 | }

      at Object.<anonymous> (src/app/store/app/app.selectors.ts:7:25)
      at Object.<anonymous> (src/app/services/some-nice-service/some-nice-service.spec.ts:3:1)

### Additional context

This error came up in the context of migration to Angular 14 but it seems to be related to this package.

### Environment

```shell
System:
  OS: macOS 12.6
  CPU: (10) arm64 Apple M1 Max
Binaries:
  Node: 16.13.1 - /usr/local/bin/node
  Yarn: 1.22.17 - /usr/local/bin/yarn
  npm: 8.3.0 - /usr/local/bin/npm
npmPackages:
  jest: 28.1.1 => 28.1.1
```

**Comment by anschm** [comment]
I have the same issue

**Comment by valiant-code** [comment]
Looks like this was discussed in #1199 as well.

**Comment by valiant-code** [comment]
For me jest-preset-angular 12.0.0 works but 12.2.0 runs into this issue with decorators.

**Comment by nedecoTHo** [comment]
Are there any updates on this?

**Comment by dylannnn** [comment]
Hi, is there any updates? I have tried  all versions from 11 to 12 and none of them works.

**Comment by anschm** [comment]
Any update on this? This issues is still present with release 12.2.3.

**Comment by jbjhjm** [comment]
Confirming this issue. I just created a repo for reproduction too, 
which might be a simpler for debugging as it does not use a full ng app at all.
Also tests/confirms for a few situations if it happens/not happens.

https://github.com/jbjhjm/jest28-bug

The repo doesn't even touch angular libs, use of jest-preset-angular is enough to make jest error in a certain situation:

- Import a interface from a module that contains nothing but interfaces
- Use it on a method that is being decorated
- Have emitDecoratorMetadata enabled
- use jest-preset-angular for transformation & test-setup

It contains a test suite 4 times:

- src/tsjest -  with ts-jest, works fine
- src/ngdevkit -  with jest-preset-angular, Reference Error is thrown

(these two can be ignored, no difference to using or omitting nx)
- lib/test-tsjest - with nx, with ts-jest
- lib/test-ngdevkit - with nx, with jest-preset-angular

**Comment by valiant-code** [comment]
Today I attempted to update to Angular 15.1.0 and with it, jest-preset-angular (12.2.0 -> 12.2.3), but I am still running into this issue which may block my upgrade.

**Comment by jbjhjm** [comment]
@valiant-code 12.2.3 won't work. You'll have to wait for the next release.
Be sure to watch https://github.com/thymikee/jest-preset-angular/issues/1199 to be notified when there're news about it.

**Comment by jbjhjm** [comment]
Perfect, 12.2.4 seems to be fully compatible with ts 4.8!
Updated my issue repo and all tests are passing as expected now. ( https://github.com/jbjhjm/jest28-bug )
Unit tests in our main repo (ng14, jest28, ts4.8) are passing fine too.
I think this issue is resolved @ahnpnl !
