### ISSUE TITLE
Angular 15 Support

### ISSUE THREAD

**Issue by michaelfaith** [thymikee/jest-preset-angular#1838]
Just creating this for tracking.  Per:

> The leftover work now includes:
> - Adopt changes from `ts-jest` 29
> - Migrate any config under `globals` to be transformer config, just like `ts-jest`
> - Test with angular 15

_Originally posted by @ahnpnl in https://github.com/thymikee/jest-preset-angular/issues/1774#issuecomment-1301100124_

**Comment by Coly010** [comment]
cc @ahnpnl @thymikee any chance this could get looked at? I don't mind submitting a PR
