### ISSUE TITLE
[Feature]: Create 12.2.3 release with angular 15 support 

### ISSUE THREAD

**Issue by swierzbicki** [thymikee/jest-preset-angular#1842]
### 🚀 Feature Proposal

Publish version with:
PR - https://github.com/thymikee/jest-preset-angular/pull/1840
Commit - https://github.com/thymikee/jest-preset-angular/commit/c629535b68327cf7d81c095c2da05202cb7dca32

### Motivation

Still it's not possible to use jest-preset-angular with new angular 15 :)

**Comment by maartentibau** [comment]
![image](https://user-images.githubusercontent.com/4103756/203927446-74f23a51-a6f6-4771-a922-c716af9de7eb.png)

![image](https://user-images.githubusercontent.com/4103756/203927483-73690cae-851b-452c-8a0b-0978cb62c767.png)

**Comment by swierzbicki** [comment]
@maartentibau what do you want to say by pasting this screenshot? 

This Github Action run is for pull request:
https://github.com/thymikee/jest-preset-angular/pull/1836

Support for angular 15 is merged already. PR: https://github.com/thymikee/jest-preset-angular/pull/1840

So as i assume it is just a matter of creating a new tag (for example 12.2.3) and publish this version with this action:
https://github.com/thymikee/jest-preset-angular/actions/workflows/release-and-publish.yml

**Comment by maartentibau** [comment]
@swierzbicki it’s indeed just to point out the build was failed and I assumed that was the reason why the new version wasn’t released

**Comment by ahnpnl** [comment]
Already released.
