### ISSUE TITLE
Angular 6+: SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by ayyazzafar** [thymikee/jest-preset-angular#185]
Its not working for me.
I am using Angular 6+ but I always get this error:
```
src\setup-jest.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import 'jest-preset-angular';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)


```

What can be the issue? How can we resolve it?

**Comment by l7960261** [comment]
same issue as @ayyazzafar

**Comment by joelmuskwe** [comment]
same issue too

**Comment by ahnpnl** [comment]
hi all, please add `"module": "commonjs",` to your `tsconfig.spec.json`. It will solve your issue :)

**Comment by ahnpnl** [comment]
@l7960261 you can try to run clear cache of jest, it should solve after modifying `tsconfig.spec.json`. It worked for me

**Comment by l7960261** [comment]
@ahnpnl  Cool. It's work fine.

**Comment by boazrymland** [comment]
> hi all, please add `"module": "commonjs",` to your `tsconfig.spec.json`. It will solve your issue :)

This should be added to the compilerOptions section of the mentioned file, not in its root.
Only after I moved this to the correct location it worked out.

**Comment by boazrymland** [comment]
> hi all, please add `"module": "commonjs",` to your `tsconfig.spec.json`. It will solve your issue :)

This should be added to the compilerOptions section of the mentioned file, not in its root.
Only after I moved this to the correct location it worked out.
