### ISSUE TITLE
[Bug]: 12.2.3 breaks compatibility with Angular 12

### ISSUE THREAD

**Issue by pschaub** [thymikee/jest-preset-angular#1863]
### Version

12.2.3

### Steps to reproduce

I am not able to install `jest-preset-angular@12.2.3` for Angular 12 because of the increased minimum version of typescript.

Angular 12 is using `@angular/compiler-cli@12.2.17` that only supports `typescript@">=4.2.3 <4.4`:
> npm ERR! Could not resolve dependency:
> npm ERR! peer typescript@">=4.2.3 <4.4" from @angular/compiler-cli@12.2.17

But `jest-preset-angular@12.2.3` increased the minimum typescript version to `>=4.4`, see https://github.com/thymikee/jest-preset-angular/commit/dc58df132e58d51b01f0bcb96dd11aa362f5e2a6
> npm ERR!   peer typescript@">=4.4" from jest-preset-angular@12.2.3

According to the commit message of https://github.com/thymikee/jest-preset-angular/commit/dc58df132e58d51b01f0bcb96dd11aa362f5e2a6 I think it was accidentally merged into 12.2.3 and was planned to be released in 13.0.0.

### Expected behavior

Angular 12 is still supported in `jest-preset-angular@12.2`

### Actual behavior

Angular 12 is not supported in `jest-preset-angular@12.2.3`

### Environment

```shell
-
```

**Comment by ahnpnl** [comment]
fixed in **12.2.4**
