### ISSUE TITLE
[Bug]: Can not install latest version with "npm install"

### ISSUE THREAD

**Issue by developingdenny** [thymikee/jest-preset-angular#1867]
### Version

12.2.3 (latest)

### Steps to reproduce

The dependencies listed in `package.json` published to npm appear to be inconsistent with those intended. 

The `package.json` file in the repository declares version 12.2.3 dependencies on Jest version 29; however, the package.json retrieved and installed in node_modules via `npm install` states dependencies on Jest version 28.

The result is that `jest-preset-angular` version 12.2.3 cannot be installed via `npm install` without applying the `--force` flag.

The issue can be seen by attempting to install from npm to setup the example Angular 14 project.

1. Clone jest-preset-angular project from github
2. Open the example project via terminal: `cd examples/example-app-v14`
3. Run `npm install`

Note installation fails due to unmet peer dependency related to Jest as shown below. 

<img width="479" alt="image" src="https://user-images.githubusercontent.com/10047590/205499632-6a097a22-3d7a-46ec-a7d5-33ba3c0a5718.png">

Errors state that `jest-preset-angular` depends on Jest version 28. However, the latest package.json in the repository declares that version 12.2.3 depends on Jest version 29.

Running `npm install --force` will retrieve `jest-preset-angular` version 12.2.3 from npm and place it into local project directory `node_modules`.

As shown below, the `package.json` within that installed package states a Jest 28 dependency:

<img width="516" alt="image" src="https://user-images.githubusercontent.com/10047590/205501276-61cd6f28-d2b0-40e9-9daa-aa5236915d76.png">

### Expected behavior

Using `npm install` succeeds without complaints of unresolved peer dependencies.

Installing `jest-preset-angular` version 12.2.3 completes with `package.json` file that declares peer dependencies on Jest 29, not Jest 28.

### Actual behavior

Cannot install project depending on `jest-preset-angular` version 12.2.3 via `npm install` without producing peer dependency error messages and/or applying the `--force` flag.

### Additional context

I suspect somehow the latest `package.json` file contents from the repository has not been / is not being included when publishing to npm.

### Environment

```shell
System:
    OS: macOS 13.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.18.1 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    jest: ^29.1.2 => 29.3.1
```

**Comment by ahnpnl** [comment]
Duplicated with #1774 please follow the discussion there.
