### ISSUE TITLE
[Bug]:  SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by samyak087** [thymikee/jest-preset-angular#1878]
### Version

12.2.3

### Steps to reproduce

**The project consist of Storybook and Angular.**
After migration of Angular v12 to v13 the project consist of the following versions:
Angular - v13
Storybook - 6.5.12
I upgraded jest, ts-jest, @types/jest and jest-preset-angular to the latest versions.
After I ran the npm run test command for the unit test cases which is throwing the following error:

 Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

 C:\node_modules\@angular\core\fesm2020\testing.mjs:7
    import { getDebugNode, RendererFactory2, ɵstringify, ɵReflectionCapabilities, Directive, Component, Pipe, NgModule, ɵgetInjectableDef, resolveForwardRef, ɵNG_COMP_DEF, ɵRender3NgModuleRef, ApplicationInitStatus, LOCALE_ID, ɵDEFAULT_LOCALE_ID, ɵsetLocaleId, ɵRender3ComponentFactory, ɵcompileComponent, ɵNG_DIR_DEF, ɵcompileDirective, ɵNG_PIPE_DEF, ɵcompilePipe, ɵNG_MOD_DEF, ɵtransitiveScopesFor, ɵpatchComponentDefWithScope, ɵNG_INJ_DEF, ɵcompileNgModuleDefs, NgZone, Compiler, COMPILER_OPTIONS, ɵNgModuleFactory, ModuleWithComponentFactories, InjectionToken, Injector, InjectFlags, ɵresetCompiledComponents, ɵflushModuleScopingQueueAsMuchAsPossible } from '@angular/core';
 SyntaxError: Cannot use import statement outside a module

My jest-config.js has transformIgnorePatterns-
transformIgnorePatterns: [
        'node_modules/(?!@storybook/*)'
    ],

According to the official documentation of jest-preset-angular [https://thymikee.github.io/jest-preset-angular/docs/guides/angular-13+/](url) they mentioned to add the following-
const jestConfig: Config = {
  // ...other options
  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$)'],
};
If I add the above line in my code mentioned in documentation and comment the 'node_modules/(?!@storybook/*)'  line the error is resolved. So is it the right method to solve? 

In [https://jestjs.io/docs/configuration#transformignorepatterns-arraystring](url) link they mentioned one line that -
**"Providing regexp patterns that overlap with each other may result in files not being transformed that you expected to be transformed"**
So may be commenting this 'node_modules/(?!@storybook/*)' is preventing from collision.

### Expected behavior

We expect preset to manage transforms for all required files and avoid SyntaxError: Cannot use import statement outside a module error on some js files in node_modules.

### Actual behavior

SyntaxError: Cannot use import statement outside a module error on some js files in node_modules.

### Environment

```shell
System:
    OS:	Microsoft Windows 11 Enterprise
Binaries:
    Node: 14.15.0 
    npm: 6.14.8
npmPackages:
   "jest": "^29.3.1",
```

**Comment by ahnpnl** [comment]
Please check our documentation https://thymikee.github.io/jest-preset-angular/docs/guides/angular-13+ as well as check example apps https://github.com/thymikee/jest-preset-angular/tree/main/examples
