### ISSUE TITLE
Watch running all tests (not doing incremental testing)

### ISSUE THREAD

**Issue by itslenny** [thymikee/jest-preset-angular#189]
I'm currently using jest on my backend (Node / TypeScript), and one of the main reasons I wanted to move our angular project to jest is because it has a really intelligent incremental test system. When I change a file it will JUST run the tests for that file or other related files. Additionally, it is git aware so if you run test with `--watch` it only tests things that have changed since the last commit.

However, on angular (using jest-preset-angular). It's running my entire test suite on every file change. I'm just running `ng test --watch` and haven't overridden any options or anything.

Is there a config value I need to set to get this functionality? or is it just not possible because of angular bundling or something?

**Comment by ahnpnl** [comment]
Hi @itslenny, if you are using this preset for your node backend, it's a bit wrong. This preset is only for Angular project.

In your situation you are actually using ts-jest to run Jest with your Node TypeScript project. Under the hood, this preset also uses ts-jest. I'd suggest you to post this question on ts-jest or jest repository. Those are the right places :)

Besides, I have seen this issue occuring to my Windows machine, not on Mac. This issue also appeared before on Jest repository. You can get the most help from Jest GitHub

**Comment by itslenny** [comment]
Thanks for the guidance. I'll go ask over there.
