### ISSUE TITLE
personalice root path

### ISSUE THREAD

**Issue by SrHuevo** [thymikee/jest-preset-angular#19]
Hello,

My app is in src/www but jest try find tsconfig.spec.ts in src ¿Can I change the path?

Thanks :D

**Comment by thymikee** [comment]
yup, add this to your jest config in package.json:
```json
  "globals": {
    "__TS_CONFIG__": "src/www/tsconfig.json",
    "__TRANSFORM_HTML__": true
  }
```

**Comment by SrHuevo** [comment]
Thank you and thank you very much for your work is great

**Comment by Simon-Bru** [comment]
Hi ! 
I tried to do the same thing, but it results in an error : 

● Test suite failed to run

    .../src/setupJest.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){require('ts-jest').install();import 'jest-preset-angular';
                                                                                                                          ^^^^^^
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:106:13)


However, my files tsconfig.json and tsconfig.spec.json are exactly identical. Here's the content of the file: 

`{

    "compilerOptions": {
        "baseUrl": "",
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": true,
        "lib": [
            "es2017",
            "es2016.array.include",
            "dom"
        ],
        "mapRoot": "./",
        "module": "es6",
        "moduleResolution": "node",
        "outDir": "../dist/out-tsc",
        "sourceMap": true,
        "target": "es5",
        "typeRoots": [
            "../node_modules/@types"
        ]
    }
}`


This issue shouldn't happen as my tests run very well with tsconfig.spec.ts but both file have the same content so it should run as well with that modification.

Thanks in advance for your help

Simon

**Comment by thymikee** [comment]
your tsconfig.spec.json needs `"module": "commonjs"`

**Comment by Simon-Bru** [comment]
I already tried with commonjs. And it results into the same error but with a different stack trace: 

`  ● Test suite failed to run

    .../src/setupJest.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){require('ts-jest').install();import 'jest-preset-angular';
                                                                                                                          ^^^^^^
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at process._tickCallback (internal/process/next_tick.js:103:7)
`
