### ISSUE TITLE
webpack serve fails with ''canot find name 'global' in jest-global-mock.ts

### ISSUE THREAD

**Issue by nirajkrz** [thymikee/jest-preset-angular#190]
When running the webpack serve in local, the build fails by stating that:

global' is undefined in mock file.
 Below is my mock:

> global['CSS'] = null;
const mock = () => {
    let storage = {};
    return {
        getItem: key => key in storage ? storage[key] : null,
        setItem: (key, value) => storage[key] = value || '',
        removeItem: key => delete storage[key],
        clear: () => storage = {},
    };
};

Object.defineProperty(window, 'localStorage', { value: mock() });
Object.defineProperty(window, 'sessionStorage', { value: mock() });
Object.defineProperty(document, 'doctype', {
    value: '<!DOCTYPE html>'
});
Object.defineProperty(window, 'getComputedStyle', {
    value: () => {
        return {
            display: 'none',
            appearance: ['-webkit-appearance']
        };
    }
});

Object.defineProperty(document.body.style, 'transform', {
    value: () => {
        return {
            enumerable: true,
            configurable: true,
        };
    },
});

Object.defineProperty(window, 'matchMedia', {
    value: () => (
        {
            matches: false,
            addListener: () => { },
            removeListener: () => { },
        }
    )
});

**Comment by thymikee** [comment]
Jest (test runner) is not meant to be running with webpack (bundler). These are 2 different tools for different purposes.

**Comment by nirajkrz** [comment]
Thanks, i moved tehnmock file out of source directory so that webpack ignores it. thanks for checking this.
