### ISSUE TITLE
[Bug]: Breaking changes -  TypeError: typescript_1.default.canHaveDecorators is not a function

### ISSUE THREAD

**Issue by splincode** [thymikee/jest-preset-angular#1919]
### Version

12.2.4

### Steps to reproduce

1) Clone repo from branch https://github.com/Tinkoff/taiga-ui/pull/3438
2) $ npm install
3) $ nx test demo

### Expected behavior

No error

### Actual behavior

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/12021443/212872954-c3a3f972-145b-49ff-8c84-e836d30559d5.png">

### Environment

```shell
Angular 12
npm 8
Node.js 16
```

**Comment by p0d4r14n** [comment]
Can confirm I get the same error with 12.2.4 (Angular 13, npm 8, Node 16)

**Comment by Robouste** [comment]
Same here, I had to set the version to `12.2.0` to make it work.

**Comment by du-almeidalima** [comment]
I can also confirm this is happening with Angular 12 - 15 using the jest-preset-angular 12.2.4

**Comment by TheRealOha** [comment]
Can confirm also with ng 13. Downgrade to 12.2.0 works as @Robouste already said, if anyone is looking for a workaround

**Comment by Nillcon248** [comment]
Got the same issue today!

**Comment by ahnpnl** [comment]
please check **12.2.5**, should be fixed.

**Comment by stefanone91** [comment]
It seems **fixed** in **12.2.5**! 
Thank you!

**Comment by splincode** [comment]
fixed
