### ISSUE TITLE
TypeError is not a function for function define in another ts file

### ISSUE THREAD

**Issue by McKratt** [thymikee/jest-preset-angular#193]
Hi there,

I'm pretty sure this problem will have a easy ending but I'm not aware of the right way to solve it.
My problem,

I have a test file : composant-fonction-limite-list.component.spec.ts which call function from antoher file : composant-fonction.model.mock.ts during the test ts compiler find it well but is seems that jest not : 

> TypeError: composant_fonction_model_mock_1.generateComposantFonctionMock is not a function
> 
>       112 |     // Given
>       113 |     http.expectOne('assets/i18n/plan/fr.json').flush(TRANSLATIONS_PLAN_FR);
>     > 114 |     component.composantFonctionLimites = [generateComposantFonctionMock()];
>           |                                           ^
>       115 |     component.composantFonctionLitmitType = ComposantFonctionTypeEnum.VALEURS_LIMITES;
>       116 |     component.numberOfValuers = 2;
>       117 |     // When
> 
>       at src/app/modules/invalidite/components/composant-fonction-limite-list/composant-fonction-limite-list.component.spec.ts:114:43
>       at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
>       at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:106:39)
>       at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:125:39)
>       at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
>       at Zone.Object.<anonymous>.Zone.runGuarded (node_modules/zone.js/dist/zone.js:151:47)
>       at runInTestZone (node_modules/@angular/core/bundles/core-testing.umd.js:141:25)
>       at node_modules/@angular/core/bundles/core-testing.umd.js:80:13
>       at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
>       at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:128:39)
>       at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
>       at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
>       at Object.testBody.length.done (node_modules/jest-zone-patch/index.js:51:29)

Here is my jest configuration (inside package.json) : 
```json
  "jest": {
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/src/jest/setupJest.ts",
    "globals": {
      "ts-jest": {
        "tsConfigFile": "src/tsconfig.spec.json",
        "useBabel": true
      },
      "__TRANSFORM_HTML__": true
    },
    "transform": {
      "^.+\\.(ts|html)$": "<rootDir>/node_modules/jest-preset-angular/preprocessor.js",
      "^.+\\.js$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(@ngrx|@mobi))"
    ],
    "moduleNameMapper": {
      "^.*\\.(jpg|jpeg|png|ico)$": "<rootDir>/src/jest/assetsTransformer.js",
      "@mobi/rwc-utils-ng-jslib": "<rootDir>/node_modules/@mobi/rwc-utils-ng-jslib/rwc-utils-ng-jslib.bundle.js",
      "@plandialog/invalidite": "<rootDir>/src/app/modules/invalidite/",
      "@plandialog/plan": "<rootDir>/src/app/modules/plan/",
      "@plandialog/domain": "<rootDir>/src/app/domain/",
      "@plandialog/shared": "<rootDir>/src/app/shared/",
      "@plandialog/core": "<rootDir>/src/app/core/",
      "@plandialog/(.*)": "<rootDir>/src/app/$1"
    }
  },
```
The incriminate function : 
```typescript
export const generateComposantFonctionMock = (): ComposantFonction => {
  return _.cloneDeep({
    numeroSequence: 1,
    base: generateLigneFonctionBaseMock(),
    minimum: generateLigneFonctionMinMock(),
    maximum: generateLigneFonctionMaxMock(),
  });
};
```
If you can point me what I'm doing wrong i would be hugely nice !! It's make a long time I'm looking for a solution.

Thanks in advance

**Comment by wtho** [comment]
I don't know if this is still relevant for you, but the issue seems to be with jest not being able to resolve the module `composant_fonction_model_mock`.

Can you list show us the file system relation and paths of the test file and the file exporting the mock function?
Could be an additional moduleNameMapper is required.

**Comment by McKratt** [comment]
Remove the code incriminated here
