### ISSUE TITLE
Not compatible with ts-jest@23.10.0

### ISSUE THREAD

**Issue by FrozenPandaz** [thymikee/jest-preset-angular#195]
## Current Behavior

`ts-jest@23.10.0` (published today) is a rewrite of the package and has many breaking changes

```
yarn list v1.9.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ jest-preset-angular@6.0.0
│  └─ ts-jest@23.10.0
```

## Expected Behavior

Short term, lock `ts-jest` to `~23.1.0`.

Long term, ensure compatibility with `ts-jest@^23.10.0`.

**Comment by ahnpnl** [comment]
PR is welcome 🙂

**Comment by byronmejia** [comment]
Thanks for the fix @FrozenPandaz ! Such a shame that  [`kulshekhar/ts-jest`](https://github.com/kulshekhar/ts-jest) can't follow semver...

How can we help with ensuring compatibility with 23.1.0? Any places to start at, or any tips?

**Comment by ahnpnl** [comment]
Hi @byronmejia

I contacted with ts-jest's contributors and got some clues to start but I am on vacation now so I don't have much time to look into it. You can contact @huafu to discuss a point to start :)

**Comment by byronmejia** [comment]
Awesome! Cheers. :)

**Comment by huafu** [comment]
@danil-z and others, here is my WIP PR #201, since I have no time for now to continue working on it. The big stuff remaining is explained in the header of the preprocessor.js file which itself needs to be removed.
