### ISSUE TITLE
Using jest-preset-angular with Pact for Contract Testing

### ISSUE THREAD

**Issue by Bmahecha123** [thymikee/jest-preset-angular#198]
Hello I'm trying to configure a Consumer based contract test using Pact library which requires Jest to run in a Node test environment. 

Receiving this error when I try to run my test.
```ReferenceError: XMLHttpRequest is not defined```
I see that jest-preset-angular brings in zone.js which is trying to pull in xhr.

Any way around this? Thank you for your time.

**Comment by ahnpnl** [comment]
Are you testing an Angular app or just a Node codebase ?

**Comment by Bmahecha123** [comment]
This is an Angular application that has Jest configured.

**Comment by willyboy** [comment]
It would be nice to be able to specify some tests be run in node. Like, angular service tests don't need zone usually so you could speed it up using:
/**
 * @jest-environment node
 */
at the top of those files.

**Comment by wtho** [comment]
@willyboy I have not tried it out, but jest can work with several configurations, see the [jest projects config](https://jestjs.io/docs/en/configuration#projects-array-string-projectconfig).

My first idea would be to use some naming scheme like `some-component.angular.spec.ts` and `some-service.unit.spec.ts`.

This way you can include and exclude files in tests, which would work file wise as you suggested.

**Comment by adriantoczydlowski** [comment]
@Bmahecha123 I have noticed that in the Node environment XMLHttpRequest is not defined. You can fix it by installing `xmlhttprequest` and add it to global variables:
```
global.provider = {
...
};
global.XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
```

**Comment by 39ro** [comment]
The environment used for testing is "jsdom" (default), as mentioned by their documentation:
https://jestjs.io/docs/en/configuration#testenvironment-string
"If you are building a node service, you can use the node option to use a node-like environment instead."

So in case "jsdom" is what you need, in your package.json or jest config file be sure ```testEnvironment``` is not being overwritten by a "node" environment.

**Comment by wtho** [comment]
@39ro actually we override `testEnvironment` when you load `jest-preset-angular` to use the latest jsdom as test environment:
https://github.com/thymikee/jest-preset-angular/blob/c05c122ec4e364d3a59b8524478b9425feadd059/jest-preset.js#L15

Anyway the `XMLHttpRequest` error is usually related to the preset not being loaded properly or `global.ts-jest` options overwritten in a wrong way, not as described in the README.md. If the ts-jest ast transformers are loaded properly, `XMLHttpRequest`s are not required anymore.

**Comment by wtho** [comment]
@Bmahecha123 does your problem still exist? It should work if you read through and follow the instructions in the README of this repo.
If there are still problems, feel free to address them here, otherwise please close this issue.
Cheers!

**Comment by ahnpnl** [comment]
Close as inactivity
