### ISSUE TITLE
[Bug]: NGCC Processor Throwing Error in Angular 16

### ISSUE THREAD

**Issue by michaelfaith** [thymikee/jest-preset-angular#1987]
### Version

13.0.0

### Steps to reproduce

This is more of a proactive issue, now that Angular 16.0.0-next.1 is released.  NGCC has been removed starting in Angular 16.  I set up this stackblitz to see how `jest-preset-angular` would behave, since it has the ngcc processor, and it's erroring out, whether you have `skipNgcc` enabled or not.  So this process will need to be removed in order for the library to continue working with v16.

https://stackblitz.com/edit/angular-16-jest-preset?file=jest.config.js&view=editor
Run `yarn test`

### Expected behavior

Should no longer import or attempt to run ngcc in the next major version.

### Actual behavior

Error: 
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Jest: Got error running globalSetup - /home/projects/angular-16-jest-preset/node_modules/jest-preset-angular/global-setup.js, reason: Package subpath './ngcc' is not defined by "exports" in /home/projects/angular-16-jest-preset/node_modules/@angular/compiler-cli/package.json
    at InternalError.get (https://angular16jestpreset-xiwd.w-credentialless.staticblitz.com/blitz.fc57b779eff411414c7b91114df9b720faaf721b.js:6:292489)
    at Object.run (file:///home/projects/angular-16-jest-preset/node_modules/jest-cli/build/run.js:129:14)
```

### Additional context

Angular CLI Release Notes: https://github.com/angular/angular-cli/releases/tag/16.0.0-next.0
Commit With NGCC Removal: https://github.com/angular/angular-cli/commit/c8ac660d8b13922be7ebcc92dfd5b18392602c40

### Environment

```shell
jest: 29.4.3
Angular core: 16.0.0-next.0
Angular cli: 16.0.0-next.1
typescript: 4.9.5
```

**Comment by michaelfaith** [comment]
@ahnpnl with the first Angular 16 Release Candidate published this week, I wonder if it would be appropriate to put out a "next" version with this issue addressed, so library authors can start prepping for the v16 release?

**Comment by ocombe** [comment]
That would be really great, this lib is the only thing holding us down now

**Comment by ahnpnl** [comment]
IIRC `setup-jest` is optional and not included in preset so if you don’t define `globalSetup` in your jest config you will be able to test with Angular 16.

**Comment by michaelfaith** [comment]
> IIRC `global-setup` is optional and not included in preset so if you don’t use it for Jest `globalSetup` in your jest config you will be able to test with Angular 16.

Yep, this works as a workaround.  Thanks for the tip.  I'm able to move forward with this.  It looks like `global-setup`'s entire purpose is to run `ngcc`.  So, is the ultimate solution to this bug, just removing `global-setup` from the lib entirely?

**Comment by ahnpnl** [comment]
The lib still supports angular 14 + 15 so the `global-setup` file would stay. Perhaps adding some error handling when cannot require the ngcc file at https://github.com/thymikee/jest-preset-angular/blob/85f4a58611efd499e1b16fe3a4c919fa05b0567f/src/utils/ngcc-jest-processor.ts#L11 would be the way to handle support 14 + 15

**Comment by PieterjanDeClippel** [comment]
@michaelfaith Isn't ngcc required in order to have intellisense in VS Code, without needing to rebuild the libs/apps?

**Comment by michaelfaith** [comment]
> @michaelfaith Isn't ngcc required in order to have intellisense in VS Code, without needing to rebuild the libs/apps?

No. ngcc has been removed from angular, as of v16.  It was only being used to convert (old) ViewEngine compiled libraries to work with the Ivy compiler.  But ViewEngine libraries are no longer supported, and the combability compiler (ngcc) was removed.
