### ISSUE TITLE
The coverage for constructors with injectables is wrong

### ISSUE THREAD

**Issue by danil-z** [thymikee/jest-preset-angular#199]
```
jest 23.6.0
ts-jest 23.10.3
jest-preset-angular-6.0.1
```

<img width="661" alt="screen shot 2018-10-03 at 7 12 46 pm" src="https://user-images.githubusercontent.com/509032/46450784-fdd4fe80-c747-11e8-8729-fbc2b5608ad8.png">

**Comment by ahnpnl** [comment]
This is a known issue and at the moment we still can't figure out how to solve this.

Basically this preset uses ts-jest to be able to run Jest with Angular ts file and add extra 2 snapshot serializers to support rendering HTML template.

Besides, the current version 6.0.1 isn't compatible with ts-jest 23.10.0 therefore we don't know if the coverage issue has been solved yet or not.

PR is welcome to solve coverage issue. We plan to make this preset compatible with 23.10.0 which is mentioned in #195

**Comment by danil-z** [comment]
repo to reproduce

https://github.com/danil-z/covjest

**Comment by 100hz** [comment]
Hey @thymikee,

wrote a plugin based on yours some time ago, which fixes the coverage problem. Please see https://github.com/100hz/jest-preset-ngx/blob/master/preprocessor.js#L33 It is mainly based on your work with some patches for accurate coverage. If you like i can make a PR, or you simply take this piece of code yourself.

Thanks for your work!

**Comment by thymikee** [comment]
@100hz I'm curious why we actually need that. If that works though, I'm happy to accept a PR with your changes, provided that you add some tests for this js regex.

**Comment by thymikee** [comment]
Maybe we should just fix the new ts-jest integration. Is anybody willing to take over that PR?

**Comment by huafu** [comment]
I'm sorry, new location, new house, new job, ... if it's not done yet as soon as I have a bit of time, I'll continue my work, but I don't think I'll be able to work on it before a 1 or 2 weeks

**Comment by thymikee** [comment]
Awesome, thanks! Enjoy new house :)

**Comment by ahnpnl** [comment]
confirm fixed in `7.0.0-alpha.1` cc @huafu
