### ISSUE TITLE
HTML file not transformed

### ISSUE THREAD

**Issue by thymikee** [thymikee/jest-preset-angular#2]
Source: https://twitter.com/beeman_nl/status/848244255105720324
@beeman can you provide a repro? I've tried new version of preset on your repo and all tests passed.

**Comment by beeman** [comment]
@thymikee it seems that it was something in my local repo :)

I nuked everything and it works like a charm. About to add tests to a bigger project 👍

**Comment by thymikee** [comment]
Awesome to hear that!
