### ISSUE TITLE
[Bug]: Jest snapshots feature is broken with Angular 15.2.2

### ISSUE THREAD

**Issue by richardeschloss** [thymikee/jest-preset-angular#2003]
### Version

13.0.0-next.1 

### Steps to reproduce

Attempt to create a snapshot on a very simple component: (AppComponent here, for example)
```js
//
...
await TestBed.configureTestingModule({
  declarations: [AppComponent],
}).compileComponents();
const fixture = TestBed.createComponent(AppComponent);
expect(fixture).toMatchSnapshot()
```

The test errors out because the latest @angular/core at 15.2.2 no longer exports `ɵivyEnabled` :( as the serializer is expecting [here](https://github.com/thymikee/jest-preset-angular/blob/ea8bf80ee8b58acc1313bed19592632d6f203dcf/src/serializers/ng-snapshot.ts#L46) and as a result, the else block [here](https://github.com/thymikee/jest-preset-angular/blob/ea8bf80ee8b58acc1313bed19592632d6f203dcf/src/serializers/ng-snapshot.ts#L63) incorrectly gets hit, causing the undefined error.

### Expected behavior

Expect snapshots to be taken / tested against.

### Actual behavior

Test failing on undefined errors.

### Additional context

Perhaps we might want to do away with the "is Ivy check?" altogether, and just make the latest preset only compatible with Ivy (and eliminate the else condition)? (Alternatives: read in the version property from angular/core to do the isIvy check)

### Environment

```shell
Windows 11 (I'm away from work computer at the moment)
```

**Comment by richardeschloss** [comment]
That export was removed recently in this PR: https://github.com/angular/angular/pull/49296 

I'm not sure what the meaning is behind their use of "theta" as a prefix for the export. Is that a Google convention?

**Comment by ahnpnl** [comment]
Indeed we observed our CI also failed in https://github.com/thymikee/jest-preset-angular/pull/2001

The theta is an Angular thing when they made the Ivy compiler. 

The original PR for Ivy compatibility is here https://github.com/thymikee/jest-preset-angular/pull/366

This preset is still supporting Angular versions which contain VE so I think we should create a separate serializer which doesn’t use that `ivyEnabled` check and ask Ivy users to use the new serializer. That will not become a breaking change.

**Comment by ahnpnl** [comment]
As long as there is an alternative way to detect Ivy mode, it should be ok. PR is welcome.

**Comment by vicentematus** [comment]
What would be the solution the to make snapshots works? is there any flag for the ivy related thing for Angular 15?

**Comment by vicentematus** [comment]
Ok so the solution was to update to  jest-preset-angular 13.0.1 based on the [issue on angular-builders](https://github.com/just-jeb/angular-builders/issues/1350). And also Jest.

Running

`ng update jest-preset-angular@13.0.1 jest@29 ts-jest@29 
`

And after that the snapshots started working
