### ISSUE TITLE
Tests failing only on WSL with 'Cannot find module'

### ISSUE THREAD

**Issue by bniedermeyer** [thymikee/jest-preset-angular#203]
Suddenly when running jest in my Angular app within a WSL terminal tests are failing at random with a variation of `Cannot find module ` or `No such file` error message pointing at my `node_modules` folder. Note: I ran `npm install` within the WSL work space so I don't believe it's an issue of incompatibility between windows and unix installs. 
e.g. 
```bash
# example of no such file error
ENOENT: no such file or directory, lstat '<root dir>/node_modules/tr46/lib/regexes.js'

      at Object.<anonymous> (node_modules/tr46/index.js:4:17)

# example of Cannot find module error
 Cannot find module '../start_of_week/index.js' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (node_modules/date-fns/start_of_iso_week/index.js:1:46)
```
I have not yet been able to find a pattern that is reproducible - the same tests aren't failing each time. To add even more confusion when I run my tests with my IDE (pointing to the same exact node_modules folder) everything works without issue - and the problem doesn't happen in our CI either. Here is the relevant sections of my `package.json`

```json
"dependencies": {
    "@angular-devkit/core": "^0.7.5",
    "@angular-devkit/schematics": "^0.7.5",
    "@angular/animations": "6.1.3",
    "@angular/cdk": "^6.4.6",
    "@angular/cli": "6.1.4",
    "@angular/common": "6.1.3",
    "@angular/compiler": "6.1.3",
    "@angular/core": "6.1.3",
    "@angular/forms": "6.1.3",
    "@angular/http": "6.1.3",
    "@angular/platform-browser": "6.1.3",
    "@angular/platform-browser-dynamic": "6.1.3",
    "@angular/router": "6.1.3",
    "core-js": "^2.4.1",
    "date-fns": "^1.29.0",
    "normalize.css": "^7.0.0",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.4",
    "@angular/compiler-cli": "6.1.3",
    "@angular/language-service": "6.1.3",
    "@angularclass/hmr": "^2.1.3",
    "@types/jest": "^23.3.2",
    "babel-preset-env": "^1.7.0",
    "codelyzer": "^4.3.0",
    "cz-conventional-changelog": "^2.1.0",
    "git-describe": "^4.0.3",
    "husky": "^0.14.3",
    "jasmine-marbles": "^0.3.1",
    "jest": "^23.5.0",
    "jest-preset-angular": "^6.0.0",
    "json-server": "^0.14.0",
    "lint-staged": "^7.2.0",
    "prettier": "^1.15.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "tslint-angular": "^1.1.1",
    "tslint-config-prettier": "^1.12.0",
    "typescript": "2.9.2"
  },
```

**Comment by ahnpnl** [comment]
hi @bniedermeyer, have you tried to add those packages in your `node_modules` into the white list to ignore transforming by jest ? It is `transformIgnorePatterns` configuration from jest.

**Comment by bniedermeyer** [comment]
@ahnpnl I have yes and still have the same issue. However the same commands work when run via my IDE's test commands (It's pointing at the same node_modules folder). 

It's almost like it's a permissions issue within WSL but I can't find a culprit.

**Comment by kazumeat** [comment]
I have the same issue. This is Windows problem..?

**Comment by bniedermeyer** [comment]
@kazumeat It might be - but I haven't had time to look into it further. I found a workaround to call my tests via my IDE (using webstorm) and have been using that for now.

**Comment by bvitale** [comment]
I don't use jest-preset-angular but this ticket convinced me I wasn't crazy when I was getting these same random file not found errors.. when running Jest based tests on WSL.

I was able to resolve the issues with the latest Windows 10 updates. I think the root cause was this:
https://github.com/Microsoft/WSL/issues/2712
https://docs.microsoft.com/en-us/windows/wsl/release-notes (search for 2712)

Hope this helps someone else.

**Comment by csaxe** [comment]
I had the same issue; resolved when IT allowed me to upgrade my machine to 1903.

**Comment by bniedermeyer** [comment]
Yeah - I think this is definitely an issue more on the WSL side vs a jest-preset-angular issue. I'm going to close this for now. FWIW if anyone runs across this later I found that if I don't have any processes (e.g my IDE) open to the directory my tests are in the chance for this random failure is much lower.

**Comment by csaxe** [comment]
A note that after an hour or more of searching, this was the first resource I found that addressed the same issue I was having, so this does seem a valuable resource for anyone working within an environment where they may not have access to latest Windows releases.

**Comment by ovgu12** [comment]
Thanks for reporting the issue as we are also having the issue while using jest with Vue. After trying to blame it for babel and co.. and googling to this thread i think we should upgrade to the latest Windows release.
