### ISSUE TITLE
[Bug]: ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. with ts-jest 29.0.5

### ISSUE THREAD

**Issue by msiemczyk** [thymikee/jest-preset-angular#2037]
### Version

13.0.1

### Steps to reproduce

There is no globals section in my jest.config.js; ie

globals: {
   'ts-jest': {
        tsconfig: '<rootDir>/tsconfig.spec.json',
   },
},

1. Setup Angular project with Jest 29.5.0 and jest-preset-angular 13.0.1
2. Run ng test or however you execute jest

### Expected behavior

Not to see any warnings.

### Actual behavior

Warning about use of ts-jest in globals:

ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},

![image](https://user-images.githubusercontent.com/5693250/228263141-b4b5c282-d338-4d15-9e7b-116705db03bb.png)

### Additional context

I had originally seen that warning when I actually had ts-jest in globals config, but I realized I didn't actually need it because I'm using default tsconfig.spec.json file. I don't think it's my configuration, but maybe I'm wrong.

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^29.5.0 => 29.5.0
```

**Comment by msiemczyk** [comment]
Ah, I just realized that you have a ticket for it already and it was merged. I guess we just need to release new version now.

https://github.com/thymikee/jest-preset-angular/pull/1937

**Comment by Halfist** [comment]
Still an issue in Angular 15 and Jest 28/29.
