### ISSUE TITLE
[Feature]: Support Angular 16

### ISSUE THREAD

**Issue by leosvelperez** [thymikee/jest-preset-angular#2058]
### 🚀 Feature Proposal

Add support for the upcoming Angular 16 version. If no changes are required (from what I tested, it seems fine), at least we need to extend the version range in the Angular package peer dependencies to include v16.

### Motivation

Angular 16 should be released this week https://angular.io/guide/releases#release-schedule. It would be good to have support for it as early as possible.

**Comment by michaelfaith** [comment]
#1987

**Comment by leosvelperez** [comment]
> Related: #1987

Yeah, it's related, but that one has a narrower scope. It's focused on a specific issue with Angular 16 that only happens in an optional setup where you use functionality that's no longer valid for that Angular version. I considered mentioning this there but I thought it was better to be its own issue so proper support for Angular 16 was done.

**Comment by michaelfaith** [comment]
v16 is now generally available: https://github.com/angular/angular/releases/tag/16.0.0 #

**Comment by henryruhs** [comment]
As the Angular team supports Jest now, does it make sense they provide a preset instead?

**Comment by ahnpnl** [comment]
what do you mean about "Angular team supports Jest now"? I didn't see they mentioned in `CHANGELOG`

**Comment by ocombe** [comment]
They talk about it here: https://blog.angular.io/moving-angular-cli-to-jest-and-web-test-runner-ef85ef69ceca

and the PR is here: https://github.com/angular/angular-cli/pull/25055

**Comment by ahnpnl** [comment]
Probably when the support becomes ready, this preset won't need anymore:)

**Comment by henryruhs** [comment]
This is how far I got to support Angular powered feature-libs but direct imports from node_modules are not allowed. If someone has an idea, please post it.

### npm scripts
```
"test": "NODE_OPTIONS=--experimental-vm-modules jest",
```

### jest.config.mjs

```
import { globalSetup } from '@angular-devkit/build-angular/src/builders/jest';

module.exports =
{
	globalSetup
};
```

**Comment by michaelfaith** [comment]
My team will be sticking with this library until Angular's jest support is production-ready.  You might ask in the Angular repo.

**Comment by henryruhs** [comment]
Sorry for hijacking this issue - I move the discussion to the Angular repo.

**Comment by nosaku** [comment]
Seems there is already PR for this, #2061

**Comment by k3nsei** [comment]
When would it be released? The required PRs have been merged.

**Comment by PieterjanDeClippel** [comment]
> @ahnpnl When would it be released? The required PRs have been merged.

Hi, the release happened 2 hours ago 🎉🎉🎉
