### ISSUE TITLE
Debugging does not work

### ISSUE THREAD

**Issue by kpaxton** [thymikee/jest-preset-angular#21]
I've gotten jest to work with my Angular v4+ application, which is great. Even installed the vscode-jest extension and got that working too. Thanks for writing this up!

However, now I'm trying to set up debugging within vscode and it doesn't seem to line up. The debugger starts, and is properly listening to node and the jest execution. However the breakpoints are never loaded and don't ever get hit. I'm assuming it has something to do with the transpiling that the ts-jest is doing and/or the sourcemaps not lining up properly. 

Any ideas on how to get this working with the debugger?

**Comment by thymikee** [comment]
I'm away currently, but search for debugging on jest repo on github, it should be an open issue, something a bit debugger statement

**Comment by thymikee** [comment]
It's this issue: https://github.com/facebook/jest/issues/1652

**Comment by kpaxton** [comment]
Thanks,
I'll check it out. I've tried a number of things so far to no avail though.

**Comment by thymikee** [comment]
Have you tried to use node 7 locally?

**Comment by thymikee** [comment]
Also cc @orta, maybe he can help with this

**Comment by kpaxton** [comment]
I have not tried Node 7. For us I think needing to upgrade to a non-LTS version would be too much of a risk for a production system for us to move to jest.

I would really like to get this working though.

**Comment by thymikee** [comment]
I mean just locally, you can still use LTS on production server. It's pretty easy to change node versions back and forth through `nvm` or `n`.

Because node 6 has known issues with not running debugger statement in vm context, which jest is using.

**Comment by thymikee** [comment]
Node 8 fixed the mentioned vm issue in one of their minor releases and it is now possible to debug Jest.
