### ISSUE TITLE
[Feature]: Documentation is missing information

### ISSUE THREAD

**Issue by Pauan** [thymikee/jest-preset-angular#2114]
### 🚀 Feature Proposal

I installed a new Angular project using `npx -p @angular/cli@latest ng new angular-jest`

Then I followed the [directions to install jest-preset-angular](https://thymikee.github.io/jest-preset-angular/docs/getting-started/installation).

However, when I ran `npm test` it continued to use Karma, not Jest.

The documentation fails to mention that you must change your `package.json` to this:

```json
"scripts": {
  "test": "jest --verbose",
  "test:watch": "jest --watch"
},
```

### Motivation

When following the documentation, the user should have a working setup.

**Comment by ahnpnl** [comment]
PR is welcome :)
