### ISSUE TITLE
Missing astTransformer

### ISSUE THREAD

**Issue by apo34** [thymikee/jest-preset-angular#215]
Hello,
First of all thanks for your great work. It really helped me to get on with testing our project.

Unfortunately, I stumbled upon an error.
I tried to migrate to 6.0.2, but since I have custom tsConfig.json location, I had to modify my jest.config, and now it looks like this
```module.exports = {
  preset: 'jest-preset-angular',
  global: {
    'ts-jest': {
      stringifyContentPathRegex: '\\.html$',
      tsConfig: 'tsconfig.json',
      astTransformer: [ require.resolve('jest-preset-angular/InlineHtmlStripStylesTransformer')]
    },
  },
...
```

unfortunately, it doesn't find `astTransformer` in that location, giving me an error:
`Error: Cannot find module 'jest-preset-angular/InlineHtmlStripStylesTransformer' ...`
I've noticed that given file is being ignored in .gitignore, maybe that's the reason.

I sure hope for a quick resolution!

**Comment by thymikee** [comment]
astTransformer is on `next` tag, version `7.0.0-alpha.2`, please use that :)

**Comment by apo34** [comment]
great, that solved that one!

however there's new problem down the road:

```PortalComponent
    ✕ should create component (184ms)

  ● PortalComponent › should create component

    Uncaught (in promise): Failed to load portal.component.html

      at resolvePromise (node_modules/zone.js/dist/zone.js:814:31)
      at resolvePromise (node_modules/zone.js/dist/zone.js:771:17)

  ● PortalComponent › should create component

    This test module uses the component PortalComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test.

      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine._initIfNeeded (../../packages/core/testing/src/test_bed.ts:403:17)
      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:602:10)

  ● PortalComponent › should create component

    expect(received).toBeTruthy()

    Received: undefined


```

Unfortunately even the simplest test fails to execute

**Comment by ahnpnl** [comment]
pls provide your sample code :)

**Comment by thymikee** [comment]
Please note that first time you run new transformer you likely need to do it with `--no-cache` flag passed (only when you're changing transformers)

**Comment by apo34** [comment]
Already tried `--no-cache`, however without success

Here's the test:
```
import { async, ComponentFixture, TestBed } from '@angular/core/testing';

import { PortalComponent } from './portal.component';

describe('PortalComponent', () => {
  let component: PortalComponent;
  let fixture: ComponentFixture<PortalComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        PortalComponent
      ],
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(PortalComponent);
    component = fixture.componentInstance;

    fixture.detectChanges();
  });

  it('should create component', () => {
    expect(component).toBeTruthy();
  });
});

```

and here's component: 
```
import { Component } from '@angular/core';

@Component({
  selector: 'portal',
  templateUrl: 'portal.component.html',
  styleUrls: ['portal.component.scss']
})

export class PortalComponent { }
```

both just the simpliest possible

**Comment by thymikee** [comment]
Can you extract this to a repository that we can download? The configuration is important here I guess.

**Comment by apo34** [comment]
Ok, I'll try that

**Comment by ahnpnl** [comment]
from the codes, I see it looks a bit wrong, you use `beforeEach(async())` to initialize `TestBed` environment, and `beforeEach` to create your component. What might happen is `beforeEach(async())` and not finish yet but `beforeEach` runs parallel and it can result in your `TestBed` environment is not ready to create the component. If you put like this
```
beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        PortalComponent
      ],
    })
    .compileComponents().then(() => {
         fixture = TestBed.createComponent(PortalComponent);
         component = fixture.componentInstance;

         fixture.detectChanges();
     });
  }));
```
it will work, or 
```
beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        PortalComponent
      ],
    });
    fixture = TestBed.createComponent(PortalComponent);
    component = fixture.componentInstance;

    fixture.detectChanges();
}));
```

More examples about are in our example folder. It contains a small app with some small test examples

**Comment by apo34** [comment]
@ahnpnl: Changing this indeed makes this more redable, but unfortunately, still with the same errors.
I'll link to the stripped repo in a minute

**Comment by apo34** [comment]
Here's the reproduction repo: https://github.com/apo34/angular-jest-test

**Comment by wtho** [comment]
Typo in `jest.config.js`:
```diff
-      astTransformer: [require.resolve('jest-preset-angular/InlineHtmlStripStylesTransformer')]
+      astTransformers: [require.resolve('jest-preset-angular/InlineHtmlStripStylesTransformer')]
```
Test is then passing for me.

**Comment by thymikee** [comment]
Ugh, we have validation in Jest, but `global` is omitted, because it's user generated :< I'd consider it closed then. Thanks @ahnpnl and @wtho for your help :)

**Comment by apo34** [comment]
Ugh.. Sorry for the fuss, and thank all of You for your help.
