### ISSUE TITLE
Use jest-localstorage-mock instead of mocking those objects oneself

### ISSUE THREAD

**Issue by jeserkin** [thymikee/jest-preset-angular#216]
`yarn add -D jest-localstorage-mock`

**Comment by thymikee** [comment]
I think this preset should use latest jsdom environment, like https://github.com/theneva/jest-environment-jsdom-thirteen. It already has localStorage built in, so we don't have to mock it. Plus other improvements. The drawback is that it requires Node 8, but one can always fallback to older jsdom and we can document it.
cc @ahnpnl @wtho
