### ISSUE TITLE
[Feature]: Ionic 6 - angular 14 setup 

### ISSUE THREAD

**Issue by sandy1198** [thymikee/jest-preset-angular#2177]
### 🚀 Feature Proposal

we have been getting lot of bug while trying to setup on ionic framework please helps for setup Documentation and support

### Motivation

we use same angular in ionic framework but imports are little different

**Comment by ahnpnl** [comment]
You can view doc at https://thymikee.github.io/jest-preset-angular/docs/guides/angular-13+#usage-with-ionic-6-or-7
