### ISSUE TITLE
[Feature]: Support Angular 16

### ISSUE THREAD

**Issue by tsteuwer-accesso** [thymikee/jest-preset-angular#2178]
### 🚀 Feature Proposal

The addon should support Angular 16.

### Motivation

Version 16 is the latest version of Angular. Currently it cannot be installed without using the npm `--force` flag due to it having a peer dependency on `@angular-devkit/build-angular` of <16, where the current version is 16.2.19.

**Comment by senbagaraman04** [comment]
Yeah without the support for 16.x, we are left with **--force** option

**Comment by ahnpnl** [comment]
Do you mean support v17?

The current latest tag in npm supported v16 already, see https://github.com/thymikee/jest-preset-angular/blob/3b3e58f1cedbf6b3fb64374b102e42b32b01dceb/package.json#L58

**Comment by senbagaraman04** [comment]
Angular 16 only , but with v13.1.2 , it started working without force  option. but same it was not working two three days back . Anyhow thanks for the fix

**Comment by GeoffreyBrunet** [comment]
up!

**Comment by ahnpnl** [comment]
The support version is now up to 17, I will close this
