### ISSUE TITLE
Unable to run tests [Bug]: 

### ISSUE THREAD

**Issue by sprakashg22** [thymikee/jest-preset-angular#2190]
### Version

8.3.2

### Steps to reproduce

Using the below config for package.json
"jest-preset-angular": "^8.3.2",
   "@types/jest": "^26.0.14",
  "@angular/core": "~8.2.1",
jest.config.json
module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  moduleNameMapper: {
    '^@ws-widget/utils$': '<rootDir>/library/ws-widget/utils/src/lib/services/configurations.service',
    'ws': '<rootDir>/project/ws/app/src/lib/routes/org/org-service.service',
    'src': '<rootDir>/src'
  }
}
setup-jest.ts
import 'jest-preset-angular/setup-jest'
at project level also and at an individual level, I'm getting this error message
$ npx jest src/app/maternity-callback/maternity-callback.component.spec.ts
FAIL src/app/maternity-callback/maternity-callback.component.spec.ts
  ● Test suite failed to run

    TypeError: platformBrowserDynamicTesting is not a function

    > 1 | import 'jest-preset-angular/setup-jest'
        | ^

      at Object.<anonymous> (node_modules/jest-preset-angular/build/setup-jest.js:18:63)
      at Object.<anonymous> (node_modules/jest-preset-angular/setup-jest.js:1:107)
      at Object.<anonymous> (setup-jest.ts:1:1)

  console.log
    undefined

      at Object.<anonymous> (library/ws-widget/utils/src/lib/services/configurations.service.ts:10:9)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.25 s
Ran all test suites matching /src\\app\\maternity-callback\\maternity-callback.component.spec.ts/i.

I have also renamed src/test.ts to src/karmaTest.ts
![image](https://github.com/thymikee/jest-preset-angular/assets/89121816/dc06039a-8641-4a5a-b45b-e55673eb155b)

### Expected behavior

I expect the test to pass or fail at the component.spec.ts level, 

### Actual behavior

here I guess its not even entering the component

### Environment

```shell
Windows 11
```

**Comment by ahnpnl** [comment]
You can check our examples folder for the setup.
