### ISSUE TITLE
[Feature]: Angular 17 Support

### ISSUE THREAD

**Issue by beshad** [thymikee/jest-preset-angular#2192]
### 🚀 Feature Proposal

Any idea if/when jest-preset-angular will support Angular 17? currently it requires ">=13.0.0 <17.0.0"

### Motivation

just to allow us to upgrade our applications to latest angular version

**Comment by ahnpnl** [comment]
Pls use 13.1.4 :)

**Comment by beshad** [comment]
perfect, that worked, thanks : )
