### ISSUE TITLE
[Feature]: Angular 17 support 

### ISSUE THREAD

**Issue by devgojokotech** [thymikee/jest-preset-angular#2196]
### 🚀 Feature Proposal

We need to update the import `zone.js/bundles/zone-testing.js` and `zone.js/dist/zone` to `zone.js` and `zone.js/testing` as they are updates now in angular version 17, it leads to incompatible issue while upgrading from 17.

### Motivation

It will add compatibility for angular 17.

### Example

.

**Comment by kpeters-cbsi** [comment]
So is `jest-preset-angular` not compatible with Angular 17?

**Comment by devgojokotech** [comment]
Yeah its not as of now, due to zonejs import path
<img width="867" alt="Screenshot 2023-12-21 at 10 37 42 AM" src="https://github.com/thymikee/jest-preset-angular/assets/118733747/5674a328-8ee9-469f-a594-492d704ffee2">

**Comment by cfrezier** [comment]
We also need this.

**Comment by ahnpnl** [comment]
We already made a release with updated zone import, see https://github.com/thymikee/jest-preset-angular/pull/2163

**Comment by ahnpnl** [comment]
Should be fixed with **v13.1.5**
