### ISSUE TITLE
Error when I use browser animations

### ISSUE THREAD

**Issue by SrHuevo** [thymikee/jest-preset-angular#22]
hello,

You should see the error here:

https://github.com/SrHuevo/error-jest-preset-bowser-animations-module

Greetings!

**Comment by thymikee** [comment]
So the error is gone if you remove this line:
```js
fixture.detectChanges();
```
but I have no idea, what's going on. Maybe it's a bug in Angular which gets covered by a browser.

**Comment by SrHuevo** [comment]
But if you use "fixture.detectChanges()" for update the view then the error will be displayed

**Comment by thymikee** [comment]
Yeah, I've seen its working in Karma, just not sure what's the problem. The error comes from Angular, like it needs some extra provider (I understand it should be included by the animation class). If you have some time to dig into it, that would be great.

**Comment by SrHuevo** [comment]
I tried, but I do not have enough knowledge. The only thing I have discovered is that in the test, BrowserAnimationsModule is not defined, whereas in app.module it is defined

**Comment by thymikee** [comment]
It's a bug in a preset, which I'll address later. To temporarily fix it, just move `animations` key above `styleUrls`

**Comment by SrHuevo** [comment]
great!, thanks @thymikee With this I can continue 😁
