### ISSUE TITLE
Add implicit peerDependencies explicitly to support Angular Libraries better

### ISSUE THREAD

**Issue by patoncrispy** [thymikee/jest-preset-angular#221]
I've been creating some Angular Libraries. Angular creates these in a `projects` subdirectory with their own `node_modules` and `package.json`. `jest-preset-angular` assumes that the dependencies listed below exist (which is usually true for standard Angular apps, but not necessarily for a library). If NPM can't find the package in the local `node_modules` it looks in parent directory for it and uses that one.

Problems arise when one starts to update these dependencies. Compatibility becomes an issue. I updated some of my dependencies and started getting all sorts of confusing issues. To resolve the issues I explicitly added the listed dependencies as `devDependencies`.

It would be great if these could be added as `peerDependencies` to state that they are indeed required by `jest-preset-angular`. It would help a lot when creating an Angular Library. I was going to create a PR myself, but I thought it should be up to the maintainers to decide the minimum version of each package supported as `jest-preset-angular` supports Angular 2+. :)

The required dependencies are:

- @angular/compiler
- @angular/platform-browser
- @angular/platform-browser-dynamic
- core-js
- rxjs
- zone.js

**Comment by ahnpnl** [comment]
Hi,

I checked the code base and we only require `@angular/core`, `@angular/platform-browser-dynamic`, `core-js`, `zone.js`. I don't know why `rxjs`, `@angular/compiler` and ` @angular/platform-browser` are in the list ?

**Comment by patoncrispy** [comment]
I think they're deps of `@angular/platform-browser-dynamic`? These were the dependencies I had to install to get Jest to run my tests, at least, so they may not _all_ be required...

**Comment by ahnpnl** [comment]
@wtho what do you think ?

**Comment by ahnpnl** [comment]
We won’t do anything for this as the current peerDependencies list is correct and reflects to what our source uses.
