### ISSUE TITLE
[Bug]: Input signals in components cause tests to error out (Angular v17.1.0)

### ISSUE THREAD

**Issue by gpremo-re** [thymikee/jest-preset-angular#2246]
### Version

14.0.0

### Steps to reproduce

1. Clone my repo (forked from this repo) https://github.com/gpremo-re/jest-preset-angular
2. Run tests in `example-app-v17` (specifically `DashboardHeroComponent`)

### Expected behavior

I expect unit tests to succeed when using `input()` signals in a component.

### Actual behavior

All tests fail.

For example:
`DashboardHeroComponent when inside a test host` fails with the following errors
```
  console.error
    NG0303: Can't bind to 'hero' since it isn't a known property of 'dashboard-hero' (used in the 'TestHostComponent' component template).
    1. If 'dashboard-hero' is an Angular component and it has the 'hero' input, then verify that it is included in the '@Component.imports' of this component.
    2. If 'dashboard-hero' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@Component.schemas' of this component.

      at reportUnknownPropertyError (node_modules/@angular/core/fesm2022/core.mjs:7418:17)
      at TestHostComponent_Template (ng:/TestHostComponent.js:14:21)
      at src/app/dashboard/dashboard-hero.component.spec.ts:100:13
```

```
Error: NG0950: Input is required but no value is available yet. Find more at https://angular.io/errors/NG0950

    at DashboardHeroComponent.inputValueFn [as hero] (C:\Projects\jest-preset-angular\examples\example-app-v17\node_modules\@angular\core\fesm2022\core.mjs:98:19)
    at DashboardHeroComponent_Template (ng:///DashboardHeroComponent.js:19:65)
    at executeTemplate (C:\Projects\jest-preset-angular\examples\example-app-v17\node_modules\@angular\core\fesm2022\core.mjs:12263:9)
    at refreshView (C:\Projects\jest-preset-angular\examples\example-app-v17\node_modules\@angular\core\fesm2022\core.mjs:13490:13)
    ...
    at NgZone.run (C:\Projects\jest-preset-angular\examples\example-app-v17\node_modules\@angular\core\fesm2022\core.mjs:14632:28)
    at ComponentFixture.detectChanges (C:\Projects\jest-preset-angular\examples\example-app-v17\node_modules\@angular\core\fesm2022\testing.mjs:251:22)
    at C:\Projects\jest-preset-angular\examples\example-app-v17\src\app\dashboard\dashboard-hero.component.spec.ts:100:13
```
`

### Additional context

The diff between my local branch and the mainline branch: https://github.com/thymikee/jest-preset-angular/compare/main...gpremo-re:jest-preset-angular:main

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
  Binaries:
    Node: 20.9.0 - ~\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 3.7.0 - ~\scoop\apps\nodejs-lts\current\bin\yarn.CMD
    npm: 10.1.0 - ~\scoop\apps\nodejs-lts\current\bin\npm.CMD
    pnpm: 8.10.2 - ~\scoop\apps\nodejs-lts\current\bin\pnpm.CMD
```

**Comment by ahnpnl** [comment]
I already had a chat with Angular team about this, an extra AST transformation needed. WIP to adopt it

**Comment by gpremo-re** [comment]
@ahnpnl Love to see you guys are so on top of it! I was wondering what the status of this was, and if you're looking for any additional help. I'd be happy to spearhead this specific issue if the core contributors have higher priorities.

**Comment by ahnpnl** [comment]
I just opened a PR. We are trying to use `esbuild bundle` mode to remove the effort of manually downloading angular source but let `esbuild` take care of it and build everything.

**Comment by bhalperin** [comment]
I'm also waiting for a fix. Thanks.

**Comment by Nesho-Developer** [comment]
when will the PR be merged?

**Comment by vikashkumar29** [comment]
We are using nx monorepo where we are still seeing the same issue. We tried the latest version but could not get through. We are using the following versions:

nx: 18.0.8
jest: 29.7.0
jest-preset-angular: 14.0.3

Any help on this would be really helpful.

**Comment by vikashkumar29** [comment]
Update:
with **useESM:true** in the jest.config.ts we are not seeing this issue anymore. I am not sure, if this flag is mandatory for the input signal.

**Comment by PowerSupply** [comment]
I would like to add that this is also a problem when dynamically creating a component through using [createComponent](https://angular.io/api/core/createComponent).

This is really a problem since it prevents us from creating any component that has a signal input. The problem gets even bigger since there is no way of knowing if any inputs are required or not. The [ComponentMirror interface is missing](https://github.com/angular/angular/issues/52117) that information.

**Comment by vbraun** [comment]
With 14.0.3 I can set normal input signals, but `input.required` signals fail. I've opened https://github.com/thymikee/jest-preset-angular/issues/2370
