### ISSUE TITLE
Promise and Async not found when using 7.0.0-alpha.2

### ISSUE THREAD

**Issue by distante** [thymikee/jest-preset-angular#225]
After update `jest-preset-angular` to 7.0.0-alpha.2 when I run jest the tests that uses `Promise` or `async` fail when they worked correctly with version 6.

This is reproducible cloning this repository and updating jest-preset-angular to 7.0.0-alpha.2 : https://github.com/ajcrites/ionic-jest-testing-example

![image](https://user-images.githubusercontent.com/5490201/52032562-bdcd2f00-2521-11e9-947d-330933a02f6b.png)

**Comment by wtho** [comment]
I am not sure why it worked with v6, but to use Promises and Async/Await you have to add `"lib": [ "es2018" ]` (or a lower level) to `tsconfig.spec.json`, or extend from `../tsconfig.json`.

Otherwise you will just work with `es5`, which does not include these language features.

**Comment by distante** [comment]
You are right @wtho ! Thank you for pointed it out.
