### ISSUE TITLE
"@types/jest" had a breaking change in 23.3.14

### ISSUE THREAD

**Issue by iRoyPeleg** [thymikee/jest-preset-angular#226]
Hey,

So you currently have `@types/jest` under dependencies:
```
"dependencies": {
    "@types/jest": "^23.3.10",
    "ts-jest": "~23.10.5"
  },
```

Version 23.3.13 of `@types/jest` was compatible all the way down to TypeScript 2.2 I believe.
Version 23.3.14 requires at least TypeScript 2.8, which broke one of our apps build process.

First, do you need `@types/jest` under dependencies at all? can it be under `devDepenedencies` instead?

Second, we're currently aiming at `^23.3.10`, maybe change it to `23.3.13` just so it won't break apps under TS 2.8?

Thanks.

**Comment by thymikee** [comment]
It should be a dev dep, happy to accept PR :)

**Comment by wtho** [comment]
I think it was a conscious decision to put it in devdep, but I'm not sure why.

https://github.com/thymikee/jest-preset-angular/commit/2273e1f4229720fc38508fa8232d0eeecf099a0d

**cc @ahnpnl**

**Comment by ahnpnl** [comment]
My idea at the point I put into dependencies was to make it easier when installing the preset. But no problem to put it in dev deps again👍
