### ISSUE TITLE
Add snapshot support

### ISSUE THREAD

**Issue by thymikee** [thymikee/jest-preset-angular#23]
📸

**Comment by intellix** [comment]
Noticed that the angular version is within the snapshots and imagine it'll cause all snapshots to break each major/minor/bugfix version bump. Is it worth hacking away that attribute? 

When Angular is updated, do you just remove your snapshot folder and let it take another?

**Comment by thymikee** [comment]
You never remove snapshots folder manually. It should always be handled by Jest. I think we're good to remove the `ng-version` attribute though 👍

**Comment by jblankenhorn** [comment]
@thymikee sorry for the question, but is this already released to npm?

**Comment by thymikee** [comment]
Yes! It's version 1.1.0
