### ISSUE TITLE
[Feature]: Support viewChild query from 17.2

### ISSUE THREAD

**Issue by eiswind** [thymikee/jest-preset-angular#2315]
### 🚀 Feature Proposal

17.2 has added signal queries like

```
newMessageRef = viewChild.required<ElementRef<HTMLInputElement>>('newmessage');
```

currently this fails when we try to read the signal in a test with

```
 NG0951: Child query result is required but no value is available. Find more at https://angular.io/errors/NG0951

      48 |     this.messageService.saveMessage({ text: message, likes: 0});
      49 |     this.updateMessages();
    > 50 |     this.newMessageRef().nativeElement.value = '';
```

The same test is fine when run with karma.
I had hoped this would have worked already.

### Motivation

It would be great if this was working ootb.

**Comment by ahnpnl** [comment]
I thought https://github.com/thymikee/jest-preset-angular/pull/2303 would already support queries like `viewChild`? With **v14.0.2** it doesn't work with `viewChild`?

**Comment by eiswind** [comment]
I thought the same, but it doesnt.

https://stackblitz.com/~/github.com/eiswind/mre-viewchild-query-jest

ng test runs karma -> works
jest -> fails

**Comment by eiswind** [comment]
@ahnpnl thanks a lot for looking into this. I can see this new test working, but now I am completely lost. I checked out the v17 example from your source, and I cannot get it working there either:

```
@Component({
  template: `
    <h2 highlight="skyblue">About</h2>
    <h3 #el>Quote of the day:</h3>
    <twain-quote></twain-quote>
  `,
  standalone: true,
  imports: [HighlightDirective, TwainComponent],
})
export class AboutComponent {
  input = viewChild.required<ElementRef>('el');
}
```
added a test like:
``` 
it('should read the viewChild',()=>{
    expect(fixture.componentInstance.input()).toBeDefined();
  })
``` 
so it must be something with the project setup I guess. I already tried a couple if things I don't competeley understand.
I would really appreciate if you could take another look into this.

If it helps I could publish the example test in a fork.

**Comment by eiswind** [comment]
OK sorry twice, after updating to 14.03. its working. 
Thanks again for looking into this.
