### ISSUE TITLE
[Feature]: Package Updation

### ISSUE THREAD

**Issue by mithun2003** [thymikee/jest-preset-angular#2368]
### 🚀 Feature Proposal

The @angular-devkit/build-angular package is now at version 17.3.3 but in the jest-preset-angular the version is 17.2.3 so please update that

### Motivation

when i use the package i get an error

### Example

npm ERR! Found: @angular-devkit/build-angular@17.2.3
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"^17.3.1" from the root project
npm ERR!   peer @angular-devkit/build-angular@">=13.0.0 <18.0.0" from jest-preset-angular@13.1.6

**Comment by ahnpnl** [comment]
Hi, you are not using the latest version **14.0.3**, your version is `jest-preset-angular@13.1.6` from the logging
