### ISSUE TITLE
preprocessor.js in the transform option was not

### ISSUE THREAD

**Issue by snebjorn** [thymikee/jest-preset-angular#238]
I updated 

> `"@types/node": "~11.9.5"` ->  `"@types/node": "^11.11.3"`
> `"jest": "^23.6.0"` ->  `"jest": "^24.5.0"`
> `"jest-preset-angular": "^6.0.2"` -> `"jest-preset-angular": "^7.0.1"`

Also have `"@angular-builders/jest": "^7.3.1"` installed

And now I'm getting this error when running `ng test`

> ● Validation Error:
> 
>   Module ...\node_modules\jest-preset-angular\preprocessor.js in the transform option was not found.
>          <rootDir> is: ...
> 
>   Configuration Documentation:
>   https://jestjs.io/docs/configuration.html

Please help :)

**Comment by wtho** [comment]
jest-preset-angular v7 was released only some days ago.

angular-builders/jest still uses v6 with preprocessors.

If you want to use the newest version of this preset you have to wait for angular-builders to release a new version or to use the preset without the builders wrapper (by calling jest directly, not through ng)

**Comment by snebjorn** [comment]
I see, thank you for the quick response :)
