### ISSUE TITLE
core-js v2 not listed as dependency, but imported in setupJest.js

### ISSUE THREAD

**Issue by wtho** [thymikee/jest-preset-angular#244]
Some days ago core-js v3 was released and changed its library structure.

`jest-preaet-angular` imports core-js in `setupJest.ts`, without specifying the version anywhere.

This leads to confusion as more projects update to v3 and the old interface is not available anymore.

I think we should specify the core-js version at least as peerDependency, so that npm can warn the developer when core-js v2 is not available.

**Comment by lonix1** [comment]
Yes this would be a great help! It was so confusing because the errors I was getting did not help to trace the problem.

**Comment by thymikee** [comment]
Feel free to make it a peer dep :)

**Comment by skorunka** [comment]
What helped me was to add `"jest-preset-angular": "7.1.0",`(just latest) to `devDependencies` and `yarn`(`npm i`).

**Comment by wtho** [comment]
@skorunka Yeah, it was released in `7.1.0`, but should also be solved when using a newer version.
