### ISSUE TITLE
[Question] Multi-app nx workspace

### ISSUE THREAD

**Issue by lonix1** [thymikee/jest-preset-angular#248]
I'm using nx, so my workspace has angular and express apps and libraries, each with their own config files:

````
/jest.config.js
/apps/angularclient/jest.config.js
/apps/expresserver/jest.config.js
/libs/shared/jest.config.js
````

The child config files extend/override the root config file.

The problem is I can't specify `preset: 'jest-preset-angular'` in the root config as it would also apply to an express app (which uses other presets). So I specify it in the angular app's config.

However then the jest tests fail (missing references, etc.) How can I get this to work?

**Comment by thymikee** [comment]
Use `projects` instead of extending configs: https://jestjs.io/docs/en/configuration#projects-array-string-projectconfig

**Comment by lonix1** [comment]
That doesn't solve the problem because the preset needs to apply to everything or nothing. It doesn't seem to work selectively with only certain projects in the workspace.

**Comment by thymikee** [comment]
Can you prepare a minimal repro so we can investigate? This seems weird. What errors do you get btw?

**Comment by lonix1** [comment]
Let me hack on but a bit longer before I waste any more of your time :) Thanks
