### ISSUE TITLE
[Bug]: ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by pierreclaverkoko** [thymikee/jest-preset-angular#2514]
### Version

14.1.0

### Steps to reproduce

![Uploading Screenshot from 2024-06-10 14-26-27.png…]()
![Uploading Screenshot from 2024-06-10 14-26-27.png…]()
![Uploading Screenshot from 2024-06-10 14-26-27.png…]()

### Expected behavior

I expect to see successful test.

### Actual behavior

When running "npm run test", some components test failling with message "ReferenceError: TextEncoder is not defined".

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 9.1.3 - ~/.local/share/pnpm/pnpm
  npmPackages:
    jest: ^29.7.0 => 29.7.0
```

**Comment by ahnpnl** [comment]
Hi, you can check duplicated issue #1914
