### ISSUE TITLE
[Question] Using multiple presets

### ISSUE THREAD

**Issue by lonix1** [thymikee/jest-preset-angular#253]
Hey @thymikee I appreciate this preset.

Quick question: can we use multiple presets at the same time? I can't get it to work and I'm unsure whether it's my config or whether it's impossible.

I'm using [`ts-nameof`](https://github.com/dsherret/ts-nameof/blob/master/packages/ts-nameof/setup/jest.md) (brilliant library that allows `nameof` in typescript!) and it wants this config:

````javascript
"globals": {
  "ts-jest": {
    "astTransformers": ["ts-nameof"]
  }
},
preset: "ts-jest",
````

But that will [override your preset](https://github.com/thymikee/jest-preset-angular#exposed-configuration). So I combine them:

````javascript
globals: {
  "ts-jest": {
    tsConfig: "<rootDir>/tsconfig.spec.json",
    stringifyContentPathRegex: "\\.html$",
    astTransformers: [
      "ts-nameof",
      require.resolve("jest-preset-angular/InlineHtmlStripStylesTransformer"),
    ]
  }
},
preset: "jest-preset-angular",      // <-- not a problem as it wraps ts-jest
````

But then your preset works, and that one fails (compiler doesn't understand `nameof`).

Can your preset be combined with other presets? I assume so because `astTransformers` is an array, but in practice it doesn't work. I just need a pointer - where do you think the problem is 1) this preset, 2) nameof preset, or 3) ts-jest?

**Comment by thymikee** [comment]
No they can't be in JSON config. But you can use JS config (`jest.config.js`) and merge objects as you wish (you'll need to require `jest-preset-angular/jest-preset.js` and `ts-jest/jest-preset.js` or json, go figure).

**Comment by lonix1** [comment]
Sorry I'm a little confused... I'm already using js config.

Are you saying that in theory using multiple presets is possible - so the problem is my config, not any of these libraries?

**Comment by thymikee** [comment]
Yes, something like this.

**Comment by lonix1** [comment]
Thanks!

**Comment by lonix1** [comment]
No that doesn't make a difference, it actually gives the same result as what I put in the original comment.

So for anyone else with this problem, the short answer is: yes, presets can be combined.

But this particular combination doesn't work. Probably the problem is with ts-jest or ts-nameof.

**Comment by RaviH** [comment]
@lonix1 Can you please share an example of how you merged the presets?

**Comment by lonix1** [comment]
@RaviH Sorry I don't use this anymore :(
