### ISSUE TITLE
[Bug]: Seems ts-jest 29.2.x broke something

### ISSUE THREAD

**Issue by Delagen** [thymikee/jest-preset-angular#2585]
### Version

14.1.1

### Steps to reproduce

Install ts-jest 29.2.x
Tune tests in ESM mode

```ts
 setupFilesAfterEnv: [
        resolve(currentDir, 'jest.setup.ts'),
    ],
```

jest.setup.ts
```ts
import 'jest-preset-angular/setup-jest.mjs';

const jest = import.meta.jest;
```

### Expected behavior

All works as expected

### Actual behavior

```log
jest.setup.ts:11:14 - error TS1470: The 'import.meta' meta-property is not allowed in files which will build into CommonJS output.

    11 const jest = import.meta.jest;
                    ~~~~~~~~~~~
```

### Environment

```shell
System:
    OS: Windows 11 10.0.26252
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
  Binaries:
    Node: 22.4.0
    npm: 10.8.2
  npmPackages:
    jest: ~29.7.0 => 29.7.0
```

**Comment by ahnpnl** [comment]
Hi, we have example apps at https://github.com/thymikee/jest-preset-angular/tree/main/examples which already had **29.2.x** Would you please put your reproduce scenario there? Thanks!

**Comment by ahnpnl** [comment]
Hmm CI passes though using yarn. could you pls try yarn instead? Not sure what’s going on with npm though.

**Comment by Delagen** [comment]
@ahnpnl Seems I find the case of my issue.

Need to set  "moduleResolution": "NodeNext" in tsconfig.spec.json, because strange but it stops to work with value `Bundler`
