### ISSUE TITLE
Bundle all in one file using @angular-devkit/build-angular:browser-esbuild and run with ESM

### ISSUE THREAD

**Issue by remi-amadeus** [thymikee/jest-preset-angular#2634]
Hi,

Is there anyway easy way to leverage @angular-devkit/build-angular:browser-esbuild to bundle all the application + the spec files in a single file. And then run it with jest esm? It would speed up the tests execution a lot in my opinion. 

Thank you

**Comment by ahnpnl** [comment]
I think there is an existing direction is following what `AnalogJS` does with `Vitest`
