### ISSUE TITLE
Jest with Angular 2 Unexpected Token when Import * as React from 'react'

### ISSUE THREAD

**Issue by k9a8r7e6n5** [thymikee/jest-preset-angular#265]
Hi,

Error as below throw out:
 FAIL  src/app/services/login.service.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in you
r config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMa
pper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    ...*\ButtonGroup.jsx:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as React from 'rea
ct';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      17 |   Button,

Seems file ButtonGroup.jsx imports 'react' that triggered this error. 
I tried #64 and #66 , but still not working. 

Using jest is "jest": "^24.8.0"

**Comment by ahnpnl** [comment]
hi, I don't think this is related. This preset is meant for Angular. Regarding to React, jest and typescript, please refer to `ts-jest`.

**Comment by wtho** [comment]
What the error `Unexpected Token when Import * as React from 'react'` is trying to tell you, is that it expects `es5`, but the `import`-syntax is `es6`. You need some transformer (babel) to handle this. Please refer to jest for this issue.

If you really want to import the react components inside the angular tests, you might have to combine the two presets in some way, which might be very tricky to setup.

Another solution might be to completely mock the react part while testing the angular components. For this please refer to the jest mocking documentation.

https://jest.io

**Comment by rafik-z** [comment]
You can try going with 'esModuleInterop' in your tsconfig. Did the trick for me.

**Comment by louMoxy** [comment]
Did anyone get a solution to this? 'esModuleInterdrop' didn't work for me

**Comment by louMoxy** [comment]
Okay managed it by adding to my jest config:
transform: {
    "^.+\\.(ts|tsx|html)$": "ts-jest",
    "^.+\\.js$": "babel-jest"
  },

and then adding babel config: 

module.exports = function(api) {
  api.cache(true);

  const presets = ['@babel/preset-env'];
  const plugins = [];

  return {
    presets,
    plugins,
  };
};

**Comment by k9a8r7e6n5** [comment]
@ahnpnl 
We rewrite the *.jsx file using Object.defineProperty, set esModuleInterop as true in tsconfig.json, then it works.
