### ISSUE TITLE
[Bug]: Test modifier `failing` is not supported

### ISSUE THREAD

**Issue by marcelhohn** [thymikee/jest-preset-angular#2672]
### Version

14.2.2

### Steps to reproduce

1. Clone the repository at https://github.com/marcelhohn/jest-playground
2. run `npm i`
3. run `jest`
4. See the error `TypeError: it.failing is not a function` originating from `src/test.spec.ts`

For checking `it.only.failling` and `it.skip.failing` replace `test.failing` in `src/test.spec.ts` with the respective command and show the error occur again.

### Expected behavior

The method [`test.failing`](https://jestjs.io/docs/api#testfailingname-fn-timeout), and its related methods `test.failing.each`, `test.skip.failing`, and `test.only.failing`, as well as their aliases are supported.

Altervative: The missing support is documented as known issue.

### Actual behavior

Tests fail to run and produce the error `TypeError: it.failing is not a function` .

### Additional context

To be honest, I didn't know whether to report this as a bug report or a feature request. Since the test modifier  `failure` has been added [already two years ago](https://github.com/jestjs/jest/blob/main/CHANGELOG.md#features-17), I thought it should be at least documented that it is not supported.

It looks like this issue is caused by [Zone.js](https://github.com/angular/angular/tree/main/packages/zone.js) not supporting the modifier. This is supported by the fact that the test suite runs as expected when commenting out `require('zone.js/testing')`  in `jest-preset-angular/setup-jest.js`.

Probably adding a line similiar to [this one](https://github.com/angular/angular/blob/main/packages/zone.js/lib/jest/jest.ts#L133) in Zone.js would fix the issue. However, since Angular is [moving towards a zoneless application model](https://github.com/angular/angular/tree/main/packages/zone.js#development-status-of-zonejs), it seems quite unlikely to me that this would be addressed. 

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
  Binaries:
    Node: 20.11.1 - ~\AppData\Local\Programs\nodejs\node.EXE
    npm: 10.2.4 - ~\AppData\Local\Programs\nodejs\npm.CMD
  npmPackages:
    jest: ^29.7.0 => 29.7.0
```

**Comment by ahnpnl** [comment]
@marcelhohn the fix will be in the new release of `zone.js`. I will close this issue as it was merged on Angular repo. Thanks for your report 👍
