### ISSUE TITLE
I could not run test of componente that use ng-snotify service

### ISSUE THREAD

**Issue by yoan-asdrubal** [thymikee/jest-preset-angular#268]
Hi everyone. I am begining with testing in angular apps, reclently I made works my proyect with Wallabyjs + jest, everything was fine, but some guy of the team need to use ng-snotify, he made all changes and the project works, but when I run test I get fails because of ng-snotify. 
there is my jest config, working fine before add  ng-snotify.
<pre> module.exports = {
	globals: {
		'ts-jest': {
			tsConfigFile: '<rootDir>/src/tsconfig.spec.json',
		},
		__TRANSFORM_HTML__: true,
	},
	testMatch: ['**/__tests__/**/*.+(ts|js)?(x)', '**/+(*.)+(spec|test).+(ts|js)?(x)'],
	setupFilesAfterEnv: ['<rootDir>/node_modules/@angular-builders/jest/src/jest-config/setup.js'],
	transformIgnorePatterns: ['node_modules/(?!@ngrx)'],
	moduleDirectories: [
		"node_modules",
		"src/app",
	],
	collectCoverageFrom: [
		'src/app/module/**/*.{ts}',
		'!src/app/*.{ts}',
		'!src/app/**/*.{js}',
		'!src/app/environment/*.{ts}',
		'!src/app/language/*.{ts}',
		'!src/app/**/*.module.{ts}',
		'!src/app/**/*.interface.{ts}',
		'!src/app/**/*.state.{ts}',
		'!src/app/**/*.entity.{ts}'
	],
	moduleFileExtensions: [
		'ts',
		'tsx',
		'json',
		'js'
	],
	moduleNameMapper: {
		'@app/(.*)': "<rootDir>/src/app/$1",
		'@env/(.*)': "<rootDir>/src/environments/$1"
	}
};
</pre>
This is the error I get.
<pre>

Jest encountered an unexpected token

This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

Here's what you can do:
 • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
 • If you need a custom transformation specify a "transform" option in your config.
 • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

URL_TO_NODE_MODULES\node_modules\ng-snotify\index.js:1

({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { ChangeDetectionStrategy, Component, EventEmitter, Inject, Injectable, Input, NgModule, Output, Pipe, ViewEncapsulation } from '@angular/core';
</pre>
I checked there and I sow there is some file named index.js and index.d.ts with diferent contents, I dont know if that throw some conflict.

index.js
<br>
![image](https://user-images.githubusercontent.com/42411788/57859347-c25fdf80-77c0-11e9-952d-a1881e06392b.png)
<br>
index.d.ts
![image](https://user-images.githubusercontent.com/42411788/57859303-abb98880-77c0-11e9-845f-972a4c5bebfd.png)

Here my tsconfig.spec.json if you need it.
<pre>
{
	"extends": "../tsconfig.json",
	"compilerOptions": {
		"outDir": "../out-tsc/spec",
		"module": "commonjs",
		"types": [
			"jest",
			"node"
		],
		"paths": {
			"@app/*": [
				"src/app/*"
			],
			"@env/*": [
				"src/environments/*"
			]
		}
	},
	"files": [
		"polyfills.ts"
	],
	"include": [
		"**/*.spec.ts",
		"**/*.d.ts"
	]
}
</pre>
I tried to adding  'node_modules/(?!ng-snotify)' to transformIgnorePatterns property but nothing  changes.

**Comment by wtho** [comment]
Hey,
there are several StackOverflow posts regarding this (and similar issues), and I think this would also be the better place for support requests. Especially, as later on answered questions are generally easier to find than closed issues.

Anyhow, in Node you can only work with the commonjs-import syntax (`const x = require('...')`) and not with `import { ... }`.
In case libraries are published in es6-import style (like `ng-snotify),  you have to do two things to transpile it before passing it to jest:
* Tell jest to not ignore it (you did that right using `transformIgnorePatterns`)
* Tell the transpiler to process the file. As the transpiler in this case is `tsc`, it will only transpile `.ts` files. To also process `es6`-js files, add `"allowJs": true` to your `compilerOptions` in `tsconfig.spec.js`. This way `tsc` will not ignore the `ng-snotify`-library anymore, but transform the import statements and make it usable for jest.

**Comment by yoan-asdrubal** [comment]
HI <strong>wtho</strong>, thanks for your PD, I updated the images of the description of issue, I did not realize about that ;) 👍 . And thanks again for your answer, I found similar solutions but no nobody mentioned  to add "allowJs": true in <b> tsconfig.spec.json</b>, everybody mentioned just <b>transformIgnorePatterns</b>. Thanks again.

**Comment by yoan-asdrubal** [comment]
Hi again, I reopened it because now all my test pass using jest, but when I try to wallaby.js with jest I get the same error, I dont know if is here when I should post this topic, sorry if I am in a wrong place and thanks for your help.
here my config of wallaby.js in my app.
<pre> 
const ngxWallabyJest = require('ngx-wallaby-jest');

module.exports = function (wallaby) {
	return {
		files: [
			'src/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
			'tsconfig.json',
			'tsconfig.spec.json',
			'jest.config.js',
			'!src/**/*.spec.ts',
		],

		tests: ['src/**/*.spec.ts'],

		env: {
			type: 'node',
			runner: 'node'
		},
		compilers: {
			'**/*.ts?(x)': wallaby.compilers.typeScript({ module: 'commonjs' }),
		},
		preprocessors: {
			// This translate templateUrl and styleUrls to the right implementation
			// For wallaby
			'src/**/*.component.ts': ngxWallabyJest,
		},
		testFramework: 'jest'
	};
};
</pre>

Even when log file show me its a problem of jest config, only with jest everything works good.
<br>
![image](https://user-images.githubusercontent.com/42411788/57874520-c7cc2280-77de-11e9-88fd-88b8be325bf0.png)

**Comment by wtho** [comment]
I do not know much about `wallaby.js` and we are not concerned about it.

If the tests run fine in jest using this preset (and also fail if expected), this preset works perfectly. If you could confirm this and close the issue then would be awesome.

Maybe open a follow-up issue at `wallaby.js`'s repo or a question on StackOverflow.

**Comment by yoan-asdrubal** [comment]
You are rigth, everything works without problems, thanks for your help.
