### ISSUE TITLE
[Bug]: Missing build directory in version 14.2.3

### ISSUE THREAD

**Issue by skrtheboss** [thymikee/jest-preset-angular#2740]
### Version

14.2.3

### Steps to reproduce

Update to jest-preset-angular 14.2.3 and execute tests:

`Module jest-preset-angular in the transform option was not found.`

### Expected behavior

Should ship build files

### Actual behavior

Build files are missing

### Environment

```shell
System:
    OS: Linux 6.10 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 9.8.0 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
  npmPackages:
    jest: 29.7.0 => 29.7.0
```

**Comment by ghiscoding** [comment]
I'm not sure if it's related but I'm also getting errors, though a bit different, on my side as well and it was working fine before (I use Renovate)

> $ jest --runInBand --coverage=true --ci --config ./test/jest.config.ts
Error: ● Validation Error:
>
>  Preset jest-preset-angular not found.

**Comment by ahnpnl** [comment]
I think this should be fine now, pls take a look
