### ISSUE TITLE
[Bug]: Module jest-preset-angular in the transform option was not found

### ISSUE THREAD

**Issue by splincode** [thymikee/jest-preset-angular#2745]
### Version

latest

### Steps to reproduce

https://github.com/taiga-family/ng-morph/pull/879

<img width="682" alt="image" src="https://github.com/user-attachments/assets/3b9011df-50f5-4b1c-9222-5bd391ea6478">

https://github.com/taiga-family/ng-morph/actions/runs/10829760839/job/30048015399?pr=879

**Comment by ahnpnl** [comment]
fixed in **14.2.4**
