### ISSUE TITLE
[Feature]: setup-jest as function instead of import with side effect

### ISSUE THREAD

**Issue by StavNoyAkur8** [thymikee/jest-preset-angular#2755]
### 🚀 Feature Proposal

In the current setup, we import the setup file, and it executes as a side effect:

```ts
// <root>/test-setup.ts
import "jest-preset-angular/setup-jest";
```

I would like instead to be able to import it as a function:

```ts
import { setupJest } from "jest-preset-angular/setup-jest";

setupJest();
```

### Motivation

Importing as a side effect is non obvious.
Many formatters will automatically put import statements at the top of the document. This makes it so that if we want to setup the global `ngJest`, which should be before the import, so it's accessible to the setup:

```ts
globalThis.ngJest = {
  testEnvironmentOptions:  {
    errorOnUnknownElements: true,
    errorOnUnknownProperties: true,
  };
};
import "jest-preset-angular/setup-jest";
```
After formatting it goes under the import:

```ts
import "jest-preset-angular/setup-jest";

globalThis.ngJest = ...
```

Rendering it effectively useless.

By having it as a function, we can circumvents that problem by calling it when we're ready:

```ts
import { setupJest } from "jest-preset-angular/setup-jest";

globalThis.ngJest = ...
setupJest();
```

Additionally, it opens the possibility to pass that config as a parameter, instead of having to set the (untyped) global:

```ts
setupJest({
  testEnvironmentOptions:  ...
});
```

Currently, my other workaround is to set the [`globals` ](https://jestjs.io/docs/configuration#globals-object) in the jest config (which is maybe a better option anyway)

**Comment by ahnpnl** [comment]
Oh ya I was playing around with this, which is related to this https://github.com/thymikee/jest-preset-angular/issues/354#issuecomment-2143821144
