### ISSUE TITLE
Angular 19 support

### ISSUE THREAD

**Issue by sheikalthaf** [thymikee/jest-preset-angular#2856]
### Please do not submit this issue.

- [X] I understand

**Comment by ahnpnl** [comment]
The work has been done and we will release soon :)

**Comment by MattiaMalandrone** [comment]
trying to update to angular 19 today, got this errors:

_ng update @angular/cli
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 19.0.1 to perform the update.
✔ Packages successfully installed.
Using package manager: npm
Collecting installed dependencies...
Found 100 dependencies.
Fetching dependency metadata from registry...
                  **Package "jest-preset-angular" has an incompatible peer dependency to "@angular-devkit/build-angular" (requires ">=15.0.0 <19.0.0", would install "19.0.1").**
                  Package "@angular-eslint/schematics" has an incompatible peer dependency to "@angular-devkit/schematics" (requires ">= 18.0.0 < 19.0.0", would install "19.0.1").
                  Package "typedoc" has an incompatible peer dependency to "typescript" (requires "4.6.x || 4.7.x || 4.8.x || 4.9.x || 5.0.x || 5.1.x || 5.2.x || 5.3.x || 5.4.x || 5.5.x", would install "5.6.3")._

the package json inside node_modules/jest-presets-angular got:

  "peerDependencies": {
    **"@angular-devkit/build-angular": ">=15.0.0 <19.0.0",**
    "@angular/compiler-cli": ">=15.0.0 <19.0.0",
    "@angular/core": ">=15.0.0 <19.0.0",
    "@angular/platform-browser-dynamic": ">=15.0.0 <19.0.0",
    "jest": "^29.0.0",
    "typescript": ">=4.8"
  },

instead the package json of this repo got:

"peerDependencies": {
    **"@angular-devkit/build-angular": ">=15.0.0 <20.0.0",**
    "@angular/compiler-cli": ">=15.0.0 <20.0.0",
    "@angular/core": ">=15.0.0 <20.0.0",
    "@angular/platform-browser-dynamic": ">=15.0.0 <20.0.0",
    "jest": "^29.0.0",
    "typescript": ">=4.8"
  },

it could be a concern?
Thanks!

**Comment by ahnpnl** [comment]
Hi @MattiaMalandrone, the support is under **14.4.0-rc.0** for now. We are waiting for stability moment to release.

**Comment by MattiaMalandrone** [comment]
> Hi @MattiaMalandrone, the support is under **14.4.0-rc.0** for now. We are waiting for stable moment to release.

thanks!
