### ISSUE TITLE
[Bug]: Performance regression in 14.2.0 and 14.2.1

### ISSUE THREAD

**Issue by mattlewis92** [thymikee/jest-preset-angular#2886]
### Version

14.4.1

### Steps to reproduce

As this is a performance issue, it's really difficult to reproduce this outside of our repo as you need a large amount of source files and tests to see the problem.

### Expected behavior

Performance does not change between versions

### Actual behavior

After upgrading from `14.1.1` to `14.4.1` we noticed a massive performance hit in our unit test times, where everything got more than twice as slow.

We managed to track down the source of the slow performance to these commits:
* https://github.com/thymikee/jest-preset-angular/commit/31e78b1 (this makes our tests take 2.5x times as long)
* https://github.com/thymikee/jest-preset-angular/commit/ad7a297 (after locally reverting the previous commit, this makes our tests take ~20% longer, presumably due to the overhead of creating multiple typescript programs instead of 1 as we were before)

Once we reverted both of these commits locally, our test times returned to what they were on the previous version.

As these commits were just refactors, would it be possible to just revert these 2 commits and restore the previous performance? The only test that fails when I did this locally, was [this one](https://github.com/thymikee/jest-preset-angular/blob/bd37f7f1893d6a2b33fab48b22caa7e76e728ccc/src/compiler/ng-jest-compiler.spec.ts#L328) but I don't think we need to access the type at runtime as we are using an injection token, so I think it's fine for that to be compiled to `undefined`.

### Additional context

We are using the `isolatedModules: true` flag in our jest config to disable type-checking

### Environment

```shell
System:
  OS: macOS 14.7
  CPU: (16) arm64 Apple M3 Max
Binaries:
  Node: 22.11.0 - ~/Library/pnpm/nodejs/22.11.0/bin/node
  Yarn: 1.22.22 - ~/Library/pnpm/yarn
  npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
  pnpm: 9.14.4 - ~/.nvm/versions/node/v20.15.0/bin/pnpm
npmPackages:
  jest: 29.7.0 => 29.7.0
```

**Comment by ahnpnl** [comment]
Thanks, indeed I could see the issue

**Comment by mattlewis92** [comment]
Thank you so much!! It's very much appreciated 😄
