### ISSUE TITLE
Refactor and improve preprocessor

### ISSUE THREAD

**Issue by thymikee** [thymikee/jest-preset-angular#29]
Currently our preprocessor is trying to bypass Angular limitations in terms of `templateUrl` and `styleUrls` with regular expressions. This is not a greatest solution. We need to use some AST transform to handle this properly.

What's more, currently, to enable html loading the whole html content is wrapped in template literal:
```js
src = 'module.exports=`' + src + '`;';'
```

Which treats a string like `price: ${{price}}` as a JS object, instead of variable.

**Comment by blackholegalaxy** [comment]
@thymikee Any news on that? Especially for animations, it's kind of bothering to have to more animations on top of `styleUrls`.

**Comment by thymikee** [comment]
AFAICT we cannot transform the AST with TypeScript. There is a possibility to use Babel, but it has its limitations transforming TS. I think the best solution for now is to just improve the regex, which I'm happy to accept a PR with :)

**Comment by blackholegalaxy** [comment]
Where exactly is this regex in the code?

**Comment by AhnpGit** [comment]
https://github.com/thymikee/jest-preset-angular/blob/master/preprocessor.js
It is here @blackholegalaxy

**Comment by blackholegalaxy** [comment]
I don't exactly get why placing animations before styleUrls "fixes" the encountered animation stack trace. Do you have any queue for us to be able to maybe find a fix?

**Comment by ahnpnl** [comment]
I think this can be closed ? Some works have been done by @wtho related to this recently.

**Comment by wtho** [comment]
Yes, basically we can close it.

Just one more question:
> to enable html loading the whole html content is wrapped in template literal
> Which treats a string like `price: ${{price}}` as a JS object, instead of variable

AFAIK `ts-jest` does the very same thing, how was this an issue? Should we add a test to cover this?

**Comment by wtho** [comment]
Ok, this is already tested:
https://github.com/thymikee/jest-preset-angular/blob/a692cc611fd10f26e45da79c5e656d24d0498655/example/src/app/app.component.html#L4
