### ISSUE TITLE
[Bug]: can't access lexical declaration 'zone_1' before initialization

### ISSUE THREAD

**Issue by BojanKogoj** [thymikee/jest-preset-angular#2901]
### Version

14.4.2

### Steps to reproduce

https://stackblitz.com/edit/stackblitz-starters-t9yu2zeb?file=setup-jest.ts
Run `npm i --legacy-peer-deps && npm run test`

### Expected behavior

Test to run

### Actual behavior

❯ npm run test

> test
> jest

 FAIL  src/example.component.spec.ts
  ● Test suite failed to run

    can't access lexical declaration 'zone_1' before initialization

      _execModule@file:///home/projects/stackblitz-starters-t9yu2zeb/node_modules/jest-runtime/build/index.js#cjs:1439:24
      _loadModule@file:///home/projects/stackblitz-starters-t9yu2zeb/node_modules/jest-runtime/build/index.js#cjs:1022:12
      requireModule@file:///home/projects/stackblitz-starters-t9yu2zeb/node_modules/jest-runtime/build/index.js#cjs:882:12
      jestAdapter@file:///home/projects/stackblitz-starters-t9yu2zeb/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js#cjs:70:15

### Environment

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    jest: ^29.7.0 => 29.7.0
```

**Comment by BojanKogoj** [comment]
I've tried pretty much the same configuration locally (not on StackBlitz) and it works well.

**Comment by ahnpnl** [comment]
I think probably the StackBlitz issue with dependencies installation?

**Comment by ahnpnl** [comment]
I checked your StackBlitz link and couldn't reproduce the issue

**Comment by BojanKogoj** [comment]
This seems to still be an issue, but only happens on Firefox.
