### ISSUE TITLE
Override preset configuration?

### ISSUE THREAD

**Issue by basickarl** [thymikee/jest-preset-angular#296]
How does one override fields in the configuration at https://github.com/thymikee/jest-preset-angular/blob/master/jest-preset.js ?

I don't have my `tsconfig.spec.json` file at `<rootDir>/src/tsconfig.spec.json`. I have it at `<rootDir>/tsconfig.test.json` instead. Hoe does fix this config?

**Comment by wtho** [comment]
See https://github.com/thymikee/jest-preset-angular#custom-tsconfig
