### ISSUE TITLE
JEST: Cannot find module 'source-map' from 'source-map-support.js' after npm test

### ISSUE THREAD

**Issue by anuragmca90** [thymikee/jest-preset-angular#298]
I am using jest with angular 8.1.0
after running the `npm test` :  I am getting the below error-

> > br-events-ui@0.0.0 test \br-events-ui> jest

 FAIL  /br-events-ui/src/test/index.test.js
  ● Test suite failed to run

    Cannot find module 'source-map' from 'source-map-support.js'

      at Resolver.resolveModule (/br-events-ui/node_modules/jest/node_modules/jest-resolve/build/index.js:221:17)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        13.605s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

**Comment by ahnpnl** [comment]
Please use jest 26 and jest-preset-angular latest. If you still experience the issue, please provide a repo to reproduce the problem.
