### ISSUE TITLE
Error loading html template

### ISSUE THREAD

**Issue by 4kochi** [thymikee/jest-preset-angular#3]
This preset is really cool. Now our tests run a lot faster. But we have a little issue.

We have an Angular2 project and additionally an Angular 2 component lib (my-ui-lib), which includes all the shared components. The components lib is installed as a node module and includes all the code in `.ts`

I have added the following setting in the jest configuration in the package.json:

```
"transformIgnorePatterns": [
  "node_modules/(?!my-ui-lib)"
]
```

Now all components in `my-ui-lib` will by transformed to js and the tests in the project compile and run with jest.

But in some tests I get the following error: 

```
Cannot find module 'ul-action-bar.component.html' from 'ul-action-bar.component.ts'

  at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:176:17)
  at Object.<anonymous> (node_modules/my-ui-lib/src/lib/components/container/ul-action-bar/ul-action-bar.component.ts:14:19)

```

ul-action-bar is a component with a template. Here the code:

```
import { Component } from '@angular/core';

@Component({
  selector: 'ul-action-bar',
  styleUrls: ['ul-action-bar.component.scss'],
  templateUrl: 'ul-action-bar.component.html'
})

export class UlActionBarComponent { }
```

So it seems like the `.html` file cannot be resolved. Do you have any idea what the problem might be?

**Comment by thymikee** [comment]
Does it work with relative import?
```js
templateUrl: './ul-action-bar.component.html'
```

**Comment by 4kochi** [comment]
That was a fast answer 🏎. It seems to work now. I will change this in all my components and than I can say it for sure. Thanks.

**Comment by thymikee** [comment]
Is setting absolute imports to html always resolved to adjacent html file? I think I could add a `moduleNameMapper` to handle that

**Comment by 4kochi** [comment]
It works in Angular 2.x and webpack. But I have not tested Angular 4.x yet. 

I just looked at the angular documentation and the code the angular-cli produces. It seems like it's best practice to use the relative path anyway. So I will change my components.

**Comment by thymikee** [comment]
CLI generates relative paths ([example](https://github.com/thymikee/jest-preset-angular/tree/master/example) directory is generated with CLI).

btw, awesome to hear it works for you and it's a change for better ❤️!

**Comment by PsychicCat** [comment]
I'm experiencing this issue but I am using relative imports. Anyone else?

**Comment by catull** [comment]
Me too.

**Comment by catull** [comment]
I also removed these files:

- src/karma.config.js
- src/test.ts

Removed these depedencies in `package.json`:

- jasmine-core
- jasmine-spec-reporter
- karma
- karma-chrome-launcher
- karma-coverage-istanbul-reporter
- karma-jasmine
- karma-jasmine-html-reporter

Deleted `node_modules/` entirely and `npm install`-ed again.

Running jest still gives me the error above.

Tried both `jest-preset-angular` 5.2.3 and 6.0.0, with the same outcome.

How can I fix this ?

**Comment by ahnpnl** [comment]
hi @catull Please check the folder example in the repository and follow the configuration there. It is an example app which was already configured to run with this preset.

**Comment by thymikee** [comment]
You overriden default transformer with ts-jest, that's why you can process HTML files. Please use default configuration where possible.

**Comment by catull** [comment]
Thanks, got it to work now.
