### ISSUE TITLE
Skip ts-jest compiling?

### ISSUE THREAD

**Issue by basickarl** [thymikee/jest-preset-angular#300]
Is there a way to skip this preset using ts-jest to compile the TypeScript?

**Comment by wtho** [comment]
This preset is basically just a collection of settings, that you can just put in your own `jest.config.js`.

Furthermore it applies ASTTransformers, that
* make `templateUrl` to inline `template` and
* `styleUrls` to inline `styles`

This has to happen, as Angular serves html files while testing on Karma over HTTP, as it anyway has a dev server open. Jest does not have a server, so all HTTP requests will throw.

You can skip the astTransformes, if you only use inline `template: ...` and `styles: [...]` in all your tested components in your project.

Furthermore this preset comes with some serializers which make the html and components for Jest's `matchSnapshot()` a bit nicer.

**Comment by wtho** [comment]
@basickarl was your question answered? I would like to close the issue if this is the case.

I think I misread it back then. Just a small clarification: This preset uses `ts-jest` internally to transpile. The preset itself does no transpiling, just minor adjustments to work with `templateUrl` as described above. If you use only inline `template` in Angular components. this preset (or the included ast transformer) will not be required at all.

**Comment by basickarl** [comment]
@wtho Hey man I think I got it figured out. I'll reopen if it's an issue down the line, thanks for the help!
