### ISSUE TITLE
Cannot find Asset Config

### ISSUE THREAD

**Issue by Godrules500** [thymikee/jest-preset-angular#302]
This is most likely an issue with my understanding, but I am trying to load an asset file via the below code. I am receiving a 404 file not found error. Thoughts?

Now I am able to load it via require("assets/config/config.json") in the spec, but I don't want to do that if I don't have to because then I'd have to change the config method to accept a parameter just for tests.

app.component.spec.ts
```
providers: [
        {
          provide: APP_INITIALIZER, // TODO: Abstract this out into app load module and load into a global APP_SETTTINGS
          multi: true,
          deps: [ConfigService],
          useFactory: (appConfigService: ConfigService) => () => appConfigService.loadAppConfig(myTestStuff) // loadAppConfig must return a promise
        }
      ]
```
Config file
```
return this.dataService.get('assets/config/config.json')
      .toPromise()
      .then(data => {
        this.appConfig = data;
      });
```

**Comment by ahnpnl** [comment]
would you please provide a minimum repo for your situation ?

**Comment by wtho** [comment]
Do you use `HttpClient` inside your `dataService`?

Jest is a fast, minimal unit-test framework, that does not spin up any server. If you try to use Angular's `HttpClient` to fetch some data, this will fail, as there is no server spun up.

To unit test the config service, you should mock the data service, by replacing it with a dummy implementation, or only mock the `get`-method, using `jest.fn()`, to returns the expected json. You usually want to only test the isolated Angular component to make sure it works as expected.

Please close this issue if this solved your problem.

**Comment by wtho** [comment]
Will close this for now, seems not to be an issue with `jest-preset-angular`, feel free to reopen or to ask on StackOverflow, if this issue persists.
