### ISSUE TITLE
TypeError: Cannot read property 'each' of undefined when upgrading to Jest 24.9.0

### ISSUE THREAD

**Issue by Timebutt** [thymikee/jest-preset-angular#305]
When upgrading our repository from Jest 23 to Jest 24, I am seeing this error message when running a test with `npx jest --watch *pattern*`:

```
Test suite failed to run

    TypeError: Cannot read property 'each' of undefined

      1 | import 'jest-preset-angular';
      2 | import './jestGlobalMocks';
    > 3 |
        | ^
      4 | import { BrowserAnimationsModule, NoopAnimationsModule } from '@angular/platform-browser/animations';
      5 | import { RouterModule, ROUTES } from '@angular/router';
      6 | import { RouterTestingModule } from '@angular/router/testing';

      at Object.<anonymous>.forEach.methodName (node_modules/jest-preset-angular/zone-patch/index.js:71:54)
          at Array.forEach (<anonymous>)
```

I am currently using `jest-preset-angular` version `7.1.1` but also tried `7.0.0`. My Angular packages are at `7.2.12`, `zone-js` is at `0.9.0`, `jest` at `24.9.0`. 

This is my `jest.config.js`:

```
module.exports = {
    preset: 'jest-preset-angular',
    setupFiles: ['<rootDir>/jest/setupJest.ts'],
    globals: {
        'ts-jest': {
            stringifyContentPathRegex: '\\.html?$',
            ignoreCoverageForAllDecorators: true,
            tsConfig: 'tsconfig.spec.json'
        }
    },
    collectCoverageFrom: [
        '{apps,libs}/**/src/**/*.ts',
        '!jest/*.ts',
        '!e2e/**/*.ts',
        '!{apps,libs}/**/src/**/index.ts',
        '!{apps,libs}/**/src/**/*.actions.ts',
        '!{apps,libs}/**/src/**/*.module.ts',
        '!{apps,libs}/**/src/**/*.builder.ts',
        '!{apps,libs}/**/src/**/*.config.ts',
        '!{apps,libs}/**/src/**/*.routes.ts',
        '!{apps,libs}/**/src/**/*.type.ts',
        '!{apps,libs}/**/src/**/*.interface.ts',
        '!{apps,libs}/**/src/**/*.constants.ts',
        '!apps/**/src/environments/*.ts',
        '!apps/**/src/main.ts',
        '!apps/**/src/polyfills.ts'
    ],
    coverageReporters: ['json', 'lcov', 'html'],
    coverageThreshold: {
        global: {
            statements: 95,
            branches: 80,
            functions: 90,
            lines: 95
        }
    },
    moduleNameMapper: {
        *MODULE_MAPPERS*
    },
    testPathIgnorePatterns: [
        '<rootDir>/e2e',
        '<rootDir>/dist',
        '<rootDir>/apps/(.*)/src/environments/environment.test.ts'
    ],
    transform: {
        '^.+\\.(ts|js|html)$': 'ts-jest'
    }
};
```

When I check the related line of code in `jest-preset-angular/zone-patch/index.js:71:54`, I see that `xdescribe`, `fdescribe` nor `describe` exist in the `env` at all, which is why `originaljestFn` is undefined and finally throws the error at `originaljestFn.each`.

Am I using incompatible packages?
Does anybody know why I am seeing this behaviour?

**Comment by wtho** [comment]
I know that there are several pitfalls configuring an Angular project with jest, and through the last years we did not really adjust the README properly to point them out directly at first sight.

Anyway, your problem is, that you use `setupFiles`, which is run before jest is setting up the environment, while you would want to apply the patches *after* jest is setup. So better use `setupFilesAfterEnv`.

Another pitfall will be that you do not have `astTransformers` configured. Please have a good look at our `README.md`. If you set `global.ts-jest`, you will override and discard all settings from the `global.ts-jest` in the preset. So make sure you copy the values you do not want to modify.

Please close this issue if this helped you.

Happy Coding!

**Comment by Timebutt** [comment]
Wow, that's both a very fast and accurate reply 🙌  I will immediately get to it and report back to see if that fixed it.

**Comment by wtho** [comment]
@Timebutt did this get solved?

**Comment by Timebutt** [comment]
Yes absolutely, sorry for not coming back to this.
