### ISSUE TITLE
Released version does not support TypeScript 2.8.4

### ISSUE THREAD

**Issue by carnegie-jwilliamson** [thymikee/jest-preset-angular#320]
We have an Ionic 3 project that is not supported by TypeScript v2.9 or newer. jest-preset-angular v7.1.1 does not work with older versions of TypeScript, so we can't use it right now, and we try to avoid using unreleased versions.

Can you release a new version that includes the fix for older TypeScript compilers (#261 )?

**Comment by ahnpnl** [comment]
Hi,

Actually your request is related to ts-jest dependency we have in this preset. 7.0.0+ uses ts-jest 23.10.x which is a breaking change. < 7.0.0 ts-jest doesn't support to use AST transformers. I don't think it's possible to fulfil your needs.

**Comment by carnegie-jwilliamson** [comment]
Maybe I've misdiagnosed the problem, but if I use jest-preset-angular=7.1.1, my tests fail to build with `TypeError: ts.createStringLiteral is not a function`. If I update jest-preset-angular to use the latest master then the tests build fine.

**Comment by wtho** [comment]
Yeah, this is already solved, but not published yet (#272).

If you don't mind I will close this issue, the new version will be published soon.

**Comment by carnegie-jwilliamson** [comment]
Thanks. Looking forward to the new version.
