### ISSUE TITLE
HTML import broken

### ISSUE THREAD

**Issue by aloifolia** [thymikee/jest-preset-angular#323]
The HTML file imports inside my Typescript files are broken:

<img width="491" alt="Screenshot 2019-10-11 at 17 54 10" src="https://user-images.githubusercontent.com/1295054/66666122-44f5a980-ec50-11e9-9a97-6f7ac712db90.png">

tsconfig.spec.json:
```json
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "resolveJsonModule": true,
        "target": "es5",
        "lib": ["es2018", "dom"],
        "outDir": "../out-tsc/spec",
        "module": "commonjs",
        "esModuleInterop": true
    },
    "include": ["**/*.spec.ts", "**/*.d.ts"]
}
```

jest.config.js:

```js
module.exports = {
    preset: 'jest-preset-angular',
    roots: ['app'],
    setupFilesAfterEnv: ['<rootDir>/src/setup-jest.ts'],
    moduleNameMapper: {
        '@app/(.*)': '<rootDir>/app/$1',
    },
    transformIgnorePatterns: ['node_modules/(?!(jest-test))'],
    transform: { // can be removed, seems to be useless
        '^.+\\.(ts|html)$': 'ts-jest',
        '^.+\\.(js)$': 'babel-jest',
    },
    testMatch: ['<rootDir>/app/**/*.spec.ts'],
};
```

I use the packages

```
        "jest": "24.9.0",
        "jest-preset-angular": "7.1.1",
```

Is this behaviour a bug or should I change the config files?

**Comment by wtho** [comment]
Can you share an overview of your project structure and the imports or references of the html?
Does it compile using Angular?

**Comment by aloifolia** [comment]
The project is a mixed AngularJs-Angular application. Thus, we have have a customized Webpack configuration. The html is imported like this:

```ts
import template from '../../components/content/shared/dialogs/global_spinner_dialog/global_spinner_dialog.tpl.html';
```

This compiles and works flawlessly in the browser.

**Comment by wtho** [comment]
I see. As Jest does not use webpack, additional non-standard adjustments have to be done for jest as well.

We wrote some ASTTransformers to let jest deal with these (especially some peculiarities of Angular), so you could write your own, that transforms imports to `require` for html files. This is not a trivial task though.

If you agree, I would suggest to close this issue, as it's probably not in the scope of this preset.
