### ISSUE TITLE
Remove jsdom v15 environment once jest v25 is out

### ISSUE THREAD

**Issue by wtho** [thymikee/jest-preset-angular#325]
Jest v25 does use JSDOM v15 [by default](https://github.com/facebook/jest/pull/8851), so we do not have to define this version in the preset anymore.

This issue is a reminder and can be solved by a simple PR once jest v25 is out.

**Comment by wtho** [comment]
There are also [plans for v25](https://github.com/facebook/jest/issues/5815) to set the default env to node.js instead of jsdom, so we might have to keep setting jsdom anyway, let's see!

**Comment by ahnpnl** [comment]
The plan to set default to jsdom is moved to v26, so we can just remove the dependency for now
