### ISSUE TITLE
 File not found: jest-preset-angular/InlineHtmlStripStylesTransformer.js

### ISSUE THREAD

**Issue by Niore** [thymikee/jest-preset-angular#332]
I got the following error running ng test:

File not found: jest-preset-angular/InlineHtmlStripStylesTransformer.js (resolved as: /home/dev/development/projects/test/jesttest/jest-preset-angular/InlineHtmlStripStylesTransformer.js)

      at ConfigSet.resolvePath (node_modules/ts-jest/dist/config/config-set.js:712:19)
      at node_modules/ts-jest/dist/config/config-set.js:225:98
          at Array.map (<anonymous>)
      at ConfigSet.get (node_modules/ts-jest/dist/config/config-set.js:225:64)
      at ConfigSet.tsJest (node_modules/ts-jest/dist/util/memoize.js:43:24)
      at ConfigSet.get (node_modules/ts-jest/dist/config/config-set.js:297:41)
      at ConfigSet.versions (node_modules/ts-jest/dist/util/memoize.js:43:24)
      at ConfigSet.get (node_modules/ts-jest/dist/config/config-set.js:583:32)
      at ConfigSet.jsonValue (node_modules/ts-jest/dist/util/memoize.js:43:24)
      at ConfigSet.get [as cacheKey] (node_modules/ts-jest/dist/config/config-set.js:598:25)

these are my configs:
- angular..json
 "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "configPath": "./tests/jest.config.js",
            "no-cache": true,
            "watch": true,
            "verbose": true
          },
          "configurations": {
          }
        },

- package.json
"devDependencies": {
    "@angular-builders/jest": "^8.2.0",
    "@angular-devkit/build-angular": "~0.803.14",
    "@angular/cli": "~8.3.14",
    "@angular/compiler-cli": "~8.2.11",
    "@angular/language-service": "~8.2.11",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "^24.0.20",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "^24.9.0",
    "jest-preset-angular": "^8.0.0",
    "protractor": "~5.4.0",
    "ts-jest": "^24.1.0",
    "ts-node": "^7.0.1",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }

- jest.config.js
'use strict';
const { pathsToModuleNameMapper } = require('ts-jest/utils');
const { compilerOptions } = require('../tsconfig');

module.exports = {
  preset: "jest-preset-angular",
  setupFilesAfterEnv: ['<rootDir>/tests/setupJest.ts'],
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, { prefix: '<rootDir>/' })
};

- setupJest.ts
import 'jest-preset-angular';
import './jestGlobalMocks';

What am i doing wrong? thx for your help

**Comment by kevinbeal** [comment]
> * You do not run your tests using `./node_modules/.bin/jest`
> * You do run your tests with `ng test`

That makes sense, however, using Wallaby.js requires *without* `./node_modules/.bin/jest` is not supported out of the box, and would require bending it in ways it was not meant to be bent, and requiring knowledge I do not yet possess.

Is there any way bending `jest-preset-angular` to run via `jest` might be easier than bending Wallaby.js to reproduce the internals of the `ng test` command?

**Comment by wtho** [comment]
@kevinbeal I think you got this wrong, the previous mistake was to **not** use `./node_modules/.bin/jest`, but `ng test`, which again disregards `jest.config.js`. 

If you can use `./node_modules/.bin/jest`, that's simpler and better for us to help. `jest-preset-angular` is a preset that focuses on being run directly via `jest`, as jest originally intends, while being able to work with an Angular codebase.

You can use `ng test`, but some additional magic is required, as provided by e. g. the package of `angular-builders` or `nx`.

I do not know enough about `wallaby.js` though to help you out further.

**Comment by kevinbeal** [comment]
You're right. I did misunderstand. Thanks for the clarification. :)

I'm using the Nx Workspace, so my case may be unusual. But I was actually able to solve my issue with modifications to `jest.config.js` alone. (I was confusing two separate scenarios when I said wallaby needed to be bent).

If it helps anyone, I was able to make it work using a modified version of the approach taken [here](https://wallabyjs.com/docs/integration/nrwl.html#how-to-run-wallaby-on-the-entire-monorepo).

My jest.config.js looks like this:

```javascript
module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  transform: {
    '^.+\\.(ts|js|html)$': 'ts-jest'
  },
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageReporters: ['html'],
  setupFilesAfterEnv: ['./wallaby-test-setup.ts'],
  globals: {
    'ts-jest': {
      tsConfig: './tsconfig.wallaby.json',
      diagnostics: { warnOnly: true },
      stringifyContentPathRegex: '\\.html$',
      astTransformers: [
        'jest-preset-angular/build/InlineFilesTransformer',
        'jest-preset-angular/build/StripStylesTransformer'
      ]
    }
  },
  testPathIgnorePatterns: ['/node_modules/', '/integration/'],
  transformIgnorePatterns: ['node_modules/(?!@ngrx)'],
  snapshotSerializers: [
    'jest-preset-angular/build/AngularNoNgAttributesSnapshotSerializer.js',
    'jest-preset-angular/build/AngularSnapshotSerializer.js',
    'jest-preset-angular/build/HTMLCommentSerializer.js'
  ]
};
```

I copied the `tsconfig.spec.json` and added it to the root directory as `tsconfig.wallaby.json` and did the equivalent for `test-setup.ts` as `wallaby-test-setup.ts`.

I haven't tested it extensively, but it seems to work.
