### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by Maxstgt** [thymikee/jest-preset-angular#335]
Hello guys,
I was setting up jest for my nrwl workspace and encountered some old paths in the docs.
In the docs there is something like
```
  snapshotSerializers: [
    'jest-preset-angular/build/AngularSnapshotSerializer.js',
    'jest-preset-angular/build/HTMLCommentSerializer.js',
  ],
```
But for me, there were no such files or build directory. I only could this.
``` astTransformers: [
        'jest-preset-angular/InlineHtmlStripStylesTransformer',
      ]
```
![Screenshot from 2019-11-29 10-23-14](https://user-images.githubusercontent.com/39312833/69858585-9f93a500-1292-11ea-82a8-4b06426a8aea.png)
Version is = `    "jest-preset-angular": "7.1.1"`

**Comment by wtho** [comment]
Note that the current master is on version 8, if you want to see the docs of version 7, please head to [npm](https://www.npmjs.com/package/jest-preset-angular/v/7.1.1).
