### ISSUE TITLE
Compatibility with Jest 25

### ISSUE THREAD

**Issue by kemsky** [thymikee/jest-preset-angular#344]
```
warning " > jest-preset-angular@8.0.0" has incorrect peer dependency "jest@^24.1.0".
warning "jest-preset-angular > ts-jest@24.0.2" has incorrect peer dependency "jest@>=24 <25".
```

**Comment by ahnpnl** [comment]
@wtho @thymikee shall we set `ts-jest` to `^25.0.0` ?

**Comment by thymikee** [comment]
Yes please

**Comment by PeterBenko** [comment]
When can we expect this to land in a release?

**Comment by ahnpnl** [comment]
I don’t see any blockers for this. @wtho @thymikee ?

**Comment by reid-harrison** [comment]
+1 Hoping for a release here!

**Comment by VilleSalonen** [comment]
@thymikee any updates on releasing this to npm?

**Comment by ahnpnl** [comment]
@VilleSalonen v8 is compatible with jest 25 :)

**Comment by wtho** [comment]
@VilleSalonen This was already released on March 10th

**Comment by VilleSalonen** [comment]
Sorry, my mistake. I just checked Releases tab on this Github project and for some reason it had collapsed the latest 4 releases.

Thanks for the quick replies!
