### ISSUE TITLE
Uncaught Error: Can't resolve all parameters for EventsListComponent: (?).     at syntaxError (compiler.js:2193)

### ISSUE THREAD

**Issue by susilpadhi** [thymikee/jest-preset-angular#349]
Uncaught Error: Can't resolve all parameters for EventsListComponent: (?).
    at syntaxError (compiler.js:2193)
==================================================
Component 
===========
import { Component, OnInit } from '@angular/core';
import { EventService } from './Shared/event.service';

@Component({
    selector: 'app-events-list',
    template: `
    <p>
     {{newcomponent}}
    </p>
    <p>
      Today's Date : {{todaydate}}
    </p>
    `
  })
  export class EventsListComponent implements OnInit {
    public todaydate;
    newcomponent = 'Entered in new component created';
    constructor(private myservice: EventService) {}
    ngOnInit() {
       this.todaydate = this.myservice.showTodayDate();
    }
  }
=======================
Service
=======================
import { Injectable } from '@angular/core';
@Injectable({
  providedIn: 'root'
})
export class EventService {
  constructor() { }
  showTodayDate() {
     const ndate = new Date();
     return ndate;
}
}

**Comment by ahnpnl** [comment]
duplicated #288

**Comment by wtho** [comment]
closed as a copy-paste duplicate of #348
