### ISSUE TITLE
Getting Validation Error: Module ./setupJest.ts in the setupFIlesAfterEnv option was not found.

### ISSUE THREAD

**Issue by imnickvaughn** [thymikee/jest-preset-angular#352]
#Getting Validation Error: Module ./setupJest.ts in the setupFIlesAfterEnv option was not found.

Hello and thank you for making this package!  I have successfully used your package to help configure Jest in an Angular application in the past.  I am now hoping to use it to configure Jest within an Angular Library and I am having some issues.  The current issue is illustrated below.
![image](https://user-images.githubusercontent.com/24948723/75571372-09088880-5a27-11ea-86eb-c8fa267b0cdd.png)
```
● Validation Error:

  Module ./setupJest.ts in the setupFilesAfterEnv option was not found.
         <rootDir> is: C:\Users\a638553\git\common2\frontend\ng-component-lib

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```
I have attached the component library I am attempting to use jest-preset-angular in order to configure Jest.
[ng-component-lib.zip](https://github.com/thymikee/jest-preset-angular/files/4268309/ng-component-lib.zip)

##What I have done so far:
So I was following [this tutorial](https://itnext.io/how-i-do-configure-jest-to-test-my-angular-8-project-2bd84a21d725) and [the documentation provided](https://github.com/thymikee/jest-preset-angular/blob/master/jest-preset.js).  Right before the current issue my issue looked simlar to [this issue](https://github.com/briebug/jest-schematic/issues/12) and there was [a schematic](https://github.com/briebug/jest-schematic) written in [this thread](https://github.com/thymikee/jest-preset-angular/issues/286) that I tried as well.  So now I feel like it is just a mosaic, and kind of a mess, of problems.  If you look at my project and agree, please use this project from a few commits earlier.
[ng-component-lib-earlier-commit.zip](https://github.com/thymikee/jest-preset-angular/files/4268345/ng-component-lib-earlier-commit.zip)
At that point the error was:
![image](https://user-images.githubusercontent.com/24948723/75572569-0a3ab500-5a29-11ea-96d0-e6e00216c468.png)
```
File not found: <rootDir>/tsconfig.spec.json (resolved as: C:\Users\a638553\git\common2\frontend\ng-component-lib\tsconfig.spec.json)

      at ConfigSet.resolvePath (node_modules/ts-jest/dist/config/config-set.js:712:19)
      at ConfigSet.get (node_modules/ts-jest/dist/config/config-set.js:202:67)
      at ConfigSet.tsJest (node_modules/ts-jest/dist/util/memoize.js:43:24)
      at ConfigSet.get (node_modules/ts-jest/dist/config/config-set.js:297:41)
      at ConfigSet.versions (node_modules/ts-jest/dist/util/memoize.js:43:24)
      at ConfigSet.get (node_modules/ts-jest/dist/config/config-set.js:583:32)
      at ConfigSet.jsonValue (node_modules/ts-jest/dist/util/memoize.js:43:24)
      at ConfigSet.get [as cacheKey] (node_modules/ts-jest/dist/config/config-set.js:598:25)
      at TsJestTransformer.getCacheKey (node_modules/ts-jest/dist/ts-jest-transformer.js:126:36)
      at ScriptTransformer._getCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:266:23)
```
Note: the difference in commands

##Call to action!

If anyone has any helpful suggestions I am all ears.

Please let me know if I can provide additional information that can help.

Thanks!

Nick

**Comment by mousedownmike** [comment]
Hi @imnickvaughn  Have you tried using the Jest Builder from here:
https://github.com/just-jeb/angular-builders/tree/master/packages/jest

I have successfully been using that with a multi-project workspace (i.e. library and app).  I won't claim to understand all of the details but it leverages `jest-preset-angular` and ties things in nicely with the ng cli.   I have been using it with a project that has 2 libraries and 2 apps, all in the same workspace.  I was running Angular 8 and now I'm running with Angular 9, without problems.

I opened your project but it appears the configurations are quite different between using the builder and using `jest-preset-angular` directly so I'm not able to provide any details for your specific problem.

**Comment by wtho** [comment]
Hey!

Please post your jest configuration and your `tsconfig.json` so we can understand your problem from the configuration side of angular.
If you look at the [Changelog](https://github.com/thymikee/jest-preset-angular/blob/master/CHANGELOG.md), you can see we moved the standard location for `tsconfig.spec.json` with v8, which seems to resonate with the error of your second screenshot.

As far as the first one, I would like to see your config, specifically the value set in 
`setupFilesAfterEnv`.

**Comment by imnickvaughn** [comment]
@wtho 
lib container  tsconfig
frontend\ng-component-lib\tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "geode-scheduler": [
        "geode-scheduler"
      ],
      "geode-scheduler/*": [
        "geode-scheduler/*"
      ],
      "@angular/*": [
        "./node_modules/@angular/*"
      ],
      "tslib": [
        "./node_modules/tslib"
      ],
      "geode-security-search": [
        "dist/geode-security-search"
      ],
      "geode-security-search/*": [
        "dist/geode-security-search/*"
      ],
      "geode-lib": [
        "dist/geode-lib"
      ],
      "geode-lib/*": [
        "dist/geode-lib/*"
      ]
    },
    "esModuleInterop": true
  }
}
```

lib container tsconfig.spec.json
frontend\ng-component-lib\src\tsconfig.spec.json
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "types": [
      "node"
    ]
  },
  "files": [
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

lib tsconfig.spec
frontend\ng-component-lib\projects\geode-lib\tsconfig.spec.json
```{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/spec",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "src/test.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

**Comment by wtho** [comment]
Ok, almost there, please, more importantly, let me see your jest config!

**Comment by imnickvaughn** [comment]
jest.base.config.js
frontend\ng-component-lib\jest.base.config.js
```
module.exports = {
    preset: 'jest-preset-angular',
    setupFilesAfterEnv: ['./jest.base.setup.ts'],
    modulePathIgnorePatterns: ['./dist']
};
```

jest.config.js
frontend\ng-component-lib\projects\geode-lib\jest.config.js
```
const baseConfig = require('../../jest.base.config');

module.exports = {
    ...baseConfig
};
```

**Comment by imnickvaughn** [comment]
Are you not looking at my .zip files because of viruses? Or did you just miss that part of my post?

**Comment by wtho** [comment]
It's just more convenient to post it. I mostly check the issues when I'm travelling while on my phone, and handling zips on the phone is just no fun to me.

-----

So when you run `npm test`, jest will look for a config, e. g. a file named `jest.config.js` or the `jest` part in `package.json`.

You do not have a `jest.config.js` in your root folder, so running jest from the root will load what you configured in `package.json`. There you set `setupFilesAfterEnv` to `./setupJest.ts`, but as the error message is telling you, there is no `setupJest.ts` in your root folder `ng-component-lib`.

I guess what you want to do there is to fix this to point at `./src/setupJest.ts` in `package.json` or to remove this configuration part.

-----

If you run `npm run test:lib`, where you pass a config value, jest will set the location of this config to its root dir, so it will be run in `projects/geode-lib/`. The `jest.base.config.js` is loaded properly, but the reference to `./jest.base.setup.ts` is not correct anymore, as it is located two folders up.

From here I cannot help you anymore, as there is no `jest.base.setup.ts` anywhere in your project.

Feel free to ask again if you are still stuck. Cheers!

**Comment by imnickvaughn** [comment]
Thanks for your help.  I think your explanation of how what's going on helped.  It allowed me to follow the angular-present tutorial and customize it to my needs.  After several frustrating days, it is working now :)
