### ISSUE TITLE
Angular: Jest without Zone (noNgZone).

### ISSUE THREAD

**Issue by x47188** [thymikee/jest-preset-angular#354]
Hey 🙌

I was wondering if there was any documented way to run Angular 9 + Jest without zone.js ( [setupJest.ts](https://github.com/thymikee/jest-preset-angular/blob/master/src/setupJest.ts#L5) heavily relies on Zone)?

**Comment by wtho** [comment]
Hey!

No, we just got into the first compatibility issues with Angular 9, so there's no work done on this field so far.
But you can try removing these imports in your project and report your findings!

**Comment by x47188** [comment]
Removing the zone imports will raise an `In this configuration Angular requires Zone.js` error at boot.

Some interesting findings:

- I'm not getting a `TestBedRender3` instance from `getTestBed()` (probably related to the fact that I'm not using ngcc-compiled Ivy bundles).

- Nothing is available inside current `TestBedViewEngine` or `TestBedRender3` implementations to easily disable Zone.js (that [`noNgZone`](https://github.com/angular/angular/blob/63c9c2d2be910edb3058272acbe96e68e0d67b87/packages/core/testing/src/r3_test_bed.ts#L338) flag could be a potential answer though).

- I tried toying with the injection container replacing NgZone value with a NoopNgZone etc... without success.

**Comment by ahnpnl** [comment]
I remember I tried this before, with Angular 8  or lower I also got some similar errors so I gave up about excluding zone. Angular looks like tightly coupled with zone

**Comment by wtho** [comment]
@x47188 but if I interpret the issue right, you do have an app that runs without zone.js and you want to achieve the same in jsdom for jest, is that the case?
Then I think we should look into it.

**Comment by x47188** [comment]
@wtho Absolutely.

**Comment by wtho** [comment]
Do your zoneless tests run in Karma?

**Comment by x47188** [comment]
@wtho good question, I'll create a "repro" to verify that.

**Comment by wtho** [comment]
Thanks, if you could also share it, that would be awesome!

**Comment by ahnpnl** [comment]
I think this depends on the development from Angular to work without zone, which is currently in roadmap https://angular.io/guide/roadmap#leverage-full-framework-capabilities-with-zonejs-opt-out

**Comment by igorzablotny** [comment]
@ahnpnl  Hi, since angular 18 features experimental zoneless support, is that planned for the near future? Right now in the application without zone, importing preset with `import 'jest-preset-angular/setup-jest';` throws an error, since zone is not loaded in zoneless application. 

```
Cannot find module 'zone.js' from 'node_modules/jest-preset-angular/setup-jest.js'
```

**Comment by ahnpnl** [comment]
Hi, yes I think if we can rely on a flag from angular package to detect when zone is available to import, it should be easy to implement into the existing setup file.

If there is no such flag, i think we might need a separate setup file for testing zoneless application. 

PR is welcome :)

**Comment by meierw** [comment]
This currently is a blocker for us to start using Zoneless apps in Angular 18. Would love to see a fix :bow:

**Comment by ahnpnl** [comment]
You can simply copy the content of `setup-file.js` and remove zone import.

**Comment by meierw** [comment]
Ok it was a bit of an ordeal that I had to go through. Cause I was using `@angular-builders/jest`.

Even though I understood from the docs that `@angular-builders/jest` merges it's config with the user config. I still couldn't get all the correct config values to work and overwrite the base config that `@angular-builders/jest` had under the hood.

In the end I completely ripped out `@angular-builders/jest` in favor of just using `jest` directly.

Now my jest config looks like this and works with `provideExperimentalZonelessChangeDetection()` everywhere. In my app config as well as in my `TestBed` `providers`.

```json
// package.json
{  
  "jest": {
    "preset": "jest-preset-angular",
    "setupFilesAfterEnv": [
      "<rootDir>/jest.setup.ts"
    ]
  }
}
```

```ts
// jest.setup.ts
import { getTestBed } from "@angular/core/testing"
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting,
} from "@angular/platform-browser-dynamic/testing"

const testEnvironmentOptions =
  (globalThis as any).ngJest?.testEnvironmentOptions ?? Object.create(null)

const testBed = getTestBed()
testBed.initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
  testEnvironmentOptions,
)
```

Thanks. @ahnpnl for the hint of just copying the setup code.

**Comment by ahnpnl** [comment]
Besides, I asked Angular team and they also suggested to include this https://github.com/angular/components/blob/04d3b63de2fb843beb55836e39e930c3342d26f1/test/angular-test-init-spec.ts#L35
