### ISSUE TITLE
zone.js error while using routing

### ISSUE THREAD

**Issue by vlaude** [thymikee/jest-preset-angular#364]
Hi !

I'm still getting this error when I import _RoutingTestingModule_ with _TestBed_ (even in another way like mocking _Router_) in my tests.

```sh
console.warn node_modules/@angular/core/bundles/core.umd.js:26906
    Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?

  console.error node_modules/zone.js/dist/zone.js:699
    Unhandled Promise rejection: Cannot match any routes. URL Segment: 'meeting' ; Zone: ProxyZone ; Task: Promise.then ; Value: Error: Cannot match any routes. URL Segment: 'meeting'
        at ApplyRedirects.noMatchError (/Users/vlaude/workspace/campus/packages/router/src/apply_redirects.ts:112:12)
        at CatchSubscriber.selector (/Users/vlaude/workspace/campus/packages/router/src/apply_redirects.ts:89:20) Error: Cannot match any routes. URL Segment: 'meeting'
        at ApplyRedirects.noMatchError (/Users/vlaude/workspace/campus/packages/router/src/apply_redirects.ts:112:12)
        at CatchSubscriber.selector (/Users/vlaude/workspace/campus/packages/router/src/apply_redirects.ts:89:20)
```

All my tests pass anyway, but my console is fullfill with red... (despite ```Error.stackTraceLimit = 2;``` in my **jestSetup.js**)

I thought _jest-zone-patch_ was fixing this, did I forget something ?
Is this related to Angular9 and Ivy ?

I'm using _jest-preset-angular@8.1.2_ and _jsdom-sixteen_ and all my config is following the blog mentionned in the README.

**Comment by ahnpnl** [comment]
hi, this is unrelated to Angular 9 and Ivy. This is purely about how to write test with routing. For example I have a test like this 
```
router.navigate([ '' ]).then(() => {
        expect(messagingService.setDrillbackMessage).toHaveBeenCalledWith({
          ViewId: 'MessageList',
          Type: 'ALERT',
          ID: undefined,
        });
      }).catch(() => {
      });
```

**Comment by vlaude** [comment]
Alright, thought it was a known error and that I was missing something.
I find a workaround using https://www.npmjs.com/package/jest-createspyobj

example:
```let routerSpy = createSpyObj(Router, ['navigate']);```

Thx !
