### ISSUE TITLE
Support Jest 26

### ISSUE THREAD

**Issue by ahnpnl** [thymikee/jest-preset-angular#367]
## 🚀 Feature Proposal

Jest 26 has released. We want to add support for Jest 26 once ts-jest releases a compatible version.

## Motivation

Make developers feel comfortable to work

## TODO

- Upgrade ts-jest and pretty-format dependencies to ^26.0.0

- Set jest peerDependency to ^26.0.0

- Upgrade jest to 26.0.0 and typescript to 3.8.3

- Upgrade dependencies for example project.

- Update README regarding to jest-environment-jsdom 16 which is default in jest 26

Since jest 26 requires TypeScript 3.8.3, default jsdom 16 this support should be in a major version.

**Comment by leon** [comment]
Yeey ts-jest 26 is out :)
https://github.com/kulshekhar/ts-jest/releases/tag/v26.0.0
