### ISSUE TITLE
Test unable to find elements but they are present [Angular Material + JSDOM]

### ISSUE THREAD

**Issue by Princezhm** [thymikee/jest-preset-angular#368]
I have an angular app and I changed from `karma` to `jest`, because karma was giving me a lot of headaches, also I need the snapshot test, so I have a test like this:

```
  it('should have show and have a list of 2 elements', async () => {
    spyOn(notificationService, 'getNotifications').and.returnValue(notificationData);
    fixture.detectChanges();
    expect(fixture).toMatchSnapshot();
    // TODO: fix this test. there is something wrong that we can not find the `.url-link`
    const fakeUrl = fixture.debugElement.query(By.css('.url-link'));
    
    expect(fakeUrl).toBeTruthy(); // this fails.
```

but if we see the `napshot` that it takes from the fixture, we can see this:

```
// Jest Snapshot v1

exports[`NotificationsComponent should have show and have a list of 2 elements 1`] = `
<app-notifications
  current="0"
  display={[Function Notification]}
  lastLevel={[Function String]}
  list={[Function Array]}
  navigationService={[Function NavigationService]}
  notificationService={[Function NotificationsService]}
>
  <mat-toolbar class="pl-md-5 mat-toolbar info show mat-toolbar-single-row">
    <span tabindex="0">
      <span class="url-link">
        Click here                <---- here is the wanted item
      </span>
       to get verified
    </span>
  </mat-toolbar>
</app-notifications>
`;

```

but my test always fail with:

```
NotificationsComponent › should have show and have a list of 2 elements

    expect(received).toBeTruthy()

    Received: null
    > 45 |     expect(fakeUrl).toBeTruthy();
```

does anyone know why this happens? in my component I have this:

```
<mat-toolbar class="pl-md-5" [ngClass]="notificationClass">
  <span [routerLink]="display?.link?.url" [innerHTML]="getMessage()"></span>
</mat-toolbar>

```

where `getMessage` sometimes return a `string` or sometimes it returns an `span` with a link (like the snapshot)

update: if I do:
```
fixture.debugElement.query(By.css('mat-toolbar'));
```
it works but doing:
```
fixture.debugElement.query(By.css('mat-toolbar span'));
fixture.debugElement.query(By.css('mat-toolbar .url-link'));
fixture.debugElement.query(By.css('span'));
```
it doesn't

**Comment by wtho** [comment]
Hey!
This seems like a novel problem with `[innerHTML]` and `.query`.

I tried to make a quick test in the example project of this repository to reproduce your issue, but I fail to do so. My `query` returns the `span` element.

Here the reproduction:
https://github.com/wtho/jest-preset-angular/blob/fix/query-inner-html/example/src/app/app.component.ts#L15-L17

It would be of great help if you can fork my reproduction and make it fail there as well (note it is on branch `fix/query-inner-html`).
To set it up:
* run yarn install in the repository root
* then run yarn install in the example folder
To run the tests in the example project, better use `yarn test --no-cache` from inside the example folder.

-----
I want to solve this, but I like to mention that `[innerHTML]` should not be used in Angular whenever it can be avoided. Better use `*ngSwitch` or `ng-template` if all cases of interpolated html are known.

Cheers!

**Comment by ahnpnl** [comment]
I think it is most likely related to how angular material renders in jsdom. It is kind of different from a normal html element like our example with `div` and `innerHTML`.

I also face the same issue with the project at work.

**Comment by ahnpnl** [comment]
hi @Princezhm , would you please provide us a reproduce repo for your issue ?

**Comment by ahnpnl** [comment]
Close as inactivity
