### ISSUE TITLE
override/add to moduleNameWrapper doesn't work

### ISSUE THREAD

**Issue by pmestrum** [thymikee/jest-preset-angular#37]
I tried to override/add a mapper to the moduleNameWrapper but new mappers are not used/tested since the default mapper **(.*)** that is defined in jest-preset.json always has a successful test so that mapper is always used, and other mappers are not taken into consideration.

In the doc, it's suggested to remap (.*) to a falsy path so that other mappers are actually tested, but this has no effect.  Only removing the moduleNameWrapper from test-preset.json in the node_module itself has an effect, which is obviously not what we want to do.

Used version:
jest 20.0.3
ts-jest 20.0.3
@types/jest 19.2.3
jest-preset-angular 2.0.2

**Comment by thymikee** [comment]
@pmestrum it's not a falsy path, it's a 1:1 mapping. 
Is this failing for you?
```json
{
  "moduleNameMapper": {
    "(.*)": "$1",
    "testing/(.*)": "<rootDir>/app/testing/$1"
  }
}
```

**Comment by pmestrum** [comment]
You’re right, I stated it wrong.  The path indeed succeeds, and that’s the problem since the other mappers are not tested.  So I never come to the second mapper “testing(.*)”.  I debugged jest-resolve/index.js:315 (somewhere over there).  You’ll see that it stops looking for other mappers once a mapper is found that passed the test.  And since your 1:1 mapper is the first, it stops there.

Jest-resolve 20.0.3



Best regards - Vriendelijke groeten - Meilleures salutations
Paul Mestrum
[id:image001.jpg@01D28841.8FBB1520]<http://www.delawareconsulting.com/>

M   +32 474 63 71 84 E    paul.mestrum@delawareconsulting.com<mailto:paul.mestrum@delawareconsulting.com>

Blog <http://blog.delawareconsulting.com/> • Twitter <https://twitter.com/_DelawareC> • LinkedIn <https://www.linkedin.com/company/delaware-consulting> • Facebook<https://www.facebook.com/Delawarec>

**Comment by thymikee** [comment]
Oh, so it's similar to what happens here: https://github.com/facebook/jest/issues/3565
I'll need to investigate further on how we can make it better.

**Comment by pmestrum** [comment]
Yes, that seems to better describe exactly what I’m experiencing.  Thanks for being so responsive ;-)

Looking forward for a new version.  Keep up the good work !



Best regards - Vriendelijke groeten - Meilleures salutations
Paul Mestrum
[id:image001.jpg@01D28841.8FBB1520]<http://www.delawareconsulting.com/>

M   +32 474 63 71 84 E    paul.mestrum@delawareconsulting.com<mailto:paul.mestrum@delawareconsulting.com>

Blog <http://blog.delawareconsulting.com/> • Twitter <https://twitter.com/_DelawareC> • LinkedIn <https://www.linkedin.com/company/delaware-consulting> • Facebook<https://www.facebook.com/Delawarec>

**Comment by pmestrum** [comment]
Hi,

It’s obvious a bug in jest itself.  So I assume I have to wait for a bugfix from their side.

Thanks anyway,
Paul



Best regards - Vriendelijke groeten - Meilleures salutations
Paul Mestrum
[id:image001.jpg@01D28841.8FBB1520]<http://www.delawareconsulting.com/>

M   +32 474 63 71 84 E    paul.mestrum@delawareconsulting.com<mailto:paul.mestrum@delawareconsulting.com>

Blog <http://blog.delawareconsulting.com/> • Twitter <https://twitter.com/_DelawareC> • LinkedIn <https://www.linkedin.com/company/delaware-consulting> • Facebook<https://www.facebook.com/Delawarec>

**Comment by Lonli-Lokli** [comment]
I It possible to load modules from tsconfig?

I have module inside src and use path property from compilerOptions (https://www.typescriptlang.org/docs/handbook/compiler-options.html), create kind of synonym. 
Why this mapper cann use tsconfig for module resolving?

**Comment by thymikee** [comment]
@Lonli-Lokli you'll need to provide the mapping by hand, or maybe write your own helper to do so. Jest (and this preset) doesn't support this kind of things out-of-the-box, but who knows, there may be something out there in the wild.

**Comment by markwhitfeld** [comment]
Submitted a pull request (facebook/jest#3689) to Jest to fix issue facebook/jest#3565 which should resolve this issue when the fix is published. 

> Adjusted the order so that the options mappings are checked first and then the preset mappings are checked.
The preset mappings can be overridden by the options mappings

**Comment by thymikee** [comment]
Awesome, thanks!

**Comment by markwhitfeld** [comment]
@thymikee Are you a jest contributor? Are you able to merge the pull request? It doesn't seem like the pull requests get looked at that often.

**Comment by thymikee** [comment]
I don't have privileges to merge PRs in Jest repo. I can review and stamp it and I'll try to look at it today, but that's all. Just be patient, it will get reviewed sooner or later and if we have luck, released as a patch or minor version – but I can't guarantee anything in this matter.

**Comment by thymikee** [comment]
I've posted my point of view on this. But I totally understand that this PR may not get merged. In this case I'll resign from loose `(.*)` mapping and fall back to some popular ones.

**Comment by pmestrum** [comment]
@markwhitfeld 
Didn't you make a mistake in your fix?  It seems like you did copy/paste instead of cut/paste

    options.moduleNameMapper = Object.assign(
      {},
      options.moduleNameMapper,
      preset.moduleNameMapper,
      options.moduleNameMapper,
    );

**Comment by markwhitfeld** [comment]
Hi @pmestrum 
Nope. This is very deliberate. Try the cut/paste instead of the copy/paste and you will see the tests fail 😉 
The first assign from the options lets the options determine the order of the mappers.
The second assign from the presets writes the preset values into the config, overwriting any option values that exist, and adding new values after the last option value.
The third assign fixes the overwritten option values by writing the option values to the object again.
(See the tests for clarification on the scenario that this fixes)

For example:
```javascript
const preset = { p1: '1', p2:'2', p3:'3' };
const options = { o1:'a', p2:'b', o2:'c', p1:'d', o3:'e', o4:'f' }
const expectedResult = { o1:'a', p3:'b', o2:'c', p1:'d', o3:'e', o4:'f', p2:'2' }
```
This allows your preset to provide values that you have not specified in your options, and for your options to have all the power in terms of mapper priority and overriding preset values and order.
Hope this makes sense 😃
