### ISSUE TITLE
Does jest-preset-angular support fakeAsync with rxJS?

### ISSUE THREAD

**Issue by anno1985** [thymikee/jest-preset-angular#377]
In the readme, you have a [guide](https://github.com/thymikee/jest-preset-angular#observable--is-not-a-function) for projects using Angular <= version 5 on what to do to make rxjs work with jest-preset-angular.

For Angular >= version 6, will `fakeAsync(testFn)` work with jest out of the box using your project, or are set-up steps such as those [described in the Angular docs for Jasmine](https://angular.io/guide/testing#using-the-rxjs-scheduler-inside-fakeasync) (i.e. importing `zone.js/dist/zone-patch-rxjs-fake-async`) necessary?

Maybe this could be added to an FAQ somewhere? (You don't seem to have a wiki associated with this repo; the link immediately takes me back to the project's start page.)

On an unrelated note, when opening a new ticket, one's attention is drawn to issue templates that are supposed to be in the repo - but I didn't see any. Can you please provide a link for future reference? :)

**Comment by ahnpnl** [comment]
hi, issue template is in #375 :)

**Comment by wtho** [comment]
@anno1985 is your question answered? If so, please close the issue.

Cheers!
