### ISSUE TITLE
inline template: caused by: No value accessor for form control with unspecified name attribute

### ISSUE THREAD

**Issue by geocine** [thymikee/jest-preset-angular#38]
Any idea with this error? My test works in mocha.

**Comment by thymikee** [comment]
Hard to tell without a repro. Can you provide one? Otherwise I can't really help much.

**Comment by geocine** [comment]
Sorry for no details at all , this is a confidential project so it is unlikely that I could post an exact repro. Anyway I was just hoping that you encounter the same error and what would have caused it on your setup. Since this is not really an issue but a question, I will politely close it.

**Comment by thymikee** [comment]
BTW, have you tried to google the issue? https://stackoverflow.com/questions/38958347/angular2-rc-5-custom-input-no-value-accessor-for-form-control-with-unspecified

**Comment by geocine** [comment]
@thymikee  I know have value accessor works I have correctly implemented on my controls, my existing test suites are actually working just wanted to try jest. 👍 , Thanks

**Comment by davidyaha** [comment]
@geocine 
I had this issue while moving existing test suite to jest as well.
For me it was solved after adding `DefaultValueAccessor` to the declarations part of the test module in my custom input test.

```typescript
beforeEach(() => {
  TestBed.configureTestingModule({
    providers: [MdIconRegistry],
    declarations: [CustomInputComponent, MdIcon, NgModel, DefaultValueAccessor],
  }).compileComponents();
});
```
