### ISSUE TITLE
Compatibility for projects importing Ivy-compiled Angular libraries

### ISSUE THREAD

**Issue by mistic100** [thymikee/jest-preset-angular#389]
## 🚀 Feature Proposal

When a library in node_modules is compiled for Ivy instead of View Engine, the tests of the application throws errors like :
> Cannot find module './modal.component.html' from 'my-common.umd.js'

This is because the AST transformer tries to replace `templateUrl` by `template` even though it is uncessary (the output of Ivy compiler already contains the template function).

I was able to bypass the transformer by adding the following condition near the end of InlineFilesTransformer
```js
if (sf.fileName.indexOf('@sglk/') !== -1) {
  return sf;
}
```
but I have no idea how to get this behaviour without modifying the module file. There is no `astTransformersIgnore` or related in ts-jest as far as I can tell.

## Motivation

My company have multiple common librairies, those are build and published with `enableIvy: true` in order to speed up the CI jobs (it removes the necessity to build for View Engine then rebuild for Ivy when an application is deployed).

I don't know how things will be in the future when Ivy will be enabled by default everywhere, but for having skimmed the angular and ng-packagr repositories the last two weeks I know for sure I am not the only one to publish Ivy libraries to Nexus or other private repositories.

**Comment by ahnpnl** [comment]
FYI: you can opt-in/out any ast transformers provided by jest-preset-angular by specifying the ones you need in ts-jest astTransformers property.

Definitely full ivy compatibility should be taken into account for jest-present-angular 👍

**Comment by mistic100** [comment]
@ahnpnl You are correct, however completely opt-out to the transformer is not suitable either, other libraries and the app itself still need to be transformed.

That's why I tried to extend the transformer to ignore my packages only but I was not able to register it because of angular-builder/jest options merging policy (see linked issue).
My next step is to drop angular-builder/jest to directly run jest with jest-preset-angular.

**Comment by wtho** [comment]
I think it should be easy to spot ivy-compiled libs at runtime.
Can you reference some ivy-compiled library, preferably from npm? Would help a ton!

**Comment by mistic100** [comment]
@wtho I don't think you will find any because it is against the current guideline ti publish Ivy libs to NPM, and it is bloked by a "prepublish" script, unless using `npm publish --ignore-scripts` like I did to publish on our Nexus.

In theory you use any library using templateUrl (unfortunately I cannot think of any right now), compile it with `enableIvy: true` and use it in your app.

Here bellow an extract of the UMD bundle as it appears in node_modules, reduced to a single component

```ts
    var _c0$4 = [[["sglk-icon"], ["", "title-icon", ""]], "*"];
    var _c1$3 = ["sglk-icon,[title-icon]", "*"];
    var SglkTitleComponent = /** @class */ (function (_super) {
        __extends(SglkTitleComponent, _super);
        function SglkTitleComponent() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        SglkTitleComponent.prototype.getClassList = function () {
            return {
                'sglk-title': true,
            };
        };
        SglkTitleComponent.ɵfac = function SglkTitleComponent_Factory(t) { return ɵSglkTitleComponent_BaseFactory(t || SglkTitleComponent); };
        SglkTitleComponent.ɵcmp = core.ɵɵdefineComponent({ type: SglkTitleComponent, selectors: [["sglk-title"]], features: [core.ɵɵInheritDefinitionFeature], ngContentSelectors: _c1$3, decls: 5, vars: 0, consts: [["sglkLayout", "horizontal; gap; align:center"], ["sglkLayoutItem", "fixed", 1, "sglk-title__icon"], ["sglkLayoutItem", "", 1, "sglk-title__content"]], template: function SglkTitleComponent_Template(rf, ctx) { if (rf & 1) {
                core.ɵɵprojectionDef(_c0$4);
                core.ɵɵelementStart(0, "div", 0);
                core.ɵɵelementStart(1, "span", 1);
                core.ɵɵprojection(2);
                core.ɵɵelementEnd();
                core.ɵɵelementStart(3, "h4", 2);
                core.ɵɵprojection(4, 1);
                core.ɵɵelementEnd();
                core.ɵɵelementEnd();
            } }, directives: [SglkLayoutDirective, SglkLayoutItemDirective], styles: ["@charset \"UTF-8\";.sglk-title{display:block;margin:10px 0}.sglk-title__content{margin:0;width:100%;border-bottom:1px solid currentColor}.sglk-app--INGENIERIE .sglk-title__content{color:#41b285;border-color:#41b285}.sglk-app--CONSTRUCTION .sglk-title__content{color:#718ec6;border-color:#718ec6}.sglk-app--PATRIMOINE .sglk-title__content{color:#ed6d4c;border-color:#ed6d4c}.sglk-app--SOGELINK .sglk-title__content{color:#0062ad}.sglk-app--INTERNE .sglk-title__content{color:#4f4d48}.sglk-app--INTERNE .sglk-title__content,.sglk-app--SOGELINK .sglk-title__content{border-color:#fdc300}.sglk-title__icon sglk-icon{width:21px;height:21px}.sglk-app--INGENIERIE .sglk-title__icon{color:#41b285}.sglk-app--CONSTRUCTION .sglk-title__icon{color:#718ec6}.sglk-app--PATRIMOINE .sglk-title__icon{color:#ed6d4c}.sglk-app--INTERNE .sglk-title__icon,.sglk-app--SOGELINK .sglk-title__icon{color:#fdc300}.sglk-title__icon:empty{display:none}"], encapsulation: 2 });
        return SglkTitleComponent;
    }(AbstractComponentWithClasses));
    var ɵSglkTitleComponent_BaseFactory = core.ɵɵgetInheritedFactory(SglkTitleComponent);
    /*@__PURE__*/ (function () { core.ɵsetClassMetadata(SglkTitleComponent, [{
            type: core.Component,
            args: [{
                    selector: 'sglk-title',
                    templateUrl: './title.component.html',
                    styleUrls: ['./title.component.scss'],
                    encapsulation: core.ViewEncapsulation.None,
                }]
        }], null, null); })();
```
You can see the `template` and `styles` properties already exist additionally to `templateUrl` and `stylesUrl`, but it's not in the same object at all, might be difficult to handle this in the AST visitor.
There is the `ɵsetClassMetadata` call which might help (Ignore anything inside that call ?)

**Comment by mistic100** [comment]
So by calling directly jest without angular-builders/jest I was able to register my own transformer.
However completely removing the transformer for my librairies is not enough : "something" is trying to load the templateUrl and stylesUrl at runtime and obviously fails.

> Failed: "Failed to load icon.component.scss" 

thrown during `TestBed.compileComponents`

**Comment by ahnpnl** [comment]
> So by calling directly jest without angular-builders/jest I was able to register my own transformer.
> However completely removing the transformer for my librairies is not enough : "something" is trying to load the templateUrl and stylesUrl at runtime and obviously fails.
> 
> > Failed: "Failed to load icon.component.scss"
> 
> thrown during `TestBed.compileComponents`

Do you use https://github.com/thymikee/jest-preset-angular/blob/master/src/StripStylesTransformer.ts ?

**Comment by mistic100** [comment]
Yes. But StripStylesTransformer only removes `styles`, not `stylesUrl`

**Comment by ahnpnl** [comment]
ohh so that is a bug there, we can include `styleUrl` into it

**Comment by mistic100** [comment]
By using another custom transformer to also remove `styleUrls` I was able to past this error, but now :
> No template specified for component SglkIconComponent

The tests seems to run with the View Engine JIT compiler.

**Comment by ahnpnl** [comment]
I think you don't use https://github.com/thymikee/jest-preset-angular/blob/master/src/InlineFilesTransformer.ts but use your own version ?

**Comment by mistic100** [comment]
It's a really dumb overload done to avoid the first error 
> Cannot find module './modal.component.html' from 'my-common.umd.js'

```js
const baseFactory = require('jest-preset-angular/build/InlineFilesTransformer').factory;

exports.factory = (cs) => {
    const baseTransformer = baseFactory(cs);

    return (ctx) => {
        const baseVisitor = baseTransformer(ctx);

        return (sf) => {
            if (sf.fileName.indexOf('@sglk/') !== -1) {
                return sf;
            }
            return baseVisitor(sf);
        };
    };
};
```

**Comment by mistic100** [comment]
I pause my investigations for now, other subjects require my attention.  
Perhaps I'll consider publishing the libs for View Engine and respect the current Angular guidelines, bummer for the CI performances.

**Comment by ahnpnl** [comment]
i think it's wise to publish VE library until Angular team says it's ok to publish Ivy library. That will give some times for the eco to adapt :)

**Comment by mistic100** [comment]
On second (or third, I stopped counting) thought I cannot do that. All our libraries are part of single mono-repo which also have an application which serves as test application and documentation.
Because of current flaws of Ivy https://github.com/angular/angular/issues/33395, https://github.com/angular/angular/issues/36386 and others, I cannot use VE in this mono-repo or it is trashed after the first run of ngcc accross the librairies.

Considering many inexperienced people work on this librairies, with no over-the-top computers, I cannot ask everyone to clean everything after running tests or similar tasks (we are talking of ~15 minutes of compile time when done from scratch).

I only choosed to convert everything to full-Ivy after trying every other solutions I found to make our ecosystem work as much as easily as possible. Too late to revert back.
And unfortunately unit tests support was the last item of a long checklist to allow my company to migrate to Angular 9.

**Comment by wtho** [comment]
It is no rocket science to extend the ASTTransformer to differentiate between components that have the `template` set and others that don't.

What confuses me more is that in your setup the compiled component seems to be processed by the InlineTemplateTransformer, although it is only supposed to process `.ts` files with `@Component` decorators :confused:
In the UMD bundle there is no TypeScript or decorator provided, so it should not be transformed.

**Comment by mistic100** [comment]
I don't know much about AST transformers but for what I understand about InlineFilesTransformer, there is no strict filter on .ts files nor on @Component decorators.
And since all .ts and .js files are processed by ts-jest it is no surprise the transformer is applied on UMD bundles as well.

**Comment by wtho** [comment]
Yeah, a demo repo would help a ton!
Thank you!

**Comment by johncrim** [comment]
I'm also very interested in using Jest + Ivy together - mainly to benefit from perf improvements during development, including not having to recompile components between every test.

Do you have any guidance or simple examples demonstrating getting that working? I tried removing `    "emitDecoratorMetadata": true, ` and enabling ivy in my tsconfig.spec.json and ran into a bunch of errors, and deduced by browsing github issues that it's because jest-preset-angular is using the ViewEngine version of the compiler. My next hope is that tests will rebuild and run faster after changing to the Ivy compiler, and we should also see better compile checks in tests.

Anything I can do to help?

**Comment by ahnpnl** [comment]
I think the main issue is because `jest-preset-angular` doesn't have some logics which are internally done by Angular team. @wtho is it right ?

**Comment by wtho** [comment]
Yes, but with #406 we start to catch up.

We need any help to analyze the [AngularCompilerPlugin](https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/angular_compiler_plugin.ts) as well as functionality in `@angular/compiler-cli` to understand which transformers are required to make ivy tests work.

**Comment by wtho** [comment]
I updated the title to emphasize on the import of the ivy-compiled library.

To progress with this, we really need a reproduction, or at least basic instructions of your setup.

**Comment by ahnpnl** [comment]
Hi @alan-agius4, hopefully you can help us with

> Yes, but with #406 we start to catch up.
> 
> We need any help to analyze the [AngularCompilerPlugin](https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/angular_compiler_plugin.ts) as well as functionality in `@angular/compiler-cli` to understand which transformers are required to make ivy tests work.

Hi @alan-agius4, hopefully you can help us a bit by pointing out which transformers are required to make ivy tests work.

**Comment by ahnpnl** [comment]
A bit more information on this topic. Angular CLI runs tests with `karma + jasmine`, it doesn't use Angular compiler but uses plain TypeScript [Program](https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/angular_compiler_plugin.ts#L371) together with a few AST [transformers](https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/angular_compiler_plugin.ts#L1039). This behavior is different from `ng build --prod` which will use Angular [compiler](https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/angular_compiler_plugin.ts#L381).

Currently, we are working in #562 to replicate the similar behavior of Angular CLI does. However, the work in #562 will only focus on JIT mode, which Angular CLI is currently doing. AOT mode will come later. AOT mode will eventually touch this topic.

**Comment by norbertkovacs95** [comment]
Hi @ahnpnl,  would you please give an update on this issue? We are using Angular Workspaces and when running tests we are forced to compile our libraries with the `View Engine` compiler which complicates our workflows since we are hence forced to run `ngcc` as well.

**Comment by ahnpnl** [comment]
Hi @norbertkovacs95 I think if you use Angular libraries, it should be fine as long as you run `ngcc` before running tests.

Is your scenario different? What kind of errors do you get?

**Comment by norbertkovacs95** [comment]
Thank you for the quick answer. I am using @angular11.2.14 with jest-preset-angular@9.0.5. I built a library with the ivy compiler (simply running `ng build my-lib`). Once I start to test an application which imports this libraray I have to following issue:
`thrown: "Failed to load doc-viewer.component.html"`

I use the following jest configs:

```
module.exports = {
    preset: 'jest-preset-angular',
    maxWorkers: 1,
    roots: ['<rootDir>/src/'],
    testEnvironment: 'jsdom',
    testMatch: ['**/+(*.)+(spec).+(ts)'],
    setupFilesAfterEnv: ['<rootDir>/src/test.ts'],
    verbose: false,
    silent: true,
    collectCoverage: false,
    globals: {
        'ts-jest': {
            isolatedModules: true,
            tsconfig: './tsconfig.spec.json',
        },
    },
    moduleNameMapper: {
        'doc-viewer': '<rootDir>/../../packages/doc-viewer/dist/doc-viewer',
    },
};
```

Am I missing something? Should I be able to test applications which import `Ivy` libraries?

**Comment by ahnpnl** [comment]
The error you get can be caused by 2 things:

- `ngcc` is not run at root of the project before running Jest. You can verify this by opening `node_modules` and look for the file `__ngcc_entry_points__.json`, normally it's somewhere at end of `node_modules`.
- Jest doesn't load the correct files into tests.

**Comment by norbertkovacs95** [comment]
Thank you very much, you were right, running `ngcc` in the root solves that, sorry I missed that part of the Quides. The only question I have if there is a way to reduce to compilation time because it doesn take some time. Can we for example use the `properties` flag of `ngcc` to limit the compiled modules?

**Comment by ahnpnl** [comment]
If you run `ngcc` command directly from package json or from any js, it is possible to add additional flag. 

You can also use our util optimized script `ngcc-jest-preprocessor` (which is mentioned in the doc).

**Comment by ahnpnl** [comment]
Added e2e tests to prove that build with `main` branch, Angular full Ivy library as well as Angular partial Ivy library passed the tests, see https://github.com/thymikee/jest-preset-angular/pull/1176
