### ISSUE TITLE
__decorate is not defined

### ISSUE THREAD

**Issue by ollwenjones** [thymikee/jest-preset-angular#39]
Our project has a webpack config a little different from the CLI, so we have some customization on the setup, and I keep getting this error on the first test I converted to use Jest:
```shell
> jest --no-cache  # running with no-cache every time until I get it working

 FAIL  src\app\+module\module.actions.test.ts
  ● Test suite failed to run

    ReferenceError: __decorate is not defined
...
```
**It makes me think that decorator annotations aren't being processed by the preprocessor?**

Our tsconfig is pretty standard for Angular 4+, and here is the JEST part of the package.json
```
"jest": {
    "globals": {
      "__TS_CONFIG__": "tsconfig.json",
      "__TRANSFORM_HTML__": true
    },
    "setupTestFrameworkScriptFile": "<rootDir>/setupJest.ts",
    "transform": {
      "^.+\\.(ts|js|html)$": "<rootDir>/node_modules/jest-preset-angular/preprocessor.js"
    },
    "testRegex": "^.+\\.test\\.(ts|js)$",
    "moduleFileExtensions": [
      "ts",
      "js",
      "html"
    ],
    "moduleNameMapper": {
      ".+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
      ".+\\.(scss|css|less)": "<rootDir>/__mocks__/styleMock.js",
      ... (a few others)
    },
    "transformIgnorePatterns": [
      "node_modules/(?!@ngrx)"
    ]
  }
```

**Comment by thymikee** [comment]
I've found this on SO: https://stackoverflow.com/questions/36808303/webpackangular2-error-uncaught-referenceerror-decorate-is-not-defined
Maybe you can create a separate tsconfig for testing and apply these updates?

**Comment by ollwenjones** [comment]
Great find! Sorry I didn't think to check SO first.

> Maybe you can create a separate tsconfig for testing and apply these updates?

Your very helpful example has a separate `tsconfig.spec.json`, so I know exactly what you mean.

Hoping I can get back to this task next week.

**Comment by thymikee** [comment]
Awesome, good luck!

**Comment by ollwenjones** [comment]
Setting `"noEmitHelpers": false,` in the `tsconfig.spec.json` did the trick. Thanks!
