### ISSUE TITLE
Webpack require() assets

### ISSUE THREAD

**Issue by cgatian** [thymikee/jest-preset-angular#41]
Looks like this issue has been answered several times on the internet but nothing seems to work for me.

The approach I tried was to redirect the require to a mock, as suggested by the [Jest Webpack documentation](http://facebook.github.io/jest/docs/en/webpack.html#handling-static-assets)
```
"moduleNameMapper": {
      "\\.(jpg|jpeg|png)$": "<rootDir>/__mocks__/fileMock.js"
    },
```
This approach seems to work for the majority of users, but for some reason isn't for me.  I understand all setups are a little different, but I'm wondering if anyone has ran into this issue while running the preset, and how they solved it.

**Comment by thymikee** [comment]
Hard to tell without a repo where the problem happens. Are you able to provide such? Otherwise there's little I can do

**Comment by cgatian** [comment]
In your Angular CLI project example if you attempt to `require` a png file within a component that's under test, you should see the issue. 

I will attempt to fork your repo to show later tonight.

**Comment by thymikee** [comment]
Can you send a PR with failing test which we can fix later?
