### ISSUE TITLE
Does not work with node v4.4.4

### ISSUE THREAD

**Issue by carlcheel** [thymikee/jest-preset-angular#43]
Although this might be intended, it would be nice to document it.

I've modified the project to work with v4.4.4 by removing the object destructuring syntax in a couple of key files.

If you intended to support node v4.4.4 let me know and I'll create a pull request.

**Comment by thymikee** [comment]
I wasn't aware Angular 2/4 supports Node 4 so I just went with latest LTS. 
I'm happy to accept a PR, sure! You can also add node 4 to Travis queue.

**Comment by thymikee** [comment]
Fixed with #44
