### ISSUE TITLE
Jest 26 on Node10 throws error

### ISSUE THREAD

**Issue by Lonli-Lokli** [thymikee/jest-preset-angular#469]
## 🐛 Bug Report

Node10 does not work with Jest26 

## To Reproduce

Node10 + Jest26 - try to run test with coverage

## Expected behavior

It should work
## Link to repo (highly encouraged)

I believe it's caused (by this comment) mocking globalThis in reflect-metadata utils (see https://github.com/jsdom/jsdom/issues/2795#issuecomment-624460723 for details)

## Error log:

> ng run vo:test --coverage 
 FAIL  apps/vo/src/app/app.component.spec.ts
  ● Test suite failed to run

    evalmachine.<anonymous>:1
    globalThis
    ^

    ReferenceError: globalThis is not defined

      at ../../evalmachine.<anonymous>:1:1
      at setupWindow (../../node_modules/jsdom/lib/jsdom/browser/Window.js:51:55)
      at new Window (../../node_modules/jsdom/lib/jsdom/browser/Window.js:107:3)
      at exports.createWindow (../../node_modules/jsdom/lib/jsdom/browser/Window.js:38:10)
      at new JSDOM (../../node_modules/jsdom/lib/api.js:36:20)
```
# content of error stacktrace :

```

## envinfo

```
System:
    OS: Win10

Npm packages:
    jest:26.2.2
    jest-preset-angular:8.2.1
    typescript:3.9.3
```

**Comment by wtho** [comment]
Yeah, this looks like a `jsdom`-related error, which does not occur in the browser.
The easy workaround is to update node.js to v12. If this does not work, you can also try to initialize `globalThis` in `setup-jest.ts`. This is just a guess though.

**Comment by ahnpnl** [comment]
our CI runs with node 10 but I never see this issue, kinda odd.

**Comment by Lonli-Lokli** [comment]
Yep. I will try to reproduce it with the clean repo and let you know.

**Comment by Lonli-Lokli** [comment]
Seems like it's not preset fault, but Nx one.
