### ISSUE TITLE
One issue about requiring modules after another.

### ISSUE THREAD

**Issue by rantiev** [thymikee/jest-preset-angular#47]
First it says i have no zone.js, then @angular/core/ ... then something else and else. 
Don't you need to add all this stuff into package.json?

I'm trying to use this module in the project generated without angular-cli. (tried to install  it using 'npm i @angular/cli' but didn't help)

By the way do you have any working example with angular 1.x with Jest where i can see how proper configuration looks?

**Comment by thymikee** [comment]
I think I need to be more clear on the support this preset provides. This is for **Angular**, not AngularJS. 
Take a look here, second sentence: https://www.xfive.co/blog/testing-angular-faster-jest/

You'll also find a blog post on setting up Jest with AngularJS 1.5+ here: https://facebook.github.io/jest/docs/en/testing-frameworks.html#angularjs

**Comment by thymikee** [comment]
I made it clear in [README](https://github.com/thymikee/jest-preset-angular/blob/master/README.md#jest-preset-angular) now.

**Comment by rantiev** [comment]
One who needed to make it clear is google with their angularJs is not angular approach. A lot of people use old angular and if one says angular they don't think about angular v2 but about both.

I was thinking that angular cli can be used to generate angular 1.x project so it was not obvious for me that it's only for 2.

I see now, thanks, and sorry for disturbing.

**Comment by thymikee** [comment]
Yea, I hate that too :<. Have a great week! :)
