### ISSUE TITLE
Testbed not initialized on a monorepo

### ISSUE THREAD

**Issue by Tallyb** [thymikee/jest-preset-angular#50]
@thymikee - Kudos for the great work! 

We have an Angular monorepo (lerna) with multiple packages. 
I was trying to run tests from the top level with jest `packages` and jest `roots`  configuration, and tests are failing due to Testbed is not initialized properly. 
I have created a repo demonstrating the problem. 
https://github.com/Tallyb/ng-jest-packages

If you run `npm run test` (or test:only) from top - tests will fail.
If you will run `npm run jest` (not test - this will run karma) from pack1 - tests are passing. (All tests are angular-cli base tests). 
Is that something that might be supported? (unfortunately, I could not solve it myself)

**Comment by thymikee** [comment]
I'm currently on a vacation, will take a look after nearest Monday

**Comment by Tallyb** [comment]
Ok, that was miserable. 
Apparently, I have used `packages: '<rootDir>/packages/'`
and omitted the *. Should be: `packages: '<rootDir>/packages/*'`

**Comment by Tallyb** [comment]
Was a bit premature joy. I still get an error.  
Probably an issue with module mapper, but I cannot get my head around it. 
Help will be highly appreciated

**Comment by thymikee** [comment]
Just cloned your repo and everything seems fine. Installed packages with `yarn` instead of `npm`.

<img width="413" alt="screen shot 2017-06-19 at 16 19 21" src="https://user-images.githubusercontent.com/5106466/27289696-2681229c-550b-11e7-93f9-ec8880d45ee0.png">

**Comment by Tallyb** [comment]
Problems starts when you install package dependencies

**Comment by thymikee** [comment]
Can you add some so I can see the issue?

**Comment by Tallyb** [comment]
cd /packages/pack1/web  && npm install (--no-shrinkwrap...)
and then run tests

**Comment by Tallyb** [comment]
Ok, so it seems the issue is a bad module resolution for angular. 
Current solution was to add to `jest.config`: 
```
moduleDirectories: [
    "<rootDir>/node_modules"
  ],
```
