### ISSUE TITLE
Create custom testEnvironment for perf

### ISSUE THREAD

**Issue by thymikee** [thymikee/jest-preset-angular#51]
We can decrease the total parsing time of tests dramatically by shifting imports for `core-js`, `zone.js` et al. from `setupFiles` to custom test environment. This way all the heavy initialization scripting will be performed once per worker (cpu core) instead of once per test file.

**Comment by patrickmichalina** [comment]
Have an example of this?

**Comment by thymikee** [comment]
You mean custom environment? Here's one example: https://github.com/Micromeritics/jest-environment-jsdom-11.0.0
I'm also not super sure about perf gains, parsing time will be reduced, but it may be very small compared to whole test suite.

**Comment by patrickmichalina** [comment]
Thanks! The reason I am interested is that i need to have an instance of Nightmare for the entire set of tests. Right now, my configuration loads a new Nightmare browser on each test. That means firing up electron for each suite.... Not cool. Maybe I can create the single instance with this. Thanks again.
