### ISSUE TITLE
Angular 9 Setup - ReferenceError: Zone is not defined

### ISSUE THREAD

**Issue by shannonlal** [thymikee/jest-preset-angular#512]
## 🐛 Bug Report

I am trying to setup a project using Angular 9 with Jest and I have been following the instructions within the README.md and I am getting an error when trying to run a test.  Here is the output of the test:

command:
```
npm run test:unit
```
Output:
```

    ReferenceError: Zone is not defined

      at node_modules/zone.js/dist/zone.js:670:5
```

There is an existing issue on stackoverflow but no one has been able to find a solution.  I have attached my question to the existing thread here (https://stackoverflow.com/questions/61890453/migrating-to-jest-in-angular-9-gives-zone-is-not-defined-error/64020391#64020391).

## To Reproduce

1. I have setup a repo that can be cloned and I have documented the steps below that I followed to get this up and running.

**Reproduce Steps using sample repo:**

```
git clone https://github.com/shannonlal/jest-sample.git

npm/yarn install

npm run test:unit
```

**Reproduce Steps from scratch**

```
In my repo I have created a Setup instructions and I have linked the steps here.

https://github.com/shannonlal/jest-sample/blob/master/JEST-SETUP.md
```

## Expected behavior

Jest Tests should be able to execute without displaying an issue with Reference Error

## Link to repo (highly encouraged)
https://github.com/shannonlal/jest-sample

## Error log:
Test suite failed to run

    ReferenceError: Zone is not defined

      at node_modules/zone.js/dist/zone.js:670:5

```
# content of error stacktrace :

```

## envinfo

```
System:
    OS:Mac
    Node: v10.13.0

Npm packages:
    jest: 6.4.2
    jest-preset-angular:8.3.1
    typescript:3.8.3
```

**Comment by wtho** [comment]
I tried your setup and it's running for me on node v14.
Then I reverted your additions in `setup-jest` and `polyfills.ts` and again it's running.

Then I switched to node v10 just to be sure, but again the tests started to run and succeeded.

Maybe you can try to reproduce the error, @ahnpnl? Otherwise we have to close the issue.

**Comment by shannonlal** [comment]
@wtho Thank you very much for the quick reply.  To confirm it looks like it was the node version.  Following your comments above I switched node v12, and reinstalled the node_modules and the test work.  Thanks again for quick reply and taking the time to clone and run the test.  

Thank you very much
