### ISSUE TITLE
Expected 'styles' to be an array of strings.

### ISSUE THREAD

**Issue by michahell** [thymikee/jest-preset-angular#56]
Running into this error: 

`Expected 'styles' to be an array of strings.`

After we changed our Angular component definitions to the following:

```TypeScript
@Component({
	selector: 'summary',
	styles: [require('./summary.scss')],
	template: require('./summary.html')
})
```

I am still wrapping my head around the difference between WebPack compiling and running our webapp, and Jest doing it's own transforms and TypeScript compilation, but I suspect it has to do with the preprocessor, am I right ?

I tried changing the following line:

`const STYLE_URLS_REGEX = /styleUrls:\s*\[\s*((?:'|").*\s*(?:'|")).*\s*.*\]/g;`

to this line:

`const STYLE_URLS_REGEX = /styles:\s*\[\s*((?:'|").*\s*(?:'|")).*\s*.*\]/g;`

to no avail 🤓  halp!

**Comment by thymikee** [comment]
Is this even valid way to provide styles? Why can't you use styleUrls?

**Comment by michahell** [comment]
I get the same error if I use `styleUrls` :(

`Expected 'styleUrls' to be an array of strings.`

**Comment by thymikee** [comment]
Yes, because you need to pass array of strings
```
styleUrls: ['path/to/style', './other/path']
```

**Comment by michahell** [comment]
That makes sense. But as I am working on getting testing working with Jest (and apart from this it works great, with help of your preset package) and our webapp compiles and runs just fine using WebPack, I'm trying to figure out what the exact difference is here

**Comment by thymikee** [comment]
Because we're unit/integration testing, we want to styles to be stubbed (and eventually replaced by something like `styles: []`). 
This regex will work for single require call. 
```js
/styles:\s*\[\s*require\((.*)\).*\s*.*\]/g
```

Just tweak it to work with multiple requires and you'll be good :)

**Comment by michahell** [comment]
Thanks! this seems to indeed have been the problem! I used the following regex:
```regex
styles:\s*\[\s*require\((.*)\).*]
```
