### ISSUE TITLE
Are some mocks of ngrx needed?

### ISSUE THREAD

**Issue by blackholegalaxy** [thymikee/jest-preset-angular#60]
In article and example we can see some Mocks can be provided. What's exactly their purpose?

We have an Angular CLI project with NGRX store and effets. We have a bunchload of tests written. We are looking into moving to JEST to improve test speed and remove bundling requirement from webpack.

But we need to know more about Mocks and what is mandatory to change / add compared to a standard karma webpack jasmine testing stack.

Thanks!

**Comment by thymikee** [comment]
These are to patch environment so it's closer to what angular expects from the browser. You set it once and that's all.

**Comment by thymikee** [comment]
Ngrx is a library and as far as I tested with it, didn't need to mock it or whatever, integration went smoothly
