### ISSUE TITLE
Support jest 27

### ISSUE THREAD

**Issue by ahnpnl** [thymikee/jest-preset-angular#674]
## 🚀 Feature Proposal

Adopt `ts-jest` v27 and `jest` 27 changes

**Notes**

- Have to explicitly set `testRunner` to `jest-jasmine2` because `jest-circus` has issues with `asycn done => {}` (see https://github.com/facebook/jest/issues/10529)

- **BLOCKER**: Jest 27 and JSDOM has issues with node 10 related to `globalThis`, see https://github.com/jsdom/jsdom/issues/2961

**Comment by ahnpnl** [comment]
Hi @JiaLiPassion , we have issues with zone 10 with jest 27. The error is thrown for `async done =>`
```
Error: Test functions cannot both take a 'done' callback and return something. Either use a 'done' callback, or return a promise.
    Returned value: ZoneAwarePromise {
"__zone_symbol__state": true,
"__zone_symbol__value": undefined,
}
```

Would you please help to check it ?

**Comment by JiaLiPassion** [comment]
@ahnpnl , sure , I will check it.

**Comment by ahnpnl** [comment]
FYI: The issue is caused by default `testRunner` in Jest 27 is `jest-circus`, switch back to `jest-jasmine2` the test passed again. I think this information is helpful

**Comment by JiaLiPassion** [comment]
@ahnpnl , I just checked, I think it is not a zone.js or jest-preset-angular issue.
I created an empty project with single test file.

```
describe('test fake', () => {
  it('async with done should work', async done => {
    let flag = false;
    setTimeout(() => {
      flag = true;
      expect(flag).toBe(true);
      done();
    }, 100);
  });
});
```

And use `jest 27` to run it, it will throw the same error. So it seems `jest-circus` not allow to 
`use done` with `return something` at the same time.
https://github.com/facebook/jest/issues/10529

**Comment by ahnpnl** [comment]
I see, thanks a lot 👍  I will set to `jest-jasmine2` for now while waiting for Jest to fix it.
