### ISSUE TITLE
Watch fails with EMFILE on OSX

### ISSUE THREAD

**Issue by intellix** [thymikee/jest-preset-angular#7]
**System:** MBP 15" Retina
**OS:** OSX Sierra
**Jest:** 19.2.2
**CLI:** 1.0.0

Was attempting to benchmark the watch stuff in CLI and am getting an EMFILE error when doing: `npm run test:watch`. I've a feeling that it's something to do with configuration here with which files to watch. I'll try and dig deeper.

```
> xc-r2d2@0.0.0 test:watch /Users/dominicwatson/Sites/stash/xcaf/xc-r2d2
> jest --watch --no-cache

2017-04-05 00:31 node[63236] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-04-05 00:31 node[63236] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-04-05 00:31 node[63236] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1274:11)
```

**Comment by thymikee** [comment]
First thing, don't use `--watch` with `--no-cache`, you'll loose lots of speed benefits. 
No kidding, I see this kind of error for the first time ever. Can you install `watchman` (`brew install watchman`) and run watch again?

**Comment by intellix** [comment]
I wasn't originally trying with no-cache but in this attempt I tried it :P 
It works now with watchman!

**Comment by thymikee** [comment]
🎉

**Comment by intellix** [comment]
Just a question: `--watch` says that it'll only `Run tests related to changed files based on hg/git (uncommitted files):`

but I'm getting my entire suite being run if I don't use filter patterns. Is there some extra configuration required there or?
If I have a component like:
```
/payment/payment.component.ts
/payment/payment.component.spec.ts
```

and I save either of those files, is there any way for it to only run the `payment.component.spec.ts`?

**Comment by thymikee** [comment]
If other tests are running, it's because some other component relies on / renders `payment.component.ts`, hence it's related.

To test only payment, you can run `jest --watch payment`, where _payment_ is regex that matches tests you want.
