### ISSUE TITLE
Importing const from barrel = undefined

### ISSUE THREAD

**Issue by montella1507** [thymikee/jest-preset-angular#72]
//index.ts 
import * as components from './components';

export const COMPONENTS = [
    components.WidgetComponent
];

// module.ts
import { COMPONENTS } from './index';
@NgModule({
  declarations: [
    ...COMPONENTS 
  ],

= components are undefined.

**Comment by thymikee** [comment]
Hi @montella1507, thanks for your report, but this doesn't tell much. A repo with the issue would be helpful.

**Comment by montella1507** [comment]
Hello, 

ok i will try to simulate it in your example app.

**Comment by montella1507** [comment]
@thymikee  i have resolved my issue, yet i dont know why it occurs..

my project structure:
/src
  app.module.ts
  /shared
    /models
       /app 
           index.ts    


That index.ts was reexported:
`export *  from './app'`;
it works for every build - ng build, ngc build, aot build.. but with JEST.. 

it takes "from './app'" as app.module.ts file.. So it is error...

**Comment by thymikee** [comment]
Try the latest version of the preset

**Comment by montella1507** [comment]
Current:
jest-preset-angular@^2.0.5

 i would try and i will let you know.

**Comment by montella1507** [comment]
4.0.0-beta.1 works. Thank you :-)) 

Uff. i have spent 6 hours on everything  :-) Reworked imports, tried to get rid of several barrels... Madge tool, ng tool for circullar dependencies :D  unfortunately i just had to wait for the new version of preset :-)

**Comment by thymikee** [comment]
The fix for issues like this was a part of v3, which was released some time ago. Glad it worked for you :)
