### ISSUE TITLE
Could not locate module ./app/firebase_app

### ISSUE THREAD

**Issue by phsims** [thymikee/jest-preset-angular#73]
I am using firebase as part of my core module for authentication, (I wont be keeping it) and I keep getting this error when testing

```
    Configuration error:

    Could not locate module ./app/firebase_app (mapped as ...\src\app\firebase_app)

    Please check:

    "moduleNameMapper": {
      "/app\/(.*)/": "...\src\app\$1"
    },
    "resolver": undefined
```

**Comment by thymikee** [comment]
For starters, don't use Windows specific path separators in moduleNameMapper, use normal unix slashes

**Comment by phsims** [comment]
Thanks for the fast response.  The thing is am just using the basic setup.  There is no firebase folder other than the one in node.  
```
  "jest": {
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts"
  }
```

**Comment by thymikee** [comment]
You're probably encountering issue fixed here: https://github.com/thymikee/jest-preset-angular/pull/71.
I'll try to publish it in a moment, looks like I forgot to do it.

**Comment by thymikee** [comment]
Published v3.0.2, let me know if it works for you :)

**Comment by phsims** [comment]
Perfect thanks :)

**Comment by phsims** [comment]
I reinstalled firebase and its working fine now.  Feel free to close the issue
