### ISSUE TITLE
lodash functions cause: TypeError: get_1.default is not a function

### ISSUE THREAD

**Issue by Tuizi** [thymikee/jest-preset-angular#77]
I have an Angular app generated with angular/cli with a dependency to `"lodash": "^4.17.4"`. The application works well but it is not possible to test it with jest.

In my component I import the lodash function that I need with `import get from 'lodash/get';`, testing this component cause the error `TypeError: get_1.default is not a function`.

Any idea of how to fix this issue?

**Comment by thymikee** [comment]
I don't get that error in my examples (just used latest lodash and imported to component) but funny things happen to snapshot serializer when I name it `get` (other names are ok)

**Comment by Tuizi** [comment]
Ok so I have:

    "lodash": "^4.17.4",
    "@types/jest": "^21.1.2",
    "jest": "^21.2.1",
    "jest-preset-angular": "^4.0.0",
    "jest": {
    	"preset": "jest-preset-angular",
    	"setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts"
    }

Nothing different than the default configuration in your readme and still `TypeError: isString_1.isString is not a function` in my component with the code `import { isString } from 'lodash/isString';`

**Comment by thymikee** [comment]
Once you use default export, now it's named export, which is weird. 
You can clone this repository and repro your case in the `example` dir.

**Comment by Tuizi** [comment]
I have the exact same issue using the example dir:

● SimpleComponent › snapshots

    TypeError: isString_1.isString is not a function

**Comment by thymikee** [comment]
This is not a problem of Jest, it's your code. You should use `lodash-es` if you want to use ES modules. As a workaround, ESM provides this syntax, which will let you use non-ESM compliant code:
```js
import * as isString from 'lodash/isString';
```

**Comment by zyasir** [comment]
Moving to lodash-es causes jest to give error:

```
 /Users/yasira/Documents/zo_field_app/node_modules/redux-offline-apollo-link/node_modules/lodash-es/get.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import baseGet from './_baseGet.js';
                                                                                                    ^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (node_modules/redux-offline-apollo-link/src/index.ts:12:1)
```

Any ideas?

**Comment by wtho** [comment]
@zyasir you bump an issue closed two years ago with a different error message, probably you do not have setup jest + typescript properly.

Please follow the configuration in `README.md` to solve your problem or create a new issue if it still persists.

**Comment by zyasir** [comment]
Affirmative @wtho

**Comment by wtho** [comment]
@zyasir no need to delete the comment, I also didn't want to come across too harsh, but your error message looked more like an issue with a wrong typescript+jest setup and just accidentally showing `lodash` in the error message.
If you follow the README, it should help you solving it.
Cheers!

**Comment by zyasir** [comment]
Thanks @wtho I appreciate it.

**Comment by maddhruv** [comment]
If you're using typescript, setting
`"esModuleInterop": true`
will work like charm

**Comment by oneEyedSunday** [comment]
im on angular 9 and this + https://stackoverflow.com/a/52747002 doesn't work for me

**Comment by benjiwheeler** [comment]
> If you're using typescript, setting `"esModuleInterop": true` will work like charm

To clarify, you set this in your tsconfig file, under the `compilerOptions` section. This worked for me.
