### ISSUE TITLE
TypeError: require(...).install is not a function

### ISSUE THREAD

**Issue by 4kochi** [thymikee/jest-preset-angular#8]
With the latest patch of the `jest.preset.json` (https://github.com/thymikee/jest-preset-angular/commit/8e9c6035e95e9462dae55f2ee9b002687db4e076) I get the following error:

```
Test suite failed to run

    TypeError: require(...).install is not a function
      
      at Object.<anonymous> (src/core/index.ts:1:122)
      at Object.<anonymous> (node_modules/resolve/lib/async.js:1:101)
      at Object.<anonymous> (node_modules/resolve/index.js:2:28)
      at Object.<anonymous> (node_modules/ts-jest/dist/utils.js:8:17)
      at Object.<anonymous> (node_modules/ts-jest/dist/transpile-if-ts.js:4:15)
      at Object.<anonymous> (node_modules/ts-jest/dist/default-retrieve-file-handler.js:4:25)
      at Object.<anonymous> (node_modules/ts-jest/dist/index.js:3:39)
      at Object.<anonymous> (node_modules/ts-jest/index.js:1:107)
      at Object.<anonymous> (config/setupJest.ts:1:103)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

I am not sure what the problem is. Without the change it works fine.

**Comment by thymikee** [comment]
Does it happen when you run `jest --no-cache`?

**Comment by 4kochi** [comment]
yes

**Comment by thymikee** [comment]
I've also made this change: https://github.com/thymikee/jest-preset-angular/commit/d80598b78b7cf6463c2f0ad4816b502c4579a34b

Can you confirm you're using `"module": "commonjs"` in your TS config file?

**Comment by 4kochi** [comment]
Yes, it is.

**Comment by thymikee** [comment]
Hm, so it works with this `moduleNameMapper` in your `package.json`?
```json
"moduleNameMapper": {
    "app/(.*)": "<rootDir>/src/app/$1",
    "environments/(.*)": "<rootDir>/src/environments/$1"
}
```

**Comment by 4kochi** [comment]
Exactly.

I thought I could just use the old setting of "moduleNameMapper" in my "jest" config on the `package.json` in my project. But then my setting of  "moduleNameMapper" get merged with the setting of your module.

**Comment by 4kochi** [comment]
Btw. my Angular2 is not generated by the angular-cli. Is it a custom setup with webpack with a slightly different folder structure.

**Comment by thymikee** [comment]
`moduleNameMapper` gets shallow-merged, so you can override `(.*)`:
```json
"moduleNameMapper": {
    "(.*)": "(.*)",
    "app/(.*)": "<rootDir>/src/app/$1",
    "environments/(.*)": "<rootDir>/src/environments/$1"
}
```

But I'm not so happy with this rule anyway...

**Comment by thymikee** [comment]
Does it help?

**Comment by 4kochi** [comment]
Yes, it does. Thx

**Comment by thymikee** [comment]
I've added a brief troubleshooting guide: https://github.com/thymikee/jest-preset-angular#troubleshooting
Would appreciate if you have anything more to add, based on your experience.

**Comment by 4kochi** [comment]
I will have a look. Thanks a lot again for the fast response.
