### ISSUE TITLE
Error: Uncaught [Error: Found the synthetic listener @state.done. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.]

### ISSUE THREAD

**Issue by thekip** [thymikee/jest-preset-angular#80]
Obviously it's easy to fix, just add what it wants, but the problem here, that this error doesn't mark test as failed. 

Need help to investigate why it happens, and how to fix that (force test be red in this case)

> Error: Uncaught [Error: Found the synthetic listener @state.done. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.]
>     at reportException (project\node_modules\jest-preset-angular\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
>     at Timeout.callback [as _onTimeout] (project\node_modules\jest-preset-angular\node_modules\jsdom\lib\jsdom\browser\Window.js:544:7)
>     at ontimeout (timers.js:488:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:283:5) { Error: Found the synthetic listener @state.done. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
>     at checkNoSyntheticProp (project\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:2964:15)
>     at DefaultDomRenderer2.Object.<anonymous>.DefaultDomRenderer2.listen (project\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:2948:9)
>     at DebugRenderer2.Object.<anonymous>.DebugRenderer2.listen (project\node_modules\@angular\core\bundles\core.umd.js:13806:30)
>     at listenToElementOutputs (project\node_modules\@angular\core\bundles\core.umd.js:9245:66)
>     at createViewNodes (project\node_modules\@angular\core\bundles\core.umd.js:12209:17)
>     at createRootView (project\node_modules\@angular\core\bundles\core.umd.js:12132:5)
>     at callWithDebugContext (project\node_modules\@angular\core\bundles\core.umd.js:13518:42)
>     at Object.debugCreateRootView [as createRootView] (project\node_modules\@angular\core\bundles\core.umd.js:12835:12)
>     at ComponentFactory_.Object.<anonymous>.ComponentFactory_.create (project\node_modules\@angular\core\bundles\core.umd.js:9904:46)
>     at ComponentFactoryBoundToModule.Object.<anonymous>.ComponentFactoryBoundToModule.create (project\node_modules\@angular\core\bundles\core.umd.js:3365:29)
>     at DomPortalHost.Object.<anonymous>.DomPortalHost.attachComponentPortal (project\node_modules\@angular\cdk\bundles\cdk-portal.umd.js:354:45)
>     at DomPortalHost.Object.<anonymous>.BasePortalHost.attach (project\node_modules\@angular\cdk\bundles\cdk-portal.umd.js:253:25)
>     at OverlayRef.Object.<anonymous>.OverlayRef.attach (project\node_modules\@angular\cdk\bundles\cdk-overlay.umd.js:137:62)
>     at MdSnackBar.Object.<anonymous>.MdSnackBar._attachSnackBarContainer (project\node_modules\@angular\material\bundles\material.umd.js:20234:56)
>     at MdSnackBar.Object.<anonymous>.MdSnackBar._attach (project\node_modules\@angular\material\bundles\material.umd.js:20247:47)
>     at MdSnackBar.Object.<anonymous>.MdSnackBar.openFromComponent (project\node_modules\@angular\material\bundles\material.umd.js:20171:49)
>     at MdSnackBar.Object.<anonymous>.MdSnackBar.open (project\node_modules\@angular\material\bundles\material.umd.js:20215:21)
>     at project\src\app\common\snack-bar.service.ts:26:32
>     at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (project\node_modules\zone.js\dist\zone.js:425:31)
>     at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (project\node_modules\zone.js\dist\proxy.js:103:39)
>     at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (project\node_modules\zone.js\dist\zone.js:424:36)
>     at Zone.Object.<anonymous>.Zone.runTask (project\node_modules\zone.js\dist\zone.js:192:47)
>     at Object.<anonymous>.ZoneTask.invokeTask (project\node_modules\zone.js\dist\zone.js:499:34)
>     at ZoneTask.invoke (project\node_modules\zone.js\dist\zone.js:488:48)
>     at timer (project\node_modules\zone.js\dist\zone.js:1896:29)
>     at Timeout.callback [as _onTimeout] (project\node_modules\jest-preset-angular\node_modules\jsdom\lib\jsdom\browser\Window.js:542:19)
>     at ontimeout (timers.js:488:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:283:5)

**Comment by thekip** [comment]
looks like I need investigate it by myself :grin:

**Comment by thymikee** [comment]
Not sure if you looked at similar issues, like this one: https://github.com/thymikee/jest-preset-angular/issues/22

**Comment by SRINIVAS-B-SINDAGI** [comment]
> looks like I need investigate it by myself

Hey how did you solve this issue?
Facing the same issue in my project.

**Comment by francomac** [comment]
> > looks like I need investigate it by myself
> 
> Hey how did you solve this issue?
> Facing the same issue in my project.

add this in your module, inside imports array. BrowserAnimationsModule

**Comment by SRINIVAS-B-SINDAGI** [comment]
Yeah yeah already solved it .
Thank you

On Tue, 6 Aug 2019 at 7:44 AM, Franco <notifications@github.com> wrote:

looks like I need investigate it by myself

Hey how did you solve this issue?
Facing the same issue in my project.

add this in your module, inside imports array. BrowserAnimationsModule

?
