### ISSUE TITLE
File changes not getting picked up in --watch mode (9.0.0-next.8)

### ISSUE THREAD

**Issue by johncrim** [thymikee/jest-preset-angular#803]
## 🐛 Bug Report

This is _almost_ the same as #764 - it's safe to consider this a regression in the new code, though the behavior is slightly different. I'm submitting a new issue to avoid confusion (since I know it's a different issue in new code).

When using 9.0.0-next.8 with isolatedModules: false, in  `jest --watch` file changes are not being properly incorporated - it appears that the cache trails file changes.

## To Reproduce

If I have a test like the following, which fails to compile b/c the commented out line is missing

```ts
describe('A directive can be declared in the test file', () => {

  it('and used in a test', () => {
    TestBed.configureTestingModule({
      declarations: [BlockClickBubbleDirective, TestHostComponent]
    });
    //const fixture = TestBed.createComponent(TestHostComponent);

    const directive = fixture.debugElement.children[0].children[0].injector.get(BlockClickBubbleDirective);
    expect(directive).toBeTruthy();
  })

});
```

then run `jest --watch`, I receive an error (as expected). If I then uncomment the `const fixture` line and save, the file is rebuilt and the test is re-run, but it uses the original (erroring) code and I receive the original error. If I then change the code back (to the erroring state) and save, the non-erroring code is run and the test passes.

If I exit jest after any of the changes and restart (or run jest not in watch mode), the current code is compiled and run, resulting in compile error or test success as expected.

## Expected behavior

In `--watch` mode, code changes are compiled and run after the file is saved.

## Link to repo

https://github.com/johncrim/repro-ivy-jest-preset-angular/tree/bug/jest-watch-update

```
git clone git@github.com:johncrim/repro-ivy-jest-preset-angular.git
git checkout  bug/jest-watch-update

yarn
yarn test:watch inline-directive # test failure expected
# uncomment 'const fixture' line; test re-runs and still fails
# exit + restart
yarn jest inline-directive # test passes
```

## envinfo

```
System:
    OS: Windows

Npm packages:
    jest: 27.0.0-next.2
    jest-preset-angular: 9.0.0-next.8
    typescript: 4.0.5
```

**Comment by johncrim** [comment]
Note: I did [include a test](https://github.com/thymikee/jest-preset-angular/pull/765/commits/a40d5747e997eb210d41a77607b368a7284a74bf) when I submitted a PR for #764, but it looks like it was removed.

**Comment by ahnpnl** [comment]
It was removed because now we rely on `ts-jest` for compilation :) so this bug is for `ts-jest` actually.

**Comment by ahnpnl** [comment]
hmm I found out that it's `jest-preset-angular` bug because we used the wrong cache key which `ts-jest` couldn't resolve the correct cached compiler.

**Comment by ahnpnl** [comment]
would you please try this [build.zip](https://github.com/thymikee/jest-preset-angular/files/5974482/build.zip)

Just need to extract it and replace `build` folder under `jest-preset-angular` with the `build` folder from the zip file. Then clear Jest cache and run test.

**Comment by johncrim** [comment]
Yes! The problem is fixed with this build, given 10+ permutations I couldn't get the test output to mismatch the test code. Thank you!!

**Comment by johncrim** [comment]
Hi @ahnpnl : Any chance of an updated beta release with this fix incorporated? I'm holding off on merging my branch b/c I don't want other devs to waste time on this.

**Comment by ahnpnl** [comment]
Hmm I’m waiting for `ts-jest` changes to be released first :)

**Comment by johncrim** [comment]
Makes sense - Thanks for the update.

**Comment by ahnpnl** [comment]
Some updates: after testing with latest `ts-jest` next tag, I found out watch mode doesn’t work properly when changing types in another file which is referenced by test file so we have to wait for another fix.

**Comment by ahnpnl** [comment]
I will close this as fixed in next-10 . The other watch mode issue https://github.com/kulshekhar/ts-jest/issues/943  was also for `ts-jest` to fix which is unrelated to this preset.
