### ISSUE TITLE
getComputedStyle mock breaks @testing-library/angular support for aria roles

### ISSUE THREAD

**Issue by enolive** [thymikee/jest-preset-angular#807]
## 🐛 Bug Report

Using the default jest-global-mocks.ts from the README renders the support for aria roles from @testing-library/angular unusable. When removing the getComputedStyle mock, everything works fine. I am not sure if this is a problem with this preset or with @testing-library/angular. Please tell me if I should report the problem to testing-library/angular instead. 

It might be just a configuration/documentation problem. I do not fully understand the suggested global mocks entries.

Please see also my Stackoverflow question: https://stackoverflow.com/questions/63182537/angular-testing-library-getbyrole-query-works-only-with-hidden-true-option/66147002#66147002

## To Reproduce

Setup a new angular project to use both jest and @testing-library/angular. Try to access aria roles by the getByRole function (such as button or heading).

## Expected behavior

Aria roles should work.

## Link to repo (highly encouraged)

https://github.com/enolive/chuck-norris.ng

Please look at the commit history, I recently removed the getComputedStyle mock in order to make it work.

## Error log:
```
TestingLibraryElementError: Unable to find an accessible element with the role "button"

There are no accessible roles. But there might be some inaccessible roles. If you wish to access them, then set the `hidden` option to `true`. Learn more about this here: https://testing-library.com/docs/dom-testing-library/api-queries#byrole

```

## envinfo

```
System:
    OS: Ubuntu 20.04

Npm packages:
    jest: 26.2.1
    jest-preset-angular: 8.2.1
    typescript: 3.9.7
```

Also happens with the latest & greatest angular plus other npm packages

**Comment by ahnpnl** [comment]
The mock `getComputedStyle` was added to fix an issue with Angular Material, see https://github.com/thymikee/jest-preset-angular/pull/61 It can be that now it's not required to have it anymore.

The file `jest-global-mocks.ts` is optional, you can copy anything from it :)

**Comment by ahnpnl** [comment]
and I don't think it's the issue with `@testing-library/angular`, just documentation of `jest-preset-angular` needs to be improved.

**Comment by enolive** [comment]
> and I don't think it's the issue with `@testing-library/angular`, just documentation of `jest-preset-angular` needs to be improved.

my thoughts exactly :wink:
