### ISSUE TITLE
How do we deal with declare var x: any; from 3rd party component?

### ISSUE THREAD

**Issue by ghiscoding** [thymikee/jest-preset-angular#81]
I'm trying to get Angular test working with Jest with your nice plugin, however I have some issues with a an Angular component (which I created and is called [angular-slickgrid](https://github.com/ghiscoding/Angular-Slickgrid), though it doesn't have any tests in it) which uses 3rd party javascript libraries called `SlickGrid` which creates a `Slick` object with the help of jquery extends, and it throws the following error in Jest:
```bash
AppComponent & RouterTestingModule › should navigate to "Grid Basic" immediately
Uncaught (in promise): ReferenceError: Slick is not defined
    ReferenceError: Slick is not defined

at new AngularSlickgridComponent (node_modules/angular-slickgrid/src/components/angular-slickgrid.component.ts:42:18)
      at createClass (node_modules/@angular/core/bundles/core.umd.js:10978:26)
```

In the Angular Component, I had to declare that variable as `any` in TypeScript with this line of code:
```javascript
declare var Slick: any;
```

In relation to my issue, I also read a big portion of issues #64 and #66, which made me change my `package.json` with the following (to ignore `angular-validation`):
```json
"jest": {
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts",
    "transformIgnorePatterns": [
      "node_modules/(?!@ngrx|angular-slickgrid)"
    ]
  }
```
I also added `"allowJs": true` to `"compilerOptions"` of `src/tsconfig.spec.ts` 

So I assume the questions is mainly, how do we deal with `declare var x: any;` which are declared in 3rd party component without influencing current App component test? My application in itself is working without any errors, I'm just trying to add tests to it.

I also found this SO question: [Test component with “declare var”](https://stackoverflow.com/questions/41099179/test-component-with-declare-var), but it's related to Karma, so I doubt it would fixes my issue with Jest.

*Note:* I'm new to almost everything... new to Angular 4 (coming from AngularJS), ng4 unit testing and Jest as well. However I'm really interested in Jest.

**Comment by thymikee** [comment]
Can't you just redeclare the variable in test? I'm not an expert in TypeScript unfortunately and I'm not working on any TS project currently, so I'm afraid I won't be helpful here. Maybe someone from the community will help :)

**Comment by ghiscoding** [comment]
I tried that already and unfortunately it doesn't help. I added the declare in both the `jestGlobalMocks.ts` and in the test too and keeps throwing the same error. So I'm kinda stuck and I can't run any tests because my page call this external 3rd party component.

I tried this in the file `jestGlobalMocks.ts` too, but that doesn't help, it's actually making it fail faster
```javascript
declare var Slick: any;
Object.defineProperty(window, 'Slick', {value: Slick});
```

**Comment by thekip** [comment]
```typescript
declare var Slick: any;
```
Means nothing for your test and Jest. This is just type declaration. In your case your `Slick` module just not exists in tests environment. 

How it's connected to your app? Does it connect with <script> tag, or Webpack provide plugin, or something else? 

Anyway you should do something like (depends on how this `Slick` package is distributed):

```typescript
import * as Slick from 'Slick';
(window as any).Slick = Slick;
```

**Comment by thymikee** [comment]
Thanks @thekip

**Comment by ghiscoding** [comment]
Thanks @thekip but I still don't think this would work in my situation since it's a legacy jquery library which doesn't have anything exported. 

> How it's connected to your app?

For that question, I followed indication of how to use a legacy app with Angular 4 from an [SO question](https://stackoverflow.com/questions/46008515/how-to-use-slickgrid-jquery-legacy-library-in-angular-4). Basically, the legacy library is loaded through the `scripts: [ slickgrid.js ]` section in `.angular-cli.json` which then make the `Slick` object a global javascript variable and then I can use the `declare var Slick: any;` to make TypeScript happy. 

The main thing I would like to do is to simply bypass (unmock) Jest for that library that I created but even then, I tried with `unmock` and `dontmock` and the error still shows up and still comes from my Angular library `angular-slickgrid`. This is what I tried
```javascript
jest.unmock('angular-slickgrid/angular-slickgrid');
// or with 
jest.dontMock('angular-slickgrid/angular-slickgrid');
```
On the other hand, the test goes through with `Jasmine`, so I might forget completely about `Jest`, which is just too bad since it's much faster and easier to work with.

**Comment by thekip** [comment]
Well, It's not about Angular neither Typescript or this project itself. This issue about how to connect legacy library which augment window, and doesn't export anything to CommonJs environment (which is Jest is actually is). 

So, I've reviewed code of `Slick` library, and found next lines: 

```js
(function ($) {
  // register namespace
  $.extend(true, window, {
    "Slick": {
      "Event": Event,
      "EventData": EventData,
      "EventHandler": EventHandler,
```

It means this library tries to augment Window inside its entry point (file referenced as main in `package.json`).
 So solution for you probably will be something like: 

// setup-jest.ts
```ts
import * as jQuery from 'jquery';
(global as any).$ = (global as any).jQuery = jQuery;

require('Slick'); //we can't use ES imports here, because we need assign jquery before
```

P.S.
And don't forget to write typing definitions for methods which you actually use, instead of ugly hack with `declare var Slick: any;` which disables all benefits of typescript.

// custom-typings/slick.d.ts
```typescript
declare namespace Slick {
  interface Column {
    // todo
  }
  
  interface Options {
    // todo
  }
  
  class Grid {
    constructor(selector: string | JQuery, data: any[], columns: Column[], options: Options);
  }
}

```
