### ISSUE TITLE
Angular hybrid app fails

### ISSUE THREAD

**Issue by JacobSchwartzSoerensen** [thymikee/jest-preset-angular#82]
When i try to test a hybrid app (angular and angularjs), every component with the following lines needed for working with angular js fails:
`angular.module('ModuleName')
  .directive(
  'ComponentName',
  downgradeComponent({ component: ComponentNameComponent, inputs: [], outputs: [] }) as angular.IDirectiveFactory
  );`

I get the following error
 ```
FAIL  src\app\ComponentName\ComponentName.component.spec.ts

  ● Test suite failed to run

    ReferenceError: angular is not defined

      at Object.<anonymous> (src/app/ComponentName/ComponentName.component.ts:64:1)
      at Object.<anonymous> (src/app/ComponentName/ComponentName.component.spec.ts:3:1)
      at next (native)
      at next (native)
```

I have installed @types/angular and desclared angular before the failing code like this:
`declare var angular: angular.IAngularStatic;`

**Comment by thymikee** [comment]
Looks like you need to include AngularJS in tests global scope (look here for example https://engineering.talentpair.com/running-angularjs-tests-with-jest-49d0cc9c6d26)

**Comment by JacobSchwartzSoerensen** [comment]
Thanks, I got it working by following the guide you send me, adding the following to my `setupTestFrameworkScriptFile`
```
const angular = require("angular");
Object.defineProperty(window, "angular", { value: angular });
```
And making sure that I got the `angular` package installed through node, instead of just the `@types/angular` package.

**Comment by teacherpan** [comment]
> Thanks, I got it working by following the guide you send me, adding the following to my `setupTestFrameworkScriptFile`
> 
> ```
> const angular = require("angular");
> Object.defineProperty(window, "angular", { value: angular });
> ```
> 
> And making sure that I got the `angular` package installed through node, instead of just the `@types/angular` package.

resolved.
thanks!
