### ISSUE TITLE
Tests fail to run if there is an Input with type `CustomType | null`

### ISSUE THREAD

**Issue by YuliaTsareva** [thymikee/jest-preset-angular#87]
Tests fail to run with an error
>  ReferenceError: size_1 is not defined

if there is an Input with type `Size | null` in a component under test:
```
import {Component, Input, OnInit} from '@angular/core';
import {Size} from './size';

@Component({
  selector: 'app-simple',
  templateUrl: 'simple.component.html',
  styleUrls: ['./simple.component.css']
})
export class SimpleComponent {
  @Input() size: Size | null = null;
}
```
where `Size` is
```
export type Size = 'normal' | 'small';
```

Message `size_1` depends on file name. If I rename file with `Size`, message changes accordingly.

I've prepared a small reproduction repo, run tests in example folder: https://github.com/YuliaTsareva/jest-preset-angular/tree/nullable-input-error

Also, it can be important that the error disappears if
* I remove Input decorator
* or move `Size` type to the component file
* or remove `| null` from declaration.

**Comment by YuliaTsareva** [comment]
I've investigated this issue and suppose it could be closed.

It turns out that the bug is not related to **jest-preset-angular** but to TypeScript itself (or probably also to **ts-jest**).

If there is no `size` initialization (`@Input() size: Size`), then transpiled version of `SimpleComponent` looks like
```
...
var core_1 = require("@angular/core");
var size_1 = require("./size");
...
```

Meanwhile if there is an initialization `size: Size | null = null`, then line `var size_1 = require("./size");` is absent. But `size_1` is used in metadata:
```
...
__metadata("design:type", typeof (_a = typeof size_1.Size !== "undefined" && size_1.Size) === "function" && _a || Object)],
...
```
And it causes that weird error
> ReferenceError: size_1 is not defined

I see two ways to solve it
* upgrade to a newer version of TypeScript (it works for me with `typescript@2.4.2`)
* or set `"emitDecoratorMetadata": false` in tsconfig.json provided to jest.

**Comment by thymikee** [comment]
Thank you for getting back with this knowledge 🙂
