### ISSUE TITLE
ng-version appears in snapshots

### ISSUE THREAD

**Issue by samgregory88** [thymikee/jest-preset-angular#89]
This is a regression from a previous fix #27

**Comment by thymikee** [comment]
Let's move conversation from #27 here.

>Ok i see the difference, i was using fixture.debugElement.nativeElement instead of just fixture. Is this expected if you use the nativeElement?

I've only tested this for `fixture`, so other use-cases are not supported. If you have ideas/suggestions on how to make Angular components snapshotting more reliable, I'm open to changes and would use some help too (sadly, I'm not currently involved in any Angular project).

**Comment by sharikovvladislav** [comment]
Hey,

fyi https://github.com/angular/angular/issues/17474#issuecomment-342801285

@thymikee do you think it is possible to remove nghost/ng-reflect/ngcontent html properties from the output? Final output will be more human-readable. 

I am thinking of doing this by special helpers (easy: just parse string and remove some stuff from it). Don't you think it should be included to some library? Like Angular schema or toMatchSnapshot matcher of your lib? I can help with PR if you are ok.

PS: note it will be breaking change.

**Comment by thymikee** [comment]
Yea, changes to snapshots are always breaking, meh :p. 

So basically we should hook into the same entities as [DOMElement plugin](https://github.com/facebook/jest/blob/master/packages/pretty-format/src/plugins/dom_element.js) with another plugin/serializer and just remove the unnecessary keys, I think that should work.

**Comment by sharikovvladislav** [comment]
Oh, `toMatchSnapshot` is not yours. Its from Jest. True. My bad.

Hm. So it is possible to add to Jest (or create it) some plugin and put it something to the middle of that pipe which jest uses to create snapshots.

**Comment by sharikovvladislav** [comment]
So something like this: https://github.com/negativetwelve/jest-plugins/tree/master/packages/jest-plugin-it-shallow-renders

I just import some helper function and use it on fixture?

**Comment by thymikee** [comment]
Oh, you could do it, but it's going to be cumbersome, no? 
What I propose is to introduce another, internal, serializer which will strip the unnecessary properties for you, just before running the main AngularSnapshotSerializer.

**Comment by sharikovvladislav** [comment]
So do you just suggest me to fix my current jestSetup to: 

```
import serializer from 'my-serializer-module';
expect.addSnapshotSerializer(serializer);

import 'jest-preset-angular';

import './globalJestMocks';
```

Like [Jest docs](https://facebook.github.io/jest/docs/en/expect.html#expectaddsnapshotserializerserializer) says?

**Comment by thymikee** [comment]
Sure, you can do it, but I'd like to have it in this repo too. Unfortunately I don't have much time for this project lately :(

**Comment by sharikovvladislav** [comment]
So you think it is good idea to do this in your library?

Do you mind increasing major version of your library for this? It is breaking change. Or it should be hiddebt behind option which is turned off by default.

I can do it by myself, test it in my project and after this I can add it to your lib. Its ok.

**Comment by thymikee** [comment]
Sooner or later we'll update to Jest 22, so we're going to have a major bump anyway. Would be cool you can test it yourself and contribute back :)

**Comment by sharikovvladislav** [comment]
I am trying to help there somehow...

How to you detect if DOM node is an Angular component? 

Looks like you use this:
```
const test = val =>
  val !== undefined &&
  val !== null &&
  typeof val === 'object' &&
  Object.prototype.hasOwnProperty.call(val, 'componentRef');
```

Is anything in this code (below) is an angular component?:

```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-snap-test',
  template: `
    <div class="kek">
      diary works!
      <div *ngIf="someVar" class="inner-class">
        <div *ngIf="anotherVar" class="inner-hidden"></div>
        <div>another case</div>
      </div>
      <div>one more case case</div>
      <div><app-kek-component kek="someVar"></app-kek-component></div>
    </div>
  `,
  styles: [
    `.kek { color: red }`
  ]
})
export class SnapTestComponent implements OnInit {
  someVar = true;
  anotherVar = false;

  constructor() {}

  ngOnInit() {}
}
```

Actually, I just wanted to use your test fn in my serializer (because it should just take same elements if I understand correctly). I tested it and it returns false for any dom node. Actually, I made a proxy to see the inputs and outputs of your function.

Whats the problem? Why I can't get true from your test fn. Will my component be serialized by some internal jest serializers or your Angular serializer will influence the snapshot?

**Comment by sharikovvladislav** [comment]
I wrote some code... 

I had this:
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`SnapTestComponent snapshot test 1`] = `
<app-snap-test
  anotherVar="false"
  someVar={[Function Boolean]}
>
  <div
    _ngcontent-c2=""
    class="kek"
  >
    diary works!
    <div
      _ngcontent-c2=""
      class="inner-class"
    >
      <div
        _ngcontent-c2=""
      >
        another case
      </div>
    </div>
    <div
      _ngcontent-c2=""
    >
      one more case case
    </div>
    <div
      _ngcontent-c2=""
    >
      <app-kek-component
        _ngcontent-c2=""
        kek="someVar"
        _nghost-c3=""
        ng-reflect-kek="someVar"
      >
        <div
          _ngcontent-c3=""
          class="kek"
        >
          someVar
        </div>
      </app-kek-component>
    </div>
  </div>
</app-snap-test>
`;
```

And now I have this:

```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`SnapTestComponent snapshot test 1`] = `
<app-snap-test
  anotherVar="false"
  someVar={[Function Boolean]}
>
  <div
    class="kek"
  >
    diary works!
    <div
      class="inner-class"
    >
      <div
      >
        another case
      </div>
    </div>
    <div
    >
      one more case case
    </div>
    <div
    >
      <app-kek-component
        kek="someVar"
      >
        <div
          class="kek"
        >
          someVar
        </div>
      </app-kek-component>
    </div>
  </div>
</app-snap-test>
`;
```

**Comment by sharikovvladislav** [comment]
It's really awful at the moment. Now I just proxy methods of main angular and modify the output of your print function. It works. I think I will make this easy foo and I will wrote tests for it for different cases. And after I will refactor it if needed (and anybody will be able to do this).

**Comment by ahnpnl** [comment]
7.1.1 now has a serializers to strip out necessary things from snapshot. Please try it out and report if there are any issues so we can improve the serializers.
