### ISSUE TITLE
Test fail after running ngcc

### ISSUE THREAD

**Issue by chrsi** [thymikee/jest-preset-angular#899]
## 🐛 Bug Report

Hi, I'm not quite sure if this is the right place for the bug report. But since we're using jest and you're currently working on making it ivy compatible, all signs led me to this repository. I prepared a sample repo for this issue.

Installing all packages and executing `npm test` lets the test inside this repository pass.
But once someone is calling ngcc (without any param) the tests fail. The reason for the failing test is that the dependency (ngx-permissions) is undefined, although it has been mocked previously.

The issue came up, because the _angular language service extension_ of vscode automatically calls ngcc (without any param) breaking all our tests once vscode gets (re)opened. To fix it, we always had to reinstall all packages (npm ci) and the tests work until the next time vscode is started.

Somehow i found out that the parameterless ngcc is the reason for making our tests fail. When running the recommended ngcc command (eg. inside the postinstall hook) everything works fine.
`ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`

But i didn't just want to add a postinstall hook without knowing why it's even required. Especially since some other team members are using a different editor where the parameterless ngcc command isn't called initially.

This made me think, how the tests could pass without compiling the libraries, but fail once they get compiled with the parameterless `ngcc` operation. Do you have any explaination for that? Is this an issue with properly setting up the mock or the jest environment?

## To Reproduce

* Checkout my [repository](https://github.com/chrsi/angular-jest-bug)
* npm ci
* npm test (test should succeed)
* npm run ngcc (will run the parameterless ngcc command)
* npm test (test will now fail due to an unknown dependency)

The only way to recover from this is to reinstall the entire node_modules folder.

## Link to repo (highly encouraged)

On Github @ [chrsi/angular-jest-bug](https://github.com/chrsi/angular-jest-bug)

## Error log:

```
  FAIL  src/app/app.component.spec.ts
  AppComponent
    × incrementsCounter_whenClicked (741 ms)

  ● AppComponent › incrementsCounter_whenClicked

    TypeError: Cannot read property 'hasPermission' of undefined

      22 |     permissionService = TestBed.inject(NgxPermissionsService);
      23 |
    > 24 |     mocked(permissionService).hasPermission.mockReturnValue(
         |                              ^
      25 |       Promise.resolve(true)
      26 |     );
      27 |   });

      at src/app/app.component.spec.ts:24:30
      at fulfilled (src/app/app.component.spec.ts:5:58)

```

## envinfo

```
System:
    OS: Windows 10 (19042.867)

Npm packages:
    jest: ~26.6.3
    jest-preset-angular: ~8.3.2
    typescript: ~4.1.2
```

**Comment by ahnpnl** [comment]
Parameterless ngcc is actually wrong to use with Jest because Jest needs `umd` bundle while `ngcc --properties es2015 browser module main` will produce `umd` bundle.

Would you please try with `next` tag? We also have documentation for `next` tag so you should try it out as `next` tag is stable now and it works the same like Angular CLI Karma + Jasmine.

**Comment by ahnpnl** [comment]
ok the issue is because of your code
```
jest.mock('ngx-permissions');
```

If you don't specify implementation for this mock, by default it will return undefined for anything that you import from `ngx-permissions`. The behavior after running `ngcc --properties es2015 browser module main` is correct. 

To fix this issue, there are 2 ways:
- Provide factory for `jest.mock`
- Or define a stub value for dependencies

I'd do something like this
```
beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [AppComponent],
      providers: [{
        provide: NgxPermissionsService,
        useValue: {
          hasPermission: jest.fn(),  <===== since you want to mock `hasPermission`, simply define it here
        },
      }],
    }).compileComponents();

    fixture = TestBed.createComponent(AppComponent);

    permissionService = TestBed.inject(NgxPermissionsService);

    mocked(permissionService).hasPermission.mockReturnValue(
      Promise.resolve(true)
    );
  });
```

**Comment by chrsi** [comment]
Aah does this have to do with the experimental support for ESM in Jest? (see this [Open Issue in the Jest Repo](https://github.com/facebook/jest/issues/10025))
Thank you very much for you time ... this definitly helped me a lot!

**Comment by ahnpnl** [comment]
Could be related, I'm not certain but reading that Jest issue, it seems to be.

**Comment by guilhermetod** [comment]
@ahnpnl I'm facing this issue and I'm not sure if the given answer describe the exact reason for this. Jest doesn't actually return undefined for everything you import.
In fact, it creates a mocked version of everything from that module and imo, this is one of the most powerful features from Jest.

I cloned the provided repo and added `console.log(NgxPermissionService)` before any test was run.

When I run `npm test` without `ngcc` or with `ngcc-recommendned`, I get this result, with tests successfully running:

```
    [Function: NgxPermissionsService] {
      _isMockFunction: true,
      getMockImplementation: [Function (anonymous)],
      mock: [Getter/Setter],
      mockClear: [Function (anonymous)],
      mockReset: [Function (anonymous)],
      mockRestore: [Function (anonymous)],
      mockReturnValueOnce: [Function (anonymous)],
      mockResolvedValueOnce: [Function (anonymous)],
      mockRejectedValueOnce: [Function (anonymous)],
      mockReturnValue: [Function (anonymous)],
      mockResolvedValue: [Function (anonymous)],
      mockRejectedValue: [Function (anonymous)],
      mockImplementationOnce: [Function (anonymous)],
      mockImplementation: [Function (anonymous)],
      mockReturnThis: [Function (anonymous)],
      mockName: [Function (anonymous)],
      getMockName: [Function (anonymous)],
      decorators: [],
      ctorParameters: [Function: mockConstructor] {
        _isMockFunction: true,
        getMockImplementation: [Function (anonymous)],
        mock: [Getter/Setter],
        mockClear: [Function (anonymous)],
        mockReset: [Function (anonymous)],
        mockRestore: [Function (anonymous)],
        mockReturnValueOnce: [Function (anonymous)],
        mockResolvedValueOnce: [Function (anonymous)],
        mockRejectedValueOnce: [Function (anonymous)],
        mockReturnValue: [Function (anonymous)],
        mockResolvedValue: [Function (anonymous)],
        mockRejectedValue: [Function (anonymous)],
        mockImplementationOnce: [Function (anonymous)],
        mockImplementation: [Function (anonymous)],
        mockReturnThis: [Function (anonymous)],
        mockName: [Function (anonymous)],
        getMockName: [Function (anonymous)]
      }
    }
```

However, after running `ngcc`, the tests breaks and the result is the following:

```
    <ref *1> [Function: NgxPermissionsService] {
      _isMockFunction: true,
      getMockImplementation: [Function (anonymous)],
      mock: [Getter/Setter],
      mockClear: [Function (anonymous)],
      mockReset: [Function (anonymous)],
      mockRestore: [Function (anonymous)],
      mockReturnValueOnce: [Function (anonymous)],
      mockResolvedValueOnce: [Function (anonymous)],
      mockRejectedValueOnce: [Function (anonymous)],
      mockReturnValue: [Function (anonymous)],
      mockResolvedValue: [Function (anonymous)],
      mockRejectedValue: [Function (anonymous)],
      mockImplementationOnce: [Function (anonymous)],
      mockImplementation: [Function (anonymous)],
      mockReturnThis: [Function (anonymous)],
      mockName: [Function (anonymous)],
      getMockName: [Function (anonymous)],
      'ɵfac': [Function: NgxPermissionsService$Factory] {
        _isMockFunction: true,
        getMockImplementation: [Function (anonymous)],
        mock: [Getter/Setter],
        mockClear: [Function (anonymous)],
        mockReset: [Function (anonymous)],
        mockRestore: [Function (anonymous)],
        mockReturnValueOnce: [Function (anonymous)],
        mockResolvedValueOnce: [Function (anonymous)],
        mockRejectedValueOnce: [Function (anonymous)],
        mockReturnValue: [Function (anonymous)],
        mockResolvedValue: [Function (anonymous)],
        mockRejectedValue: [Function (anonymous)],
        mockImplementationOnce: [Function (anonymous)],
        mockImplementation: [Function (anonymous)],
        mockReturnThis: [Function (anonymous)],
        mockName: [Function (anonymous)],
        getMockName: [Function (anonymous)]
      },
      'ɵprov': {
        providedIn: null,
        factory: [Function: factory] {
          _isMockFunction: true,
          getMockImplementation: [Function (anonymous)],
          mock: [Getter/Setter],
          mockClear: [Function (anonymous)],
          mockReset: [Function (anonymous)],
          mockRestore: [Function (anonymous)],
          mockReturnValueOnce: [Function (anonymous)],
          mockResolvedValueOnce: [Function (anonymous)],
          mockRejectedValueOnce: [Function (anonymous)],
          mockReturnValue: [Function (anonymous)],
          mockResolvedValue: [Function (anonymous)],
          mockRejectedValue: [Function (anonymous)],
          mockImplementationOnce: [Function (anonymous)],
          mockImplementation: [Function (anonymous)],
          mockReturnThis: [Function (anonymous)],
          mockName: [Function (anonymous)],
          getMockName: [Function (anonymous)]
        },
        value: undefined,
        token: [Circular *1]
      },
      decorators: [],
      ctorParameters: [Function: mockConstructor] {
        _isMockFunction: true,
        getMockImplementation: [Function (anonymous)],
        mock: [Getter/Setter],
        mockClear: [Function (anonymous)],
        mockReset: [Function (anonymous)],
        mockRestore: [Function (anonymous)],
        mockReturnValueOnce: [Function (anonymous)],
        mockResolvedValueOnce: [Function (anonymous)],
        mockRejectedValueOnce: [Function (anonymous)],
        mockReturnValue: [Function (anonymous)],
        mockResolvedValue: [Function (anonymous)],
        mockRejectedValue: [Function (anonymous)],
        mockImplementationOnce: [Function (anonymous)],
        mockImplementation: [Function (anonymous)],
        mockReturnThis: [Function (anonymous)],
        mockName: [Function (anonymous)],
        getMockName: [Function (anonymous)]
      }
    }
```

Note the additional `ɵprov` and `ɵfac` properties from the previous result. If i run `delete NgxPermissionsService.ɵprov; delete NgxPermissionsService.ɵfac` before the TestBed setup, the tests works again, with the mocks being created as expected.

However, I'm not aware of how `ɵprov` and `ɵfac` effectively work and how they affect the DI to track down whether this is an issue with Jest mocking or with Angular. However, [since this library suggests `ngcc` before running tests for Ivi](https://thymikee.github.io/jest-preset-angular/docs/11.0/guides/angular-ivy/), I wonder if there is anything that could be done to avoid the mocking mess here, users should be aware that `jest.mock` will be kinda of useless.

**Comment by ahnpnl** [comment]
Interesting finding but unfortunately this is out of scope of what this repository can do. It looks to me like something between jest mock and Angular libraries which we don’t have any ways to modify that internal stuff.

**Comment by ahnpnl** [comment]
It might be also related to #1199 which is caused by transformation process from ts to js. It’s good to keep this in mind as a test case if any solutions found for it.
