### ISSUE TITLE
Speed up tests with setupTestBed

### ISSUE THREAD

**Issue by tb** [thymikee/jest-preset-angular#91]
In https://github.com/angular/angular/issues/12409#issuecomment-335819530 there is method to speed up tests. I can see it works with defining the method in inside single test like:

```
/// ...
import { TestBed, async, TestModuleMetadata } from '@angular/core/testing';

const resetTestingModule = TestBed.resetTestingModule,
  preventAngularFromResetting = () => TestBed.resetTestingModule = () => TestBed;
let allowAngularToReset = () => TestBed.resetTestingModule = resetTestingModule;

export const setupTestBed = (moduleDef: TestModuleMetadata) => {
  beforeAll(done => (async () => {
    resetTestingModule();
    preventAngularFromResetting();
    TestBed.configureTestingModule(moduleDef);
    await TestBed.compileComponents();

    // prevent Angular from resetting testing module
    TestBed.resetTestingModule = () => TestBed;
  })().then(done).catch(done.fail));

  afterAll(() => allowAngularToReset());
};

describe('Some Component', () => {
  setupTestBed({
    imports: [
      TestModule,
    ],
    declarations: [
      SomeComponent,
    ]
  });

  beforeEach(() => {
  /// ...
  fixture = TestBed.createComponent(SomeComponent);
  /// ...
```
 
The problem is when I import that method with:

```import {setupTestBed} from '../../../specs/setupTestBed';```
or try to set it in jest config `setupFiles` it breaks.

I suspect it would work if it was defined in https://github.com/thymikee/jest-preset-angular/blob/master/testEnvironment.js#L20

How can I get it working? Speed benefits are huge.

**Comment by tb** [comment]
@thymikee Yes, your are right it works fine when I `import './setupTestBed';` in `jest.setup.ts` that is loaded via `setupTestFrameworkScript`. Tests are now few times faster.

The down side is described i.e. in https://github.com/angular/angular/issues/12409#issuecomment-335819530

**Comment by thymikee** [comment]
How about mentioning this info alongside tradeoffs to readme or wiki? Would you be interested in such contribution? 🙂

**Comment by tb** [comment]
Ok, I will do so ;-)
