### ISSUE TITLE
performance, ts-jest & swc-jest

### ISSUE THREAD

**Issue by sod** [thymikee/jest-preset-angular#918]
The changelog mentions performance, but not swc. You should really try it.

`npm install @swc-node/jest`

jest config:
```js
transform: {
    '\\.ts$': [
        require.resolve('@swc-node/jest'),
        {
            target: 'es2018',
            module: 'commonjs',
            experimentalDecorators: true,
            emitDecoratorMetadata: true,
            dynamicImport: true,
            sourcemap: true,
        },
    ],
}
```

`@swc-node/jest` is a drop-in replacement for ts-jest, but the compiler is written in rust. [@swc-node/jest](https://yarnpkg.com/package/@swc-node/jest) is so fast, pretty much only running the tests is left, no cache required. Our suite went down from 50s to 11s, cold cache. Which is super nice for CI. Or developing tests and run them isolated from within your IDE, as recompilation is perceived as instant.

I see that you start to integrate with the angular compiler, so this switch may not be possible anymore. swc-jest forces you to run angular in JIT as there is no way to integrate angular compiler stuff into rust. Feel free to close the issue.

**Comment by ahnpnl** [comment]
Actually we only use Angular AST transformers. If switching to `swc`, it is required to rewrite those AST transformers to be compatible with `swc` in additional of adopting `swc` APIs.

The most work is probably only about rewriting those transformers unless there is a tool to convert TypeScript AST to swc AST.

**Comment by sod** [comment]
I like if jest-preset-angular is the most compatible one-stop-shop for angular unit tests. Using `@swc-node/jest` narrows the usecase as it's a native typescript to javascript compiler blackbox (you can't tap into the AST from javascript).

**Comment by ahnpnl** [comment]
Currently `jest-preset-angular` is likely identical to Angular Karma + Jasmine, except CSS testing is limited due to JSDOM limitation with `sass/scss`.
