### ISSUE TITLE
Using ng5 new locale feature

### ISSUE THREAD

**Issue by marcojahn** [thymikee/jest-preset-angular#92]
I've tried to setup Angular5s new locale System to have these features within my tests.

What I have done is (setupJest.ts)
``` JavaScript
import { registerLocaleData } from '@angular/common';
import localeDe from '@angular/common/locales/de';

import 'jest-preset-angular';

registerLocaleData(localeDe);
```

But got the following errors
```
 FAIL  src/app/foo/bar.component.spec.ts
  ● Test suite failed to run

    /Users/Projects/.../node_modules/@angular/common/locales/de.js:10
    export default [
    ^^^^^^
    
    SyntaxError: Unexpected token export
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (src/setupJest.ts:4:12)
          at Generator.next (<anonymous>)
```

Any recommendations on how to set it up ?

**Comment by thymikee** [comment]
Update you Jest config to transform `@angular/common` code:
```json
{
  "transformIgnorePatterns": [
    "node_modules/(?!@ngrx|@angular/common)"
  ]
}
```
`@ngrx` here is just an example of another module which needs transforming (Jest doesn't transform code inside node_modules by default, that's why you need to tell it to do otherwise if some modules, like `@angular/common` are published as untranspiled TypeScript).
You'll find more information in [React Native setup tutorial](http://facebook.github.io/jest/docs/en/tutorial-react-native.html#transformignorepatterns-customization) if you're curious why you need this.

**Comment by marcojahn** [comment]
Hi,

just tried a few different combinations in my package.json, but none of them is working.
```
"transformIgnorePatterns": [
      "node_modules/(?!(@angular/common)/)"
    ],

"transformIgnorePatterns": [
      "node_modules/(?!@ngrx|@angular/common)"
    ],
```

But the error still remains. Found a comment [in the JEST issue tracker](https://github.com/facebook/jest/issues/3285#issuecomment-303417599) describing that scoped packages could be a problem.

**Comment by thymikee** [comment]
It's rather unlikely it has anything to do with scoped packages (you can see it works for `@ngrx`. Can you just try ignore whole `@angular`?
```json
{
  "transformIgnorePatterns": [
    "node_modules/(?!@angular)"
  ]
}
```

**Comment by thymikee** [comment]
And run jest with `--no-cache` flag.

**Comment by marcojahn** [comment]
still the same error, here is my full jest configuration in package.json

```
"jest": {
    "moduleFileExtensions": [
      "js",
      "jsx",
      "json",
      "ts",
      "tsx",
      "tsx",
      "html"
    ],
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts",
    "transformIgnorePatterns": [
      "node_modules/(?!@angular)"
    ],
    "coverageReporters": [
      "html",
      "json",
      "lcov",
      "text"
    ],
    "coverageDirectory": "coverage",
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "jestGlobalMocks.ts",
      "setupJest.ts",
      "html",
      "kitchensink",
      "db.json"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 60,
        "functions": 80,
        "lines": 90,
        "statements": 90
      }
    }
  },
```

**Comment by marcojahn** [comment]
Got it temporary working transpiling the file `/node_modules/@angular/common/locales/de.js` by myself and that is working.

**Comment by thymikee** [comment]
You can also try clearing the cache: https://github.com/facebook/jest/issues/3705#issuecomment-312199902 and see if that helps

**Comment by marcojahn** [comment]
clearing cache does not help anyway...

Transpiling by myself is atm the only way to get the translation working in the tests...

**Comment by Brototype** [comment]
I have the same problems - even if I transpile manually as @marcojahn said 2 tests are still failing :(

**Comment by thymikee** [comment]
I wonder if we should add this by default – compiling JS files with Babel instead of TS?

**Comment by shusson** [comment]
@thymikee can we reopen this issue? I just encountered it and none of the suggested solutions work for me.

**Comment by shusson** [comment]
Actually Brototype's solution with babel works for me

**Comment by AhnpGit** [comment]
I think his solution is similar to README as well. So I think we don't need to modify README for this situation 😀
