### ISSUE TITLE
Can't resolve all parameters for DemoDirective: (?). (ElementRef)

### ISSUE THREAD

**Issue by infacto** [thymikee/jest-preset-angular#921]
Here is a demo from the code of [this docs page](https://angular.io/guide/testing-attribute-directives):

**demo-test/demo.directive.ts**

```ts
import { Directive, ElementRef, Input, OnChanges } from '@angular/core';

@Directive({ selector: '[highlight]' })
export class DemoDirective implements OnChanges {
  public defaultColor = 'rgb(211, 211, 211)';

  @Input('highlight') public bgColor: string;

  constructor(private el: ElementRef) {
    el.nativeElement.style.customProperty = true;
  }

  public ngOnChanges(): void {
    this.el.nativeElement.style.backgroundColor = this.bgColor || this.defaultColor;
  }
}
```

**demo-test/demo.module.ts**

```ts
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { IonicModule } from '@ionic/angular';
import { DemoDirective } from './demo.directive';

@NgModule({
  imports: [CommonModule, IonicModule],
  declarations: [DemoDirective],
  exports: [DemoDirective],
})
export class DemoModule {}
```

**demo-test/demo.directive.spec.ts**

```ts
import { Component, DebugElement } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { DemoDirective } from './demo.directive';

@Component({
  template: `<h2 highlight="yellow">Something Yellow</h2>
    <h2 highlight>The Default (Gray)</h2>
    <h2>No Highlight</h2>
    <input #box [highlight]="box.value" value="cyan" />`,
})
class TestComponent {}

let fixture: ComponentFixture<TestComponent>;
let des: DebugElement[];
let bareH2: DebugElement;

beforeEach(() => {
  fixture = TestBed.configureTestingModule({
    declarations: [DemoDirective, TestComponent],
  }).createComponent(TestComponent);

  fixture.detectChanges();

  des = fixture.debugElement.queryAll(By.directive(DemoDirective));
  bareH2 = fixture.debugElement.query(By.css('h2:not([highlight])'));
});

it('should have three highlighted elements', () => {
  expect(des.length).toBe(3);
});
```

This results in: 

> Can't resolve all parameters for DemoDirective: (?).

The `?` means the `ElementRef` which does not resolved / injected in the unit tests.

I tested it in a fresh new Angular project with karma/jasmine and cannot reproduce it. It works. But in my prod project with jest-preset-angular it does not work.

Some more infos about the config:

```text
jest-preset-angular: 8.4.0
jest: 26.6.3
@angular/*: 11.0.2
typescript: 4.0.5 
```

**jest.config.js**

```ts
const esModules = ['@ionic', '@ionic-native'].join('|');

module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['./jest.setup.ts'],
  transformIgnorePatterns: [`<rootDir>/node_modules/(?!${esModules})`],
  moduleDirectories: ['node_modules']
};
```

**jest.setup.ts**

```ts
import 'jest-preset-angular/setup-jest';
```

**Comment by ahnpnl** [comment]
You can follow our example apps which provides the basic setup https://github.com/thymikee/jest-preset-angular/tree/master/examples

In your case, I believe Jest doesn't find `umd` files in `node_modules` which results in that error

**Comment by infacto** [comment]
Thanks. But when I use ngcc in jest.config I get some errors:

```js
require('jest-preset-angular/ngcc-jest-processor');
```

> ngcc-jest-processor: running ngcc
> Error: Unable to process any formats for the following entry-points (tried es2015, main): 
> ./node_modules/@ionic-native/core
> and so on...

**Comment by ahnpnl** [comment]
that error looks like `ngcc` error itself. The util script we actually invoke `ngcc` from `@angular/compiler-cli`.

**Comment by infacto** [comment]
I just updated jest and jest-preset-angular to the next version and it works. (incl. ngcc in jest.config).

```text
    "jest": "^27.0.0-next.9",
    "jest-preset-angular": "^9.0.0-next.14",
```

**Comment by infacto** [comment]
So I would close this issue because it already works in upcoming stable versions. Workaround: Use the beta (next) versions. Thanks. I wasted so much time for it. ❤️

**Comment by ahnpnl** [comment]
Not sure why updating to `next` tag worked. Maybe you still can use `latest` version but first remove `node_modules`, reinstall deps then run `ngcc` again.

**Comment by infacto** [comment]
Sorry it works without `ngcc` in jest.config. But the `ElementRef` error is gone after installed the `next` versions. 
But now I get errors about `spyOn` does not exist. And `@types/jest` is not up to date. *sigh* 
With the `latest` version `spyOn` works but `ElementRef` does not. But I guess I should check out the breaking changes for the `next` versions and adapt or replace `spyOn`.

I also removed `node_modules` and tested with the latest versions. It definitely not work. With or without `ngcc`. With the next `jest` and `jest-preset-angular` versions it works. `ngcc` is not necessary in that case and will just throw the error `Unable to process any format bla bla` (see my post above). I'll check out the rest of the example app v11 repo. Maybe I need to adjust the tsconfig etc. But anyway, I see that the next versions works, but fails on spyOn. I think it's a breaking change.

**Comment by bboydflo** [comment]
> The `spyOn` function from Jest 26 does not exist in 27. It was a leftover from Jasmine mock. But fortunately it's easy to adapt.

@infacto Thanks for writing this! It was super useful :)
