### ISSUE TITLE
All component tests fail with `Unexpected token (1:0)` when using templateUrl

### ISSUE THREAD

**Issue by radfahrer** [thymikee/jest-preset-angular#93]
Seem to be a universal problem in a project I'm working to convert from karma to jest. I'm hoping it's something simple I'm missing.

**Comment by thymikee** [comment]
Please search this issue tracker and troubleshooting guide. I remember working around this problem

**Comment by 4kochi** [comment]
Make sure all you're templateUrl have an relative path

**Comment by radfahrer** [comment]
@4kochi yes my templateUrls are all relative paths.

**Comment by radfahrer** [comment]
@thymikee How did you work around this issue?

**Comment by radfahrer** [comment]
Looks like this is a duplicate of #74 but documentation could be updated to be more explicit, and save people time digging through closed issues.
