### ISSUE TITLE
missing export `build` from `package.json` in v9.0.0

### ISSUE THREAD

**Issue by NicolasTsc** [thymikee/jest-preset-angular#935]
Hi I just updated the jest-preset-angular version and now receive another error when trying to run example tests.
## 🐛 Bug Report

 File not found: jest-preset-angular/build/InlineFilesTransformer (resolved as: C:\Users\___\Documents\frontend\jest-preset-angular\build\InlineFilesTransformer)
## To Reproduce

Run ``ng test``
## Expected behavior

Tests should run 

## Link to repo (highly encouraged)
https://github.com/NicolasTsc/jest-angular

## Error log:

```

  ● Test suite failed to run

    File not found: jest-preset-angular/build/InlineFilesTransformer (resolved as: C:\Users\___\Documents\frontend\jest-preset-angular\build\InlineFilesTransformer)

      at ConfigSet.resolvePath (node_modules/ts-jest/dist/config/config-set.js:444:19)
      at node_modules/ts-jest/dist/config/config-set.js:225:46
          at Array.map (<anonymous>)
      at resolveTransformers (node_modules/ts-jest/dist/config/config-set.js:223:37)
      at ConfigSet._setupConfigSet (node_modules/ts-jest/dist/config/config-set.js:233:137)
      at new ConfigSet (node_modules/ts-jest/dist/config/config-set.js:142:14)
      at NgJestTransformer.TsJestTransformer._createConfigSet (node_modules/ts-jest/dist/ts-jest-transformer.js:111:16)
      at NgJestTransformer.TsJestTransformer._configsFor (node_modules/ts-jest/dist/ts-jest-transformer.js:89:34)
      at NgJestTransformer.TsJestTransformer.getCacheKey (node_modules/ts-jest/dist/ts-jest-transformer.js:172:28)
      at ScriptTransformer._getCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:280:41)


```
System:
    OS: Windows 10

Npm packages:
    jest: 27.0.1
    jest-preset-angular: 9.0.0
    typescript: 4.2.4
```

**Comment by NicolasTsc** [comment]
If I understand the changelog correctly I have to add snapshotSerializers by adding 
`` const jestPresetAngularSerializers = require('jest-preset-angular/build/serializers')``
at the top of the jest.config.js and inside the module.exports
`` snapshotSerializers: jestPresetAngularSerializers, ``.

When I try to run the test I receive the error
``An unhandled exception occurred: Package subpath './build/serializers' is not defined by "exports" in``

Is there anything I missed from the changelog?

**Comment by ahnpnl** [comment]
You can omit entirely `snapshotSerializers` and use only `preset: 'jest-preset-angular'`

**Comment by ahnpnl** [comment]
The error about `An unhandled exception occurred: Package subpath './build/serializers' is not defined by "exports" in` is a valid error because missing export for `build`.

**Comment by NicolasTsc** [comment]
Okay thanks for clarifying. The error occures when using the example config too.

**Comment by ahnpnl** [comment]
I see your jest config in your repo is already migrated correctly :)

**Comment by NicolasTsc** [comment]
Thanks for fixing it so quickly. How can I get the new changes?

**Comment by ahnpnl** [comment]
should be fixed now with 9.0.1

**Comment by ahnpnl** [comment]
that file doesn't exist anymore in v9.0.0 you need to remove it from your jest config. It is mentioned in `CHANGELOG`.

**Comment by NicolasTsc** [comment]
Yeah this file isn`t reference in my jest config. I tried clearing the cache and deleted / reinstalled my node_modules but the problem stays. You can check my repo for the jest-config. I also tried it with another repository but have the same error unfortunately

**Comment by ahnpnl** [comment]
The current version of `@angular-builder/jest` doesn't support v9.0.0 . Please follow this https://github.com/just-jeb/angular-builders/pull/913 

In summary, if you are using `@angular-builder/jest`, you cannot use Jest 27 and `jest-preset-angular` 9.0.0 :)

**Comment by NicolasTsc** [comment]
Do I need to use @angular-builder/jest? I need Jest 27 to import some modules I couldn`t import before.

**Comment by ahnpnl** [comment]
In your repo, if you replace `"test": "ng test" by "test": "jest"` to bypass `@angular-builder/jest`, it will work.

`@angular-builder/jest` is a way to execute `ng test`. It is not required.
