### ISSUE TITLE
Compatibility with AngularJS

### ISSUE THREAD

**Issue by cloakedninjas** [thymikee/jest-preset-angular#946]
## 💥 Regression Report

Tried upgrading

- `jest` 26 -> 27
- `jest-preset-angular` 8.4 -> 9

for a hybrid Angular/AngularJS app that was working before the upgrades were applied (also followed the list of breaking changes in Changelog & jest cache has been cleared)

## Config file

```
require('jest-preset-angular/ngcc-jest-processor');

module.exports = {
    preset: 'jest-preset-angular',
    globals: {
        'ts-jest': {
            tsconfig: '<rootDir>/my-app/tsconfig.spec.json',
            stringifyContentPathRegex: '\\.html$',
            astTransformers: [
                'jest-preset-angular/build/StripStylesTransformer'
            ]
        },
    },
    snapshotSerializers: [
        'jest-preset-angular/build/serializers/ng-snapshot',
        'jest-preset-angular/build/serializers/html-comment'
    ],
    setupFilesAfterEnv: ['<rootDir>/config/jest/setupJest.js'],
    transform: {
        '^.+\\.stories\\.ts?$': '@storybook/addon-storyshots/injectFileName',
        '^.+\\.js$': 'babel-jest',
        '^.+\\.(ts|html)$': 'jest-preset-angular'
    },
    moduleNameMapper: {
        'html-loader!(.*)$': '$1'
    },
    testMatch: ['**/client/my-app/**/*.spec.[jt]s'],
    transformIgnorePatterns: [
        '/node_modules/(?!@storybook|vis-data/peer)',
    ]
};
```
Upon running a test for an AngularJS component: ` TypeError: _angular.default.mock.module is not a function`
I can't easily get a test repo up + running, this is a monolith hybrid app. But while debugging a spec file I can see `angular.mock` is defined, but `module()` is not

<img width="526" alt="Screenshot 2021-06-04 at 11 43 04" src="https://user-images.githubusercontent.com/1395013/120774159-b02d7700-c52a-11eb-858f-e16675b23f56.png">

Hoping you can point my in a direction to debug this further

## envinfo

```
System:
    OS: OSX 11.3

Npm packages:
    jest: 27.0.4
    jest-preset-angular: 9.0.1
    typescript: 4.1.5
```

**Comment by ahnpnl** [comment]
Sorry we don’t support AngularJS, our support policy follows Angular policy only, which is 9 10 11 12.

**Comment by ahnpnl** [comment]
There is a blog post for AngularJS https://medium.zenika.com/testing-an-angularjs-app-with-jest-3029a613251

**Comment by cloakedninjas** [comment]
> Sorry we don’t support AngularJS, our support policy follows Angular policy only, which is 9 10 11 12.

Sure ok - but just FYI hybrids apps could be tested using `jest-preset-angular@8.4` and `jest@26`
