### ISSUE TITLE
Broken Storyshots with jest-preset-angular (Cannot find setup-jest module)

### ISSUE THREAD

**Issue by rowindatas25** [thymikee/jest-preset-angular#952]
## 🐛 Bug Report

The jest-preset-angular library has an issue when trying to run structural testing as a part of Storybook, which has our reusable components library. When running the command to trigger structural testing the terminal gives back a cannot find module error from jest-preset-angular/build/setup-jest.

## To Reproduce

Setup a storybook.test.js file:

```
import initStoryshots from '@storybook/addon-storyshots';
initStoryshots();
```

Add the storyshots addon to the main.js file: 

```
module.exports = {
    stories: [
        '../projects/ng-tui/src/lib/**/*.stories.ts',
        '../pages/**/*.stories.ts',
        '../projects/ng-tui/src/lib/**/*.stories.ts',
        '../stories/**/*.stories.@(ts|mdx)'
    ],
    addons: [
        '@storybook/addon-storyshots',
    ],
};

```

Run the test command configured in package.json, in this case npm run test-structural which pulls from our config file: 

In package.json: `"test-structural": "jest -c integration/test-structural/jest.config.structural.js"`

After running this command, the test starts then fails: 

```
npm run test-structural

> ng-tui@0.0.2 test-structural C:\Users\r.wadera\Documents\GitHub\ng-farmers
> jest -c integration/test-structural/jest.config.structural.js

ts-jest[versions] (WARN) Version 26.6.3 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=24.0.0 <25.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
 FAIL  integration/test-structural/storybook.structural.test.ts
  ● Test suite failed to run

    Cannot find module 'jest-preset-angular/build/setup-jest' from '../../node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js'

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:306:11)
      at setupAngularJestPreset (../../node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js:36:14)
      at Object.load (../../node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js:43:5)
      at Object.loadFramework [as default] (../../node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/frameworkLoader.js:26:19)
      at Object.testStorySnapshots [as default] (../../node_modules/@storybook/addon-storyshots/dist/ts3.9/api/index.js:60:39)
```

## Expected behavior

The structural tests should run without errors and we can then determine which tests are passing and failing 

## Error log:

```
# content of error stacktrace :
Cannot find module 'jest-preset-angular/build/setup-jest' from '../../node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js'

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:306:11)
      at setupAngularJestPreset (../../node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js:36:14)
      at Object.load (../../node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js:43:5)
      at Object.loadFramework [as default] (../../node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/frameworkLoader.js:26:19)
      at Object.testStorySnapshots [as default] (../../node_modules/@storybook/addon-storyshots/dist/ts3.9/api/index.js:60:39)
```

## envinfo

```
System:
    OS: Windows 10 

Npm packages:
    jest: "26.1.0"
    jest-preset-angular: "7.1.1"
    typescript: "3.8.3"
    storybook/angular: "6.1.15"
    storybook/addon-storyshots: "6.2.9"
```

Note: A similar issue has been created on Storybook's issue board without much of a solution, other workarounds seen involve manually touching the node modules. I was wondering if there was another way to go about resolving this. 

Storybook issue:  https://github.com/storybookjs/storybook/issues/12392

Workaround: https://www.gitmemory.com/issue/storybookjs/storybook/9072/562472401

**Comment by ahnpnl** [comment]
Moreover, this preset is delivered to work with basic project. You are using it via storybook and the stack trace points to storybook itself so it is the problem with storybook, see `at setupAngularJestPreset (../../node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js:36:14)`.

I would say this should be solved by storybook because it’s not the preset bug itself.

**Comment by ahnpnl** [comment]
I see the issue has been fixed by storybook team so if you upgrade your storybook deps, you should get the fix

**Comment by rowindatas25** [comment]
Thank you for clearing this up, where is the storybook solution posted? I can't seem to find it on their issues board.

**Comment by MatviiStelmakh** [comment]
if you have an incompatible version of the `jest-preset-angular` you can map file paths but that will not guarantee that everything works fine
```
moduleNameMapper: {
    'jest-preset-angular/build/setup-jest': 'jest-preset-angular/setup-jest',
    'jest-preset-angular/build/AngularSnapshotSerializer':  'jest-preset-angular/build/serializers/ng-snapshot',
    'jest-preset-angular/build/HTMLCommentSerializer':  'jest-preset-angular/build/serializers/html-comment'
  },
```
