### ISSUE TITLE
Zone already loaded error in version ^4.0.1 and ^5.x.x

### ISSUE THREAD

**Issue by jbgraug** [thymikee/jest-preset-angular#96]
Whenever there is a dependency on zone.js. Jest terminates.
It does not happen on v3.0.1. 

To reproduce just place
import 'zone.js' 
in setup-jest.ts

**Comment by thymikee** [comment]
Zone is already imported and lives in global scope (when you're using `setupTestFrameworkScriptFile` hook, it's not there yet in `setupFiles` which executes earlier), it's forbidden to redeclare it, so don't do it manually.

**Comment by jbgraug** [comment]
I did it manually just to show that it breaks. My project uses a lib. Wich
uses zone.js and whenever I import a file which has any direct or indirect
dependence on it, it breaks.

**Comment by thymikee** [comment]
Can you tell show something more about the error?

**Comment by jbgraug** [comment]
If i drill down into the lib using zone.js, it imports zone.js like this ``` require("zone.js");  ``` 
which is different from ``` require('zone.js/dist/zone.js'); ``` the one you are using and then it crashes.
Any test having a dependency with zone.js raises the error below, even though the app builds/run properly.
Test suite failed to run
    Zone already loaded.
      at node_modules/zone.js/dist/zone-node.js:32:15
      at node_modules/zone.js/dist/zone-node.js:646:3
      at Object.<anonymous>.FUNCTION (node_modules/zone.js/dist/zone-node.js:9:65)
      at Object.<anonymous> (node_modules/zone.js/dist/zone-node.js:12:2)
      ...
```

**Comment by Hotell** [comment]
is this still an issue ? not experiencing this at all -> angular 5.x

**Comment by thymikee** [comment]
@jbgraug can we close it?

**Comment by jbgraug** [comment]
Still got the same error, my solution was to stick to version 3.x
Tried version 5, still failing with the same error.

**Comment by jbgraug** [comment]
What's the problem of importing zone.js the "right way"?
In zone.js package.json they already have both properties "main" and "browser" set up.
Why override this functionality in importing "zone.js/dist/zone" when the right version is going to automatically be picked up?

Please take a look here https://github.com/angular/zone.js/issues/963

**Comment by patrickmichalina** [comment]
This break testing with newer versions of angularfire2

**Comment by thymikee** [comment]
Does it unbreak with #135? I didn't have the capacity to test it yet

**Comment by patrickmichalina** [comment]
@thymikee for me yes. I actually have to use a script to apply this patch for my tests to run when firebase modules are referenced. Since they added Universal support, it appears zone.js is loaded on their dep chain somewhere.

**Comment by Hotell** [comment]
@patrickmichalina if you could provide an example repo with the issue, it would help us/me, to incorporate it against whole angular.io testsuite that I migrated to jest recently :)

**Comment by patrickmichalina** [comment]
@Hotell all my work is in pretty large apps, I might be able to. It is def. specific to AngularFire2 rc-next-7.0 (the latest as of this week)

**Comment by Hotell** [comment]
So switching to load just `zone.js` within `setupJest.js` and let environment load what it needs by package.json metadata makes angular.io test suite fail. ( in jest it uses `main` field which loads `zone-node.js` )

- with explicitly loading browser version of zone.js ( same as karma is doing ):

![image](https://user-images.githubusercontent.com/1223799/39042142-cf5d97a2-4492-11e8-82d6-ea8e9f2c589a.png)

- loading just default `zone.js` with env resolution by metadata ( which loads `zone-node.js` ) because node consumes `main` field by default:

![image](https://user-images.githubusercontent.com/1223799/39042191-e695f7b6-4492-11e8-899e-c44bed16a1ac.png)

**Comment by Hotell** [comment]
> What's the problem of importing zone.js the "right way"?
In zone.js package.json they already have both properties "main" and "browser" set up.
Why override this functionality in importing "zone.js/dist/zone" when the right version is going to automatically be picked up?

we are doing the same as standard angular cli karma config, so it is the right way already :)

**Comment by Hotell** [comment]
Also the obvious problem is that angular-fire is importing directly zone.js within their index file. That's where the clash comes from because zone.js has no throw/catch mechanism to handle this properly

**Comment by joshbabb** [comment]
Also encountering this issue.
