### ISSUE TITLE
Module jest-preset-angular/build/AngularNoNgAttributesSnapshotSerializer.js in the snapshotSerializers option was not found.

### ISSUE THREAD

**Issue by maxime1992** [thymikee/jest-preset-angular#960]
## 🐛 Bug Report

After upgrading to Angular 12, Nx 12, Jest 27 and jest-preset-angular 9.0.4 I now get this error when launching my tests

> Module jest-preset-angular/build/AngularNoNgAttributesSnapshotSerializer.js in the snapshotSerializers option was not found.

I've spotted a similar issue here: https://github.com/thymikee/jest-preset-angular/issues/450 but it just said one of the versions had a bug and it was fixed in a newer one

## Error log:

```
> nx run fos:test 
● Validation Error:

  Module jest-preset-angular/build/AngularNoNgAttributesSnapshotSerializer.js in the snapshotSerializers option was not found.
         <rootDir> is: /home/maxime/Documents/cloudnc/code/frontend/apps/fos

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

## envinfo

```
System: 
    OS: Ubuntu

Npm packages:
    jest: 27.0.3
    jest-preset-angular: 9.0.4
    typescript: 4.2.4
```

**Comment by ahnpnl** [comment]
Please check our CHANGELOG because 9.0.0 contains breaking changes about this :)
