### ISSUE TITLE
moduleNameMapper override for tslib is causing  error when using esm

### ISSUE THREAD

**Issue by viceice** [thymikee/jest-preset-angular#974]
## 🐛 Bug Report

I'm using an angular nx workspace with jest projects. I need to use esm because i've some web worker usages.

See error below. My workaround is to set `allowJs=true` to my `tsconfig.spec.json` so `tslib` will be compiled by this project.

## To Reproduce

Create a nx workspoace with angular preset and some dummy libs.
Configure for esm and run tests.

## Expected behavior

Simply run tests without explicit workaround.

## Link to repo (highly encouraged)

I can provide a sample maybe later.

## Error log:

```
# content of error stacktrace :
C:\Users\kriese\projects\visualon\xfab\sx\node_modules\tslib\tslib.es6.js:24
    export function __extends(d, b) {
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1479:14)
```

## envinfo

```
System: 
    OS: Windows 10 21H1

Npm packages:
    jest: 27.0.6
    jest-preset-angular: 9.0.5
    typescript: 4.3.5
    tslib: 2.3.0
```

**Comment by viceice** [comment]
I think it's because of this line

https://github.com/thymikee/jest-preset-angular/blob/cf3874b8d856a0977e9ee5b24a12eadf940481a5/presets/index.js#L30

**Comment by ahnpnl** [comment]
We have 2 choices here: either always set `allowJs: true` internally or remove the mapping of `tslib`. I prefer the 1st choice as mapping `tslib` is required if running Jest in ESM mode.
