### ISSUE TITLE
CommonJS modules and default import problem

### ISSUE THREAD

**Issue by villelahdenvuo** [thymikee/jest-preset-angular#98]
Trying to use a module like https://www.npmjs.com/package/url-slug works fine in Angular build, but fails in the tests: 

```js
import slugify from 'url-slug';

const slug = slugify('Some String');
```

Works fine in ng serve and ng build, but in tests `TypeError: url_slug_1.default is not a function`

Using `import * as slugify from 'url-slug'` works in tests, but doesn't build.

**Comment by villelahdenvuo** [comment]
I was reading that in theory ts-jest should support these synthetic modules: https://github.com/kulshekhar/ts-jest#supports-synthetic-modules

**Comment by villelahdenvuo** [comment]
Okay I think I figured it out:

### tsconfig.spec.json
```js
	"compilerOptions": {
		"allowSyntheticDefaultImports": true,
		"allowJs": true,
		// etc...
	}
```

### jest.config.js
```js
	transformIgnorePatterns: [
		'node_modules/(?!your|third-party|modules\/.*)'
	]
```

After these the import started working. Should I make a PR and add this to the FAQ section?

**Comment by villelahdenvuo** [comment]
Okay that fixes the import problem, but now 2 non-related tests fail in a very mysterious way saying:

```
    expect(jest.fn()).toHaveBeenCalledWith(expected)
    
    Expected mock function to have been called with:
      "stuff"
    But it was not called.
```

**Comment by thymikee** [comment]
Glad you worked it out! You can add it to the FAQ, but it's also easily searchable through issues, so no rush on that.
