### ISSUE TITLE
testing angular components with jest gives resolveComponentResources

### ISSUE THREAD

**Issue by eng-dibo** [thymikee/jest-preset-angular#992]
I'm trying to test Angular components with jest via `jest-preset-angular`

it can run the test by `karma` with `ng test`,
but running the same test by `jest` gives the error
```
AppComponent › should create the app

    Component 'AppComponent' is not resolved:
     - templateUrl: ./app.component.html
     - styleUrls: ["./app.component.scss"]
    Did you run and wait for 'resolveComponentResources()'?
 ```

[reproduction](https://github.com/eng-dibo/reprod-resolveComponentResources)

 ## steps to create this reproduction (see the git commits for steps)
 1- generate a new angular project `ng new myproject`
 2- install jest dependencies
 3- create jest config file 
 4- copy and modify `src/app/app.component.spec.ts` to `app.component.spec.jest.ts`

 ## running the reproduction  
 to test `app.component.spec.ts` file by karma run `npm t` or `ng test`
 and then run `npm run test:jest` to test `app.component.spec.jest.ts` by jest

**Comment by ahnpnl** [comment]
Hi, pls go through our documentation at https://thymikee.github.io/jest-preset-angular/docs

the problem is that you are not using our transformer https://thymikee.github.io/jest-preset-angular/docs/getting-started/options which explains the error.
